### ISSUE TITLE
GH Actions Caches “Approaching total cache storage limit“

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1020]
There's the following warning:

> Approaching total cache storage limit (22.39 GB of 10 GB Used)

There:

https://github.com/ocaml/ocaml.org/actions/caches

There's probably plenty of file that should be removed

**Comment by sabine** [comment]
I think GitHub automatically removes cache entries according to a LRU policy. So I think there's nothing urgent we need to do here.

Closing this issue for the time being.
