### ISSUE TITLE
Complete redirections from V2

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#104]
#103 introduced a redirection module that maps the URLs from V2 to their new location in V3. While some of the URLs are already handled (the tutorials), there are still some URLs that need to be mapped.

**Comment by rgrupesh** [comment]
@tmattio I would like to work on this issue. What specific redirect should I specifically looking for? Any pointers to get started?

**Comment by tmattio** [comment]
Hi @rgrupesh 🙂 That sounds like a great first issue. The list of redirections to add can be seen at https://github.com/ocaml/v3.ocaml.org-server/blob/main/src/ocamlorg_web/lib/redirection.ml. The `???` are the ones that are yet to be handled. To find the equivalent route, I'd recommend looking at the router at https://github.com/ocaml/v3.ocaml.org-server/blob/main/src/ocamlorg_web/lib/router.ml, in particular the page routes at https://github.com/ocaml/v3.ocaml.org-server/blob/main/src/ocamlorg_web/lib/router.ml#L27.

Let me know if you have any questions!

**Comment by rgrupesh** [comment]
Thank you for these links @tmattio . I found some of the route and added those to the `redirection.ml`. I am having trouble finding all the routes. Are all required `.md` files present in data directory? Should I be expecting to find all the routes? 

And what is the difference between `release` and `releases`? Are they two different urls?

What should be an ideal workflow? One workflow example would be great.

**Comment by tmattio** [comment]
@rgrupesh Some of the routes won't be available in the new website, that's ok and you can redirect these to the homepage (i.e. `/`).

Don't hesitate to open a draft PR and I can help you to identify which page should have redirections and which one shouldn't.

> And what is the difference between release and releases? Are they two different urls?

`releases` contains the list of releases (see https://v3.ocaml.org/releases) and `release` is the content of a single release (see https://v3.ocaml.org/releases/3.12.1)

> What should be an ideal workflow? One workflow example would be great.

I'm not sure I understand the question 🙂 If you mean how to find the right redirections, I'd start with the old website URL in `redirection.ml`, see if there is an equivalent in `url.ml`, if so use this route, if not, use `/`.

You can also navigate both sites to get a good idea of what content/page is available on both.
