### ISSUE TITLE
Question: Why https://ocaml.org/p/learn-ocaml/latest says `Page not found`?

### ISSUE THREAD

**Issue by erikmd** [ocaml/ocaml.org#1042]
Hello,

I recently noticed that any of the following URLs yields a 404 error:

* https://ocaml.org/p/learn-ocaml/latest
* https://ocaml.org/p/learn-ocaml/latest/doc/index.html
* https://ocaml.org/p/learn-ocaml/0.14.1/doc/index.html

Is it a bug on your side ? or do you know what we'd need to change in learn-ocaml to fix this?

**Comment by sabine** [comment]
When I look up the package documentation build logs, I see solver failures like this (for all versions except 0.12):

```
Package learn-ocaml.0.13.0
Failed to find a solution:

Error from solver: Bad frame from worker: time="2.29" len="0.0"
no platform:
2022-09-01 10:08.51 [INFO] Solving for ocaml-variants, learn-ocaml

2022-09-01 10:08.56 [INFO] base: eliminated all possibilities in 1.88 s

2022-09-01 10:08.56 [INFO] = base =

2022-09-01 10:08.56 [INFO] Can't find all required versions.
Selected: angstrom.0.15.0 asak.0.3 asn1-combinators.0.2.6 astring.0.8.5
          base.v0.15.0 base-bigarray.base base-bytes.base base-domains.base
          base-nnp.base base-threads.base base-unix.base base64.3.5.0
          bigstringaf.0.9.0 bos.0.2.1 ca-certs.0.2.2 camlp-streams.5.0.1
          checkseum.0.3.4 cmdliner.1.1.1 cohttp.5.0.0 cohttp-lwt.5.0.0
          cohttp-lwt-unix.5.0.0 conduit.5.1.1 conduit-lwt.5.1.1
          conduit-lwt-unix.5.1.1 conf-git.1.1 conf-gmp.4 conf-gmp-powm-sec.3
          conf-pkg-config.2 cppo.1.6.9 csexp.1.5.1 cstruct.6.1.1
          digestif.1.1.2 domain-name.0.4.0 dune.3.4.1 dune-configurator.3.4.1
          duration.0.2.0 easy-format.1.3.4 eqaf.0.9 ezjsonm.1.3.0 fmt.0.9.0
          fpath.0.7.3 gg.1.0.0 gmap.0.3.0 hex.1.5.0 ipaddr.5.3.1
          ipaddr-sexp.5.3.1 js_of_ocaml.4.0.0 js_of_ocaml-lwt.4.0.0
          js_of_ocaml-ppx.4.0.0 js_of_ocaml-toplevel.4.0.0
          js_of_ocaml-tyxml.4.0.0 jsonm.1.0.1 logs.0.7.0 lwt.5.6.1
          lwt_react.1.2.0 lwt_ssl.1.1.3 macaddr.5.3.1 magic-mime.1.2.0
          markup.1.0.3 markup-lwt.0.5.0 mirage-crypto.0.10.6
          mirage-crypto-ec.0.10.6 mirage-crypto-pk.0.10.6
          mirage-crypto-rng.0.10.6 mirage-no-solo5.1 mirage-no-xen.1
          mtime.1.4.0 num.1.4 ocaml-compiler-libs.v0.12.4 ocaml-config.3
          ocaml-option-nnp.1 ocaml-syntax-shims.1.0.0 ocamlbuild.0.14.1
          ocamlfind.1.9.5 ocp-indent-nlfork.1.5.4 ocp-ocamlres.0.4
          ocplib-endian.1.2 ocplib-json-typed-browser.0.7.1 odoc.2.1.1
          optint.0.2.0 parsexp.v0.15.0 pbkdf.1.2.0 pprint.20220103
          ppx_cstruct.6.1.1 ppx_derivers.1.2.1 ppx_sexp_conv.v0.15.1
          ppx_tools.6.5 ppx_tools_versioned.5.4.0 ppxlib.0.27.0 ptime.1.0.0
          re.1.10.4 react.1.2.2 reactiveData.0.3.0 result.1.5 rresult.0.7.0
          seq.base sexplib.v0.15.1 sexplib0.v0.15.1 stdlib-shims.0.3.0
          stringext.1.6.0 topkg.1.0.5 tyxml.4.5.0 uchar.0.0.2 uri.4.2.0
          uri-sexp.4.2.0 uutf.1.0.3 vg.0.9.4 x509.0.16.0 yojson.2.0.2
          zarith.1.12 ocaml-variants&learn-ocaml ocaml-base-compiler
          ocaml-base-compiler ocaml-variants base-domains ocaml
          mirage-no-solo5&mirage-no-xen
- decompress -> decompress.0.8.1
    learn-ocaml 0.13.0 requires = 0.8.1
- js_of_ocaml-compiler -> (problem)
    dune 3.4.1 requires not(< 3.6.0)
    js_of_ocaml 4.0.0 requires = 4.0.0
    Rejected candidates:
      js_of_ocaml-compiler.4.0.0: Requires base-domains conflict with all versions
      js_of_ocaml-compiler.3.11.0: Incompatible with restriction: = 4.0.0
      js_of_ocaml-compiler.3.10.0: Incompatible with restriction: = 4.0.0
      js_of_ocaml-compiler.3.9.1: Incompatible with restriction: = 4.0.0
      js_of_ocaml-compiler.3.9.0: Incompatible with restriction: = 4.0.0
      ...
- learn-ocaml -> learn-ocaml.0.13.0
    User requested = 0.13.0
- ocaml -> ocaml.4.12.0
    asak 0.3 requires >= 4.05 & < 4.13
    ocaml-variants 4.12.0+domains requires = 4.12.0
- ocaml-base-compiler -> (problem)
    Rejected candidates:
      ocaml-base-compiler.5.0.0~alpha1: In same conflict class (ocaml-core-compiler) as ocaml-variants
      ocaml-base-compiler.5.0.0~alpha0: In same conflict class (ocaml-core-compiler) as ocaml-variants
      ocaml-base-compiler.4.14.0: In same conflict class (ocaml-core-compiler) as ocaml-variants
      ocaml-base-compiler.4.14.0~rc2: In same conflict class (ocaml-core-compiler) as ocaml-variants
      ocaml-base-compiler.4.14.0~rc1: In same conflict class (ocaml-core-compiler) as ocaml-variants
      ...
- ocaml-migrate-parsetree -> (problem)
    ppx_tools_versioned 5.4.0 requires >= 1.7.0 & < 2.0.0
    ppxlib 0.27.0 requires not(< 2.0.0)
    Rejected candidates:
      ocaml-migrate-parsetree.2.4.0: Incompatible with restriction: >= 1.7.0 & < 2.0.0
      ocaml-migrate-parsetree.2.3.0: Incompatible with restriction: >= 1.7.0 & < 2.0.0
      ocaml-migrate-parsetree.2.2.0: Incompatible with restriction: >= 1.7.0 & < 2.0.0
      ocaml-migrate-parsetree.2.1.0: Incompatible with restriction: >= 1.7.0 & < 2.0.0
      ocaml-migrate-parsetree.2.0.0: Requires ocaml >= 4.02.3 & < 4.12
      ...
- ocaml-variants -> ocaml-variants.4.12.0+domains
    User requested = 4.12.0+domains
- ocplib-json-typed -> (problem)
    learn-ocaml 0.13.0 requires >= 0.7
    Rejected candidates:
      ocplib-json-typed.0.7.1: Requires dune >= 1.0.1 & < 3.0.0
      ocplib-json-typed.0.7: Requires dune >= 1.0.1 & < 3.0.0
      ocplib-json-typed.0.6: Incompatible with restriction: >= 0.7
      ocplib-json-typed.0.5: Incompatible with restriction: >= 0.7
      ocplib-json-typed.0.4: Incompatible with restriction: >= 0.7
      ...
- odoc-parser -> odoc-parser.1.0.1
    odoc 2.1.1 requires >= 0.9.0 & < 2.0.0
- omd -> omd.1.3.1
    learn-ocaml 0.13.0 requires <= 1.3.1
- ssl -> (problem)
    conduit-lwt-unix 5.1.1 requires not(< 0.5.9)
    learn-ocaml 0.13.0 requires = 0.5.5
    Rejected candidates:
      ssl.0.5.12: Incompatible with restriction: = 0.5.5
      ssl.0.5.11: Incompatible with restriction: = 0.5.5
      ssl.0.5.10: Incompatible with restriction: = 0.5.5
      ssl.0.5.9: Incompatible with restriction: = 0.5.5
      ssl.0.5.8: Incompatible with restriction: not(< 0.5.9)
      ...
```

```
Package learn-ocaml.0.14.1
Failed to find a solution:

Error from solver: Bad frame from worker: time="1.23" len="0.0"
no platform:
2023-01-12 13:29.33 [INFO] Solving for ocaml-base-compiler, learn-ocaml

2023-01-12 13:29.35 [INFO] base: eliminated all possibilities in 0.91 s

2023-01-12 13:29.35 [INFO] = base =

2023-01-12 13:29.35 [INFO] Can't find all required versions.
Selected: base-bigarray.base base-domains.base base-nnp.base
          base-threads.base base-unix.base ocaml-config.3
          ocaml-options-vanilla.1 ocaml-base-compiler&learn-ocaml
          ocaml-base-compiler ocaml-base-compiler ocaml base-domains
          ocaml-base-compiler
- learn-ocaml -> (problem)
    User requested = 0.14.1
    Rejected candidates:
      learn-ocaml.0.14.1: Requires ocaml >= 4.12 & < 4.13~
- ocaml -> ocaml.5.0.0
    ocaml-base-compiler 5.0.0~beta1 requires = 5.0.0
- ocaml-base-compiler -> ocaml-base-compiler.5.0.0~beta1
    User requested = 5.0.0~beta1
```

I don't currently know enough to decide whether that's a failure of our solver or a problem with the constraints (but I would assume that the package builds for you, so chances are it's a problem on our end).

I'll look into it on Monday.

**Comment by erikmd** [comment]
Dear @sabine,
OK thanks for your quick reply!

At first sight it seems the error log for `learn-ocaml.0.14.1` is shorter (and no worries if the problem can only be solved for the latest version) and is due to a mismatch w.r.t. ocaml's version

→ do you believe that the fact learn-ocaml requires ocaml 4.12.x currently is the crux of the issue ?

(FWIW, given the architecture of the learn-ocaml project and the coupling with ocaml's AST, it is impossible, at least currently, to support several minor versions of the compiler)

**Comment by sabine** [comment]
Having strict limitations on the ocaml version should not in principle be a problem. Looking into `learn-ocaml-client`, I can see that none of its versions have any solver failures. Makes me think it's a problem on our end.

I can see you provide documentation in the `docs/` folder in markdown format. I assume this documentation is intended to show up for the `learn-ocaml` package at https://ocaml.org/p/learn-ocaml/latest/doc/index.html? Is it also intended to show up for `learn-ocaml-client`?

The documentation build system uses [`odoc`](https://github.com/ocaml/odoc) to render the documentation. An example of an opam package that does not contain libraries but provides documentation pages is here: https://github.com/tarides/opam-monorepo/tree/main/doc. See, for comparison https://ocaml.org/p/opam-monorepo/0.3.2/doc/index.html what this currently renders as. A table of contents listing all available documentation pages is highly likely to appear in the next weeks/months - the current lack of it is a major pain point. The packages section on ocaml.org is still a bit of a construction site, even though many improvements have been happening over the last months there is still quite a bit to do to make it as useful as it should be.

**Comment by erikmd** [comment]
Hi @sabine,
> I can see you provide documentation in the `docs/` folder in markdown format; I assume this documentation is intended to show up for the `learn-ocaml` package …

This folder just gathers the sources of the GitHub Pages website:
https://ocaml-sf.org/learn-ocaml/

But if it were possible to also include this documentation in https://ocaml.org/p/learn-ocaml/latest/doc/index.html, it would be nice. But this is not mandatory.

> The documentation build system uses [odoc](https://github.com/ocaml/odoc) to render the documentation.

OK! but I'm not `odoc`-savvy at all… so is there an official tutorial explaining all the requirements for a dune project to be "`odoc`-compatible"?

According to https://ocaml.github.io/odoc/odoc_for_authors.html, it seems we only need to run `dune build @doc`.
And given this works with current learn-ocaml (it generates html doc for modules `Test_lib` and `Learnocaml_report`), I'm not sure there is a bug on learn-ocaml's side.

Anyway, thanks for your feedback up to now, and have a nice week-end!

**Comment by sabine** [comment]
Here's an update: It turns out that, currently, ocaml.org's documentation build system is limited exclusively to versions 4.14 or 5.0.0 for `ocaml`. So all packages that have constraints incompatible with these versions currently won't build. This restriction may possibly be relaxed in the future, but there's no timeline for this.

Sorry I don't have better news on this.

**Comment by tmattio** [comment]
This seems fixed, the documentation of the package is available at https://ocaml.org/p/learn-ocaml/latest
