### ISSUE TITLE
Use `Ocamlorg_static.Asset.url` for all assets

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1049]
When assets change, browsers may still have them cached. To ensure modified assets reach our users, there's the cache-busting immutable URLs (based on file digest) provided via `Ocamlorg_static.Asset.url`.

The assets of ocaml.org are found in the folder [/asset](https://github.com/ocaml/ocaml.org/tree/main/asset), and they are used throughout the templates in [/src/ocamlorg_frontend/](https://github.com/ocaml/ocaml.org/tree/main/src/ocamlorg_frontend).

Here's an example of how the changes look like: https://github.com/ocaml/ocaml.org/pull/1048/files.

This is a task suitable for an inexperienced contributor.

**Comment by r17x** [comment]
Hi @sabine, 

I'm interested to handle this issue and make my first contribution at this project. Could you assignee to me?

**Comment by sabine** [comment]
Hey @r17x, happy to have you! If there's any questions don't hesitate to ask.
