### ISSUE TITLE
Support code highlighting in tutorials

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#105]
Now that ood is within this repository we have a some more freedom to decide how to do this. I'm personally in favour of improving/rewriting (and probably vendoring) something like https://github.com/patricoferris/hilite and doing this statically. This let's us: 

 1. High-light anything vscode can (dune, opam, ocamlformat etc.) see https://github.com/ocamllabs/vscode-ocaml-platform/tree/master/syntaxes
 2. No runtime client-side highlighting via highlight js (less data sent to clients, less JS running on clients)
 3. Better control over our dependencies from a privacy standpoint too because of (2)

The cost of course is more maintenance. @tmattio any thoughts?

**Comment by tmattio** [comment]
Related to https://github.com/ocaml/v3.ocaml.org-server/issues/99 - we probably want the same solution for both

**Comment by tmattio** [comment]
Hilite seems very nice! I like that it allows us to do the highlighting from the server!

If it's still unreleased, feel free to add it in `src/` directly, the same way I did with `gettext`. Ultimately, I'd like to release it independently, but I'll come back to it when it is stable in ocaml.org.

**Comment by ghost** [comment]
> No runtime client-side highlighting via highlight js

From my limited understanding, I don't think we have ever implemented code highlighting in the browser. In prior and proposed implementations, it was run as a final phase of markdown processing at build time.

**Comment by patricoferris** [comment]
Initial work done in #108
