### ISSUE TITLE
Error (warning 35 [unused-for-index]): unused for-loop index i. (from ocaml.org example)

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml.org#1050]
From https://ocaml.org/docs/first-hour
with this code:
```
Random.self_init ();;

Graphics.open_graph " 640x480";;

let rec iterate r x_init i =
  if i = 1 then x_init else
    let x = iterate r x_init (i - 1) in
      r *. x *. (1.0 -. x);;

for x = 0 to 639 do
  let r = 4.0 *. (float_of_int x) /. 640.0 in
  for i = 0 to 39 do
    let x_init = Random.float 1.0 in
    let x_final = iterate r x_init 500 in
    let y = int_of_float (x_final *. 480.) in
      Graphics.plot x y
  done
done;;

read_line ();;
```
it doesn't compile with dune.

I get
`Error (warning 35 [unused-for-index]): unused for-loop index i.`

## 1st solution

```
...
for _ = 0 to 39 do
...
```

## 2nd solution
From https://dune.readthedocs.io/en/stable/faq.html#how-to-make-warnings-non-fatal, the dune file will be
```
(executable
 (name main)
 (libraries graphics)
 (flags (:standard -w -35)))
```

**Comment by sabine** [comment]
Thank you @fredOnGitHub, that's a very helpful and clear report!

**Comment by fredOnGitHub** [comment]
With https://dune.readthedocs.io/en/stable/faq.html#how-to-make-warnings-non-fatal, it is possible to avoid the stop warning:

In this case the dune file will be : 
```
(executable
 (name main)
 (libraries graphics)
 (flags (:standard -w -35)))
```
