### ISSUE TITLE
Log data beyond update and restart

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1056]
Currently, only the data of the current run is exposed. This does not allow to compare between versions. A sliding window mechanism is required to store and display between a couple of days and a couple of weeks

**Comment by sabine** [comment]
Indeed, that's a big shortcoming of the current dashboard. The open question is... do we really want to take on the burden of creating and maintaining a full-featured dashboard, or do we want to integrate an existing solution?

**Comment by sabine** [comment]
Closing this because we retired the dashboard in favor of using plausible.io
