### ISSUE TITLE
Wrong reference to option -dtypedtree for utop

### ISSUE THREAD

**Issue by cionx** [ocaml/ocaml.org#1075]
https://github.com/ocaml/ocaml.org/blob/1a69f50f5917efe09fa32e1a5fc9d5031aa70688/data/tutorials/wf_03_metaprogramming.md?plain=1#L242-L244

utop doesn’t seem to support the option `-dtypedtree`. (This option isn’t listed in the output of `utop -help` nor in utop’s manpage, and no reference to `dtypedtree` can be found in the [utop source code][1].)

[1]: https://github.com/ocaml-community/utop/search?q=dtypedtree

**Comment by sabine** [comment]
@cionx Thank you, you're correct. Fix is incoming. :+1:

**Comment by panglesd** [comment]
Indeed, unfortunately only `ocaml` supports `-dtypedtree`!

**Comment by Octachron** [comment]
Note that with `utop-full` enabling `-dtypedtree` can be done within the REPL with `Clflags.dump_typedtree := true`.

**Comment by sabine** [comment]
@Octachron Thank you, that's very helpful and I'll add that.
