### ISSUE TITLE
wrong unicode rendering on full package search page

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocaml.org#1081]
Look at the package `anycache` in the following 2 searches:
https://ocaml.org/packages/search?q= vs https://ocaml.org/packages/search?q=anycache

The former doesn't render the unicode characters in my name correctly showing 2 question marks instead, while the latter does (https://ocaml.org/p/anycache/latest also renders it correctly).
[T��r��k Edwin <edwin@etorok.net>](https://ocaml.org/packages/search?q=author%3A%22T%C3%B6r%C3%B6k%20Edwin%20%3Cedwin%40etorok.net%3E%22)

vs
Török Edwin <edwin@etorok.net>

My name isn't the only one not rendered correctly, here is another:
[Fran��ois Bobot](https://ocaml.org/packages/search?q=author%3A%22Fran%C3%A7ois%20Bobot%22)

**Comment by sabine** [comment]
Thank you @edwintorok, that was indeed not intended. :+1:
