### ISSUE TITLE
OCaml Playground is broken

### ISSUE THREAD

**Issue by xania** [ocaml/ocaml.org#1087]
Hi, This is the first time I ever tried to explore OCaml, I thought that the easiest way to start is to try out the playground, unfortenately the playground is broken with the following error

>  Uncaught SyntaxError: Unexpected identifier 'https' (at playground.min.js:1:9)

The content of `playground.min.js` does not look like a valid javascript file. something went wrong during build maybe?

```javascript
version https://git-lfs.github.com/spec/v1
oid sha256:f23118f0fe80bdbb1760afed8b68082021a427ae44c2b43888d9c3f259b0239a
size 1065699
```

fullpath fo the js file:
https://ocaml.org/play/_/UufJ6buGZVdr0RI5Qdi8hQ/playground.min.js

**Comment by sabine** [comment]
Thank you for reporting @xania. :+1: Indeed, something went wrong with our deployment when we added `git-lfs`.

Resolved by https://github.com/ocaml/ocaml.org/pull/1093.
