### ISSUE TITLE
Metaprogramming tutorial example uses nonstandard "OSTYPE" environment variable

### ISSUE THREAD

**Issue by leviroth** [ocaml/ocaml.org#1092]
The metaprogramming tutorial has an [example](https://github.com/ocaml/ocaml.org/blob/c786a2a5ea63a2ec102882fbfa199537e4d45f43/data/tutorials/wf_03_metaprogramming.md?plain=1#L19-L39) that fetches an environment variable at compilation time. Unfortunately the variable chosen is a _shell variable_ defined in Bash, but it isn't (unless a user goes out of their way to export it) normally an environment variable. Thus in a typical environment compilation will fail. (This actually came up in the OCaml IRC/Discord, and it was confusing.)

It would be better to tweak the example to use an environment variable that is defined in typical environments.

**Comment by cuihtlauac** [comment]
Thanks @leviroth, you have a valid point there. What would be the better candidates to replace OSTYPE?

**Comment by leviroth** [comment]
Probably `PWD` would be fine?

`HOME` appears to be defined in my (both not very customized) Windows PowerShell environment and my Ubuntu Bash environment, so that could work as a way of covering both platforms, though it seems a bit more contrived (why would a program want to know the home directory of the user who compiled it?). I'm also not sure how `Sys.getenv` behaves on Windows, anyway.

**Comment by Raven49** [comment]
Hi , @sabine @SaySayo  can you please assign me this issue , i have managed to setup the project as per #1553 
![3](https://github.com/ocaml/ocaml.org/assets/70138609/6cc5f034-9311-4c80-8adf-ae605334af17)

**Comment by SaySayo** [comment]
@Raven49, you will be assigned this issue. Please let me know if you need any help. cc @sabine

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1658
