### ISSUE TITLE
Implement media archive

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#114]
Not entirely sure what should or what shouldn't be in the "media archive" perhaps all the watch.ocaml.org videos, the papers, presentation slides ? 

Once implemented we can change the link the workshop pages to point to this (perhaps sensibly filtered) as per #111

**Comment by tmattio** [comment]
I believe we decided to not implement the archive pages, so I'll close this. Feel free to re-open if that's not right.
