### ISSUE TITLE
Serve data/media files under digest URLs

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1147]
Similar to https://github.com/ocaml/ocaml.org/issues/1049, we should also serve the files from `data/media` (see [`Ocamlorg_static.Media`](https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_static/ocamlorg_static.ml)) under digest URLs. 

This requires adding a `url` function to `Ocamlorg_static.Media`, similar to [the `url` function of `Ocamlorg_static.Asset`](https://github.com/ocaml/ocaml.org/blob/384684f5b59a40ae71b07a8bb90cb0180977ff3f/src/ocamlorg_static/ocamlorg_static.ml#L14).

Apart from that we need to go through all the images in the templates and use the new function where appropriate (in the same way as https://github.com/ocaml/ocaml.org/pull/1145).

**Comment by r17x** [comment]
Can I join the party (Assignee), again? @sabine  😄

**Comment by sabine** [comment]
@r17x I am super happy to have you. :+1: :grin:
