### ISSUE TITLE
Improve the rendering of ocaml codeblocks

### ISSUE THREAD

**Issue by gpetiot** [ocaml/ocaml.org#1150]
Currently there is the same code highlighting whether the code is:
- OCaml implementation
- interface (.mli)
- REPL

To make it clear whether the user should copy/paste the code in `utop` or in their editor it would be handy to have a different rendering for these blocks (could be something CSS based, or a caption for the codeblock, etc.).

This might not be obvious for beginners that if a snippet starts with `#` it belongs in the REPL and might be followed by the output or errors. Same for type signatures/module signatures/etc that should either belong in a .mli file, or are given for reference, but should not be submitted to the REPL.

Related to this issue, it would be convenient to be able to tell whether part of a toplevel code block is an error message:

See https://ocaml.org/docs/labels#using-foo-in-a-function-call

<img width="810" alt="Screenshot 2023-05-02 at 16 08 16" src="https://user-images.githubusercontent.com/497999/235707592-544141bb-ecef-4bb8-9054-9d5b3aa5408e.png">

As you can see, the error messages is highlighted as if it was regular code, which is confusing for the reader.
Will probably need to be forwarded to `omd` or `hilite`, unless something can be done directly here?

**Comment by cuihtlauac** [comment]
You're correct; this is an upstream issue. I believe `hilite` is the right place.

**Comment by gpetiot** [comment]
I generalized the issue after reviewing #950 and seeing how easy it is to get confused when reading the OCaml code blocks

**Comment by cuihtlauac** [comment]
I believe this is now almost a dupe with: https://github.com/ocaml/ocaml.org/issues/961

**Comment by gpetiot** [comment]
Oh indeed, I'm closing this one in favor of #961 then

**Comment by cuihtlauac** [comment]
Would you mind adding your text in https://github.com/ocaml/ocaml.org/issues/961 ? Your text is an improvement over the initial one.
