### ISSUE TITLE
Optimize asset loading

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#118]
- [ ] Inline the logo as an SVG image in the header and footer
- [ ] Inline the discord logo as an SVG image
- [ ] Inline the `syntax.css` stylesheet on pages where it is needed (tutorials and package documentation)
- [ ] Inline `alpine-clipboard.js` in package overview
- [ ] Inline `doc.css` in package documentation
- [ ] Investigate strange `data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e` query in package overview
- [x] Add Compression middleware to assets and pages
- [ ] Add ETag middleware to assets and pages

**Comment by patricoferris** [comment]
As a more medium-term goal it would be good to generate some images at different resolutions so we can use `srcset` to provide smaller images on devices with smaller screens. This might be as simple as a dune rule using ffmpeg or similar and updating the HTML?

**Comment by sheykerkup** [comment]
@tmattio I have successfully set up my environment. I will like to start working on this issue.

**Comment by tmattio** [comment]
Sounds great @sheykerkup! I would suggest leaving the SVG bits and the ETag middleware out for now as they are a bit more complex. Let me know if you have any questions 🙂

**Comment by sheykerkup** [comment]
Thanks @tmattio

**Comment by sheykerkup** [comment]
> * Investigate strange `data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e` query in package overview
hi regarding this issue, is it one of the svg bits I am suppose to ignore because I do not see any strange svg in package view except the copy svg image which does not seem to work. I will put a link to the screenshot below.
![image](https://user-images.githubusercontent.com/92179262/136743377-1f559529-9c5e-4225-887d-93632e6684c5.png)
