### ISSUE TITLE
Review RSS feed scraping PR

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1183]
Reviewing scraped RSS feeds is painful 

Scraped RSS feed as stored as text files (in `data/planet`) having very long lines.

Once a story is published it is often updated a couple of times. This means only the `<updated>` tag changes.

GitHub does a poor job at presenting such changes

Here is a quick list of cheap options to make things easier

* Add newlines to the XML files.
* Make GitHub treat XML files as opaque binary
* Filter-out `<updated>` tags
* Automatically merge scraping PRs

**Comment by sabine** [comment]
Closing in favor of https://github.com/ocaml/ocaml.org/issues/1242 because we will only have markdown files in the diff - no more xml.
