### ISSUE TITLE
Syndicate https://emelle.tv/ 

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1202]
@davesnx and @fakenickels are the hosts of https://emelle.tv/

- Twitch: https://www.twitch.tv/emelletv
- YouTube: https://youtube.com/@emelletv-show

It would be nice for this to appear in ocaml.org.

**Comment by davesnx** [comment]
Thanks @cuihtlauac for opening the issue. We will need to prepare the RSS feed first, but once is working it would be great to be part of ocaml.org.

**Comment by davesnx** [comment]
Now that I think about this, maybe the YouTube RSS is good enough? https://www.youtube.com/feeds/videos.xml?channel_id=UCvVVfCa7-nzSuCdMKXnNJNQ

**Comment by tmattio** [comment]
We can use the RSS feed on watch.ocaml.org: https://watch.ocaml.org/feeds/videos.xml?videoChannelId=23

**Comment by davesnx** [comment]
That makes even more sense. Good idea @tmattio

**Comment by cuihtlauac** [comment]
Is the watch.ocaml.org feed updated manually? If it is, it may be more reliable to use the YouTube one. Less work for you?

**Comment by davesnx** [comment]
True, but I prefer to keep it manual.
