### ISSUE TITLE
Missing highlighting in docs

### ISSUE THREAD

**Issue by psb** [ocaml/ocaml.org#1211]
In ['The Representation of Integers, Tag Bits, Heap-Allocated Values'](https://ocaml.org/docs/profiling#the-representation-of-integers-tag-bits-heap-allocated-values) there is a section that mentions code highlighted in red, but there is no red highlighting:

<img width="643" alt="Screenshot 2023-05-24 at 19 39 50" src="https://github.com/ocaml/ocaml.org/assets/2823149/a12a54d0-2be6-4e9f-b37e-80e2d9e4c2aa">

The same is true for this part in ['More ~shorthand'](https://ocaml.org/docs/labels#more-shorthand):

<img width="638" alt="Screenshot 2023-05-24 at 19 45 21" src="https://github.com/ocaml/ocaml.org/assets/2823149/42a5ccca-8b4c-4d54-8e36-cff8f376fd3f">

I would try to do a pull request to fix these but I don't know if you would want the code highlighted or have the text rewritten so that it doesn't mention the highlighting.

(browser is FireFox Developer Edition; also tested on Safari)

**Comment by cuihtlauac** [comment]
Thanks, @psb; you are correct; this is inconsistent. You are more than welcome to contribute on this. What matters is to restore consistency. Highlighting is now performed automatically for OCaml and no highlighting is performed for assembly. It is going to be complex to restore colours, I suggest changing the text.
