### ISSUE TITLE
2003 May 26 incident

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1219]
At around 14:20Z, the site becomes slow/unresponsive.

@tmattio and I are seeing 502 HTTP answers, @mtelvers is not.

Package documentation pages becomes unreachable: https://ocaml.org/p/lwt/latest

Checking https://ocaml.org/dashboard shows a CPU & memory surge starting around 14:05Z. Mark confirms process `server` is eating 100% CPU. Uptime was around 8 or 9 hours.

Mark checks the logs (looked normal) and reboots (around 14:25Z). Server is quickly back online and operating normally.

During the incident, I launched a local instance. I had no problem. Suggests the problem was not cascading from https://docs-data.ocaml.org/

However, site being globally slow, but dead slow on package docs points at `ocamlorg_package`

**Comment by tmcgilchrist** [comment]
Please raise future incidents with ocaml infrastructure as issues on https://github.com/ocaml/infrastructure.

**Comment by cuihtlauac** [comment]
I'll do that

**Comment by sabine** [comment]
Closing in favor of https://github.com/ocaml/ocaml.org/issues/1268 which links back to this issue.
