### ISSUE TITLE
Preprocessors and PPXs page has 404 link

### ISSUE THREAD

**Issue by AshineFoster** [ocaml/ocaml.org#1220]
The current page links to [dune doc](https://dune.readthedocs.io/en/stable/concepts.html#preprocessing-specification) which gives a 404 error. I assume the correct link is [Preprocessing Specification](https://dune.readthedocs.io/en/stable/reference/preprocessing-spec.html).

The page with the problem is [Preprocessors and PPXs](https://ocaml.org/docs/metaprogramming) in the first section with the text `dune doc`.

**Comment by cuihtlauac** [comment]
Thanks, @AshineFoster, thanks for reporting this. Do you plan to contribute at fix?

**Comment by AshineFoster** [comment]
Pull request opened.
