### ISSUE TITLE
build error during following the first tutorial to install graphics module

### ISSUE THREAD

**Issue by zzz6519003** [ocaml/ocaml.org#1221]
<><> Error report ><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build dune       3.7.1
| - build ocamlbuild 0.14.2
| - build ocamlfind  1.9.6
+- 
+- The following changes have been performed (the rest was aborted)
| - install cmdliner 1.2.0
| - install seq      base
+- 
# Run eval $(opam env) to update the current shell environment

The former state can be restored with:
    /usr/local/bin/opam switch import
"/Users/apple/.opam/default/.opam-switch/backup/state-20230526134717.export"

**Comment by zzz6519003** [comment]
```
#=== ERROR while compiling dune.3.7.1 ==================================#
# context     2.1.4 | macos/x86_64 | ocaml.4.14.0 | https://opam.ocaml.org#93bb2e67
# path        ~/.opam/default/.opam-switch/build/dune.3.7.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml boot/bootstrap.ml -j 3
# exit-code   2
# env-file    ~/.opam/log/dune-48319-f6a466.env
# output-file ~/.opam/log/dune-48319-f6a466.out
### output ###
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
# Undefined symbols for architecture x86_64:
#   "___darwin_check_fd_set_overflow", referenced from:
#       _fdlist_to_fdset in libunix.a(select.o)
#       _fdset_to_fdlist in libunix.a(select.o)
# ld: symbol(s) not found for architecture x86_64
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "boot/duneboot.ml", line 1:
# Error: Error while building custom runtime system
```

**Comment by zzz6519003** [comment]
I might haven't install the latest version of ocaml which is 5

**Comment by cuihtlauac** [comment]
Hi, @zzz6519003, thanks for this report. Can you provide some more information about what you wanted to achieve and what you did? That would be helpful to understand what went wrong.

**Comment by gpetiot** [comment]
Looks similar to https://github.com/ocaml/dune/issues/3925
