### ISSUE TITLE
`<updated>` tags in feed.xml and 

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1230]
GitHub action `.github/workflows/scrape.yml` runs every day at 05:36. Among other things it updates the following files:
- `asset/feed.xml`
- `data/planet/*.xml`

Often, the update only replaces an `<updated>` date tag with the current date and time; the rest of the content is untouched.

This subsequently creates a vacuous pull request. We should change the logic in `tool/ood/lib/planet.ml` (see `scrape_post` and `scrape_feed` functions) to achieve the same effect without a dummy PR.

**Comment by sabine** [comment]
This issue will be obsolete when all the .xml files are removed in favor of generating the feed.xml from the markdown files at build time. Closing in favor of https://github.com/ocaml/ocaml.org/issues/1242.
