### ISSUE TITLE
Turn issues which aren't issues in discussions

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1257]
- [X] Flag @cuihtlauac issues as "this should be a discussion"
- [X] Migrate  https://github.com/ocaml/ocaml.org/labels/just%20an%20idea
- [x] Migrate https://github.com/ocaml/ocaml.org/labels/enhancement
- [x] Migrate https://github.com/ocaml/ocaml.org/labels/not%20now

Migrate instruction: https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#converting-issues-based-on-labels

**Comment by sabine** [comment]
For the enhancements, we have to weed out which ones are just ideas and which ones are clearly useful and should be done. It's a case by case basis.

I think we should tag "discussion" and then move everything tagged "discussion".

ETA: same goes for "not now". The "not now" issues that are in demand by users or which are clearly useful in the long term should remain.
