### ISSUE TITLE
Link to Specifying Functions: Two Styles gallium blog post doesn't work

### ISSUE THREAD

**Issue by rikusilvola** [ocaml/ocaml.org#1265]
Link in the RSS feed is http://gallium.inria.fr/blog/function-specs-2023-05-12
while the correct link is http://gallium.inria.fr/blog/function-specs

**Comment by sabine** [comment]
This is interesting because the link is correct in http://gallium.inria.fr/blog/index.rss, but in our markdown file we have the wrong link.

ETA: Other posts from the Gallium feed seem to be affected as well.

**Comment by Octachron** [comment]
The issue is probably that the `guid` for the RSS feed does not always match the publication url, this is in particular the case for the function specs blog post.

**Comment by sabine** [comment]
This logic in upstream `river` picks up the `guid` of the feed, because it is marked with `isPermalink="true"`:

https://github.com/kayceesrk/river/blob/2fa44943d11613a09f6f3bc92012a2b75df654d7/lib/post.ml#L212-L220

**Comment by sabine** [comment]
Was resolved by https://github.com/ocaml/ocaml.org/pull/1329.
