### ISSUE TITLE
A timeout in toplevel is needed for safer browsing

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/ocaml.org#127]
*Alternatively, we should use a custom toplevel with a limited subset of the language (most Sys things seem unneeded)*

With the introduction of #106 we're able to crash the browser page by writing an infinite loop:
```ocaml
while true do () done;;
```
at toplevel. Similarly, large outputs slow the page down.
Timeout and Truncation are often employed in most online language playgrounds. We should aim at that kind of safety as well.

On a similar note, although seems benign, we're able to get directory listings and change directories via both `Sys` and toplevel directives.

**Comment by tmattio** [comment]
Thanks @hyphenrf!

> Alternatively, we should use a custom toplevel with a limited subset of the language (most Sys things seem unneeded)

Very good idea, could you open a separate issue for this?

> On a similar note, although seems benign, we're able to get directory listings and change directories via both Sys and toplevel directives.

Is it a problem you think? The toplevel is running on the client, so it doesn't seem like a security issue to me.

**Comment by hyphenrf** [comment]
> could you open a separate issue for this?

sure!

> Is it a problem you think? The toplevel is running on the client

seems not, I'm not a security guru haha

**Comment by patricoferris** [comment]
Thanks @hyphenrf see #135 where I've split the jsoo toplevel into a web-worker which (a) means the page should always remain interactive even in the face of `while true do () done;;` and (b) we can easily terminate the worker if we don't get a timely response.

I don't think there are any security issues here, as @tmattio said it's all on the client and in fact it is a fake filesystem built into how the toplevel works :))

**Comment by patricoferris** [comment]
The toplevel now has a timeout from #135 and a separate issue exists for the other suggestions #129, thanks again for the good suggestions :))
