### ISSUE TITLE
Suggestion: a custom interactive toplevel with limited functionality

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/ocaml.org#129]
Many of the conventional functionalities provided by an ocaml toplevel (like #cd), and some of the Stdlib modules (like Sys), aren't really suitable for a quick interactive taste of the language. They only add noise to the experience.
A clean, minimal, limited and focused design may improve the user experience (and prevent certain things which may crash a conventional toplevel, see #127)

ocamlmktop can choose which modules are loaded, but as far as I'm aware, can't change directives or the startup message. A wrapper that reads and filters user inputs may be the most straightforward way to go about this. let's discuss!

**Comment by tmattio** [comment]
I'm not sure the problem this is solving or value this is adding, and this seems like a good chunk of work. Closing this for now, but feel free to continue the discussion in the issue.
