### ISSUE TITLE
OCaml 5 code samples inside markdown can't be processed by MDX

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1298]
This comes from ocamlorg being built using 4.14. MDX is using the default available compiler, not sure it can be configured to use another one.

See for instance (Section “Detecting a Data Race”): https://github.com/ocaml/ocaml.org/blob/main/data/tutorials/wf_01_debugging.md

As an interim solution, making MDX skip OCaml 5 samples seems to be the best approach. With a TODO mark. It will be stalled, but that does not seem critical until we have a ocaml5 centric docs.

**Comment by tmattio** [comment]
It should now!
