### ISSUE TITLE
Shorter path to the 4.14.x LTS release page

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml.org#1312]
Currently, OCaml 5 has still not yet reached complete feature parity with OCaml 4 (in term of supported architectures and OSs or runtime features like statmemprog or the compactor). 

To support users that rely on the missing features, the last release of the OCaml 4.14.x branch is maintained as a LTS version of OCaml 4.

However, it is currently not that straightforward to reach the release page for OCaml 4.14.x from the e `ocaml.org` front page. And the existence of such a "LTS" branch is probably not clear for people outside of the community.

Consequently, it might be a good idea to have a short link to the 4.14.x LTS version on the front page, probably with an amended release page for OCaml 4.14.1 that explains our definition of a LTS version for OCaml 4.

**Comment by sabine** [comment]
> amended release page for OCaml 4.14.1 that explains our definition of a LTS version for OCaml 4.

I struggle with this part. What is the definition of a LTS version for OCaml 4?

**Comment by Octachron** [comment]
Hm, I would suggest to focus on the practical side and note that OCaml 4 will receive bugfix updates until at least the release of OCaml 5.2 (in 2024):

> As the last version of OCaml 4, the 4.14 branch of OCaml will be maintained during the transition period for OCaml 5.
 During this period, OCaml 4.14 will receive episodic bugfix updates as a long term support branch until at least 2024.

**Comment by Octachron** [comment]
Thanks a lot for the quick update!
