### ISSUE TITLE
Cannot open website without intenet connection

### ISSUE THREAD

**Issue by AshineFoster** [ocaml/ocaml.org#1322]
I am not sure if this is the intended behaviour but I cannot open the website if I do not have an internet connection. It gives me the following when I run `make start` :
```sh
opam exec -- dune build --root .
opam exec -- dune exec src/ocamlorg_web/bin/main.exe
Saving build trace db...main.exe: [INFO] State cache file: /home/ashine/.cache/ocamlorg/package.state
main.exe: [INFO] Package state loaded (4323 packages, opam commit 01f6a0905760e389a567ee124839f7b2e4c3864e)
17.06.23 18:26:34.050                       Running on 0.0.0.0:8080 (http://localhost:8080)
17.06.23 18:26:34.050                       Type Ctrl+C to stop
fatal: unable to access 'https://github.com/ocaml/opam-repository.git/': Could not resolve host: github.com
Fatal error: exception Failure("(\"git\", \"git\" \"-C\" \"/home/ashine/.cache/ocamlorg/opam-repository\" \"pull\" \n\"-q\" \"--ff-only\" \"origin\" \"master\") exited with status 1")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Lwt.Sequential_composition.map.create_result_promise_and_callback_if_deferred.callback in file "src/core/lwt.ml", line 1966, characters 41-46
make: *** [Makefile:37: start] Error 2
```
I would like to be able to work on the website even without internet. Is there some option I can use to enable this?

**Comment by cuihtlauac** [comment]
Hi @AshineFoster; as the server needs to connect to several backends, it assumes a connection to the Internet. It should be possible to patch to enable running in a degraded mode, without access to the Internet, for debugging. Everything related to packages would be broken, but the rest could be served over localhost. I believe the errors you are seeing are coming from `src/ocamlorg_package/lib/opam_repository.ml`, this is where attempts to connect to github takes place.

Hope it helps.

**Comment by AshineFoster** [comment]
Thank you. I will try to edit that file to add an option to work offline.
