### ISSUE TITLE
package documentation search issues

### ISSUE THREAD

**Issue by hannesm** [ocaml/ocaml.org#1325]
If you search for something, such as in the url https://v3.ocaml.org/packages/search?q=tag%3A%22org%3Amirage%22 -- you don't get what you searched for in the search field, but only `tag:`.

![Screenshot 2023-06-20 at 11-31-13 OCaml Packages · Search Result](https://github.com/ocaml/ocaml.org/assets/228456/211d8839-e195-42bd-9de1-c18f337c7b17)

The text below the input field says `for "tag:"org:mirage""` correctly, though.

**Comment by sabine** [comment]
Thank you Hannes!
