### ISSUE TITLE
Avoid 404s in package docs of [latest]

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/ocaml.org#1343]
I love the `latest` option for the package docs on ocaml.org! There's one small inconvenience with it:

I think it isn't uncommon that `ocaml-doc-ci` takes a few weeks to successfully build the package documentation of of a new release. Is that right? If so, would it be feasible to modify the `latest` documentation permalink as follows? Currently, it points to the documentation of the last version, no matter whether it's a 404 or it exists. Could it instead point to the documentation of the last version that exists?

I quite often refer to the ppxlib manual as https://ocaml.org/p/ppxlib/latest/doc/index.html. E.g. I did so a few weeks ago before our last release when it still worked. Now people are telling me that I'm linking to a 404.

**Comment by sabine** [comment]
Thank you @pitag-ha, that is a really good point actually. Even when it just takes a few hours, that is too long to show a 404. We'll add a redirect to the newest versioned URL that has documentation.
