### ISSUE TITLE
Command line text hard to read in /install page

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1370]
Contrast not strong enough. Screenshot made in Chrome/Ubuntu with default settings. Same appearance observed in Android

![Screenshot_2023-07-04_10-46-07](https://github.com/ocaml/ocaml.org/assets/1917592/0f44923b-f738-4faf-81b1-d1b46cff7c1d)

**Comment by sabine** [comment]
Fixed in https://github.com/ocaml/ocaml.org/pull/1375.
