### ISSUE TITLE
Add a "clear" button for Playground output

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1382]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

# Task

It would be helpful to be able to clear the output panel of the playground.

How to solve this issue:

1. For now, clear button should be positioned in the black space next to the "Output" heading like this:

![Screenshot from 2023-10-03 14-27-22](https://github.com/ocaml/ocaml.org/assets/6594573/20180943-3a86-4cfa-b959-ce41841722bf)

2. Button style is the same as the "Get Started" button at the top of the page: `btn btn-secondary btn-sm`, and with white text color and white border: `text-white border-white`.

To render the "X" icon in the template: `<%s! Icons.close_x "h-6 w-6" %>` (height and with may need to be adjusted to match the design, I haven't checked what the correct height/width should be.

3. Effect of clicking the clear button should be to clear the innerHTML of the HTML Element with id "output":

```
document.getElementById("output").innerHTML = "";
```

**Comment by akankshat05** [comment]
Can i take up this issue?

**Comment by onuorachidimma** [comment]
Hi @sabine, can I work on this?

**Comment by AndroGenius-codes** [comment]
Can I work on this?

**Comment by SaySayo** [comment]
Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.

**Comment by AndroGenius-codes** [comment]
> Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.
![IMG_20231003_174831](https://github.com/ocaml/ocaml.org/assets/70571088/84aef63a-3667-4e0c-8095-fed4961f2856)
![IMG_20231003_173456](https://github.com/ocaml/ocaml.org/assets/70571088/670f7579-feba-466c-9971-030ab47a3240)

**Comment by SaySayo** [comment]
@AndroGenius-codes  you will be assigned this issue, let me know if you need any pointers. cc @sabine

**Comment by AndroGenius-codes** [comment]
> @AndroGenius-codes you will be assigned this issue, let me know if you need any pointers. cc @sabine

Thanks @SaySayo will sure do

**Comment by SaySayo** [comment]
For clarification purposes, are you applying for the dark mode or the GUI project? @AndroGenius-codes

**Comment by AndroGenius-codes** [comment]
@saysayo do i have to restart the server to see the changes i have made to the code.

**Comment by SaySayo** [comment]
Yes you do. You also haven't responded to my previous question @AndroGenius-codes

**Comment by AndroGenius-codes** [comment]
> Yes you do. You also haven't responded to my previous question @AndroGenius-codes

sorry just saw it. yes i am

**Comment by sabine** [comment]
Completed by https://github.com/ocaml/ocaml.org/pull/1572
