### ISSUE TITLE
Create a usable mobile view for the Playground

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1391]
The playground currently cannot be used on mobile devices. Instead of providing a mobile view, it displays a message that a mobile support is "coming soon".

This task requires making a layout inside `ocamlorg_frontend/src/pages/playground.eml` that works for the interaction with the Playground on mobile devices.

If you want to work on this, reply to this issue so we can talk a bit how this could look like.

The first step would be coming up a good layout (for example, having the code view on top, and the output window on the bottom?), and then our designer can help create styles for this layout, or you can experiment in Figma.

**Comment by kate-bagenzo** [comment]
Hi - Could I be assigned to this?

**Comment by Raven49** [comment]
can I work on this issue ? @sabine

**Comment by FatumaA** [comment]
Is there a design for this?
If so, I'd like to attempt it

**Comment by sabine** [comment]
I can ask our designer to make one, and yup, that sounds great!

**Comment by sabine** [comment]
We got a design here now: https://www.figma.com/file/eh8gAxaxrZT6RG3psHCm6M/Dark-%26-Light-mode-pages?type=design&node-id=1014%3A225&mode=dev

**Comment by FatumaA** [comment]
Nice 🚀 
I'll start on it
