### ISSUE TITLE
[doc] LaTex string displayed instead of formatted result

### ISSUE THREAD

**Issue by StonedHesus** [ocaml/ocaml.org#1398]
As pointed in the Discord channel there is a section within the documentation in which a string of LaTex code is displayed as opposed to the formatted result.

The portion in which the error is located could be found under the following section: 
https://ocaml.org/docs/if-statements-and-loops#if-statements

More specifically, it is located immediately after the following sentence: _Let's try range 9 10:_

**Comment by sabine** [comment]
If I'm not mistaken entirely, `omd` cannot render LaTeX, so we currently can't use LaTeX in the docs.

Here's what it looked like on v2.ocaml.org:

![Screenshot from 2023-07-17 08-41-25](https://github.com/ocaml/ocaml.org/assets/6594573/62b3213f-864a-4377-9334-09d50d1498f0)
