### ISSUE TITLE
Write application guides

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#140]
- [ ] Command Line Interfaces with `cmdliner`
- [ ] Web application with `dream`
- [ ] JavaScript application with `js_of_ocaml`
- [ ] Unikernel with `mirage`
- [ ] Machine Learning model with `owl`

**Comment by patricoferris** [comment]
These would all be great to have! Do you envisage them being a single, long guide per application or multi-page/step à la tutorials? If we get one out the door so the structure and HTML aspects are complete, it would be a nice thing to ask the community to contribute :)))

**Comment by tmattio** [comment]
Closing this as we'll be working on the documentation and we'll organize the work on it in the coming weeks.
