### ISSUE TITLE
Install OCaml

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#1417]
Draft: https://hackmd.io/zGcKUef_SJinRI5NW1YrfA

**Comment by christinerose** [comment]
PR:  https://github.com/ocaml/ocaml.org/pull/1431

~~Second HackMD for global edits: https://hackmd.io/5nigBVDKS7ahE57sfRLANQ?both~~ (now in PR)

**Comment by christinerose** [comment]
Added ARM Fix and Intro to opam Switches in the PR, as they're linked to from the Install doc.
