### ISSUE TITLE
Basic Data Types

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#1424]
Goal: after this tutorial, the reader is
- able to write their own variant types and records,
- with polymophism
- and recursion
- and they can define type aliases
- and pattern match on all of the types they can now define.

Draft: https://hackmd.io/jQu6NWHMTEGjiT4vgCh9Ag?view#Scope

**Comment by cuihtlauac** [comment]
My version: https://hackmd.io/cEeVRUnBQ4OEqq3w4qHJDA

**Comment by sabine** [comment]
PR: #1514

**Comment by sabine** [comment]
https://discuss.ocaml.org/t/ocaml-org-tutorial-revamping-contd-basic-datatypes/12985
