### ISSUE TITLE
Functions and Values

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#1425]

**Comment by cuihtlauac** [comment]
Work here: https://hackmd.io/@ocaml/BJvMRmJD3

Sources of inspiration:
* https://dev.realworldocaml.org/variables-and-functions.html
* https://cs3110.github.io/textbook/chapters/basics/intro.html

**Comment by sabine** [comment]
https://discuss.ocaml.org/t/ocaml-org-tutorial-revamping-cond-values-and-functions/13005
