### ISSUE TITLE
404 in digestif doc

### ISSUE THREAD

**Issue by panglesd** [ocaml/ocaml.org#143]
Some links in the [digestif doc](https://v3.ocaml.org/p/digestif/1.0.1/doc/index.html) lead to a 404 error, such as for instance [Baijiu_blake2b](https://v3.ocaml.org/p/digestif/1.0.1/doc/Baijiu_blake2b/index.html). (all `Baijiu` links have this problem except `Baijiu_sha3_256`).

**Comment by tmattio** [comment]
@jonludlam Any idea what's happening here? We have the same thing for Dream, because of the library names, but the names shouldn't cause a problem here.
