### ISSUE TITLE
Playground: loading of editor content from `#code=`  broken

### ISSUE THREAD

**Issue by just-max** [ocaml/ocaml.org#1433]
Background: The playground has the feature to share code via a URL using the "share" button, and load code that is included in the URL upon loading the page. The code is encoded in base64 and placed in the fragment identifier of the URL in the format `#code=<base64 data>`.

The problem: the playground writes the base64 string directly to the fragment identifier without URL encoding it. That would not be a problem, since the special characters in base64 (`+`, `/` and `=`) ARE safe in the fragment identifier—unlike in the query parameters, where `+` represents a space. The problem does not occur until loading the code back again: unfortunately, on line 114 the fragment identifier is interpreted as query parameters, so the `+` is parsed to a space!

https://github.com/ocaml/ocaml.org/blob/dff235aa3c0d86acbff071bfef262ee4d214764f/playground/src/main.ml#L112-L115

I would suggest not parsing the fragment identifier as key-value pairs at all—after all, these are not query parameters. Instead, I would suggest hardcoding the `#code=` prefix. This remains backwards compatible (unless people were making their own URLs with additional "query" parameters in the fragment identifier, which I don't think is very likely).

*Incidentally, try.ocamlpro.com has a similar bug: for example, the link https://try.ocamlpro.com/#rawcode/let%20x%20=%2012%20in%203%20+%20x turns the `+` into a space.*

<details>

<summary>Example/Reproduction:</summary>

Load this "code" into the playground editor:

<pre><br>| _ :: _ ->
| ->
</pre>

Note that this code snippet contains exactly one leading empty line (3 lines total + 1 trailing newline)!

Then, click the share button. The following URL is written to the browser's location/address bar: https://ocaml.org/play#code=CnwgXyA6OiBfIC0+CnwgLT4=

Now, try loading that URL in a new tab. Instead of loading the code snippet again, the default code is loaded into the editor.

For this code, trying the same loads all the code except the last `>`:

<pre><br>| _ :: _ ->
</pre>

(once again, leading newline)

</details>

**Comment by cuihtlauac** [comment]
Thanks @just-max, this is indeed a bug, and not an easy one to spot!
