### ISSUE TITLE
Mutable State / Imperative Programming

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1462]
Goal: Reader understands the different capabilities of OCaml that allow them to work with mutable state
- references
- mutable record fields
- isolating mutability / pure functions to reason about, mutable state where it's helpful

Isolate mutability in tutorials as it should be in well-architectured project. 

PR: https://github.com/ocaml/ocaml.org/pull/1529

**Comment by cuihtlauac** [comment]
This shall kill: https://ocaml.org/docs/pointers
