### ISSUE TITLE
Make the Blog more similar to the old Planet

### ISSUE THREAD

**Issue by gpetiot** [ocaml/ocaml.org#1471]
I had a few suggestions:

- in v2.ocaml.org the link to the [planet](https://v2.ocaml.org/community/planet/) is named "News", I think it was better than "Blog" especially since there are still multiple sources that are aggregated on this page, like it was the case with the planet, this is not just a single blog.

- the planet listed the syndications and it's convenient to be able to jump to some source if we want

**Comment by tmattio** [comment]
Thanks for the suggestions! I agree with both. To me, the Blog would be composed of:

- The Planet
- The Newsletters (compiler, platform, ocamlorg)
- The OCaml Changelog

But I think there's a plan to revisit this part of the site later and to conduct user research as was done for the Package area and the Learn area. Let's see how things unfold when we start work on this.
