### ISSUE TITLE
HEAD requests yield 404s

### ISSUE THREAD

**Issue by TheLortex** [ocaml/ocaml.org#148]
This is probably a Dream issue, but it's been encountered here: https://discuss.ocaml.org/t/ann-release-of-odoc-2-0-0/8582/5

Basically, `curl -sI https://v3.ocaml.org` returns 404, but `curl -sL https://v3.ocaml.org` works correctly. 
The difference ? `curl -sI` sends a `HEAD` http request, which is supposed to return the headers if a `GET` request would have been done.

**Comment by TheLortex** [comment]
After experimenting a bit, I don't know if it's `dream`'s problem. Surely it's possible to derive `HEAD`'s output from the `GET` handler, but this is not efficient when the output is large. 
For each route we should provide a `Dream.head` handler that computes the output headers either by deriving it from the `GET` handler or by doing something smarter (for static files for example we can already know the `Content-Length` in advance without loading the file)

**Comment by tmattio** [comment]
Should be relevant: https://github.com/rgrinberg/opium/blob/master/opium/src/middlewares/middleware_head.ml
