### ISSUE TITLE
Update List exercise 23: Extract a Given Number of Randomly Selected Elements From a List

### ISSUE THREAD

**Issue by calaquende** [ocaml/ocaml.org#1492]
## Overview

There seems to be an inconsistency in the recommended solution and the example answer in the exercise.
The recommended solution returns `["a"; "b"; "c"]` while the expected answer is `["g"; "d"; "a"]`.

I was wondering if it is due to the `Random` module since the problem description states that using `Random` without `Random.self_init` should allow for reproducible results. However, the closest I got to the expected answer was by applying the following steps:
1. use `Random.init 0` to explicity set the seed to 0
2. Add two `List.rev` in `extract` and on the result of `aux`.

After these steps i was able to get  `["g"; "d"; "b"]` instead of  `["g"; "d"; "a"]`, so I am not too sure if there is a bug in the solution/answer or if it an issue with my setup with Ocaml + opam that is causing this.

My setup
- ocaml version: 5.0.0
- opam version: 2.1.5
- dune version: 3.10.0

** Current exercise description, solution and modified solution below.

### Current Exercise Description/Solution

![image](https://github.com/ocaml/ocaml.org/assets/39775611/9b3e8a8b-5255-473d-90fb-00f0a0d33b20)
![image](https://github.com/ocaml/ocaml.org/assets/39775611/064fd03e-1d7b-4ba3-a336-9ba783c39ce6)

### Modified solution

This modified version of the solution returns close to the expected answer;  `["g"; "d"; "b"]` instead of  `["g"; "d"; "a"]`

```ocaml
let rand_select list n =
  Random.init 0; (* explicitly set seed to zero *)
  let rec extract acc n = function
    | [] -> raise Not_found
    | h :: t -> if n = 0 then h, List.rev acc @ t else extract (h :: acc) (n - 1) t (* reverse accumulator *)
  in
  let extract_rand list len = extract [] (Random.int len) list in
  let rec aux n acc list len =
    if n = 0
    then acc
    else (
      let picked, rest = extract_rand list len in
      aux (n - 1) (picked :: acc) rest (len - 1))
  in
  let len = List.length list in
  aux (min n len) [] list len |> List.rev (* reverse accumulated result from tail recursive helper function *)
;;
```

**Comment by tmattio** [comment]
Thanks for the report @marcfyk! Would you like to send a PR with the updated solution and the updated example? The description of the exercise can be modified to hint for "Random.init 0" as a way to make the function reproducible.
