### ISSUE TITLE
Package Search Box at top right: Nothing happens when mouse-clicking a result in Safari

### ISSUE THREAD

**Issue by frou** [ocaml/ocaml.org#1494]
This video shows the issue:

https://github.com/ocaml/ocaml.org/assets/172663/3c040061-ac11-4bc9-97e8-d8b07e93ddb5

Doesn't work in Safari (16.6). Does work in Chrome (115).

**Comment by sabine** [comment]
That's interesting and strange, thanks for reporting.

**Comment by sabine** [comment]
When the yellowish-brown circle on https://github.com/ocaml/ocaml.org/commit/533ce3bf3ea94afda7db4aa2341dae334a82f88d
![image](https://github.com/ocaml/ocaml.org/assets/6594573/46bd1147-ba33-41e7-b124-c37b43fe237c)
turns into a green checkmark, it means this patch is deployed, and it would be very helpful to know if that fixed the problem. Approx. 20 minutes from now.

**Comment by frou** [comment]
Thank you. The issue still seems to be present after that.

**Comment by frou** [comment]
For tracking let's reopen this Issue?

**Comment by sabine** [comment]
I put another attempt at fixing on staging.ocaml.org. (I have a third attempt ready to go if this one doesn't work either. Also still trying to install a macOS for testing.)

**Comment by frou** [comment]
The fix on the staging site seems to have worked. Thanks again!

**Comment by sabine** [comment]
Thanks a lot for your help @frou!
