### ISSUE TITLE
Learn menubar too wide, too many items

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1504]
Takes more that one line on my large screen, large window. 

Also, 9 items may be too many. See: https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two

![Screenshot_2023-08-21_10-47-43](https://github.com/ocaml/ocaml.org/assets/1917592/6b186bec-6fb8-4577-90e3-e2eeaed60bed)

**Comment by tmattio** [comment]
If we want to target 7 links (which I endorse), I suggest we merge Getting Started, Language and Guides into the same category.

Getting Started deserves to be highlighted, but with the button on the navbar and (presumably future) links in the overview page, I think it's enough.

**Comment by sabine** [comment]
Standard Library API and Language Manual are both not part of the design and only there temporarily.
