### ISSUE TITLE
Need more space in API documentation

### ISSUE THREAD

**Issue by Kakadu** [ocaml/ocaml.org#1506]
While scrolling API documentation it is not obvious for me which signature the documentation text belongs to. 
It could be fixed by decreasing space between English text and OCaml type. 
Brave Browser 1.56

![image](https://github.com/ocaml/ocaml.org/assets/438226/efe5a110-4188-43cc-88c9-63451331efca)

**Comment by sabine** [comment]
Agreed, it's not obvious the way it is. I reduced the spacing. Thanks!
