### ISSUE TITLE
Outreachy Winter 2021 Information

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#151]
This issue gives some information about the Outreachy application period.

If you're an Outreachy applicant who would like to contribute to the project: welcome! 🥳 

# For applicants

### Where to find issues

The good first issues should be good candidates for the application period: https://github.com/ocaml/v3.ocaml.org-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

### First Steps

First of all, to contribute to the project you'll need to get OCaml up and running. If you haven't already done that, you can have a look at the [Up and Running With OCaml](https://v3.ocaml.org/tutorials/up-and-running-with-ocaml) page on the ocaml.org site.

### How to Contribute

Once you got OCaml up and running, you can start working on an issue on one of those repos mentioned above. For that, just have a look at the conversation of the issue to see if there's already someone currently working on it. If not, you can write a quick comment stating that you'll start working on the issue and do so.

### Where to ask

The documentation might not always be straightforward. That's even more of a reason to never hesitate to ask questions! If you have a question concerning one concrete issue, you can just ask on the issue. For general questions, you can ask on Discord, which you can access via [this invitation link](https://discord.gg/fMEeySfdQd). Once you've joined Discord, if you have a question about OCaml.org or a general question that's not related to some issue, you can ask on the [Outreachy channel](https://discord.com/channels/436568060288172042/826460290367357008).

## Mentors

You have one mentor for the application period and for the internship: @tmattio. I am excited about having Outreachy applicants and later an Outreachy intern contributing to OCaml.org!

## For Non-applicants

Outreachy is an initiative to give folks from under-represented groups in open-source the opportunity to do a remote internship in an open-source project. So for open-source communities, Outreachy is a great opportunity to work together with folks from lots of different backgrounds and maybe even grow the community and become more diverse! Outreachy provides the infrastructure for the internships and application process, and the open-source communities need to provide projects and mentoring. One of the projects we -i.e. the OCaml community- is participating with in this Outreachy round consists in integrating a package health check in OCaml.org. So we might get some Outreachy applicants contributing on this repository from Oct. 8 till Nov. 5. as part of the application process to that project :)

**Credits:** This introductory issue is taken from Ppxlib, which also has an Outreachy project. Thanks @pitag-ha for the work on writing this guide!

**Comment by Simpleshell3** [comment]
Thank you @tmattio. This is vey helpful.

**Comment by victory-lydia** [comment]
Thank you @tmattio. This is helpful for me . Please I will like to ask if there is a forum for group discussion with other outreachy applicants and the mentors??

**Comment by mimi-tech** [comment]
Thank you @tmattio. I am really grateful having you as my mentor.

**Comment by tmattio** [comment]
@victory-lydia I'd recommend going to the Outreachy channel on the OCaml discord: https://discord.com/channels/436568060288172042/826460290367357008

**Comment by chepyego** [comment]
> @tmattio  i have been trying to access this but am getting something like "Email already registered" and yet i haven't sign in
  OCaml discord: https://discord.com/channels/436568060288172042/826460290367357008

**Comment by khansaUmatullah** [comment]
thank you @tmattio this is first ever detailed helpful contribution project.

**Comment by Lontchi12** [comment]
Thank you @tmattio for the detailed information, it will help us alot

**Comment by tmattio** [comment]
The application period is over, so closing this. Thank you to all of the Outreachy applicants who contributed to the project 🎉
