### ISSUE TITLE
Search bar is not large enough on desktop, e.g. on Academic Users

### ISSUE THREAD

**Issue by Khady** [ocaml/ocaml.org#1518]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

Request to be assigned to this issue only if you are applying to the Dark Mode Outreachy project.

# Task

On several pages, e.g. "Academic Users", the width of the search input box is too narrow so it looks bad.

See https://ocaml.org/academic-users:
![Screenshot 2023-10-03 at 15-24-39 Academic Users of OCaml](https://github.com/ocaml/ocaml.org/assets/6594573/8038d73a-e1a2-495a-874b-139dcddc5426)

--

How to solve this issue: 

Add appropriate `w-` Tailwind-classes (see https://tailwindcss.com) to set the width at https://github.com/ocaml/ocaml.org/blob/057450267dc605c5076c5484666f653c42ed92b7/src/ocamlorg_frontend/pages/academic_users.eml#L27C12-L27C12

Consider different screen sizes.

There are more search inputs affected by the same problem. Do look for all calls to `Form.search_input` and check that they all have a width assigned.

Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

**Comment by akankshat05** [comment]
can i work on this issue?

**Comment by sabine** [comment]
How to solve this issue: 

Add appropriate `w-` Tailwind-classes (see https://tailwindcss.com) to set the width at https://github.com/ocaml/ocaml.org/blob/057450267dc605c5076c5484666f653c42ed92b7/src/ocamlorg_frontend/pages/academic_users.eml#L27C12-L27C12

Consider different screen sizes.

There are more search inputs affected by the same problem. Do look for all calls to `Form.search_input` and check that they all have a width assigned.

**Comment by SaySayo** [comment]
Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.

**Comment by SwizzCoder** [comment]
Hello @sabine @SaySayo 
Can I be assigned to this issue?

I have successfully setup OCaml on my computer and also installed `dream` and I have also done the `hello world` tutorial and other tutorials. 
Here is a screenshot of my modified `hello world`:

<img width="596" alt="image" src="https://github.com/ocaml/ocaml.org/assets/112827178/9bde7059-2000-4e89-9f71-26ea05b94af2">

**Comment by SaySayo** [comment]
@SwizzCoder, you will be assigned this issue. Let me know if you need any help. cc @sabine, @gpetiot

**Comment by SaySayo** [comment]
For clarification purposes, are you applying for the dark mode or the GUI project? @SwizzCoder

**Comment by SwizzCoder** [comment]
@SaySayo I am applying for the Dark Mode project.
