### ISSUE TITLE
documentation for eio 0.12 is missing

### ISSUE THREAD

**Issue by tysg** [ocaml/ocaml.org#1519]
https://ocaml.org/p/eio/0.12/doc/Eio/index.html

**Comment by gasche** [comment]
Note: it looks like the 0.11 documentation [is available](https://ocaml.org/p/eio/0.11/doc/index.html).

(I got there in a weird way, https://ocaml.org/p/eio/latest shows a button that says "! No Docs", and if you click on it you are somehow redirected to the 0.11 documentation.)

**Comment by tmattio** [comment]
This issues is also tracked at https://github.com/ocaml/infrastructure/issues/73

**Comment by tysg** [comment]
The documentation linked is now available. If the root cause is tracked in https://github.com/ocaml/infrastructure/issues/73, I will proceed to close this particular issue.
