### ISSUE TITLE
Hint to contribute a job post

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#1523]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

# Task

It is currently not possible to learn how to contribute a job post to https://ocaml.org/jobs without reading the contributing guide on GitHub.

If we want more companies to add job posts there, we should add a hint on how they can do so on the job board directly.

It could take the form of a link to the relevant section of the contributing guide.

--

How to do this:

1. add an achor around the title of the jobs section in [CONTRIBUTING.md](https://github.com/ocaml/ocaml.org/blob/main/CONTRIBUTING.md)
```
<a name="jobs">...</a>
```

2. add a link to https://github.com/ocaml/ocaml.org/blob/main/CONTRIBUTING.md#jobs to [src/ocamlorg_frontend/pages/jobs.eml](https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_frontend/pages/jobs.eml)

**Comment by sabine** [comment]
How to do this:

1. add an achor around the title of the jobs section in [CONTRIBUTING.md](https://github.com/ocaml/ocaml.org/blob/main/CONTRIBUTING.md)
```
<a name="jobs">...</a>
```

2. add a link to https://github.com/ocaml/ocaml.org/blob/main/CONTRIBUTING.md#jobs to [src/ocamlorg_frontend/pages/jobs.eml](https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_frontend/pages/jobs.eml)

**Comment by biroue10** [comment]
@sabine, could you assign me this task? I have already completed the instructions in #1553.

**Comment by SaySayo** [comment]
Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.

**Comment by biroue10** [comment]
yes i do.
![image](https://github.com/ocaml/ocaml.org/assets/27910604/2885006d-d095-4953-9bbb-797baa7cf979)
![image](https://github.com/ocaml/ocaml.org/assets/27910604/ee4ac1d7-8e54-442c-8a55-dced8d2d1e2a)
these are the screnshot of hello world and my console

**Comment by biroue10** [comment]
![image](https://github.com/ocaml/ocaml.org/assets/27910604/52fbe88b-6128-4aa0-b606-a6ed4f0ff680)
this is ocaml.org running locally

**Comment by SaySayo** [comment]
@biroue10, you will be assigned this issue, let me know if you need any pointers. cc @sabine

**Comment by biroue10** [comment]
@SaySayo Of course! Yes, I would like to have some guidance, thank you.

**Comment by SaySayo** [comment]
@biroue10, you can get started by going on the `jobs.eml` file and making the changes

**Comment by biroue10** [comment]
@SaySayo i already completed this task you can check please

**Comment by SaySayo** [comment]
For clarification purposes, are you applying for the dark mode or the GUI project? @biroue10

**Comment by biroue10** [comment]
@SaySayo i am applying for dark mode project
