### ISSUE TITLE
Refactor `location` type to a single `Location.t`

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#153]
Currently we use `type location` in two places

 - https://github.com/ocaml/v3.ocaml.org-server/blob/21a140f9f7133ab9878a48add71276a7cc6ecebd/tool/ood-gen/lib/academic_institution.ml#L1
 - https://github.com/ocaml/v3.ocaml.org-server/blob/262808e10d52e9d79320425f94756cc0385d1482/tool/ood-gen/lib/meetup.ml#L1

It would be nice to refactor this into a standalone, reusable module as I'm sure we might end up redefining it again if we want map coords for some other piece of data.

**Comment by MuluhGodson** [comment]
@tmattio @patricoferris 
With regards to this, the location has two variables, lat and lon. 
Would that be something like :

```
module Location = struct
  type t = {
    lat : float;
    lon : float;
  }
end
```

**Comment by tmattio** [comment]
@MuluhGodson Yup, it looks like that's the type it should have

**Comment by oabdulhamid1** [comment]
Hi @tmattio can I work on this project?

**Comment by gs0510** [comment]
@oabdulhamid1 Is your environment set up already? We're asking applicants to get up and running before being assigned to an issue.

**Comment by oabdulhamid1** [comment]
Hi,

Yes I already set up my environment.

**Comment by gs0510** [comment]
@oabdulhamid1 Sure in that case you can go ahead and work on this :)

**Comment by oabdulhamid1** [comment]
Hi,

Kindly check my contribution I have push to GitHub.

Regards

**Comment by patricoferris** [comment]
Hi @oabdulhamid1,

Could you make a PR of your work to this repository please. It makes it easier to review and will also try to build on our CI too ?

Thanks :)

**Comment by oabdulhamid1** [comment]
Hi,

Not yet will try that.

Regards

**Comment by oabdulhamid1** [comment]
Hi,
PR made.

Regards

**Comment by tmattio** [comment]
I'd suggest waiting for it to be duplicated before we refactor. Let's close it and re-open when we want to do it.
