### ISSUE TITLE
Renaming “language” sections

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1532]
Here is the renaming I have in mind

- Learn                      --> Language
  - Overview
  - Get Started
  - Language                 --> Learn
    - LANGUAGE               --> Syntax and Semantics
    - DATA STRUCTURES
    - RUNTIME
    - METAPROGRAMMING 
  - Platform Tools
  - Guides
  - Exercises
  - Books
  - Language Manual          --> Reference Manual
- Packages
- Community
- Blog
- Playground

I think the top-level “Learn” section is misnamed. It contains information on how to learn OCaml but is not limited to learning from scratch, it also contains reference information.

**Comment by sabine** [comment]
The renaming we could consider is from "Learn" to "Docs", but that discussion would better be had somewhere else. Closing.
