### ISSUE TITLE
Loading symbol as toplevel worker is loaded

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#154]
Currently, on the home page we have one javascript file for the toplevel which is loaded immediately. This sets up some of the core UI functionality. After clicking on `Click to load toplevel` this loads in a web worker that runs the actual toplevel executions of OCaml expressions. 

There's a brief moment where the web worker hasn't fully loaded but is now interactive (i.e. we have set `disabled` to `false` https://github.com/ocaml/v3.ocaml.org-server/blob/main/src/ocamlorg_toplevel/lib/toplevel.ml#L210). Eventually the initial OCaml and jsoo versions are printed. It might be nice to have a loading symbol until that happens.

This is more of a `medium` issue as it requires some js_of_ocaml knowledge, but the scope is quite small, so for now I'll mark it as a potential good first issue.

**Comment by chinwepr** [comment]
Hi Patricoferris. i am am outreachy applicant. please can i work on this issue?''

**Comment by tmattio** [comment]
@chinwepr Is your environment set up already? We're asking applicants to get up and running before being assigned to an issue.

**Comment by chinwepr** [comment]
@tmattio   I'm setting my environment up but I'm getting an error when I run make switch.

I'm using windows 10. I installed the graphical installer for Ocaml for windows, forked and cloned the repository. But when I run make switch in the project folder I get the following error message "opam switch create . 4.13.0 --no-install
process_begin: CreateProcess(NULL, opam switch create . 4.13.0 --no-install, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [create_switch] Error 2"

Any information on how to proceed would be highly appreciated

**Comment by patricoferris** [comment]
Hi @chinwepr :)) 

With windows you'll have much better luck if you use WSL2, this will run a Linux environment on windows (OCaml does not *officially* support windows... yet!). Here are some instructions:

 - Installation: https://docs.microsoft.com/en-us/windows/wsl/install
 - Editor support: https://code.visualstudio.com/blogs/2019/09/03/wsl2
 - Our old site has some useful docs about using WSL2 too: https://github.com/ocaml/ocaml.org/blob/master/CONTRIBUTING.md#windows-some-common-errors-while-building-the-site-using-wsl

**Comment by chinwepr** [comment]
Thanks very much @patricoferris. I'll try it out right away and give you feedback

**Comment by chinwepr** [comment]
Hi @patricoferris I'm trying to set up my environment but I keep getting the error "The following actions failed
│ λ build ocaml-base-compiler 4.11.1.  ocaml-base-compiler.4.11.1 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead."

Pls what should I do

**Comment by patricoferris** [comment]
Thanks for trying to get setup :)) When hitting problems like this it is _always_ useful to provide as much information as possible (whatever you think is obvious probably isn't) so for example:

 - Is this using WSL2 or something else?
 - What command did you run to end up with this error? What series of commands were there prior to this and did they all work?
 - Is this the full error, on Github you can use markdown syntax to format a little nicer with backticks (`). 3 backticks lets you paste this kind of output in a more readable way.

**Comment by chinwepr** [comment]
Thanks for the response. I installed ubuntu 20.04 LTS on wsl2.

After that I installed opam using sudo apt-get install opam.

Then I followed the guide on installing Ocaml given at [](https://v3.ocaml.org/tutorials/up-and-running-with-ocaml#installing-ocaml) and ran opam init and then opam switch create 4.11.1 and ended up with the following error

```
     bwrap: Creating new namespace failed: Permission denied
    
    
    
    <><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    ┌─ The following actions failed
    │ λ build ocaml-base-compiler 4.11.1
    └─
    ┌─ The following changes have been performed (the rest was aborted)
    │ ∗ install base-bigarray base
    │ ∗ install base-threads  base
    │ ∗ install base-unix     base
    └─
    
    <><> ocaml-base-compiler.4.11.1 troubleshooting <><><><><><><><><><><><><><><><>
    => A failure in the middle of the build may be caused by build parallelism
          (enabled by default).
          Please file a bug report at https://github.com/ocaml/opam-repository/issues
    => You can try installing again including --jobs=1
          to force a sequential build instead.
    # Run eval $(opam env --switch=4.11.1) to update the current shell environment
    Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n]
```

**Comment by patricoferris** [comment]
Thanks! This is much more useful and I can see the problem (I think...) straight away. I think for WSL2 you need to `opam init --disable-sandboxing` because the `bwrap` sandboxing is not supported (the old v2 docs explained that a little: https://github.com/ocaml/ocaml.org/blob/master/CONTRIBUTING.md#windows-some-common-errors-while-building-the-site-using-wsl). 

Also once `opam init --disable-sandboxing` succeeds you don't need to make a `4.11.1` switch just `cd` into the v3 project and run `make switch` :))

**Comment by chinwepr** [comment]
> 
> 
> Thanks! This is much more useful and I can see the problem (I think...) straight away. I think for WSL2 you need to `opam init --disable-sandboxing` because the `bwrap` sandboxing is not supported (the old v2 docs explained that a little: https://github.com/ocaml/ocaml.org/blob/master/CONTRIBUTING.md#windows-some-common-errors-while-building-the-site-using-wsl).
> 
> Also once `opam init --disable-sandboxing` succeeds you don't need to make a `4.11.1` switch just `cd` into the v3 project and run `make switch` :))

Hello. I followed the instructions. I ran opam init --disable-sandboxing and make switch. When I ran make start I got the error command not found 'dune'

```
opam exec -- dune build --root .
[WARNING] Running as root is not recommended
[ERROR] Command not found 'dune'
make: *** [Makefile:26: all] Error 127
```

**Comment by patricoferris** [comment]
It looks like `make switch` didn't complete without errors -- was that the case ? I'm guessing this because the error points to missing dependencies (i.e. no `dune`). You can try `make deps` and paste any errors you come across. It's always useful to check whether or not a command you ran completed correctly by reading the output and you can also check the return status of the previous command you ran with `echo $?` -- anything other than 1 tends to mean something went wrong

**Comment by chinwepr** [comment]
The command `make deps` finished with the following error report

```
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build conf-pkg-config     2
│ λ build ocaml-base-compiler 4.13.0
└─
╶─ No changes have been performed

<><> ocaml-base-compiler.4.13.0 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env) to update the current shell environment
make: *** [Makefile:30: deps] Error 31
```

And the command `echo $?` returned 0

**Comment by patricoferris** [comment]
> It looks like make switch didn't complete without errors -- was that the case ? 

Was this the case? It looks like no compiler was installed at all given `make deps` from this error message is trying to install a `4.13.0` compiler (the `make switch` step should have already done this, see here: https://github.com/ocaml/v3.ocaml.org-server/blob/main/Makefile#L36). This is also I think just the tail-end of the error log, it would be useful to get the whole thing (pasted here or in github gist). For example here https://github.com/ocaml/v3.ocaml.org-server/issues/154#issuecomment-946668607 it was just that top line that pointed to the problem. Sorry about all these issues : /

**Comment by chinwepr** [comment]
@patricoferris Thanks for being really helpful. `make switch` actually completed with the following error
```
opam switch create . 4.13.0 --no-install
[WARNING] Running as root is not recommended
[ERROR] There already is an installed switch named /mnt/d/Documents/outreachy/v3.ocaml.org-server
make: *** [Makefile:36: create_switch] Error 2
```
Below is the full error message returned by `make deps`
```
#=== ERROR while compiling ocaml-base-compiler.4.13.0 =========================#
# context     2.1.0 | linux/x86_64 |  | https://opam.ocaml.org#443b52a1
# path        /mnt/d/Documents/outreachy/v3.ocaml.org-server/_opam/.opam-switch/build/ocaml-base-compiler.4.13.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix=/mnt/d/Documents/outreachy/v3.ocaml.org-server/_opam -C
# exit-code   1
# env-file    ~/.opam/log/ocaml-base-compiler-1533-bc7b57.env
# output-file ~/.opam/log/ocaml-base-compiler-1533-bc7b57.out
### output ###
# bwrap: Creating new namespace failed: Permission denied


#=== ERROR while compiling conf-pkg-config.2 ==================================#
# context     2.1.0 | linux/x86_64 |  | https://opam.ocaml.org#443b52a1
# path        /mnt/d/Documents/outreachy/v3.ocaml.org-server/_opam/.opam-switch/build/conf-pkg-config.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build pkg-config --help
# exit-code   1
# env-file    ~/.opam/log/conf-pkg-config-1533-6c64c3.env
# output-file ~/.opam/log/conf-pkg-config-1533-6c64c3.out
### output ###
# bwrap: Creating new namespace failed: Permission denied



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build conf-pkg-config     2
│ λ build ocaml-base-compiler 4.13.0
└─
╶─ No changes have been performed

<><> ocaml-base-compiler.4.13.0 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env) to update the current shell environment
make: *** [Makefile:30: deps] Error 31
```

**Comment by patricoferris** [comment]
No worries, we'll work it out soon! Ah I see, so the `--disable-sandboxing` won't update the existing opam configuration if you have already init-ed unless you ask it to do so (I know this from experience :)). I think you have two options:

1. Run `opam init --reinit --disable-sandboxing`
2. Start completely from scratch with WSL2 and run `opam init --disable-sandboxing`

Then try again. Even without previous experience here is some explanation as to how you can work out these errors. Firstly we can see the problem:

```
### output ###
# bwrap: Creating new namespace failed: Permission denied
```

Which if you search for exactly that error one of the first things that comes up (at least for me) is: https://discuss.ocaml.org/t/bwrap-failed-to-make-slave-permission-denied/6750

This looks very much like what's going on here (not exactly, but close enough), with the author of that post specifying: 

> It seems there is problem with bwrap. I tried to do opam init --disable-sandboxing and create switch again. Nothing changed.

And an answer being given of:

> opam init --disable-sandboxing should avoid the issue. But you need to erase the ~/.opam/ directory left over from your previous opam init, otherwise the second init is useless.

This is option (2) from above

**Comment by chinwepr** [comment]
> 
> 
> No worries, we'll work it out soon! Ah I see, so the `--disable-sandboxing` won't update the existing opam configuration if you have already init-ed unless you ask it to do so (I know this from experience :)). I think you have two options:
> 
>     1. Run `opam init --reinit --disable-sandboxing`
> 
>     2. Start completely from scratch with WSL2 and run `opam init --disable-sandboxing`
> 
> 
> Then try again. Even without previous experience here is some explanation as to how you can work out these errors. Firstly we can see the problem:
> 
> ```
> ### output ###
> # bwrap: Creating new namespace failed: Permission denied
> ```
> 
> Which if you search for exactly that error one of the first things that comes up (at least for me) is: https://discuss.ocaml.org/t/bwrap-failed-to-make-slave-permission-denied/6750
> 
> This looks very much like what's going on here (not exactly, but close enough), with the author of that post specifying:
> 
> > It seems there is problem with bwrap. I tried to do opam init --disable-sandboxing and create switch again. Nothing changed.
> 
> And an answer being given of:
> 
> > opam init --disable-sandboxing should avoid the issue. But you need to erase the ~/.opam/ directory left over from your previous opam init, otherwise the second init is useless.
> 
> This is option (2) from above

Hi @patricoferris I followed step 1 above; deleted `~/.opam/` directory, ran `opam init --reinit --disable-sandboxing` and ended up with the same error. 

Then I got a different laptop installed Ubuntu 20.04 LTS on it, followed step 2 but yet ended up with same exact issue. I don't know, there must be something I'm missing

**Comment by patricoferris** [comment]
Hmm strange, I just tried it cleanly on a windows machine and here's my experience:

 - Opened command prompt with admin and ran `wsl --install` and rebooted
 - Filled in various ubuntu specific questions after reboot to setup a user
 - Ran `sudo apt-get update` to update system packages (probably not required)
 - Ran the [opam install script](https://opam.ocaml.org/doc/Install.html#Binary-distribution) i.e. the thing that starts `bash -c`
 - Ran `opam init --disable-sandboxing` and opam said I didn't have `unzip` and `make` and `cc` so I ran `sudo apt-get install unzip make gcc`
 - Ran `opam init --disable-sandboxing` again all went well.
 - Ran `git clone <my-v3-fork>` and `cd`-ed into it
 - Ran `make switch` started making switch and answered `Y` to all of the questions opam asked me
 - Makefile complained I didn't have `npm` installed, so installed `nvm` from [here](https://github.com/nvm-sh/nvm/blob/master/README.md#install--update-script)
 - Ran `source ~/.bashrc` and `nvm install 16`
 - Ran `make deps` which is the make target that failed when we couldn't find `npm` which we now have. 
 - Ran `make start` navigated to `localhost:8080` and all seemed okay
 
 Is this similar to your experience? I'm not sure what more I can do? I'll update the docs with some of this soon.

**Comment by chinwepr** [comment]
> 
> 
> Hmm strange, I just tried it cleanly on a windows machine and here's my experience:
> 
>     * Opened command prompt with admin and ran `wsl --install` and rebooted
> 
>     * Filled in various ubuntu specific questions after reboot to setup a user
> 
>     * Ran `sudo apt-get update` to update system packages (probably not required)
> 
>     * Ran the [opam install script](https://opam.ocaml.org/doc/Install.html#Binary-distribution) i.e. the thing that starts `bash -c`
> 
>     * Ran `opam init --disable-sandboxing` and opam said I didn't have `unzip` and `make` and `cc` so I ran `sudo apt-get install unzip make gcc`
> 
>     * Ran `opam init --disable-sandboxing` again all went well.
> 
>     * Ran `git clone <my-v3-fork>` and `cd`-ed into it
> 
>     * Ran `make switch` started making switch and answered `Y` to all of the questions opam asked me
> 
>     * Makefile complained I didn't have `npm` installed, so installed `nvm` from [here](https://github.com/nvm-sh/nvm/blob/master/README.md#install--update-script)
> 
>     * Ran `source ~/.bashrc` and `nvm install 16`
> 
>     * Ran `make deps` which is the make target that failed when we couldn't find `npm` which we now have.
> 
>     * Ran `make start` navigated to `localhost:8080` and all seemed okay
> 
> 
> Is this similar to your experience? I'm not sure what more I can do? I'll update the docs with some of this soon.


I followed this procedure, step by step, and it worked.

My environment is now set up and I am now ready to start making contribution. I am looking forward to learning as much as possible about this project also.

Thanks very much @patricoferris

**Comment by tmattio** [comment]
This has been done I believe. Closing now.
