### ISSUE TITLE
 Setting Up VsCode is 404

### ISSUE THREAD

**Issue by Kakadu** [ocaml/ocaml.org#1542]
On the https://ocaml.org/docs there is a link to https://ocaml.org/docs/setting-up-vscode (Platform -> Setting Up VsCode)
which is 404

the same for staging 

CC @sabine

**Comment by echuber2** [comment]
I think I noticed the same thing. I was hoping this would fix it: https://github.com/ocaml/ocaml.org/pull/1552

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1552
