### ISSUE TITLE
Explicitely show broken reference in package documentation

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml.org#1547]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

# Task

Currently, broken references in the package documentation are not easy to notice. We should add some CSS to highlight them.

[Here's a page](https://ocaml.org/p/cmarkit/0.2.0/doc/Cmarkit_html/index.html) with such a broken reference ("a quick example").

What you need to do:

Add CSS to https://github.com/ocaml/ocaml.org/blob/main/asset/css/doc.css to style the broken references:

```
.xref-unresolved {
    ...
}
```

Broken reference should be styled to look like this:

![Screenshot from 2023-10-03 10-31-47](https://github.com/ocaml/ocaml.org/assets/6594573/17a75aae-f085-499a-acbb-39ba392e52f8)

**Comment by sabine** [comment]
Issue can be resolved by adding CSS to https://github.com/ocaml/ocaml.org/blob/main/asset/css/doc.css as suggested in the post above this one.

Link should be styled to look like this:

![Screenshot from 2023-10-03 10-31-47](https://github.com/ocaml/ocaml.org/assets/6594573/17a75aae-f085-499a-acbb-39ba392e52f8)

**Comment by oyenuga17** [comment]
Hi @sabine Please I'm interested in working on this issue. I have read through the [Outreachy Winter 2023 - 2024 doc](https://github.com/ocaml/ocaml.org/issues/1553), and I have successfully ran the hello-world project

**Comment by SaySayo** [comment]
Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.

**Comment by oyenuga17** [comment]
> Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.


<img width="1532" alt="Screenshot 2023-10-03 at 16 21 57" src="https://github.com/ocaml/ocaml.org/assets/64274826/3c83397b-1ccd-41d4-83cd-dc9cc78181d8">
<img width="1536" alt="Screenshot 2023-10-03 at 16 22 17" src="https://github.com/ocaml/ocaml.org/assets/64274826/265cfbb2-03f6-4a08-97ad-f72e16beeeed">

@SaySayo

**Comment by SaySayo** [comment]
@oyenuga17  you will be assigned this issue, let me know if you need any pointers. cc @sabine
