### ISSUE TITLE
Outreachy Winter 2023-2024

### ISSUE THREAD

**Issue by gpetiot** [ocaml/ocaml.org#1553]
Hi all,

here's some information about the Outreachy application period. First of all: welcome! :wave: 

For non-applicants confused by this issue, see [this section](#For-Non-applicants).

## For applicants

Thanks for contributing to the OCaml ecosystem! This is the right place to start, if you're considering applying to any of the following Outreachy projects:

- Implement a dark mode for OCaml.org
- Improve the GUI experience for OCaml users

### Quick Installation

The quickest way to install OCaml currently is using the OCaml Platform Installer.

You'll need to install some dependencies if they're not already installed. This can be done easily using a package manager.

If you're running an Ubuntu/Debian system you can run the following command in your terminal. If you're using Windows, here are the [specific instructions](https://ocaml.org/docs/ocaml-on-windows), but it is probably easier and quicker to use WSL2 on Windows and then using the Linux/macOS instructions.

```
sudo apt install bzip2 make gcc bubblewrap rsync patch curl unzip
```

After your dependencies are installed run the below install script.

```
bash < <(curl -sL https://ocaml.org/install-platform.sh)
```

Install the Platform tools.

```
ocaml-platform
```

### Other Installation Methods

If the OCaml Platform installation method does not suit you then you can take a look at the other installation methods described on ocaml.org: [here](https://ocaml.org/install) or [there](https://ocaml.org/docs/up-and-running#installing-ocaml).

## Contributions

Before being able to fully contribute to the project, here are simple steps you must follow!

## First step: seting up OCaml

If you want to apply to any of the those projects, the first step for you will be to compile OCaml. Please, read through [Installing OCaml on Your System](#Installing-OCaml-on-Your-System). If you're using Windows, here are the [specific instructions](https://ocaml.org/docs/ocaml-on-windows), but it is probably easier and quicker to use WSL2 on Windows and then using the Linux/macOS instructions.

Now you should be able to go through the basics of OCaml, please follow this tutorial: [Your First Day with OCaml](https://ocaml.org/docs/first-hour).

For more details about the OCaml language you can read this guide [about the language](https://ocaml.org/docs/language).

Try to pick up a few [exercises to practice](https://ocaml.org/problems) along the way!

## Second step: seting up ocaml.org locally

Once OCaml is successfully installed, you also need to install an opam switch that uses a version of OCaml that ocaml.org currently supports, and install the dependencies.

If you are not familiar with Github, a good practice is to fork a repository before working on it. Go on the [ocaml.org repository](https://github.com/ocaml/ocaml.org) and click on [fork](https://github.com/ocaml/ocaml.org/fork).

You can now clone your fork (https://github.com/USERNAME/ocaml.org) to get a local copy of it:
`git clone git@github.com:USERNAME/ocaml.org.git` (of course replace `USERNAME` with your actual github username, without the `@`).

Add the original repository as the "upstream" remote:
```
cd ocaml.org
git remote add upstream git@github.com:ocaml/ocaml.org.git
```

Once you have a local repository, let's build:
```
make switch
```

To locally run the ocaml.org website, simply run:

```
make start
```

You should then be able to open the website in your browser at the following URL `http://localhost:8080`.

Once you've achieved that, please let us know here on the issue that you have. And if you have troubles with it, don't hesitate to ask!

## Third step: a *good first issue*

Once you got the website to run locally, you're ready to start contributing. Where to find good issues to work on depends on the project you want to apply to.

#### To be assigned an issue for this project, every applicant must complete the following steps
- Try out the [hello world](https://github.com/aantron/dream/tree/master/example/1-hello) example on the Dream repository. This will give you a preview of how the ocaml.org website is built! Please make sure you are able to run the example locally before asking to contribute on the main repository and don't hesitate to reach out if you have any questions or need any help. Also feel free to try out any more of the Dream examples if you like!

#### To be assigned an issue for this project, every applicant must complete the following steps
- Try out the [hello world](https://github.com/aantron/dream/tree/master/example/1-hello) example on the Dream repository. This will give you a preview of how the ocaml.org website is built!  Also feel free to try out more of the Dream examples!
  + Tips: don't forget to fork the repository first, then clone locally before building 
- Try out the [hello world](https://github.com/sanette/bogue#hello-world) example on the bogue repository. This will give you a preview of how to set up and build a project with `dune`.
  + Tips: don't forget to fork the repository first, then clone locally before building
  + install the library with `dune`
  + [create a new project with `dune`](https://dune.readthedocs.io/en/latest/quick-start.html#initializing-projects)
  + edit the `dune`, `dune-project` and source files accordingly
  + build the hello-world example

Please make sure you are able to run these examples locally before asking to be attributed an issue on the main repository and don't hesitate to reach out if you have any questions or need any help.

## Ask Questions!

You are bound to get stuck somewhere and that's perfectly fine because that means you're moving towards progress!

If you don't know how to move forward with the problem you're stuck with then don't hesitate to ask .

For general questions, you can ask on discord, which you can access via [this invitation link](https://discord.gg/fMEeySfdQd). Once you've joined discord, if you have a question about ocaml.org you can ask on the [ocaml.org channel](https://discord.com/channels/436568060288172042/1126433906976112700). If you have a general question about something else, e.g. how to get OCaml up and running, you can ask on another discord channel, for example on the [Outreachy channel](https://discord.com/channels/436568060288172042/826460290367357008).

Happy hacking :)

## Mentors

You have 4 mentors for the application period: @SaySayo, @punchagan, @moazzammoriani and @gpetiot

We're all very excited about having Outreachy applicants and later Outreachy interns contributing to the OCaml ecosystem! On weekends we tend to be non- or less available.

## For Non-applicants

[Outreachy](https://www.outreachy.org/) is an initiative to give folks from under-represented groups in open-source the opportunity to do a remote internship in an open-source project. So for open-source communities, Outreachy is a great opportunity to work together with folks from lots of different backgrounds and maybe even grow the community and become more diverse! Outreachy provides the infrastructure for the internships and application process, and the open-source communities need to provide projects and mentoring. 

Two of the projects we -i.e. the OCaml community- are participating with in this Outreachy round are ocaml.org related. So we might get some Outreachy applicants contributing to this repository from **December 4, 2023** till **March 1, 2024** as part of the application process to those projects :)

## A Note on Using ChatGPT and Generative AI for Contributions

We, the mentors for ocaml.org-related projects, have discussed the role of ChatGPT and generative AI during this contribution period and have identified some of the following--non-exhaustive list of--problems in using this technology to contribute.

We don't want these tools to be substitutes for your judgement and understanding.
We don't want your responsibility to be deferred to these tools since they are often wrong and hence unreliable.
We want to make sure mentors spend their time and efforts helping you improve and learn.

### Your judgement and understanding

We don't want contributors to be using generated contributions in situations where we want you to make your judgement. Submitting generated code with little or no understanding as a contribution would be an extreme case of this.

We think if you make a contribution you should be exercising your own judgement and trying your best to solve some problem. Your effort and hard-work are the true essence of any contribution.

Borrowing code has almost always been fine, but even when you do that you are expected to make the judgement to borrow it in the first place. It also is still your responsibility to test that code and abstractly know why that code is there to begin with.

### Responsibility

A large part of open-source involves is about taking on responsibility. We think that use of these tools should not take away from that.

### Mentor time

With all the contributions, the mentor would be trying to read through this contribution and provide any feedback so that the contributor can learn from this and improve. This takes time and effort on the mentor's part. This would be wasted if they realize half-way that the code was AI-generated.

Mentors want to help you learn and improve. This is difficult or even impossible to do if you don't show them your own work.

### Concluding remarks
We only request you to be mindful of all this.

If you happened to use ChatGPT for something like brain-storming ideas for a contribution, that's ok. We ask you in that case to let your mentor know. Giving them the heads up might help them save time and even put you in a better position of trust.

**Comment by andrew21-mch** [comment]
thanks @gpetiot, 
I tried following these stup but got stock at make switch, 

I dropped a comment in the ocaml.org discord channel 
https://discord.com/channels/436568060288172042/1126433906976112700/1158330346144792606

please can you help, I am trying to setup

**Comment by andrew21-mch** [comment]
Hey guys, i think i got a fix for Kali, maybe it might work for you, 
check this out on discord

https://discord.com/channels/436568060288172042/1126433906976112700/1158371913207394356

**Comment by SwizzCoder** [comment]
Thanks for the setup guide. I have successfully setup OCaml on my machine and also the `ocaml.org` repo. 

<img width="1280" alt="image" src="https://github.com/ocaml/ocaml.org/assets/112827178/c0d5e183-ea70-4de2-b420-5e3fb7f2dee3">

**Comment by ikeadeoyin** [comment]
While working on the the second step, I got stuck at `make switch` with the error `No rule to make target switch. Stop`

<img width="617" alt="Screenshot 2023-10-02 at 20 34 48" src="https://github.com/ocaml/ocaml.org/assets/36523905/c0309975-4cd5-4000-9340-4b19972428b4">


Fix: Clone the OCaml repository and run the make switch command. You can check this guide for more details.

[https://github.com/ocaml/ocaml.org/blob/main/HACKING.md](https://github.com/ocaml/ocaml.org/blob/main/HACKING.md)

**Comment by biroue10** [comment]
thank you for the guide ocaml.org has been install sucessfully locally
![image](https://github.com/ocaml/ocaml.org/assets/27910604/9d94ab2b-18bd-44a2-a276-3ded543748bb)

**Comment by Hikmot-O** [comment]
@biroue10 can you explain how you went about it please. I'm using windows please

**Comment by Mankavelda** [comment]
Thank you @gpetiot for the directions.
![Screenshot from 2023-10-03 02-40-25](https://github.com/ocaml/ocaml.org/assets/95079621/69887e32-bc58-47e2-a502-0c34b3f48ae0)
 I succeeded in my installation, but can't run the make switch or make start command. Please can anyone help me on the next steps?

**Comment by SaySayo** [comment]
@Mankavelda did you update your opam environment by running `eval $(opam env)`

**Comment by Mankavelda** [comment]
> @Mankavelda did you update your opam environment by running `eval $(opam env)`

Yes, and I get this error on running make start
![Screenshot from 2023-10-03 08-44-52](https://github.com/ocaml/ocaml.org/assets/95079621/3729156b-a6b2-4c1b-9f01-e8bc2c9f828a)

**Comment by ikeadeoyin** [comment]
@Mankavelda I had the same issue, you can try this fix.
https://github.com/ocaml/ocaml.org/issues/1553#issuecomment-1743830781

**Comment by AndroGenius-codes** [comment]
I had this issue when I do make start 
![Uploading IMG_20231003_122405.jpg…]()

**Comment by AndroGenius-codes** [comment]
![IMG_20231003_122405](https://github.com/ocaml/ocaml.org/assets/70571088/b4428342-bc58-4a7d-b244-a8f7cb05b14e)
Make start results in this error

**Comment by FayCarsons** [comment]
I've got OCaml installed and running w/o issue but running the make switch and make start commands on my fork of this repo returns a bunch of dependency errors. I've tried running make install but it fails with the error "Library hilite not found". A little stuck at this point.

tried to move forward to the Dream example and had the same issue, even after running `make deps`, maybe there's something I'm missing in this process?

**Comment by kate-bagenzo** [comment]
Thanks for the guide! All set up now and excited to contribute 😁
![image](https://github.com/ocaml/ocaml.org/assets/124470013/0b7ddcaf-3988-4fe2-8ed6-3e9b31c6d805)
![image](https://github.com/ocaml/ocaml.org/assets/124470013/04bd4645-d856-416a-91fb-2902d0bba3bd)

**Comment by Biki-das** [comment]
Local setup done , ready to contribute to the Project
![Screenshot 2023-10-03 at 10 47 37 PM](https://github.com/ocaml/ocaml.org/assets/72331432/b80e0065-f785-4507-a44a-2470431947cb)
<img width="582" alt="Screenshot 2023-10-03 at 10 51 08 PM" src="https://github.com/ocaml/ocaml.org/assets/72331432/0b721628-4455-4596-9984-baeb9deb1ff1">

**Comment by Mankavelda** [comment]
> @Mankavelda I had the same issue, you can try this fix. [#1553 (comment)](https://github.com/ocaml/ocaml.org/issues/1553#issuecomment-1743830781)

Thank you @ikeadeoyin

**Comment by Oluwabukolab** [comment]
Hello Everyone. I'm an outreachy applicant. I have completed the setup. Here are my screenshots 
<img width="1699" alt="Screenshot 2023-10-04 at 08 58 12" src="https://github.com/ocaml/ocaml.org/assets/112485492/46c94f48-48d6-4089-a08a-058e18161db3">
<img width="1724" alt="Screenshot 2023-10-04 at 08 51 31" src="https://github.com/ocaml/ocaml.org/assets/112485492/51d9ff8c-2c07-4b48-9fc0-78794ad16693">

**Comment by Isaranwa** [comment]
![ocaml](https://github.com/ocaml/ocaml.org/assets/136800007/0b95854d-6865-4758-9329-ae1890532616)
I am done with my set up and waiting to be assigned an issue because all are already assigned.Thanks

**Comment by iamkalio** [comment]
<img width="955" alt="Screenshot 2023-10-04 173338" src="https://github.com/ocaml/ocaml.org/assets/89003403/ce90c230-4c1b-4381-8590-8a2f847c5621">
<img width="954" alt="Screenshot 2023-10-05 124315" src="https://github.com/ocaml/ocaml.org/assets/89003403/0533ff69-efbe-4049-b14a-e179433ae9ff">

Hello @sabine @SaySayo  I've been able to get Ocaml ant the project  running on my local machine without issues, ill love to move forward with solving an issue, thanks.

**Comment by SaySayo** [comment]
Hi everyone. There’s a parsing opam error that crashes [ocaml.org](http://ocaml.org/) when you try to build it locally, please rebase your patch on main to continue building OCaml without any hitches. @Biki-das @biroue10 @mohdaquib171 @oyenuga17 @SwizzCoder @tinniaru3005 @AndroGenius-codes @kate-bagenzo @sophiatunji @Isaranwa

**Comment by AndroGenius-codes** [comment]
> Hi everyone. There’s a parsing opam error that crashes [ocaml.org](http://ocaml.org/) when you try to build it locally, please rebase your patch on main to continue building OCaml without any hitches. @Biki-das @biroue10 @mohdaquib171 @oyenuga17 @SwizzCoder @tinniaru3005 @AndroGenius-codes @kate-bagenzo @sophiatunji @Isaranwa

Ok. Quick question how can we do that?

**Comment by SaySayo** [comment]
You can run the following command `git rebase main`. @AndroGenius-codes

**Comment by mohdaquib171** [comment]
Hello @SaySayo I have rebased my patch on top of the main branch. Do I need to create a new pull request?

**Comment by punchagan** [comment]
> Hello @SaySayo I have rebased my patch on top of the main branch. Do I need to create a new pull request?

You can [force push](https://zulip.readthedocs.io/en/stable/git/using.html#force-push-changes-to-github-after-you-ve-altered-your-history) to the same branch, and your pull-request will be updated.

**Comment by OkunadeNaheem** [comment]
Hello, Demilade okunade here. Setup completed Succesfully.
![Screenshot from 2023-10-06 08-11-11](https://github.com/ocaml/ocaml.org/assets/109427907/a0c180e7-eedd-4fec-8c22-41e48c669e8f)

**Comment by lawalalx** [comment]
)I am having this error while running this command:  npm install esy && npx esy
@punchagan  @SaySayo 

![Screenshot (70)](https://github.com/ocaml/ocaml.org/assets/144465715/d08bb26d-9652-4940-ab40-b9b4b69526da)

**Comment by lawalalx** [comment]
Also this has been loading for 2hrs now:

![Screenshot (71)](https://github.com/ocaml/ocaml.org/assets/144465715/e74456d7-acf6-43f8-aa58-31cbcf762be3)

**Comment by henilGondalia** [comment]
The setup guide was incredibly detailed, and thanks to that, I've been able to successfully set up OCaml on my machine and clone the ocaml.org repository.

![ocml setup](https://github.com/ocaml/ocaml.org/assets/34880491/b9dbb084-be26-4d76-a6de-dd661fecbee3)

**Comment by SaySayo** [comment]
ATTENTION!!! 📣📣📣
Hi everyone! To those applying to the dark mode project, please record your contributions before 9am EST tomorrow as the project will be closed to new contributors, meaning even if you've made contributions, you'll be unable to record it for the project on the Outreachy website, therefore making you ineligible to be selected as an intern. It's completely fine if your contribution isn't ready yet. You can just open a draft pull request and record that link. It's to make sure you have access to the project to continue recording any subsequent contribution you may have, as once the project is closed, no new applicant will be able to record a contribution asides the applicants who have recorded something(whatever it is) prior to the project closure. Also note that recording contributions is not the same as sending a final application to the project. The final application is the last step which you can do in your own time as long as it doesn't exceed Outreachy's deadline. Let me know if you have any questions or need further clarifications. Thank you all for your useful contributions so far!

**Comment by varunamm** [comment]
Hey everyone! I've just setup the environment. Just waiting for any Good first issue assigned to me! @SaySayo  @sabine 

![image](https://github.com/ocaml/ocaml.org/assets/98857609/43318e66-848b-4b84-9bcb-add45b05ca91)

**Comment by Abolade017** [comment]
![Uploading Screenshot 2023-10-12 at 09.39.14.png…]()
ocaml setup successful and ready to make contribution
<img width="1680" alt="Screenshot 2023-10-12 at 09 43 41" src="https://github.com/ocaml/ocaml.org/assets/70269933/37ffb192-853a-4a41-bcf7-f6fbdace542c">

**Comment by Abolade017** [comment]
> ATTENTION!!! 📣📣📣 Hi everyone! To those applying to the dark mode project, please record your contributions before 9am EST tomorrow as the project will be closed to new contributors, meaning even if you've made contributions, you'll be unable to record it for the project on the Outreachy website, therefore making you ineligible to be selected as an intern. It's completely fine if your contribution isn't ready yet. You can just open a draft pull request and record that link. It's to make sure you have access to the project to continue recording any subsequent contribution you may have, as once the project is closed, no new applicant will be able to record a contribution asides the applicants who have recorded something(whatever it is) prior to the project closure. Also note that recording contributions is not the same as sending a final application to the project. The final application is the last step which you can do in your own time as long as it doesn't exceed Outreachy's deadline. Let me know if you have any questions or need further clarifications. Thank you all for your useful contributions so far!

please all the issues as been assigned to people, how do i have a task to make contribution so that i can record mine before the deadline

**Comment by gpetiot** [comment]
#1624 has not been assigned yet

To filter the issues: https://github.com/ocaml/ocaml.org/issues?q=is%3Aissue+is%3Aopen+label%3Aoutreachy+no%3Aassignee

**Comment by OkunadeNaheem** [comment]
@sabine
I thought once we were done with the hello world example on both the Dream and Bogue repository, we were meant to automatically start the Dark mode project on the ocaml website with i was wrong, but i just found out we are meant to ask to be attributed an issue on the main repository. 
How do i attributed to an issue?

**Comment by KUMNADIN** [comment]
![Screenshot from 2023-10-13 01-10-45](https://github.com/ocaml/ocaml.org/assets/135359476/44837a80-5ab8-4009-b044-7e4f1e4605a1)
hi everyone, i just set up my environment

**Comment by KUMNADIN** [comment]
> ATTENTION!!! 📣📣📣 Hi everyone! To those applying to the dark mode project, please record your contributions before 9am EST tomorrow as the project will be closed to new contributors, meaning even if you've made contributions, you'll be unable to record it for the project on the Outreachy website, therefore making you ineligible to be selected as an intern. It's completely fine if your contribution isn't ready yet. You can just open a draft pull request and record that link. It's to make sure you have access to the project to continue recording any subsequent contribution you may have, as once the project is closed, no new applicant will be able to record a contribution asides the applicants who have recorded something(whatever it is) prior to the project closure. Also note that recording contributions is not the same as sending a final application to the project. The final application is the last step which you can do in your own time as long as it doesn't exceed Outreachy's deadline. Let me know if you have any questions or need further clarifications. Thank you all for your useful contributions so far!

please does it meant i am not longer eligible to record my contribution to this project. please just that i saw this late

**Comment by sabine** [comment]
> please does it meant i am not longer eligible to record my contribution to this project. please just that i saw this late

It's still possible to open an application at the Outreachy page, when you have completed an outreachy issue. Apparently all that "closing the project to new contributors" does on Outreachy is to move the project to the very bottom so it does not attract as many new applicants.

**Comment by MelakuAlehegn** [comment]
Hello Everyone, I have been trying to build Ocaml.org on  my windows machine for days, finally up and running on virtual-box Ubuntu machine.
![Screenshot from 2023-10-17 02-30-45](https://github.com/ocaml/ocaml.org/assets/49185991/8958039b-b2ca-4f06-9611-da873f1c40fd)

**Comment by gpetiot** [comment]
The application period is over, so closing this. Thank you to all of the Outreachy applicants who contributed to the project!
