### ISSUE TITLE
Refactor: Rename problems to exercises in the code

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1558]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

# Task

In all user-facing views, we call the exercises "exercises". However, in the code, they are referred to as "problems".

This should be consistent so there is less of a mismatch between how things are called to the observer and in the code.

How to solve this:

1. search for "problem" in the codebase and rename all occurrences that relate to exercises to "exercise"

Things to rename: files, modules, functions, parameters

E.g. `problem.ml` -> `exercise.ml`, or `problems.eml` -> `exercises.eml`.

Important: if you do change the URL under which the exercises page is found (optional for this issue), add a redirect in `redirection.ml` so that old links continue to work.

Important: don't rename problems to exercises inside blog posts, tutorials, unless it refers explicitly to the "Exercises" section of the OCaml.org website.

**Comment by Biki-das** [comment]
i would like to work on this @sabine please assign me

**Comment by SaySayo** [comment]
Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.

**Comment by Biki-das** [comment]
@SaySayo yes 
### OCAML WEBSITE LOCALLY RUNNING

![Screenshot 2023-10-03 at 10 47 37 PM](https://github.com/ocaml/ocaml.org/assets/72331432/ec051ba5-6696-470d-a3c2-7b80d6780f61)
<img width="582" alt="Screenshot 2023-10-03 at 10 51 08 PM" src="https://github.com/ocaml/ocaml.org/assets/72331432/c18ad296-438b-4ae8-bf30-ed480106b327">


### DREAM FRAMEWORK EXAMPLE LOCALLY RUNNING
<img width="1512" alt="Screenshot 2023-10-04 at 10 31 44 AM" src="https://github.com/ocaml/ocaml.org/assets/72331432/da65ca29-8dc6-49d8-a94b-7d0515f48d91">

**Comment by Oluwabukolab** [comment]
I'll like to work on this issue please. I have completed the setup. Can I be assigned?
<img width="1699" alt="Screenshot 2023-10-04 at 08 58 12" src="https://github.com/ocaml/ocaml.org/assets/112485492/13028cf0-03c3-4239-955a-d08475c045ae">
<img width="1724" alt="Screenshot 2023-10-04 at 08 51 31" src="https://github.com/ocaml/ocaml.org/assets/112485492/bc0eee9e-8e0e-4e7b-bc60-932ea96d52c2">

**Comment by SaySayo** [comment]
@sophiatunji, you will be assigned this issue, let me know if you need any pointers. cc @sabine

**Comment by Biki-das** [comment]
@SaySayo ? I have asked to being assigned earlier than @sophiatunji and have also shared the screenshot.

**Comment by SaySayo** [comment]
@Biki-das, Oh true. My apologies about the mixup, my notifications have been crowded so I only saw the most recent comment. Will you like to be assigned a different issue?

**Comment by Biki-das** [comment]
@SaySayo yeah works for me, i just want to start contributing and wanted to learn :-)

**Comment by Oluwabukolab** [comment]
Thank you. Will get started on it!

**Comment by SaySayo** [comment]
For clarification purposes, are you applying for the dark mode or the GUI project? @sophiatunji

**Comment by Oluwabukolab** [comment]
I'm applying to the dark mode project @SaySayo

**Comment by sabine** [comment]
Completed by #1592
