### ISSUE TITLE
Add an RSS Feed for the Changelog

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1560]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

# Task

Currently, the changelog at https://ocaml.org/changelog does not have a way for people to subscribe to it. A RSS Feed should be added at https://ocaml.org/changelog/feed.xml.

--

For an example of generating a RSS feed, see how it's done for https://ocaml.org/blog:

1. There's a function `create_feed` implemented in https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/tool/ood-gen/lib/planet.ml#L287-L333
2. `create_feed` is made accessible through the command-line tool `ood-gen` here: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/tool/ood-gen/bin/gen.ml#L24
3. In the `dune` file at the project root directory, `ood-gen` is invoked to generate `feed.xml`: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/dune#L14-L25 

-- 

Your task is to add RSS feed creation to https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/changelog.ml

For this:

1. Add a function `create_feed` to `changelog.ml`
2. Add a line to allow calling the function via the command line tool `ood-gen`
3. Modify the `dune` file to add another block similar to this that generates the changelog's `changelog/feed.xml`
4. Add a link to the RSS Feed of the changelog on the Changelog page at https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/src/ocamlorg_frontend/pages/changelog.eml so that people know where the Changelog's RSS feed is.

(Related to https://github.com/ocaml/ocaml.org/issues/1125.)

**Comment by oyenuga17** [comment]
Hi @sabine, @SaySayo please I'd love to try out this issue 🙏 
My first pr has be successfully merged [here](https://github.com/ocaml/ocaml.org/pull/1564)

**Comment by SaySayo** [comment]
@oyenuga17, you will be assigned this issue. Let me know if you need any help. cc @sabine

**Comment by oyenuga17** [comment]
Hi @sabine, @SaySayo  please I have a question 👇 

How can I change the dates coming from the changelog .md files to ISO 8601 format before passing to Syndic.Date.of_rfc3339?

Currently, unlike planet .md files which dates are in ISO 8601 format, the dates in the changelog .md files are "YYYY-MM-DD", but Syndic.Date.of_rfc3339 expects ISO 8601 formats in order to parse it correctly

<img width="711" alt="Screenshot 2023-10-04 at 16 57 59" src="https://github.com/ocaml/ocaml.org/assets/64274826/566a92d9-5b42-43b4-b307-597f53d55917">

<img width="1029" alt="Screenshot 2023-10-04 at 16 48 28" src="https://github.com/ocaml/ocaml.org/assets/64274826/1e378de6-acca-4845-9bb9-769cde241329">

**Comment by oyenuga17** [comment]
was able to tweak this by doing `let updated = Syndic.Date.of_rfc3339 (log.date ^ "T00:00:00-00:00")`

**Comment by oyenuga17** [comment]
Hi @sabine, after looking very well into this, I ended up using the LocalBlog implementation for this, so I didn't need to modify the dune and ood-gen files. However I have a question to ask 👇 

I created my rss_feed here
https://github.com/ocaml/ocaml.org/blob/e900c1a487de3d4fec0c7225e566660f6eb81f4d/tool/ood-gen/lib/changelog.ml#L49-L73
How can I pass the data from my rss_feed to here
https://github.com/ocaml/ocaml.org/blob/e900c1a487de3d4fec0c7225e566660f6eb81f4d/src/ocamlorg_web/lib/handler.ml#L76-L83

**Comment by sabine** [comment]
You don't need to pass rss feed data to `handler.ml` because the `changelog/feed.xml` file should be generated by `ood-gen` at build time from the markdown files in the `data/changelog` directory.

All that the template needs to render is the link to the static asset, so no changes to `handler.ml` should be necessary. Similar to the global RSS feed link of the OCaml Planet Blog in `footer.eml`.

Btw, you could name the feed "OCaml Changelog". :slightly_smiling_face:

**Comment by oyenuga17** [comment]
Thank you @sabine, I have reverted this changes to the way it was done for global feed, but I get a 404 not found when I navigate localhost:8080/changelog/feed.xml

https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/tool/ood-gen/lib/changelog.ml#L49-L85
https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/dune#L27-L37
https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/src/ocamlorg_static/dune#L10
https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/tool/ood-gen/bin/gen.ml#L25

**Comment by oyenuga17** [comment]
Thank you @sabine, I have reverted this changes to the way it was done for global feed, but I get a 404 not found when I navigate localhost:8080/changelog/feed.xml

https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/tool/ood-gen/lib/changelog.ml#L49-L85
https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/dune#L27-L37
https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/src/ocamlorg_static/dune#L10
https://github.com/oyenuga17/ocaml.org/blob/a228a02894ee95cf687601c982dbb586d7e03885/tool/ood-gen/bin/gen.ml#L25

**Comment by oyenuga17** [comment]
I also confirmed that the changelog feed generates properly by testing it in localhost:8080/feed.xml

**Comment by sabine** [comment]
@oyenuga17 I think my suggestion to place the changelog in the asset directory at `asset/changelog/feed.xml` is the problem.

In `router.ml`, the route
```
Dream.get (Url.changelog_entry ":id") Handler.changelog_entry;
```
handles the HTTP request to `/changelog/feed.xml`.

I think the simplest solution here is to place the changelog feed somewhere else in the `asset` directory (e.g. `asset/changelog_feed.xml`) so that it is not shadowed by an existing route.

**Comment by oyenuga17** [comment]
Yeah, this was what I noticed that made me switch to the local blog style. 
Nice tweak 👍, so changelog feed will now be at https://ocaml.org/changelog_feed.xml

**Comment by oyenuga17** [comment]
I have made this change and it works just fine 😊 
My pull request is at #1593 
Thank you @sabine 🎉

**Comment by oyenuga17** [comment]
@sabine while working on this, I noticed the changelog doesn't have pagination. Can I go ahead and create an issue for this? Already started looking into how it was implemented for the blog

**Comment by gpetiot** [comment]
> @sabine while working on this, I noticed the changelog doesn't have pagination. Can I go ahead and create an issue for this? Already started looking into how it was implemented for the blog

There is already an issue for this: #1561
