### ISSUE TITLE
Add Pagination to the Changelog

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1561]
# Task

Currently, all the entries of the changelog are displayed on a single HTML page at https://ocaml.org/changelog.

Since there are a lot of entries, it makes sense to add pagination:
![Screenshot 2023-10-03 at 15-13-43 OCaml Blog](https://github.com/ocaml/ocaml.org/assets/6594573/d9d45efd-19aa-4541-8418-27e3f57b0606)

As an example of how to do pagination (and for possible code sharing), look at how it is done for the Blog:
1. In `handler.ml`, the list of entries is paginated according to a query parameter "p" from the URL: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/src/ocamlorg_web/lib/handler.ml#L191-L218
2. In the template, the pagination component is rendered: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/src/ocamlorg_frontend/pages/blog.eml#L67

--

What you need to do:

1. modify the function `changelog` in `handler.ml` to paginate the list of changelog entries.
2. render the pagination component in `changelog.eml`

(Related to https://github.com/ocaml/ocaml.org/issues/1125.)

**Comment by biroue10** [comment]
@sabine can you assign me this task i already completed the instructions in #1553

**Comment by SaySayo** [comment]
Have you setup the project according to this [guidelines](https://github.com/ocaml/ocaml.org/issues/1553) depending on the outreachy project you're applying to? If you have, please send a screenshot.

**Comment by SaySayo** [comment]
@biki-das, you will be assigned this issue, let me know if you need any pointers. cc @sabine

**Comment by Biki-das** [comment]
@SaySayo thanks, will surely reach back to you , if i need help.

**Comment by SaySayo** [comment]
For clarification purposes, are you applying for the dark mode or the GUI project? @Biki-das

**Comment by Biki-das** [comment]
@SaySayo darkmode project

**Comment by Biki-das** [comment]
````
`let changelog req =
    let current_tag = Dream.query req "t" in
    let tags =
      Data.Changelog.all
      |> List.concat_map (fun (change : Data.Changelog.t) -> change.tags)
      |> List.sort_uniq String.compare
    in
    let changes =
      match current_tag with
      | None | Some "" -> Data.Changelog.all
      | Some tag ->
          List.filter
            (fun change -> List.exists (( = ) tag) change.Data.Changelog.tags)
            Data.Changelog.all
    in
    let page, number_of_pages, current_items =
      paginate ~req ~n:10 changes  (* Paginate the 'changes' list with 10 items per page *)
    in
    Dream.html (Ocamlorg_frontend.changelog ?current_tag ~tags ~page ~pages_number:number_of_pages current_items)ā
  `
````
i am getting an unbound value error while writing the above code, anything i am doing wrong

`File "src/ocamlorg_web/lib/handler.ml", line 73, characters 6-14:
73 |       paginate ~req ~n:10 changes  (* Paginate the 'changes' list with 10 items per page *)
           ^^^^^^^^
Error: Unbound value paginate
make: *** [all] Error 1             `

**Comment by Biki-das** [comment]
@sabine little confused around the expression it takes 
```
 exec -- dune build --root .
File "src/ocamlorg_web/lib/handler.ml", line 73, characters 13-43:
73 |   Dream.html (Ocamlorg_frontend.changelog )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type
         tags:string list ->
         ?current_tag:string -> Data.Changelog.t list -> string
       but an expression was expected of type string
make: *** [all] Error 1

```

how can i modify the arguments this ocaml.frontend.changelog takes?

**Comment by sabine** [comment]
Hey, sorry, I didn't see this.

In the template `changelog.eml`, the function `render` needs to be changed. This issue is quite similar to https://github.com/ocaml/ocaml.org/pull/1657, so inspiration can be taken from there.

**Comment by sabine** [comment]
@Biki-das It can be simpler to see where you are stuck when you open a draft pull request. I'm assuming you still plan to work on the issue?

**Comment by Girish-Jangam** [comment]
@Biki-das Are you working on this? @sabine if not, i would like to work on this!

**Comment by sabine** [comment]
Since there's been no response by @Biki-das, I'm unassigning them from this issue.

**Comment by m-spitfire** [comment]
@sabine I would like to work on this!

**Comment by florentdrousset** [comment]
I'm interested in doing this !

**Comment by sabine** [comment]
Since you were split seconds faster, I am assigning you @m-spitfire, and I'll propose another issue to @florentdrousset
