### ISSUE TITLE
Implement Capability to Link Exercise to Tutorials

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1562]
# Task

Currently, tutorials and exercises are not related to each other, even though it would be helpful to recommend to people at the end of a tutorial some exercises they should be able to do now.

To achieve that, we need the ability for exercises to reference the tutorials that they should be recommended on.

1. You need to add a field `tutorials: string list` to both the `metadata` and `t` types in `exercise.ml` which holds the slugs of all the tutorials the exercise is linked to. This will make the command-line tool `ood-gen` load the new reference between tutorials and exercises.
2. Add some sensible references between exercises and tutorials in the `data/exercises` folder, for testing purposes.
3. In `handler.ml`, in the function `tutorial`, you need to filter the exercises for those that belong to the tutorial, i.e. (`tutorial.slug` is an element of `exercise.tutorials`).
4. In `tutorial.eml`, render a plain list of links to the exercises at the bottom of the page.

**Important:** When a referenced tutorial slug does not exist, an error should be thrown by `ood-gen` so that we can be sure that the references between tutorials and exercises will stay in a good shape.

**Comment by biroue10** [comment]
@sabine can you assign this task please ?

**Comment by sabine** [comment]
@biroue10 @SaySayo assigned

**Comment by biroue10** [comment]
@sabine @SaySayo can you give me some guidance about this task please

**Comment by SaySayo** [comment]
Hi @biroue10, to get started, 
1. go into the `problems.ml` file, you'd see some predefined type which is a record field called `metadata` and `t`, modify it according to the instructions on the issue, thats the first step. 
2. Then go into the `data/problems` directory, and modify the md files, adding references of what exercises is related to what issue. 
3. In the `handler.ml` file, find the function that handles the `tutorials` and filter out exercises that fits the exercise references.
4. In the `tutorial.eml` file, display these exercises which have been filtered. 
Is this clear enough or do you need more details?

**Comment by biroue10** [comment]
@SaySayo yes i think now it is more clear thank you

**Comment by sabine** [comment]
@biroue10 are you still working on this task? If yes, it would be helpful to open a draft pull request so we can give feedback and guide you better. If no, please let us know so we can assign to someone else.

**Comment by biroue10** [comment]
@sabine you can assign it to someone else

**Comment by Raven49** [comment]
Hi @sabine @SaySayo  , I have made my first contribution as #1658  Kindly assign me any new task so that i can contribute for Outreachy.

**Comment by FatumaA** [comment]
I would like to take this on since no one is at the moment. 
@SaySayo @sabine

**Comment by sabine** [comment]
@FatumaA if you still like to take on this issue, please confirm. I'll assign you. :slightly_smiling_face:

**Comment by sabine** [comment]
Sorry @FatumaA, I just saw I assigned you to another issue a bit earlier. :slightly_smiling_face:

@florentdrousset would you be up for this issue?

**Comment by florentdrousset** [comment]
Yes absolutely, @sabine 
I'm definitely a beginner with OCaml but the instructions look clear enough to me so I'm willing to give this a try if that's fine with you.

**Comment by sabine** [comment]
For sure and no worries, open a draft PR and ask questions if/when you get stuck!

**Comment by FatumaA** [comment]
> Sorry @FatumaA, I just saw I assigned you to another issue a bit earlier. 🙂
> 
> @florentdrousset would you be up for this issue?

No problem
