### ISSUE TITLE
Remove "Language Manual" link from Learn area tab navigation

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1563]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

Only pick up this issue if you're confident to go for a medium level issue right after.

# Task

On https://ocaml.org/docs, in the tab navigation is an entry "Language Manual" that needs to be removed.

![Screenshot 2023-10-03 at 17-00-29 Learn OCaml](https://github.com/ocaml/ocaml.org/assets/6594573/cce6c70e-fd18-4f4f-b91a-2ea9f3dc6da7)

What you need to do:

1. Find this element (it is in one of the `.eml` files in `src/ocamlorg_frontend`) and remove it. That's all.

**Comment by biroue10** [comment]
@sabine can you assign me this task i have completed the instructions in #1553

**Comment by mohdaquib171** [comment]
Hi @sabine I'd like to work on this. 
I've got my OCaml setup ready. 
Can this issue be assigned to me, please? 
And yes I am confident to go for a medium level issue right after this.
Thanks!
![image](https://github.com/ocaml/ocaml.org/assets/81552805/9a63353e-8e1a-4a31-859b-4a87ad5d8000)

**Comment by prakharbhardwaj1504** [comment]
I will deliver it up to your expectation, kindly assign...

**Comment by SaySayo** [comment]
@mohdaquib171, you will be assigned this issue. Let me know if you need any help. cc @sabine , @gpetiot

**Comment by SaySayo** [comment]
For clarification purposes, are you applying for the dark mode or the GUI project? @mohdaquib171

**Comment by mohdaquib171** [comment]
Thank you for assigning me the issue! I'll get started on it. If I have any questions, I'll reach out. 😊
I'm applying for the dark mode implementation. Thanks for clarifying! 👍

**Comment by dicksonguantai** [comment]
@mohdaquib171  I see you are assigned this issue. I am willing to collaborate

**Comment by mohdaquib171** [comment]
Hello @sabine @SaySayo @gpetiot , I am aquib, I am working on this issue, and need help
when i am running the command `make start` to run ocaml locally getting this error, 
![image](https://github.com/ocaml/ocaml.org/assets/81552805/adf1c1f7-ec7e-4bc6-9976-5e2fc7d514bd)

earlier i am not getting this but now i am getting this error, 
can you please help me with this?

**Comment by SaySayo** [comment]
Hi @mohdaquib171, It should work now.

**Comment by mohdaquib171** [comment]
hey @SaySayo submitted pull request for this issue here : https://github.com/ocaml/ocaml.org/pull/1578

**Comment by sabine** [comment]
Completed by #1578
