### ISSUE TITLE
Implement New Navigation Structure on the Exercises Page

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1569]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned this issue if you're applying to the Dark Mode Outreachy project.

# Task

The Navigation in the left sidebar of the exercises at https://ocaml.org/problems needs to be improved:

|Current Exercises Page|Planned Design|
|-|-|
|![Screenshot 2023-10-04 at 16-46-24 Exercises](https://github.com/ocaml/ocaml.org/assets/6594573/650be955-1f6c-4772-867f-d7ac0dd4c936)|![Screenshot from 2023-10-04 16-47-33](https://github.com/ocaml/ocaml.org/assets/6594573/2c84b311-32a3-4aff-89b0-02dc91c27316)|

Here is [the Figma document for reference regarding the styles](https://www.figma.com/file/bL31M0WWTTdu2z9jAOX77J/UX%2FUI-OCaml-Learn-Area?type=design&node-id=1539%3A3356&mode=design&t=lTPcjIhaySpBMtWd-1).

How to solve this issue:

1. Modify the template `problems.eml` (may be renamed to `exercises.eml` by https://github.com/ocaml/ocaml.org/issues/1558): Instead of rendering a list of links in the sidebar, use `summary` and `details` HTML elements to group the exercises into different sections.
2. Do not render empty sections. (When the page is filtered by difficulty, some of the sections may be empty.)
3. Assign Tailwind CSS styles to match the Figma design. Try to make use of existing variables in `tailwind.config.js` / match what you see in other parts of the site.

**Comment by SwizzCoder** [comment]
Hello @sabine @SaySayo 
I just completed by first simple issue by opening a PR at https://github.com/ocaml/ocaml.org/pull/1570
While waiting for it to be merged, is it okay if I can be assigned to work on this task?

**Comment by SaySayo** [comment]
@SwizzCoder, you can go ahead. cc @sabine
