### ISSUE TITLE
Implement a basic monitoring dashboard

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#157]
We currently have no visibility on the performance of the server, which pages are most visited, if errors happen, etc.

To offer some visibility, we can implement a basic monitoring dashboard that would provide:

- Metrics such as:
  - Memory
  - CPU
  - Open file descriptors
- Statistics such as (check if GDPR compliant first!):
  - Requested URIs
  - User agents
  - Language
- Logs

https://github.com/tmattio/dream-analytics should be relevant.

**Comment by desirekaleba** [comment]
@tmattio, Can you please break this down for me? I would like to work on it.

**Comment by tmattio** [comment]
Hi @desirekaleba 🙂 This issue is a bit large, it's a several weeks project on its own, so maybe not the best candidate for a small issue

**Comment by desirekaleba** [comment]
@tmattio, I get that. I just wanted to challenge myself a bit harder 😆 .

**Comment by tmattio** [comment]
An initial version of the dashboard has been implemented in #399
