### ISSUE TITLE
Backlinks to sources

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1573]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

# Task

Add contribute links on all pages that display data from the `data/` folder.

The data from the `data/` folder gets transformed to OCaml modules via the command line tool in `tools/ood-gen`.

Some pages (e.g. Documentation, Jobs) include links to their source in order to invite contributions. However, this is not the case for all the pages.

How to solve this issue:

- Go through all different kinds of data in [the CONTRIBUTING.md instructions](https://github.com/ocaml/ocaml.org/blob/main/CONTRIBUTING.md) to check where they are displayed, and add a link to the respective section in the contributing instructions at https://github.com/ocaml/ocaml.org/blob/main/CONTRIBUTING.md.

Here is an example of how it was done for the Jobs page: https://github.com/ocaml/ocaml.org/pull/1568

**Comment by mays4** [comment]
I would like to work on this issue 
<img width="1315" alt="helloWorld" src="https://github.com/ocaml/ocaml.org/assets/51724111/a5fc363f-67a4-4841-998c-4b9b1b36a0e4">
<img width="1316" alt="Ocaml" src="https://github.com/ocaml/ocaml.org/assets/51724111/3a824d77-948a-4ffc-b87a-d3d8a0c98c37">

**Comment by mays4** [comment]
@cuihtlauac  @SaySayo  can I work on this issue, if I apply for the dark mode project?

**Comment by SaySayo** [comment]
This is a beginner issue for the GUI project, @mays4

**Comment by mays4** [comment]
@SaySayo  thank you for confirmation can you please assign me an issue related to the dark mode project

**Comment by mays4** [comment]
@SaySayo  @gpetiot  I've been actively searching for a 'good first issue' to contribute to in the Dark Mode project, but it appears that all such issues have already been assigned for the past two days. Could you please let me know if there are any new tasks on the horizon? In the absence of new tasks in the Dark Mode project, I'm open to shifting my focus to the GUI project and working on an issue there. Your guidance would be greatly appreciated.

**Comment by sabine** [comment]
@mays4 we are indeed very unlikely to create new issues for the dark mode project at this point. If you would consider to apply to the GUI project, let me know if you want me to assign you to this issue.

**Comment by mays4** [comment]
@sabine  yes please assign me this issue, thank you.

**Comment by sabine** [comment]
You are now assigned to this issue @mays4. Have fun! :slightly_smiling_face:

**Comment by sabine** [comment]
@mays4 how is it going? If you need help or feedback, please open a draft pull request with the current state of your work.

If you do not plan to work on this issue, let us know, so we can assign it to someone else.

**Comment by mays4** [comment]
Hi @sabine, thank you for reaching out. I've been actively working on the issue and plan to submit a draft pull request tomorrow, outlining the current state of my work. I experienced a slight delay due to some personal matters, but I'm fully back on track now. I appreciate your patience and understanding, and I am committed to delivering the best results for this project.

**Comment by mays4** [comment]
@sabine  I made a PR and converted it to a draft, please let me know if I am on the right track and I appreciate your feedback.
