### ISSUE TITLE
Replace Dependency on omd with cmarkit

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1574]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned this issue if you're applying to the GUI Outreachy project.

# Task

Currently, ocaml.org uses `omd` for markdown-to-html rendering. However, `omd` is not maintained anymore, and people are moving to a different markdown rendering package `cmarkit`.

How to solve this issue:

- Attempt to replace the dependency on `omd` with a dependency to `cmarkit`. This means going through all the sites where functions from `omd` are called and finding the appropriate matching function to call from `cmarkit`.
- There is some code in `tutorial.ml` that parses a table of contents from an `Omd.Document`. Similarly, `problem.ml` (may be renamed to `exercise.ml`) contains some code to parse the statement and solution of an exercise problem from a markdown document. Both of these will need to be adapted to parse the table of contents from the `cmarkit` document format.
 - It also requires changing the `dune-project` file to replace `omd` with `cmarkit`.

--

This issue is a prerequisite to #1565.

**Comment by AndroGenius-codes** [comment]
Hi @sabine I just finished my previous issue I am in the dark mode project is this something I can do.  If yes can I be assigned to it

**Comment by sabine** [comment]
@AndroGenius-codes working on preparing more outreachy medium issues, will notify.

**Comment by AndroGenius-codes** [comment]
> @AndroGenius-codes working on preparing more outreachy medium issues, will notify.

Alright

**Comment by AndroGenius-codes** [comment]
Hello @sabine can I go ahead with this or is it reserved for the people working on gui project ? Also can I apply to both gui and dark mode project?

**Comment by sabine** [comment]
@AndroGenius-codes we'll add another dark mode medium issue on Monday. If I understood it correctly, you have to decide.

cc @SaySayo

**Comment by AndroGenius-codes** [comment]
> @AndroGenius-codes we'll add another dark mode medium issue on Monday. If I understood it correctly, you have to decide.
> 
> cc @SaySayo

Alright. You can assign me when you create a new issue. Do have a lovely weekend

**Comment by sabine** [comment]
@oyenuga17 would you like to give this a try?

**Comment by oyenuga17** [comment]
@sabine yes I would love to 🙏

**Comment by shyusu4** [comment]
Hi there, I'd love to be assigned an issue for the GUI project since I haven't been assigned to a medium difficulty issue yet. Here's my pull request: https://github.com/ocaml/ocaml.org/pull/1634 cc @SaySayo @sabine

**Comment by AndroGenius-codes** [comment]
Alright. Will sure do

**Comment by sabine** [comment]
@shyusu4 would you consider working on https://github.com/ocaml/ocaml.org/issues/1610?

**Comment by shyusu4** [comment]
@sabine definitely!
