### ISSUE TITLE
On the package search results page: Show a "docs" link only when the package has documentation

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1576]
# Task

Currently, every search result on the packages search results page (e.g. https://ocaml.org/packages/search?q=sundial) has a "Documentation" link, but not every package has documentation.

![Screenshot 2023-10-05 at 10-41-06 OCaml Packages · Search Result](https://github.com/ocaml/ocaml.org/assets/6594573/d25518fa-b9e9-4092-8f91-2cca6ea61ab0)

Instead, when a package has no documentation, no documentation link should be rendered.

How to solve this issue:
1. Look at `handler.ml` for an example how to find out if a package has documentation: https://github.com/ocaml/ocaml.org/blob/fae1912c1882333b7f5d1a778f6056c23bf46f65/src/ocamlorg_web/lib/handler.ml#L731-L741
2. modify the `packages_search` function in `handler.ml` and the `packages_search.eml` template to omit the "Documentation" link when there is no documentation.

**Comment by kate-bagenzo** [comment]
I just finished #1566 - Could I be assigned to this next?

**Comment by sabine** [comment]
Hey @kate-bagenzo, in order to give others a chance at participating, it makes sense to apply to an issue labeled "outreachy-medium" now. There's currently only one issue, but we're working on scoping out and adding more "outreachy-medium" issues.

**Comment by dicksonguantai** [comment]
Hi @sabine kindly assign this task to me.!Ocaml is well set up.[image](https://github.com/ocaml/ocaml.org/assets/38208562/9c193bb5-5091-47f9-b90f-94f3c7fc89ed) 07.10.2023

**Comment by sabine** [comment]
@dicksonguantai here you go, sorry, we overlooked this earlier

**Comment by dicksonguantai** [comment]
Thank you, on it.😀

**Comment by dicksonguantai** [comment]
I have tried implementing in the 

> packages_search

 function in handler.ml the search logic. Upon implementing the search functionality, I have encountered a syntax error in the packages_search.eml template file.
**Problem:**
In the packages_search.eml file, specifically at line 46, I am getting the following error:
![image](https://github.com/ocaml/ocaml.org/assets/38208562/d1ca797b-a1fa-4832-920e-d6f7476143a3)

**Code Snippet(packages_search.eml)**

```<% if List.length packages > 0 then ( %>
        <ol class="flex flex-col">
          <% packages |> List.iter (fun (package : Package.package, documentation_status) -> %>*Line 46 as per the error*
          <li class="border-gray-200 border-b py-3 space-y-2">
            <div class="flex">
              <a
                href="<%s Url.Package.overview package.name %>"
                class="flex-grow text-lg font-semibold text-primary-700 inline-block"
              >
                <%s package.name %>
              </a>
              <div class="flex gap-4 justify-end items-center">
              <% match documentation_status with
              |Ocamlorg_frontend.Package.Success ->
              <a
                href="<%s Url.Package.documentation package.name %>"
                class="text-primary-700 flex gap-1 text-sm items-center"
              >
                <%s! Icons.documentation "h-5 w-5" %>
                Documentation
              </a>
              |_ ->
              <p> No Documentation Available </p>
              <% ) results %>
              </div>
            </div>
```

**Code Snippet(handler.eml) packages_search function**
```
let packages_search t req =
  match Dream.query req "q" with
  | Some search ->
      let packages =
        Ocamlorg_package.search ~is_author_match ~sort_by_popularity:true t
          search
      in
      let total = List.length packages in
      let results =
        List.map
          (fun package ->
            let documentation_status =
              match Ocamlorg_package.documentation_status package.name with
              | Some { failed = false; _ } -> Ocamlorg_frontend.Package.Success
              | Some { failed = true; _ } -> Failure
              | None -> Unknown
            in
            (Package_helper.frontend_package t package, documentation_status))
          packages
      in
      let search = Dream.from_percent_encoded search in
      Dream.html (Ocamlorg_frontend.packages_search ~total ~search results)
  | None -> Dream.redirect req Url.packages
```

**Comment by sabine** [comment]
The template language is very sensitive to brackets and indentation.

It will likely help to put brackets around the `match documentation_status with ...` expression.

<% (match ... with | Ocamlorg_frontend.Package.Success -> %>
  <a ...
<% ); %>

Or, probably even better: factor this out into another template function `render_documentation_link` in the same file which does the match on the documentation status.

**Comment by sabine** [comment]
@dicksonguantai it is much easier for us to assist specifically and help debug when you open a draft pull request.

**Comment by dicksonguantai** [comment]
@sabine please check out the draft pull request [here ](https://github.com/ocaml/ocaml.org/pull/1705)
Thank you.

**Comment by kiyov09** [comment]
Hi @sabine, I want to work on this one. Can you assign it to me?

**Comment by sabine** [comment]
Sure!

**Comment by kiyov09** [comment]
Hi @sabine . I opened a PR and also left a couple of questions for things that you may want to consider.
