### ISSUE TITLE
Add a line for the dune-project file to the package overview page

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1579]
# Task

On the package overview pages https://ocaml.org/p/irmin/latest (template at `package_overview.eml`), there is a button to copy the `opam install` command for the package. It would be nice to also have a button to copy the line you need to add to the `dune-project` file to add the dependency to your Dune project.

![Screenshot 2023-10-05 at 12-03-34 irmin 3 8 0 (latest) · OCaml Package](https://github.com/ocaml/ocaml.org/assets/6594573/2c373209-66a0-4162-8f1c-bc275bdcb58c)

Add another copyable code snippet below the existing one that contains the the line that needs to be placed in the `dune-project` file, could separate this with another heading "Dune Dependency".

Could look like this:

![Screenshot from 2023-10-05 12-14-21](https://github.com/ocaml/ocaml.org/assets/6594573/e3644b99-aba7-4fc6-b9b0-4f6cdf2ffdd5)

**Comment by ademolaomosanya** [comment]
would love to work on this issue
<img width="1280" alt="Screenshot 2023-10-05 at 09 37 29" src="https://github.com/ocaml/ocaml.org/assets/87182204/46614a84-be5d-4388-84e1-3b221051360a">

**Comment by SaySayo** [comment]
@ademolaomosanya you have been assigned a different issue.

**Comment by Raven49** [comment]
@sabine kindly assign this issue to me

**Comment by sabine** [comment]
@Raven49 have you completed the setup described in https://github.com/ocaml/ocaml.org/issues/1553? If so, please post a screenshot here, and I'll assign you.

**Comment by Raven49** [comment]
okay @sabine  i am setting up the project , I will let you know once I am done with it

**Comment by Raven49** [comment]
![1](https://github.com/ocaml/ocaml.org/assets/70138609/cfbb3b4d-ea4c-4440-a3a9-0cdb1ff9f369)
I was successfull in making the switch by make switch command , but while building there seems to be a syntax error . Kindly assign me this task and I will rectify both the errors @sabine

**Comment by SaySayo** [comment]
Hi @Raven49, you can only be assigned an issue after you have successfully set up the project. You can post errors you're getting during setup on the outreachy channel on discord for more assistance.

**Comment by henilGondalia** [comment]
Hi @SaySayo I have successfully setup project in my local machine as per #1553  Can You assign me this issue 

![ocml setup](https://github.com/ocaml/ocaml.org/assets/34880491/26f56c4e-71e1-4841-9e10-deb41dac18b3)

**Comment by SaySayo** [comment]
You will be assigned this issue @henilGondalia. cc @sabine

**Comment by Raven49** [comment]
I have managed to setup the project , kindly assign this task to me @sabine @SaySayo 
![3](https://github.com/ocaml/ocaml.org/assets/70138609/abd7c16a-5699-4522-8177-29170bcd6cf2)
