### ISSUE TITLE
SEO: robots.txt, sitemap.xml and noindex

### ISSUE THREAD

**Issue by TheLortex** [ocaml/ocaml.org#158]
The goal is to control and optimize how the website can be accessed from search engines. There are several methods to achieve that:

### robots.txt

This file describes how the site can be crawled by search engine bots: https://developers.google.com/search/docs/advanced/robots/intro

### sitemap.xml

This can be useful to expose the list of pages if we want the search engine to know about documentation pages: https://developers.google.com/search/docs/advanced/sitemaps/overview

### noindex

`<meta name="robots" content="noindex">` can be used to tell the crawler not to index the page

## For v3.ocaml.org

At first, we don't want the website to find discoverable through search engines, so `noindex` should be used for every page.

## In the future: ocaml.org

A sitemap should be provided, eventually with the documentation pages for the _latest_ packages. `noindex` should be used for parallel universes and older versions of packages. Finally, I guess it would make sense to have a somewhat stable URL for the last version of each package, something like https://v3.ocaml.org/p/base/latest/...

**Comment by tmattio** [comment]
We already have a robots.txt file here https://github.com/ocaml/v3.ocaml.org-server/blob/main/asset/robots.txt. It's not available when querying https://v3.ocaml.org/robots.txt, that's a bug.

**Comment by desirekaleba** [comment]
Querying [https://v3.ocaml.org/assets/robots.txt](https://v3.ocaml.org/assets/robots.txt) is returning the right robots.txt.

**Comment by desirekaleba** [comment]
Hi @tmattio,
Can I please be assigned to this?
