### ISSUE TITLE
Rearrange and Add Links in the Footer

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1581]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

# Task

Rearrange the links in the footer template `footer.eml` like this:

About OCaml
- Changelog
- Releases
- Industrial Users
- Academic Users
- Why OCaml?

Resources
- Install OCaml
- Get Started
- Platform Tools
- Language Manual
- Standard Library API
- Books
- Exercises
- Papers
- OCaml Playground

Ecosystem & Community
- Packages
- Community
- Blog
- Jobs

Policies
- Carbon Footprint
- Governance
- Privacy
- Code of Conduct

**Comment by ademolaomosanya** [comment]
Can I be assigned to this? (My Ocaml.org setup are posted in 
https://github.com/ocaml/ocaml.org/issues/1579)

**Comment by TheAbiSterling** [comment]
I'd like to work on this task
My setup is up and running
![Screenshot 2023-10-05 093207](https://github.com/ocaml/ocaml.org/assets/137959447/d0bed9e6-406e-4761-a42b-a81b81e6c10c)

**Comment by SaySayo** [comment]
@ademolaomosanya, you will be assigned this issue. Let me know if you need any help. cc @sabine

**Comment by ademolaomosanya** [comment]
> @ademolaomosanya, you will be assigned this issue. Let me know if you need any help. cc @sabine

thank you i'm working on it

**Comment by varunamm** [comment]
Hi @SaySayo Can I be assigned to this issue? Setup is already done and posted in #1553

**Comment by SaySayo** [comment]
Hi @varunamm, it has already been assigned and implemented

**Comment by varunamm** [comment]
Hi @SaySayo its good to know that its done. By the way I also wanted to contribute to #1463  and #1582 . Please let me know if I can be assigned to any of these?
