### ISSUE TITLE
Render the Author of a Blog Post and the Source it Came From on The OCaml Planet Blog

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1582]
# Task

On the OCaml Planet Blog at https://ocaml.org/blog we show a list of blog posts from external sources (see data format in `planet.ml`). However, we currently do not render the author of a post and the source (original blog) from which we have pulled in the post.

Your Task is to add the authors and source information to the `blog.eml` template here:

![Screenshot 2023-10-05 at 13-11-56 OCaml Blog](https://github.com/ocaml/ocaml.org/assets/6594573/91436ec5-aa2c-453c-8080-f7871c17c8a2)

Author should be below the title, original source could be at the very bottom. But you are free to come up with better placement.

**Comment by TheAbiSterling** [comment]
Hello Sabine! 
I would like to work on this project.
![Screenshot 2023-10-05 093207](https://github.com/ocaml/ocaml.org/assets/137959447/7781635a-03a1-49b1-bf6d-9c475a916cb3)

**Comment by SaySayo** [comment]
@TheAbiSterling, you will be assigned this issue. Let me know if you need any help. cc @sabine

**Comment by TheAbiSterling** [comment]
@SaySayo , thank you. I will work on this task.

**Comment by varunamm** [comment]
Hi @SaySayo, can I be assigned to this issue? The setup screenshot is posted in #1553

**Comment by SaySayo** [comment]
Hi @TheAbiSterling, are you still interested in working on this issue or can we reassign it?
