### ISSUE TITLE
Update Tailwind Configuration to Resolve Warnings

### ISSUE THREAD

**Issue by IdaraNabuk** [ocaml/ocaml.org#1583]
![image](https://github.com/ocaml/ocaml.org/assets/44207022/d48300d3-eb42-4853-89a2-0d8de44b07de)

**Comment by sabine** [comment]
I agree, these warnings are annoying, specifically since we do not use any of the mentioned colors. A PR that resolves this is welcome.

**Comment by sabine** [comment]
@123ZOKzok would you be up for looking into investigating how to resolve these warnings coming from Tailwind?

**Comment by 123ZOKzok** [comment]
Yeah, I can do that.

**Comment by sabine** [comment]
Ok great @123ZOKzok, you are now assigned to this issue!

**Comment by 123ZOKzok** [comment]
@sabine okay, working on it.

**Comment by IdaraNabuk** [comment]
Hello @SaySayo, my sincere apologies for not responding on time. It was an oversight. But I've been working on this project since last week and will create a PR as soon as I resolve all errors.

**Comment by 123ZOKzok** [comment]
Hey @IdaraNabuk I'm working on it kindly request for another one.

**Comment by 123ZOKzok** [comment]
@sabine the solution to it is running this command(npx update-browserslist-db@latest).  Should I update the same in the documentation?

**Comment by sabine** [comment]
@123ZOKzok ah, I see. Yes that would make a nice little FAQ entry for HACKING.md.

**Comment by 123ZOKzok** [comment]
![Screenshot from 2023-10-11 19-36-52](https://github.com/ocaml/ocaml.org/assets/48816919/5e20b3bb-fda1-4e46-98b7-72d1c3e3c8ce)

**Comment by IdaraNabuk** [comment]
@sabine Kindly review this: https://github.com/ocaml/ocaml.org/pull/1620

**Comment by IdaraNabuk** [comment]
> Hey @IdaraNabuk I'm working on it kindly request for another one.

@123ZOKzok The issue I worked on is different from yours. You will have to create an issue for "caniuse-lite is outdated". They are different issues.

**Comment by 123ZOKzok** [comment]
@IdaraNabuk okay.

**Comment by 123ZOKzok** [comment]
@sabine assign me another issue.

**Comment by 123ZOKzok** [comment]
### How to Fix Warnings?

#### Outdated Browserslist Warning

If you see an outdated Browserslist warning while building with `opam exec -- dune build --root .`, follow these steps:

1. Update Browserslist data using:

   ```bash
   npx update-browserslist-db@latest

**Comment by IdaraNabuk** [comment]
> ### How to Fix Warnings?
> #### Outdated Browserslist Warning
> If you see an outdated Browserslist warning while building with `opam exec -- dune build --root .`, follow these steps:
> 
> 1. Update Browserslist data using:
>    ```shell
>    npx update-browserslist-db@latest
>    ```

@123ZOKzok I don't think you are doing this right. You need to go to the repo and raise an issue. Include your solution in the appropriate configuration file, test it out, push it, and create a pull request. I hope this is helpful.

**Comment by 123ZOKzok** [comment]
@IdaraNabuk Okay. Thank you, it's helpful.

**Comment by 123ZOKzok** [comment]
@sabine Kindly review this #1633

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1620
