### ISSUE TITLE
Add a "Standard Library API" link to the mobile navigation menu

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1584]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

# Task 

In the main navigation's template `header.eml`, the search box of the desktop version of the main navigation contains a "Standard Library API" link:

![Screenshot from 2023-10-06 09-18-24](https://github.com/ocaml/ocaml.org/assets/6594573/d9cf1ff0-8f73-4776-8349-d7620cca2d9f)

However, the mobile version of the main navigation does not:

![Screenshot 2023-10-06 at 09-20-57 Get Up and Running With OCaml · OCaml Tutorials](https://github.com/ocaml/ocaml.org/assets/6594573/3dbe7bbe-21f0-4192-8253-ea38e4e5dc79)

Add a "Standard Library API" link to the mobile main navigation in `header.eml`, after "Playground" and before "Get Started".

**Comment by iamkalio** [comment]
@sabine @SaySayo  please can i be assigned this task, I've completed the initial installation and ready to move forward, ill love to contribute to the GUI experience 
<img width="955" alt="Screenshot 2023-10-04 173338" src="https://github.com/ocaml/ocaml.org/assets/89003403/ee675494-9510-4055-8fdf-c1e10a00c4d6">

**Comment by SaySayo** [comment]
@kalio007, you will be assigned this issue, cc @sabine

**Comment by iamkalio** [comment]
thank you @SaySayo ill start working on it, while i wait for @sabine

**Comment by iamkalio** [comment]
Greetings, @sabine  and @SaySayo  ! I trust this meets your expectations. If it does, I'm eager to proceed with creating a pull request and tackling a more  assignment. Thanks
<img width="472" alt="Screenshot 2023-10-09 010410" src="https://github.com/ocaml/ocaml.org/assets/89003403/c345d67c-1a50-41f0-9d18-1a0f5afd24cf">

**Comment by SaySayo** [comment]
Can you open a pull request so I can properly review your changes? Thank you! @kalio007

**Comment by iamkalio** [comment]
On it

**Comment by sabine** [comment]
Completed by #1600
