### ISSUE TITLE
Implement a Package Release History Page

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1587]
# Task

Add a page that lists all the released versions of a package.

![Screenshot from 2023-10-06 10-42-54](https://github.com/ocaml/ocaml.org/assets/6594573/e0953eb7-c9b0-40ee-afbd-b355528f298e)

Here is [a Figma document with the design for the versions page of the package](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=34%3A203&mode=design&t=AsJdiTX8o4t3ALZ7-1).

How to solve this issue:

1. Create a new template `package_versions.eml` that renders the page in the linked Figma design. Take inspiration on how to iterate over lists from other templates. Be careful about indentation, the templating engine used in this project is sensitive to it.
2. Add a rule to the `dune` file at `src/ocamlorg_frontend/dune` to process the `.package_versions.eml` template into an OCaml module `package_versions.ml`.
3. Add a function for the new template to `ocamlorg_frontend.ml`.
4. Add a handler `package_versions` to `handler.ml` that gets the relevant data (package and versions) and renders the new template.
5. Add a route for the new package versions page to `src/global/url.ml` and register the handler from the previous step it in the router at `router.ml`.
6. In the package area, on the package overview page at https://ocaml.org/p/irmin/latest (template `package_overview.eml`), a link needs to be added to go to the new package versions page. Hint: The little icon is `Icons.tag`.
7. 
![Screenshot 2023-10-06 at 10-40-55 irmin 3 8 0 (latest) · OCaml Package](https://github.com/ocaml/ocaml.org/assets/6594573/0eef68a1-6b2f-4e10-a2f0-fe59d6cf7b6f)

**Comment by kate-bagenzo** [comment]
I've finished #1566 - could I be assigned to this? (I am applying to the dark mode project).

**Comment by SaySayo** [comment]
@kate-bagenzo you will be assigned this issue. Let me know if you need any help. cc @sabine

**Comment by kate-bagenzo** [comment]
@SaySayo I've pieced together something but I can't actually test what I'm seeing here without looking at the page (and therefore doing all the steps) - could I have some guidance on how to add a handler in `handler.ml`?

`let render (package : Package.package)
=
Layout.render
~title:"Versions"
~description:"Package Versions" @@
<div class="bg-default dark:bg-dark-default py-24">
  <div class="container-fluid">
    <table class="table-auto">
        <thead>
            <tr>
                <th>Version</th>
                <th>Release Date</th>
                <th>Links</th>
            </tr>
        </thead>
        <tbody>
          <% package.versions |> List.iter (fun (version : string) -> %>
          <tr>
            <td>
              <%s version %>
            </td>
            <td>
              (date)
            </td>
            <td>
              (documentation)
            </td>
          </tr>
          <% ); %>
        </tbody>
    </table>
  </div>
</div>`

**Comment by kate-bagenzo** [comment]
@SaySayo I've pieced together something for `package_versions.eml`, but it's hard to tell if I'm doing it correctly since I can't see the page yet. I'm trying to follow the rest of the steps but having some trouble adding a new handler to `handler.ml` - any advice?

```
let render (package : Package.package)
=
Layout.render
~title:"Versions"
~description:"Package Versions" @@
<div class="bg-default dark:bg-dark-default py-24">
  <div class="container-fluid">
    <table class="table-auto">
        <thead>
            <tr>
                <th>Version</th>
                <th>Release Date</th>
                <th>Links</th>
            </tr>
        </thead>
        <tbody>
          <% package.versions |> List.iter (fun (version : string) -> %>
          <tr>
            <td>
              <%s version %>
            </td>
            <td>
              (date)
            </td>
            <td>
              (documentation)
            </td>
          </tr>
          <% ); %>
        </tbody>
    </table>
  </div>
</div>
```

**Comment by SaySayo** [comment]
IHi @kate-bagenzo, is there a reason you can't see the page yet? for testing purposes you can add it to an existing page and use the render function in it. It'll be very time consuming and tasking if you cannot see the changes you're trying to implement.

**Comment by kate-bagenzo** [comment]
@SaySayo Of course, I would never design blindly 😅 But I can't get the renderer to display the package/version list. Putting what I have now on a random existing page gives me a `handler.ml` error (`Error: This expression has type Data.Outreachy.t list but an expression was expected of type Ocamlorg_frontend.Package.package`). I'm not sure what to change to get an object of that type for testing.

**Comment by kate-bagenzo** [comment]
> @SaySayo Of course, I would never design blindly 😅 But I can't get the renderer to display the package/version list. Putting what I have now on a random existing page gives me a `handler.ml` error (`Error: This expression has type Data.Outreachy.t list but an expression was expected of type Ocamlorg_frontend.Package.package`). I'm not sure what to change to get an object of that type for testing.

@sabine Any hints here? I've been looking through `handler.ml` and trying to understand the helper functions but it's quite confusing 😅. Maybe something like a way to get a package name (for testing)?

**Comment by SaySayo** [comment]
The best way to get it tested out would be to add a rule in the dune file to generate the new page you want to add. You can look at how the outreachy page is being generated and rendered for example and do the same for the package page you're creating. @kate-bagenzo

**Comment by sabine** [comment]
@kate-bagenzo it will help a lot if you open a draft PR with your current state, so we can comment and make suggestions on that.

**Comment by kate-bagenzo** [comment]
@sabine Sure, I'll do that. #1669
