### ISSUE TITLE
Paginate the Package Search Results

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1588]
Note: this has been selected as an Outreachy issue. To be assigned, you must have completed the instructions in https://github.com/ocaml/ocaml.org/issues/1553.

Please only request to be assigned this issue if you are applying for the GUI project

# Task

Currently, all the entries of the package search results page are displayed on a single HTML page. E.g. at https://ocaml.org/packages/search?q=irmin.

Since there are a lot of entries, it makes sense to add pagination:
![Screenshot 2023-10-03 at 15-13-43 OCaml Blog](https://github.com/ocaml/ocaml.org/assets/6594573/d9d45efd-19aa-4541-8418-27e3f57b0606)

As an example of how to do pagination (and for possible code sharing), look at how it is done for the Blog:
1. In `handler.ml`, the list of entries is paginated according to a query parameter "p" from the URL: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/src/ocamlorg_web/lib/handler.ml#L191-L218
2. In the template, the pagination component is rendered: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/src/ocamlorg_frontend/pages/blog.eml#L67

--

What you need to do:

1. modify the function `packages_search` in `handler.ml` to paginate the list of changelog entries into pages that have at most 50 entries
2. modify the template `packages_search.eml` to render the pagination component

**Comment by godplayer56** [comment]
Hey! @sabine I'd love to work on this issue! :smile: 
Can you assign me this issue?

**Comment by sabine** [comment]
@godplayer56 have you completed the setup and are you applying to the GUI project? For the setup, could you please post a screenshot?

**Comment by Girish-Jangam** [comment]
Hey i would like to work on this, could you please assign this to me?

**Comment by sabine** [comment]
@Girish-Jangam have you completed the setup and are you applying to the GUI project? For the setup, could you please post a screenshot?

**Comment by Girish-Jangam** [comment]
I just want to make my first contribution, regardless of any project. I thinking this issue is very interesting and challenging & it's good for me, 

Talking about set-up, Yes I'm stack? It'll take some time to up and running

**Comment by Girish-Jangam** [comment]
![image](https://github.com/ocaml/ocaml.org/assets/59350195/fedcd26b-895c-4b82-80c4-360036130ffd)

Here's the screenshot, please assign this issue to me! I'll work hard on this

**Comment by sabine** [comment]
You are now assigned to this issue @Girish-Jangam. Have fun! :slightly_smiling_face:

**Comment by Girish-Jangam** [comment]
Thanks! I do my best

**Comment by godplayer56** [comment]
Hey @sabine I was working on this issue but due to some trouble at home I wasn't able to share my progress :disappointed: 

I tried using paginate function like this - 

```ocaml
let packages_search t req =
  match Dream.query req "q" with
  | Some search ->
      let packages =
        Ocamlorg_package.search ~is_author_match ~sort_by_popularity:true t
          search
      in
      let page, current_items, number_of_pages = 
        paginate ~req ~n:10 packages
      in
      let total = List.length packages in
      let results = List.map (Package_helper.frontend_package t) packages in
      let search = Dream.from_percent_encoded search in
      Dream.html (Ocamlorg_frontend.packages_search ~total ~search ~page:page ~current_items:current_items ~number_of_pages:number_of_pages results)
  | None -> Dream.redirect req Url.packages
```

but vs code is showing error that Ocamlorg_frontend.packages_search takes too many arguments 

I also edited the `packages_search.eml` file such as to include these parameters-

```ocaml
let render ~total ~search ~page ~current_items ~number_of_pages (packages : Package.package list) 
```
and also where should I add the pagination component in the eml file?

**Comment by Girish-Jangam** [comment]
Hey, i'm working on this, I'll commit asap!

**Comment by godplayer56** [comment]
Sure @Girish-Jangam , I just wanted to share my progress with @sabine :+1: 

@sabine should I work on some other issue? I have already completed the setup as mentioned for outreachy applicants(I can share the progress with you if necessary).

I am thinking of working on an outreachy medium issue since all the beginner issues have been assigned :disappointed:

**Comment by Girish-Jangam** [comment]
let packages_search t req =
  match Dream.query req "q" with
  | Some search ->
      let packages =
        Ocamlorg_package.search ~is_author_match ~sort_by_popularity:true t
          search
      in

      let total = List.length packages in
      
      let page, number_of_pages, current_items =
        paginate ~req ~n:50 packages
      in
      
      Dream.log "page value = %d" page;
      Dream.log "number_of_pages value = %d" number_of_pages;
      Dream.log "current_items value = %d" (List.length current_items);

      let results = List.map (Package_helper.frontend_package t) current_items in

      let base_url = Url.packages_search ^ "?q=" ^ search 

      in
      let search = Dream.from_percent_encoded search in

      Dream.log "base_url = %s" base_url;
      Dream.log "search value = %s" search;

      Dream.html (Ocamlorg_frontend.packages_search ~total ~search ~page ~number_of_pages ~base_url results)
  | None -> Dream.redirect req Url.packages


It uses paginate function

let paginate ~req ~n items = 
   let items_per_page = n in 
   let page = 
     Dream.query req "p" |> Option.map int_of_string |> Option.value ~default:1 
   in 
   let number_of_pages = 
     int_of_float 
       (Float.ceil 
          (float_of_int (List.length items) /. float_of_int items_per_page)) 
   in 
   let current_items = 
     let skip = items_per_page * (page - 1) in 
     items |> List.drop skip |> List.take items_per_page 
   in 
   (page, number_of_pages, current_items) 

<%s! Pagination.render ~total_page_count:number_of_pages ~page_number:page ~base_url:base_url %>

Error is shown in video,
Please guide me @sabine, @SaySayo 


https://github.com/ocaml/ocaml.org/assets/59350195/8f5b6216-bd95-4f4f-8a43-10993f4df408

**Comment by SaySayo** [comment]
This bug looks like it might be coming from the way you define `base_url`. You're missing the `&p=` part in the URL, which is necessary for specifying the page number when you click on pagination links. It should look more like `let base_url = Url.packages_search ^ "?q=" ^ search ^ "&p="`

**Comment by Girish-Jangam** [comment]
@SaySayo, Hello!

It's giving me following URL, I had tried this once

http://localhost:8080/packages/search?q=base&p=**?p=2**
http://localhost:8080/packages/search?q=base&p=**?p=3**
http://localhost:8080/packages/search?q=base&p=**?p=4**

Dream.query from paginate function appends ?p=number every time when i navigate through pages done on pagination. 

https://github.com/ocaml/ocaml.org/assets/59350195/9fda28da-39bc-4600-8154-354b7471e7de

**Comment by sabine** [comment]
@Girish-Jangam it will be easier to comment on the current state (and for us to try and run it) if you open a Draft PR

@godplayer56 maybe you can solve https://github.com/ocaml/ocaml.org/issues/1640 and then be assigned a medium issue?

**Comment by godplayer56** [comment]
Sure @sabine I'll work on it👍
