### ISSUE TITLE
Implement a New Footer for the Learn Area

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1591]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned this issue if you're applying to the Dark Mode Outreachy project.

# Task

The sticky footer that is currently being used in the Learn and Package documentation pages does not have space to display the links to other pages as well as the policies.

Here is a design for a new footer for the middle column of the the `learn_layout.eml` template:

![Screenshot from 2023-10-06 14-45-21](https://github.com/ocaml/ocaml.org/assets/6594573/8d64c1a5-262f-45f9-9af6-555942f60dd4)

Here is a [Figma document with the footer design](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=3%3A890&mode=design&t=AsJdiTX8o4t3ALZ7-1).

This new footer should be added to the bottom of the middle column of the learn area pages.

How to solve this issue:
1. In the `render` function in `learn_layout.eml`, move `<%s! Secondary_footer.render () %>` below `<%s! inner_html %>`.
2. Implement the new footer design from the Figma document in `secondary_footer.eml`.

Hint: check `footer.eml` for the icons used.

**Comment by sabine** [comment]
Note: work on this issue can be started after https://github.com/ocaml/ocaml.org/pull/1590 is merged.

**Comment by Oluwabukolab** [comment]
I have completed the beginner task here #1592, can I be assigned this issue? @SaySayo

**Comment by SaySayo** [comment]
@sophiatunji, you will be assigned this issue. Let me know if you need any help. cc @sabine

**Comment by mohdaquib171** [comment]
Please assign this to me, I already have completed simple issue yesterday (#1563 ) and waitting for the medium. Would like to go with this one for sure. Or if it is assigned to @sophiatunji then would like to collaborate with @sophiatunji 
And @SaySayo  please assign me some medium level issue, eagerly waiting to contribute and merge pr

**Comment by SaySayo** [comment]
Hi @mohdaquib171, we are currently out of medium issues for the dark mode project. More will be created soon and you will be assigned.

**Comment by Oluwabukolab** [comment]
Hi @sabine and @SaySayo, I've been working on the issue for a week and the changes I made in the secondary footer doesn't display the on the page when I run it, can't seem to figure out why

**Comment by henilGondalia** [comment]
Hi @sophiatunji, Should I help you with this task ??

**Comment by Oluwabukolab** [comment]
Thanks. You can comment any pointers you have here. But I already fixed the display problem. @henilGondalia

**Comment by sabine** [comment]
@sophiatunji when I rushed to create outreachy issues, I messed something up here wrt the layouts.

What should be done to make sure every page has only one footer:
1. in `layout.eml`: create a function `base` that renders the layout without any footer. All the functions that render actual layouts in `layout.eml`, `learn_layout.eml` and `package_layout.eml` can then use the `Layout.base` function.

**Comment by sabine** [comment]
Regarding double footer: I am applying this patch to live: https://github.com/ocaml/ocaml.org/pull/1646, ideally you can cherry-pick or rebase on this.
