### ISSUE TITLE
Jump to definition in package does not work on Safari

### ISSUE THREAD

**Issue by syedtaz** [ocaml/ocaml.org#1594]
Tested using Safari Version 16.6 (18615.3.12.11.2). Works on Chrome just fine.

https://github.com/ocaml/ocaml.org/assets/58488504/391bd17f-2029-47c6-aba7-f8f9d33e67fc

**Comment by sabine** [comment]
Thank you for reporting @syedtaz.

**Comment by shyusu4** [comment]
Hi, @sabine! I'm an outreachy applicant and I was wondering if it's possible for me to work on this issue. I noticed that all the _good first issues_ tagged with _outreachy_ already have someone assigned. Any chance I could still get involved? Thanks.

**Comment by sabine** [comment]
@shyusu4 Yes, this is fine to work on as a good first issue for outreachy. We're having trouble coming up with enough medium issues, though.

**Comment by 123ZOKzok** [comment]
@sabine I have not been assigned any issue, could you assign me one?
