### ISSUE TITLE
Documentation: wrong public library names

### ISSUE THREAD

**Issue by art-w** [ocaml/ocaml.org#1601]
On the [documentation page for the `yaml` package](https://ocaml.org/p/yaml/latest/doc/index.html), the sidebar lists libraries names with an underscore: `yaml_bindings`, `yaml_unix`, ... but it looks like the public names are written with a dot:

```
$ ocamlfind list | grep 'yaml'      
yaml                (version: 3.1.0)
yaml.bindings       (version: 3.1.0)
yaml.bindings.types (version: 3.1.0)
yaml.c              (version: 3.1.0)
yaml.ffi            (version: 3.1.0)
yaml.types          (version: 3.1.0)
yaml.unix           (version: 3.1.0)
```

Perhaps this is caused by `name` vs `public_name` in the dune file? https://github.com/avsm/ocaml-yaml/blob/master/unix/dune

In any case, the sidebar can cause confusion to users of the yaml library, since they must use the invisible `yaml.unix` rather than the documented `yaml_unix` ([as seen on discuss](https://discuss.ocaml.org/t/how-to-use-yaml-unix-in-dune-project/13198))

I believe other packages are affected, for example the documentation for [core](https://ocaml.org/p/core/latest/doc/index.html) lists libraries names which are missing their `core.` prefix.

**Comment by sabine** [comment]
Thanks for reporting, Arthur! I wasn't aware of this yet and opened an upstream issue on voodoo.

**Comment by Raven49** [comment]
Can I work on this issue ? @sabine @SaySayo I have already done #1658

**Comment by sabine** [comment]
@Raven49 This issue has to be resolved in an upstream repository which is out of scope for the Outreachy application.

**Comment by art-w** [comment]
Thanks for the fix! :heart:

**Comment by sabine** [comment]
This will save me so much time being confused at why using the libraries doesn't work. 😅
