### ISSUE TITLE
Apply Figma Styles for Package Search Dropdown

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1602]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned this issue if you're applying to the Dark Mode Outreachy project.

# Task

On the package area and in the main navigation, there is a search bar that allows people to search for opam packages:

![Screenshot 2023-10-09 at 17-34-27 OCaml Packages · Browse Community Packages](https://github.com/ocaml/ocaml.org/assets/6594573/fdea178a-f06e-43ae-bd70-28640d1726a9)

|old|new|
|-|-|
|![Screenshot from 2023-10-09 17-36-00](https://github.com/ocaml/ocaml.org/assets/6594573/773b2f7b-ee73-4d4f-a6f4-168af385ca6e)| ![Screenshot from 2023-10-09 17-37-32](https://github.com/ocaml/ocaml.org/assets/6594573/87027177-d51b-4544-8d12-a596592ad0bf)|

Here is a [Figma document with the styles](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=33%3A155&mode=design&t=AsJdiTX8o4t3ALZ7-1).

How to solve this issue:

1. apply the styles from the Figma document to the package search results in `packages_autocomplete_fragment.eml`.
2. apply the styles for the dropdown in `header.eml`
3. change `packages.eml` to render a dropdown on the package search input

**Comment by sabine** [comment]
@AndroGenius-codes do you want to be assigned to this issue?

**Comment by AndroGenius-codes** [comment]
Yes @sabine I would like that

**Comment by sabine** [comment]
@AndroGenius-codes you're now assigned. Have fun! 😀

**Comment by AndroGenius-codes** [comment]
> @AndroGenius-codes you're now assigned. Have fun! 😀

lol will sure do

**Comment by AndroGenius-codes** [comment]
@sabine  i have a little bit of challenge, from the figma files provided i am supposed to change the date the package was released to the number of times it was downloaded. but i can't seem to find the template for download data. Can you point me in the right direction please

**Comment by sabine** [comment]
@AndroGenius-codes you are not supposed to change anything except the package search dropdown as it appears on the page https://ocaml.org/packages (`packages.eml`) and in the main navigation (`header.eml`).

**Comment by AndroGenius-codes** [comment]
> @AndroGenius-codes you are not supposed to change anything except the package search dropdown as it appears on the page https://ocaml.org/packages (`packages.eml`) and in the main navigation (`header.eml`).

Oh I thought I was to implement the changes as they are in the figma link you sent . Alright then

**Comment by sabine** [comment]
No, that would be a huge ask and overlap with other tasks. Only the exact thing being linked to inside the document is for this issue. 🙂 I can copy the package dropdown to another Figma Document for clarity tomorrow, if it helps.

**Comment by AndroGenius-codes** [comment]
> No, that would be a huge ask and overlap with other tasks. Only the exact thing being linked to inside the document is for this issue. 🙂 I can copy the package dropdown to another Figma Document for clarity tomorrow, if it helps.

that would be helpful although i already have some edits that i would love for you to review. i will a commit very soon.

**Comment by sabine** [comment]
Here's a Figma document for all the Outreachy issues, with a page for this one: https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=33%3A155&mode=design&t=AsJdiTX8o4t3ALZ7-1
