### ISSUE TITLE
Implement Tutorial Bottom Section Styles (Also read / ask commmunity / contribute)

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1603]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned this issue if you're applying to the Dark Mode Outreachy project.

# Task

The `tutorial.eml` template currently has a section that encourages people to contribute to improve the documentation or to open an issue or ask questions. A new design should be applied to this section as given by [this Figma document](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=3%3A890&mode=design&t=AsJdiTX8o4t3ALZ7-1).

|before|after|
|-|-|
|![Screenshot 2023-10-09 at 18-21-46 Get Up and Running With OCaml · OCaml Tutorials](https://github.com/ocaml/ocaml.org/assets/6594573/b633fe2d-477a-4787-9034-9978adc32117)|![Screenshot from 2023-10-09 18-22-37](https://github.com/ocaml/ocaml.org/assets/6594573/7d641b43-b0c7-474a-9ade-0ce42b6f6968)|

For the "Also read" section, do place dummy data, such as in the Figma document. Your patch will be merged after https://github.com/ocaml/ocaml.org/issues/1589, which will provide the required data, is complete.

How to solve this:
- modify `tutorial.eml` and implement the styles from the Figma document as best as you can.

**Comment by sabine** [comment]
@mohdaquib171 do you want to be assigned to this issue?

**Comment by henilGondalia** [comment]
Hello @sabine @SaySayo,

May I take up this issue for work? My initial pull request for the 'outreachy' 'good first issue' is currently under review. If it's alright, I'd like to begin working on this one as well.

**Comment by mohdaquib171** [comment]
> @mohdaquib171 do you want to be assigned to this issue?

Yes @sabine @SaySayo  please assign this to me, would like to go ahead,  please assign
thanks

**Comment by gpetiot** [comment]
@mohdaquib171 you are now assigned to this issue.

**Comment by SaySayo** [comment]
@mohdaquib171 you have already been assigned to this issue.

**Comment by mohdaquib171** [comment]
hey @sabine @gpetiot  @SaySayo submitted pull request for this issue here : https://github.com/ocaml/ocaml.org/pull/1617
Please merge it and let me know anything i need to do further
thanks
