### ISSUE TITLE
Apply New Styles to Package Documentation Module Navigation

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1607]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned this issue if you're applying to the Dark Mode Outreachy project.

# Task

Currently, the module navigation on the package documentation area (e.g. at https://ocaml.org/p/irmin/latest/doc/index.html) looks like this:
![Screenshot 2023-10-10 at 17-45-14 irmin 3 8 0 (latest) · OCaml Package](https://github.com/ocaml/ocaml.org/assets/6594573/4369befd-7d18-49cb-983b-f6fed3a4a56f)

New styles:
![Screenshot from 2023-10-10 17-44-17](https://github.com/ocaml/ocaml.org/assets/6594573/1099a8ce-1057-4c9b-85bb-20943e72ecb0)

[Here's a Figma Document with the styles](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=27%3A136&mode=design&t=KUzqK4w2r2nJuXGF-1).

How to solve this issue:
1. Inspect the styles from the Figma document to adjust the styles of the different existing tags in `doc.css`.
2. Make changes in `navmap.eml` to use the open/close icons and implement the rest of the Figma design.

**Comment by oyenuga17** [comment]
Hi @sabine, please I'd love to take on this task if possible?

**Comment by henilGondalia** [comment]
Hi @sabine, Can you please assign this to me ?

**Comment by SaySayo** [comment]
@henilGondalia, you will be assigned this issue. Please let me know if you need any help. cc @sabine (she has not been assigned a medium issue yet)

**Comment by henilGondalia** [comment]
Thank you @SaySayo @sabine , I will start working on it and If I need any assistance, I'll be sure to reach out.

**Comment by henilGondalia** [comment]
Hello @sabine @SaySayo. Here in design only Module and Parameter are shown. Does it mean I have to remove Library, Module type, Class and Class type or take module color fill design as reference and do the same for rest ?

**Comment by sabine** [comment]
@henilGondalia Take the design as a reference and apply similar styles to the rest.

**Comment by henilGondalia** [comment]
> @henilGondalia Take the design as a reference and apply similar styles to the rest.

Hi @sabine @SaySayo, I have done changes according to figma design. Do let me know if there is any further changes needed or if any other issue is there for me to resolve.
