### ISSUE TITLE
Grammar in OCaml on Windows page

### ISSUE THREAD

**Issue by Alizter** [ocaml/ocaml.org#1609]
https://ocaml.org/docs/ocaml-on-windows

The list of recommended actions reads a bit funny.

```
Our guidance is when you want:

Only to run, not develop, applications...
```
I would perhaps replace that with "To only run, and not develop, applications...". That way all the sentences in the list start with To so you could lift those out of the bulleted items and replace it with:

```
Our guidance is when you want to:

Only run, and not develop, applications, use [Docker](https://ocaml.org/docs/ocaml-on-windows#docker-images) or [WSL2](https://ocaml.org/docs/ocaml-on-windows#wsl2)
Develop applications and have some familiarity with Unix, use [opam-repository-mingw](https://ocaml.org/docs/ocaml-on-windows#opam-repository-mingw)
Develop applications and care more about stability and ease-of-use than the latest compiler, use [Diskuv OCaml](https://diskuv-ocaml.gitlab.io/distributions/dkml/)
```

**Comment by Raven49** [comment]
Kindly assign me this issue @sabine @SaySayo .I have setup the project as per #1553 
![3](https://github.com/ocaml/ocaml.org/assets/70138609/44f3a049-02cc-4fe7-8759-ce11999a4369)

**Comment by SaySayo** [comment]
@Raven49, you have been assigned to a different issue. Will you rather work on this one?

**Comment by Raven49** [comment]
Okay , I will work on the other issue where I am assigned , but I want to ask that are all the issues listed over in this project counting towards contribution to outreachy ?

**Comment by SaySayo** [comment]
If it has the outreachy tag then it counts towards an outreachy contribution. Although, some issues specifically state if they're for the dark mode or GUI project.

**Comment by Raven49** [comment]
does this issue count towards contribution to outreachy ? @SaySayo @sabine

**Comment by SaySayo** [comment]
I have responded to your question in my previous comment. If it has the outreachy tag then it counts towards an outreachy contribution. @Raven49

**Comment by FatumaA** [comment]
@SaySayo  can i do this as a first outreachy issue

**Comment by CodebyCc** [comment]
can i be assigned to this issue please?

**Comment by SaySayo** [comment]
It has already been fixed and should be closed. cc @sabine

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1615
