### ISSUE TITLE
Add Sub-Navigation on the Blog/News Section

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1610]
# Task

The page at https://ocaml.org/blog (template `blog.eml`) currently just contains the OCaml Planet blog and the News feed. However, we need a place for the changelog and compiler releases to be more easily discoverable.

|before|after|
|-|-|
|![Screenshot 2023-10-11 at 09-22-37 OCaml Blog](https://github.com/ocaml/ocaml.org/assets/6594573/92cd26d4-19e1-48d0-b3e5-6e7d903d5d67)|![Screenshot 2023-10-10 at 18-09-12 OCaml Blog](https://github.com/ocaml/ocaml.org/assets/6594573/2f257912-e059-4bac-9bf8-11c009a4cb56)|

How to solve this issue:
1. refactor the `tabs` component and the `single_column_layout` found in `learn_layout.eml` to a separate `subnav_layout.eml`. The tabs component should take the list of links to display as well as the current link as parameters. Define both the tab links for the Learn section and the tab links for the News section as constants.
2. For this, a rule needs to be added to the dune file at `src/ocamlorg_frontend/dune` to transform the new `subnav_layout.eml` template into an OCaml module.
3. rename "Blog" in `header.eml` to "News".
4. modify `blog.eml`, `releases.eml` and `changelog.eml` to use functions and values from `subnav_layout.eml`.

**Comment by oyenuga17** [comment]
Hi @sabine, please I'd love to be assigned to this issue if no one is on the line 😊 🙏

**Comment by sabine** [comment]
Hey @oyenuga17 which project are you applying to? If you're applying for dark mode, I would like you to do https://github.com/ocaml/ocaml.org/issues/1611 instead because it's about working with the Figma styles.

**Comment by oyenuga17** [comment]
Oh... yes, I'm applying to darkmode

**Comment by oyenuga17** [comment]
@sabine please I'm just curious to know what project this issue is for

**Comment by sabine** [comment]
@oyenuga17 since this does not require working with Figma, the issue is better suited for the GUI project.

**Comment by oyenuga17** [comment]
Thank you @sabine. I was asking because I think I already solved a GUI issue without knowing here #1593. 
Can this also count for darkmode? or I can go ahead and keep contributing to both darkmode and GUI

**Comment by sabine** [comment]
@oyenuga17 because I saw that you are really interested in dark mode, I assigned you a dark mode issue (https://github.com/ocaml/ocaml.org/issues/1611), so that you can apply for dark mode. :slightly_smiling_face: You did great work on https://github.com/ocaml/ocaml.org/pull/1593 and I didn't want to lose your application for dark mode just because I had you do an issue that didn't involve looking up Figma styles. It's up to you to decide which project to apply to now.

**Comment by oyenuga17** [comment]
Thanks so much for the clarification @sabine, I'm still very much interested in the dark mode😊. However I would still love to keep contributing to the GUI when there are no darkmode issues to work on 🙏

**Comment by SwizzCoder** [comment]
Hello @sabine 
I will love to switch to GUI and will love to work on this issue. Please can I be assigned here. 
I initially began contributing to Dark Mode.
I'll begin working on this just in case it's finally assigned to me.

**Comment by IdaraNabuk** [comment]
Hi @sabine, I would love to work on this project if no one is assigned to it. I earlier worked on an issue in the Dark Mode project. Can I still pick up an issue in the GUI project like this one?

**Comment by sabine** [comment]
@shyusu4 I'll assign you to this issue as you didn't have an outreachy-medium issue before.

**Comment by sabine** [comment]
@shyusu4 can you comment on this, so I can assign you? GitHub UI doesn't let me assign you unless there's a comment, I think.

**Comment by shyusu4** [comment]
> @shyusu4 can you comment on this, so I can assign you? GitHub UI doesn't let me assign you unless there's a comment, I think.

sure, here's a comment

**Comment by sabine** [comment]
@shyusu4 I assigned you to this issue!

**Comment by shyusu4** [comment]
@sabine Hey just clarifying, I'm working on solving this issue and I've read through the criteria and I want to make sure I understand correctly. So, basically what I have to do here is create `subnav_layout.eml` and make sure the secondary navigation works for both the learn page and the blog/news page? I'm just a bit confused as what you meant by refactor from `learn_layout.eml`

**Comment by sabine** [comment]
@shyusu4 yes, that's right.

Create `subnav_layout.eml`, move the tabs component there, and then use it in both learn and blog/news page, but with different links provided in the respective pages.

**Comment by shyusu4** [comment]
An update - I've decided to focus on another project, so I'm unassigning myself from this issue. @sabine @SaySayo

**Comment by SwizzCoder** [comment]
Hi @sabine and @SaySayo 
Can I work on this issue now?
I love that it is for the GUI project and this is my preferred project.

**Comment by sabine** [comment]
@SwizzCoder sorry about that, I totally missed this message.

Either way, this issue is up for taking by anyone.

**Comment by SwizzCoder** [comment]
@sabine. Great. I'll love to work on it for the GUI project

**Comment by sabine** [comment]
@SwizzCoder you are now assigned to this issue!

**Comment by SaySayo** [comment]
Hi @SwizzCoder, are you still interested in working on this?

**Comment by Girish-Jangam** [comment]
If no one working on this, @SaySayo i would like to work on this

**Comment by Girish-Jangam** [comment]
@SwizzCoder are you working on this?

**Comment by sabine** [comment]
@Girish-Jangam I'm assigning you to this issue. Thanks for the help!

**Comment by sabine** [comment]
@Girish-Jangam what is the status on this, are you planning to work on this?

**Comment by Girish-Jangam** [comment]
Yup! I'm working on it. I got lot of queries to ask?

**Comment by sabine** [comment]
For sure, don't hesitate to ask questions here.

If the question is about some specific code, open a draft PR with your current branch state. Very easy for me to comment on that and make suggestions.

**Comment by sabine** [comment]
Closing this because we're reworking the entire design of the Main landing page and community sections (including blog).
