### ISSUE TITLE
Adjust styles on the Package Overview Page: Dependencies

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1611]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

This issue is for the Dark Mode project. Only request to be assigned this issue if you are applying for the Outreachy Dark Mode project.

# Task

On the package overview page at, e.g., https://ocaml.org/p/irmin/latest, the styles of the dependencies need to be modified to match the Figma design:

|before|after|
|-|-|
| ![Screenshot 2023-10-11 at 10-47-39 irmin 3 9 0 (latest) · OCaml Package](https://github.com/ocaml/ocaml.org/assets/6594573/c616e032-3328-4b69-a733-e22e9a0fb094)|![Screenshot 2023-10-11 at 10-47-23 Figma](https://github.com/ocaml/ocaml.org/assets/6594573/51e1aec3-3cdb-44b4-833d-21efedfb3d3a)|

[Here is a link to a Figma Document with the styles](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=45%3A92&mode=design&t=q6e3n0Ul6MatGJqY-1).

**Important: Ignore everything except the section with the package dependencies/development dependencies/reverse dependencies/conflicts.**

How to solve this issue:
* In `package_overview.eml`, apply Tailwind styles to make the design match the Figma document, as closely as you can.

**Comment by oyenuga17** [comment]
Hi, @sabine I'm interested in this issue

**Comment by sabine** [comment]
You're now assigned to this issue @oyenuga17 :+1:
