### ISSUE TITLE
Learn page is misaligned

### ISSUE THREAD

**Issue by FatumaA** [ocaml/ocaml.org#1614]
The overview page under docs then learn is misaligned. On small screens at the 'Papers' section and at larger screens at papers and books and the hero section. 

I've attached media to help illustrate this.
![learnPage](https://github.com/ocaml/ocaml.org/assets/67555014/4fe05837-efd9-4195-9bc8-124452037956)

https://github.com/ocaml/ocaml.org/assets/67555014/da29bce8-0f71-49ef-9289-fb2086aab849

**Comment by sabine** [comment]
The page is undergoing another round of UI rework to achieve better alignment and fit the overall site branding currently, but that is not yet ready to be implemented.
