### ISSUE TITLE
The paper in the Language Manual under the Learn section seems a little unclear

### ISSUE THREAD

**Issue by i-shm** [ocaml/ocaml.org#1622]
As shown in the image, the color of the font conflicts with the background. Maybe it would be better to add a blurry background to the paper :)

![image](https://github.com/ocaml/ocaml.org/assets/66583620/97e4ae21-d485-4caf-bb7f-b845890f45fa)

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1623
