### ISSUE TITLE
Reducing the News column on the Blog Page

### ISSUE THREAD

**Issue by iamkalio** [ocaml/ocaml.org#1624]
@sabine @SaySayo  I hope you're having a great day. I went through the Issues and don't think this issue has been raised and not sure if there is a plan for the  section, but, 
on the Blog page the News column is way longer than the Ocaml planet section and this has a large white noise before you get to the footer.
How about we reduce the array of the News at News Section so that  the number of News rendered can match the Ocaml Planet Column,  the most updated is at the top and other can been seen with the `see more` button  to reduce the space below the Ocaml Planet column

<img width="960" alt="Screenshot 2023-10-12 103323" src="https://github.com/ocaml/ocaml.org/assets/89003403/64a244f5-2e9f-4790-a64f-7d536eb87dc8">

**Comment by sabine** [comment]
Sounds good to me. This page is due for a redesign in the future, but for now reducing the number of news elements to be displayed would improve the page. This makes a good simple outreachy issue.

**Comment by Abolade017** [comment]
can i be assigned this issue, I am interested in it and i will like to make contribution on it @SaySayo

**Comment by SaySayo** [comment]
You will be assigned this issue, @Abolade017. Cc @gpetiot

**Comment by Abolade017** [comment]
> You will be assigned this issue, @Abolade017. Cc @gpetiot

alright

**Comment by Abolade017** [comment]
> Sounds good to me. This page is due for a redesign in the future, but for now reducing the number of news elements to be displayed would improve the page. This makes a good simple outreachy issue.

I have made the news column and the ocaml planet columns to be equal in my first commit and i later found out that the images in mobile view is not aligned well, then i thought of centering it and adjusted the width because the ocaml logo image  width is not equal to the other images

**Comment by sabine** [comment]
I think there is some confusion what should be done here.

The only thing that should be done here is to change the number of news items so that the height of the News column and the OCaml Planet column on the largest screen is approximately the same height.

**Comment by kiyov09** [comment]
Is this issue available @sabine? I would like to help.

**Comment by sabine** [comment]
@kiyov09 sounds great to me.

**Comment by kiyov09** [comment]
Got it. I'll do it as soon as I can. Thnx

**Comment by kiyov09** [comment]
This is fixed and live now. FYI

**Comment by tmattio** [comment]
Thanks @kalio007!
