### ISSUE TITLE
Books: link to the English version of "Développement d'applications avec Objective Caml"

### ISSUE THREAD

**Issue by brabalan** [ocaml/ocaml.org#1632]
There was a community translation of "Développement d'applications avec Objective Caml" a long time ago. The result is at https://caml.inria.fr/pub/docs/oreilly-book/

How about linking it from the Books page?

**Comment by sabine** [comment]
Sure, adding that as an additional book to https://github.com/ocaml/ocaml.org/tree/main/data/books sounds fine to me!

**Comment by RWUBAKWANAYO** [comment]
Hi @sabine, I'd like to help with this issue. Can you assign it to me, please?

**Comment by sabine** [comment]
@RWUBAKWANAYO have you completed the setup instructions in https://github.com/ocaml/ocaml.org/issues/1553 and successfully built ocaml.org? If so send a screenshot please.

**Comment by RWUBAKWANAYO** [comment]
> @RWUBAKWANAYO have you completed the setup instructions in #1553 and successfully built ocaml.org? If so send a screenshot please.

Sure!


<img width="1280" alt="Screen Shot 2023-10-16 at 12 13 25" src="https://github.com/ocaml/ocaml.org/assets/68381641/25113504-ad45-4c14-9dad-f4686e271979">


<img width="1280" alt="Screen Shot 2023-10-16 at 12 20 22" src="https://github.com/ocaml/ocaml.org/assets/68381641/ead31548-cf59-43a6-9e0e-4de9230e87cc">

**Comment by sabine** [comment]
Alright @RWUBAKWANAYO, you are now assigned to this issue!

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1659

**Comment by brabalan** [comment]
Thank you!
