### ISSUE TITLE
Map guide: stop promoting using clear text passwords

### ISSUE THREAD

**Issue by benjamin-thomas** [ocaml/ocaml.org#1644]
The guide for [Map](https://ocaml.org/docs/map) is nicely done but promotes the bad practice of using clear text passwords.

I suppose this is common knowledge but this looks bad as-is IMO, plus there's the off chance that some reader may not know the security implications of doing so.

I propose to take another example for Map: **Books**, having

- an ISBN number for the key
- a title for the value

I can take care of rewriting the page, but getting some feedback first is probably a good idea.

**Comment by sabine** [comment]
@benjamin-thomas Sounds like a much better example to me, and a rewrite would be very welcome!

**Comment by Raven49** [comment]
Kindly assign this issue to me @sabine
