### ISSUE TITLE
Releases links are broken

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#165]
The releases have been imported as-is and the relative links are currently broken. We need to update the links to redirect to the correct URL.

**Comment by Angelvicks** [comment]
Hello @tmattio , can I work on this issue please?

**Comment by tmattio** [comment]
Sure, that sounds good @Angelvicks. Let me know when your environment is set up and I'll assign you 🙂

**Comment by Angelvicks** [comment]
hello @tmattio I succeeded in setting up my environment using this links as guide https://github.com/ocaml/v3.ocaml.org-server/blob/main/CONTRIBUTING.md , Do I have to do anything else before working on this issue?

**Comment by Angelvicks** [comment]
if the answer is no, please I will more information on how I can successfully work on this issue?

**Comment by patricoferris** [comment]
Hi @Angelvicks thanks for getting set up :)) 

The issue wants to convert all links in the releases to point to something in v3.ocaml.org. For example look at the markdown of this release page https://raw.githubusercontent.com/ocaml/v3.ocaml.org-server/main/data/releases/en/4.09.1.md it links to a relative path `4.09.0.html` so if you try and use it https://v3.ocaml.org/releases/4.09.1 you'll see it 404s. We want to update all the broken links in the markdown to point to the right place wherever we can

**Comment by Angelvicks** [comment]
hello @patricoferris , after clicking on the link https://v3.ocaml.org/releases/4.09.1 , I did not see 404s so I am wandering how to update links when its not broken. Please can u throw more lights on this issue?

**Comment by patricoferris** [comment]
The link to 4.09.0 _on the 4.09.1_ page 404s, sorry if I wasn't clear :))

**Comment by Angelvicks** [comment]
Please I still don't understand. I verified the links in the markdown, https://raw.githubusercontent.com/ocaml/v3.ocaml.org-server/main/data/releases/en/4.09.1.md and it points to github issues. My question is how then can I correct the broken link inside the 4.09.1 page, must it be done through the code that I setup locally or from github using the markdown code?

**Comment by patricoferris** [comment]
This first part contains an incorrect link: 

```
This page describe OCaml **4.09.1**, released on Mar 16, 2020.  It is
a bug-fix release of [OCaml 4.09.0](4.09.0.html).
```

There is no route in our server that will match `4.09.0.html`, there are quite a lot of examples like this. 

> My question is how then can I correct the broken link inside the 4.09.1 page, must it be done through the code that I setup locally or from github using the markdown code?

Both really, you can't test that your links work without having it setup locally but a majority of the corrections will be in the markdown yes. But you could also maybe add things to the routing logic to point to say the latest `4.X` release so if we linked to `4.10` this would go to `4.10.2` for example. Just a thought.

**Comment by Angelvicks** [comment]
Hello @patricoferris , After days of research, I am still trying to find out how to solve this issue. Its not really clear to me. Sorry if its taken too long, I have never fixed broken links before.

**Comment by Angelvicks** [comment]
Hello @tmattio and @patricoferris Please help me review my pull request. thanks
