### ISSUE TITLE
Add videos of Outreachy presentations to the Outreachy page

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#1650]
There have been presentations of the Outreachy internship for the past few cohorts:
- May 2023: https://watch.ocaml.org/w/kTwq4AVQtRtFuQx9R5cPro
- December 2022: https://watch.ocaml.org/w/pQSAfZ9kDSsSnr8Bxzocn3
- May 2022: https://watch.ocaml.org/w/vXJtTj3cULRa1bZB5HrecX
- December 2021https://watch.ocaml.org/w/eSSmoyEcPTEXPGAqDtKENX

There is also a dedicated page on OCaml.org with the summaries of the internships: https://ocaml.org/outreachy

We should add these videos as a section of the Outreachy page.

cc @pitag-ha

**Comment by sabine** [comment]
# Task

1. In `outreachy.ml`, add a field `all_presentations_video` to the type `t` (which is the type that describes an outreachy round).
2. Modify `outreachy.yml` to include the link to the full presentations as in the issue comment above.
3. In the template `outreachy.eml`, add a video embed (for how to do these see `platform.eml`) at the top of each respective section for which we have a video.

**Comment by Solar-Rays** [comment]
Can I handle this issue please? @sabine @SaySayo @gpetiot

**Comment by sabine** [comment]
@Solar-Rays I assigned you to https://github.com/ocaml/ocaml.org/issues/1651. This issue is still available for someone to take.

**Comment by Solar-Rays** [comment]
That is fine. Thanks

**Comment by CodebyCc** [comment]
please can i be assigned to this issue

**Comment by SaySayo** [comment]
Do you proof of the setup running on your computer? @CodebyCc

**Comment by CodebyCc** [comment]
Yes please

**Comment by SaySayo** [comment]
Can you post the screenshot ? @CodebyCc

**Comment by CodebyCc** [comment]
Okay sure here it is

**Comment by CodebyCc** [comment]
![unnamed](https://github.com/ocaml/ocaml.org/assets/95186244/dd52b157-40a5-46a8-9d92-b52a7c49c6b6)

**Comment by SaySayo** [comment]
@CodebyCc you'll be assigned this issue. Cc @sabine

**Comment by MelakuAlehegn** [comment]
Hi @SaySayo @sabine , can I be assigned to this issue? or any issues out there that I can contribute on, I have seen the list of the outreachy open issues and the list is almost empty.

**Comment by SaySayo** [comment]
Hi @MelakuAlehegn, there are currently no more available outreachy issues to be assigned at the moment.

**Comment by CodebyCc** [comment]
> @CodebyCc you'll be assigned this issue. Cc @sabine

ok thanks im working on it.

**Comment by MelakuAlehegn** [comment]
@SaySayo so should I find issues that are not tagged outreachy or should I wait for issues to be open?

**Comment by SaySayo** [comment]
Sure, if you find an issue you think you can work on, you can tag me on it. @MelakuAlehegn

**Comment by SaySayo** [comment]
Hi @CodebyCc, I sent you a message on discord

**Comment by CodebyCc** [comment]
Hi I saw it not too long ago I have replied .

Thanks

**Comment by MelakuAlehegn** [comment]
hi @SaySayo I have mentioned you on an issue I want to work on, can you check please?

**Comment by SaySayo** [comment]
The presentation videos are already included in the `outreachy.ml` file. To be clear, is this issue meant to display the embedded video on the page? as currently, the videos to the outreachy presentation only leads to an external link on `watch.ocaml.org`. cc @sabine

**Comment by tmattio** [comment]
Ah indeed, I hadn't realised we already had links already, apologies for the noise!

I think it would be good to have thumbnails, but I suggest we do this when we do a design pass on this page.
