### ISSUE TITLE
Content spills over the viewport in mobile

### ISSUE THREAD

**Issue by Solar-Rays** [ocaml/ocaml.org#1651]
The content of some pages on the website extends beyond the viewport on mobile devices. Some of the pages affected are listed here: 

https://ocaml.org/community (View Ocaml Outreachy Internship Projects button)
https://ocaml.org/outreachy (Winer 2021 section)

![Screenshot_2023-10-14-17-48-19-437_com android chrome](https://github.com/ocaml/ocaml.org/assets/62729684/99946759-c51b-4e10-83ab-0426181a90b6)
![Screenshot_2023-10-14-17-48-55-549_com android chrome](https://github.com/ocaml/ocaml.org/assets/62729684/fcef9405-0c79-4478-929e-98f435016822)

**Comment by sabine** [comment]
Yes, that makes a wonderful Outreachy issue. Do you want to be assigned to this issue?

**Comment by Solar-Rays** [comment]
Yes please. I would love to work on it

**Comment by sabine** [comment]
@Solar-Rays you are now assigned to this issue!

**Comment by Solar-Rays** [comment]
Thanks @sabine

**Comment by sabine** [comment]
Seems to be resolved by #1722.

**Comment by Solar-Rays** [comment]
Hi @sabine This does not seem to be fixed yet. Please check the Winter 2021 section of the ocaml.org/outreachy page on mobile.
