### ISSUE TITLE
Border radius missing

### ISSUE THREAD

**Issue by OkunadeNaheem** [ocaml/ocaml.org#1652]
![WhatsApp Image 2023-10-16 at 11 30 45_535f92a2](https://github.com/ocaml/ocaml.org/assets/109427907/c0090130-c708-45bf-9275-7c90dfa09e90)

**Comment by sabine** [comment]
This is not a missing border-radius. This is related to https://github.com/ocaml/ocaml.org/issues/819 and is already being addressed by https://github.com/ocaml/ocaml.org/pull/1626.
