### ISSUE TITLE
Margin/padding missing in between "see all releases" button and Div element with The Ocaml Ecosystem <p> element

### ISSUE THREAD

**Issue by OkunadeNaheem** [ocaml/ocaml.org#1653]
![WhatsApp Image 2023-10-16 at 11 30 46_16d471fd](https://github.com/ocaml/ocaml.org/assets/109427907/c1d86fc3-7909-43ce-a58d-f0b36ca36ce5)

**Comment by sabine** [comment]
Will already be addressed by https://github.com/ocaml/ocaml.org/issues/1463 (new design to make changelog reachable from the homepage. In order to avoid unnecessary conflicts between patches, I am closing this issue in favor of https://github.com/ocaml/ocaml.org/issues/1463.
