### ISSUE TITLE
Bad Media query for Mobile screen size of the community page

### ISSUE THREAD

**Issue by OkunadeNaheem** [ocaml/ocaml.org#1654]
![WhatsApp Image 2023-10-16 at 11 54 40_9afc80ea](https://github.com/ocaml/ocaml.org/assets/109427907/2f625605-eec3-4bf2-a3a5-82c271768478)
![WhatsApp Image 2023-10-16 at 11 54 40_bb3c6c6c](https://github.com/ocaml/ocaml.org/assets/109427907/7070a546-5b5c-4aee-b1e8-b65d6135e2a8)
![WhatsApp Image 2023-10-16 at 11 54 40_fad3b075](https://github.com/ocaml/ocaml.org/assets/109427907/f789c0e0-3542-4728-81bc-123c0e2fd5be)

**Comment by sabine** [comment]
Seems to be the same report as https://github.com/ocaml/ocaml.org/issues/1651
