### ISSUE TITLE
Missing Search image in all screen size mode

### ISSUE THREAD

**Issue by OkunadeNaheem** [ocaml/ocaml.org#1655]
![WhatsApp Image 2023-10-16 at 12 06 57_beba53f4](https://github.com/ocaml/ocaml.org/assets/109427907/2381d63e-38db-4db6-90de-341c1d180ae7)
![WhatsApp Image 2023-10-16 at 12 06 58_f9e0319c](https://github.com/ocaml/ocaml.org/assets/109427907/b22d2ff7-8f1b-4d0e-b7d5-267eed12b0be)

**Comment by sabine** [comment]
Cannot be fixed on this repository. Would need to be fixed upstream at https://github.com/ocaml/v2.ocaml.org/.

Will be resolved either way when language manual migrates to odoc and v2.ocaml.org is retired.
