### ISSUE TITLE
Incorrect Media query of Changelog page for Mobile screen size

### ISSUE THREAD

**Issue by OkunadeNaheem** [ocaml/ocaml.org#1656]
![WhatsApp Image 2023-10-16 at 12 21 40_837015a4](https://github.com/ocaml/ocaml.org/assets/109427907/2598fecd-ab8e-427e-a57f-a07f3840036f)
![WhatsApp Image 2023-10-16 at 12 21 40_06d26548](https://github.com/ocaml/ocaml.org/assets/109427907/52c65bee-8131-4ce7-9b61-1ff7b4c5f83d)
![WhatsApp Image 2023-10-16 at 12 21 41_7593c7cb](https://github.com/ocaml/ocaml.org/assets/109427907/a36c592b-be64-4673-aa1d-b9689ed02c56)
![WhatsApp Image 2023-10-16 at 12 25 14_41175990](https://github.com/ocaml/ocaml.org/assets/109427907/d8a7b6e9-6018-43ed-b3c4-160683b658f4)

**Comment by sabine** [comment]
Something might be overflowing on the changelog page, investigating this is a valid Outreachy issue. Do you want to be assigned to this issue @Demmythetechie?

**Comment by OkunadeNaheem** [comment]
Yes, I would be glad to work on this issue

**Comment by sabine** [comment]
You're now assigned to this issue @Demmythetechie!
