### ISSUE TITLE
Handle trailing slash

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#166]
Currently most of the pages 404 when there's a trailing slash, I think commonly web pages either still provide the implicit `index.html` file or do a redirection either to or from the trailing slash version. For example https://v3.ocaml.org/users is fine but https://v3.ocaml.org/users/ 404s, this was most noticeable for me when looking at packages like https://v3.ocaml.org/p/conan which redirects but https://v3.ocaml.org/p/conan/ does not. 

I don't know what the cleanest way to handle this, some middleware @tmattio ? The old site seems to redirect anything that doesn't end with a trailing slash to the same URL with one e.g. https://ocaml.org/docs goes to https://ocaml.org/docs/

**Comment by desirekaleba** [comment]
Hi @tmattio, Can I try this, please?

**Comment by tmattio** [comment]
Hi @desirekaleba 🙂 It looks like a good issue to get started, but let's wait for you to be up and running before I can assign you: we're asking applicants to have their environment ready before assigning them issues.

**Comment by desirekaleba** [comment]
Sure @tmattio, I tried setting up my development environment  following the [contributing guide](https://github.com/ocaml/v3.ocaml.org-server/blob/main/CONTRIBUTING.md) but I am getting an error saying `Failed to get sources of pecu.0.6: "/usr/bin/cp -PRp /tmp/opam-162262-ca2c6c/pecu-v0.6/.gitignore
        /tmp/opam-162262-ca2c6c/pecu-v0.6/.ocamlformat /tmp/opam-162262-ca2c6c/pecu-v0.6/.travis.yml
        /tmp/opam-162262-ca2c6c/pecu-v0.6/CHANGES.md /tmp/opam-162262-ca2c6c/pecu-v0.6/LICENSE.md
        /tmp/opam-162262-ca2c6c/pecu-v0.6/README.md /tmp/opam-162262-ca2c6c/pecu-v0.6/dune-project
        /tmp/opam-162262-ca2c6c/pecu-v0.6/fuzz /tmp/opam-162262-ca2c6c/pecu-v0.6/lib /tmp/opam-162262-ca2c6c/pecu-v0.6/pecu.opam
        /tmp/opam-162262-ca2c6c/pecu-v0.6/test`.
        
This is a huge blocker for me now.

**Comment by desirekaleba** [comment]
Hi @tmattio, I am now up and running. I am requesting if I can be assigned to this issue.

**Comment by tmattio** [comment]
Sure @desirekaleba, assigning you now

**Comment by desirekaleba** [comment]
Should I get more light on it, please?

**Comment by tmattio** [comment]
FYI, as @patricoferris hinted, I think the best way to solve this is by creating a middleware. Reading the code, we already have one that does that here: https://github.com/ocaml/v3.ocaml.org-server/blob/main/src/ocamlorg_web/lib/middleware.ml#L1, so this issue is about investigating why it doesn't work.

**Comment by desirekaleba** [comment]
I am currently looking at that. But before I proceed, Can you please suggest a good vs code extension for .ml extensions?

**Comment by patricoferris** [comment]
https://github.com/ocamllabs/vscode-ocaml-platform is the recommended one, in VSCode I believe it is still called OCaml Platform or something like that

**Comment by desirekaleba** [comment]
I have it up and running now. Thank you @patricoferris.

**Comment by desirekaleba** [comment]
@tmattio, I have been looking for a way to fix this and I have just noticed that the middleware (`no_trailing_slash`) is only running when you hit home("/").

**Comment by tmattio** [comment]
Done in #170
