### ISSUE TITLE
Your First Ocaml Program takes you to an error 404 page

### ISSUE THREAD

**Issue by Solar-Rays** [ocaml/ocaml.org#1660]
When going through the Ocaml learn page, clicking on the "Your First Ocaml Program" link takes you to an error 404 page. Here is the link to the page: https://ocaml.org/docs/your-first-ocaml-program

**Comment by sabine** [comment]
Cannot reproduce. Link on the Learn Overview page seems to go to https://ocaml.org/docs/your-first-program, which does not 404.

**Comment by cuihtlauac** [comment]
Can't reproduce it either. `git grep your-first-ocaml-program` returns nothing. Seems like a hosting or caching artefact
