### ISSUE TITLE
Misalignment of search bar on medium-sized screens

### ISSUE THREAD

**Issue by RWUBAKWANAYO** [ocaml/ocaml.org#1661]
### Description:
When accessing the [https://ocaml.org/packages](https://ocaml.org/packages) page, there is an issue with the responsiveness of the search bar on medium-sized screens. The search bar appears misaligned, positioned to the left of the screen with a fixed width, which disrupts the visual presentation of the user interface.

### Screenshot Reference:
Please refer to the screenshot below for a visual representation of the problem.

<img width="1280" alt="Screen Shot 2023-10-17 at 07 35 41" src="https://github.com/ocaml/ocaml.org/assets/68381641/d0179354-3a84-4b5b-ad0e-ec95f6b9ae9d">

**Comment by sabine** [comment]
Thank you for reporting @RWUBAKWANAYO, do you want to be assigned this issue as an Outreachy issue?

**Comment by RWUBAKWANAYO** [comment]
@sabine,   I'd be happy to work on this. Please assign me the issue.

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1665
