### ISSUE TITLE
Add Capability for a Book Entry to have Multiple Languages

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1666]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned to this issue if you are applying to the GUI project.

# Task

With https://github.com/ocaml/ocaml.org/pull/1659, we now have a book entry that is available in multiple languages (English and French).

Your task is to add the capability for a book entry to have multiple languages.

How to solve this issue:
1. edit `book.ml` and change language from a `string` to a `string list`.
2. edit all the files in `data/books` to adjust the language to list format.
3. update `handler.ml` to filter wrt list of languages of the book.

**Comment by IdaraNabuk** [comment]
@sabine Kindly assign this tasks to me. I have started working on it.

**Comment by sabine** [comment]
@IdaraNabuk You are now assigned to this issue!

**Comment by 123ZOKzok** [comment]
@sabine kindly assign me an outreachy-medium task

**Comment by IdaraNabuk** [comment]
@sabine I just created a draft pull request: https://github.com/ocaml/ocaml.org/pull/1679
It is still a work in progress.

**Comment by IdaraNabuk** [comment]
@sabine Kindly review: https://github.com/ocaml/ocaml.org/pull/1679

**Comment by Raven49** [comment]
Hi @sabine @SaySayo  , I have made my first contribution as #1658  Kindly assign me any new task so that i can contribute for Outreachy.

**Comment by IdaraNabuk** [comment]
Hello @sabine, I am still expecting your comments regarding my PR: https://github.com/ocaml/ocaml.org/pull/1679. 
I want to know if it solves the problem the way you want it, or if I should work on it again, especially concerning the last task of the issue.

**Comment by IdaraNabuk** [comment]
@sabine If everything is okay with the PR, I would love to be assigned another issue. Thank you.
