### ISSUE TITLE
Tour of OCaml recommendations point to 404

### ISSUE THREAD

**Issue by maiste** [ocaml/ocaml.org#1671]
Hi! :)
First, thanks for the great work you've made with [ocaml.org](ocaml.org)! :sparkle: 

I was looking at the new pages on the website and, at the end of [this page](https://ocaml.org/docs/tour-of-ocaml#conclusion), there are few links, but they all seem to point to `404 Not Found`. Looking at the repository, they don't seem to point to anything in the directory ([code](https://github.com/ocaml/ocaml.org/blob/16a3b37db96a40fdaec6b5b9e7cf6a8f604e4a3c/data/tutorials/getting-started/1_01_a_tour_of_ocaml.md?plain=1#L749)).

Maybe it is intended as the other articles are coming, but I preferred pointed to the problem to make sure it isn't one :smile:

**Comment by cuihtlauac** [comment]
Thanks @maiste. This is indeed a bug. I believe the URLs in the markdown source are missing a slash at the beginning.

**Comment by cuihtlauac** [comment]
PR: https://github.com/ocaml/ocaml.org/pull/1672
