### ISSUE TITLE
Add a Policies Page for the OCaml Logo

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1674]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned to this issue if you are applying to the GUI project.

# Task

At https://v2.ocaml.org/docs/logos.html, the old version of the website has a page that lists the OCaml logos and refers to the ocaml/ocaml-logo repository. The new website at ocaml.org does not yet have such a page.

Create a dedicated page for the logos, taking some inspiration from the old page.

1. Create a new template `logos.eml` that renders the page. Be careful about indentation, the templating engine used in this project is sensitive to it.
2. Add a rule to the dune file at `src/ocamlorg_frontend/dune` to process the `logos.eml` template into an OCaml module `logos.ml`.
3. Add a function for the new template to `ocamlorg_frontend.ml`.
4. Add a handler `logos` to `handler.ml` that renders the new template.
5. Add a route `/policies/logos` for the new page to `src/global/url.ml` and register the handler from the previous step it in the router at `router.ml`.

**Comment by sabine** [comment]
@FatumaA do you want to be assigned this task, and are you applying to the GUI project?

**Comment by Raven49** [comment]
@sabine could you please assign me this issue ? I have already made my first contribution #1658

**Comment by Girish-Jangam** [comment]
@sabine While i have my PR for Review, i would like to start on this too. please assign this to me.

**Comment by FatumaA** [comment]
@sabine ive applied to the dark mode project. Yes, i'd like to take this task

**Comment by sabine** [comment]
@Girish-Jangam @Raven49 Who of you is applying to the GUI project?

**Comment by sabine** [comment]
@FatumaA I will try and come up with another task for you.

**Comment by Girish-Jangam** [comment]
@sabine Regardless of any project i want to contribute to this & as I've already worked on one previous GUI issue, I would like to take on this too! Yes i'm applying to GUI Project.

**Comment by SaySayo** [comment]
@Girish-Jangam you will be assigned this issue. cc @sabine

**Comment by Raven49** [comment]
> @Girish-Jangam @Raven49 Who of you is applying to the GUI project?

@sabine I am working on the dark mode project so if it is the same as the GUI project then kindly assign this task to me .

**Comment by Girish-Jangam** [comment]
https://github.com/ocaml/ocaml.org/assets/59350195/8e93aa5d-656a-4e79-8a86-5639ac3eb16d

 @sabine @SaySayo An Update on the issue. 
 
 Could you please let me know if I am on track?
 
 Thank you for assigning this task to me!

**Comment by SaySayo** [comment]
Can you open a draft pull request @Girish-Jangam
