### ISSUE TITLE
Button Centering on Ocaml Homepage

### ISSUE THREAD

**Issue by MelakuAlehegn** [ocaml/ocaml.org#1676]
@SaySayo @sabine  I have seen that the button to view all releases has some distortion(attached to the bottom section) when displayed on screens less than 1023. I have attached the screenshots for both the screens. I don't know if this is a major issue or the button is supposed to be that way in the first place but putting it in the middle as it is on wider screens seems convenient for me. Please confirm so that I can create the issue and work on it.

this is how the button looks on medium screen 
![uncenteredbutton](https://github.com/ocaml/ocaml.org/assets/49185991/fa59dd78-a39e-49ae-bf55-bb4170965a7c)

how it was supposed to look like 
![centered button](https://github.com/ocaml/ocaml.org/assets/49185991/e96c33a7-800d-48cc-be32-3dc048ac06b6)

**Comment by sabine** [comment]
Will be resolved by https://github.com/ocaml/ocaml.org/issues/1463. Thus, closing.
