### ISSUE TITLE
Update Learn Area Left Sidebar Styles

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1678]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned this issue if you're applying to the Dark Mode Outreachy project.

# Task

The Navigation in the left sidebar of the Learn area at https://ocaml.org/docs/data-types needs to be improved:

|Current Page|Planned Design|
|-|-|
|![Screenshot 2023-10-18 at 17-37-10 Basic Datatypes and Pattern Matching · OCaml Tutorials](https://github.com/ocaml/ocaml.org/assets/6594573/513fbf49-4190-4406-bf7c-f9301dfb3387)|![Screenshot 2023-10-18 at 17-37-10 Basic Datatypes and Pattern Matching · OCaml Tutorials](https://github.com/ocaml/ocaml.org/assets/6594573/fa1c7f97-271c-4d50-a97a-228151f1c673)|

Here is [the Figma document for reference regarding the styles](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=300%3A2&mode=dev&t=SVZcP2fuAQa8onKt-1).

How to solve this issue:

1. Assign Tailwind CSS styles in `learn_sidebar.eml` to match the Figma design. Try to match the design as closely as you can with default Tailwind spacings.

**Comment by sabine** [comment]
@FatumaA do you want to be assigned to this issue?

**Comment by FatumaA** [comment]
Yes

**Comment by sabine** [comment]
Great, you're now assigned this issue @FatumaA

**Comment by Raven49** [comment]
I  have solved one issue labelled outreachy and good first issue . Kindly assign me any new outreachy or outreachy-medium  labelled issue @sabine @SaySayo
