### ISSUE TITLE
Improve Platform Page Card Styles

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1685]
# Task

The Platform Tools page at https://ocaml.org/docs/platform needs to be improved:

|Current|Planned Design|
|-|-|
|![Screenshot 2023-10-19 at 13-58-09 OCaml Platform](https://github.com/ocaml/ocaml.org/assets/6594573/9a2484a1-5116-40d8-88bb-c6af21e81e56)|![Screenshot from 2023-10-19 13-58-57](https://github.com/ocaml/ocaml.org/assets/6594573/f1159a0b-b190-4cec-86cc-8011845d2c97)|

Here is [the Figma document for reference regarding the styles](https://www.figma.com/file/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?type=design&node-id=326%3A20&mode=dev&t=2r15NvzWGSZIepb5-1).

How to solve this issue:

1. Assign Tailwind CSS styles in `platform.eml` to match the Figma design. Try to match the design as closely as you can with default Tailwind spacings.

**Comment by sabine** [comment]
@Raven49 do you want to be assigned to this issue?

**Comment by 123ZOKzok** [comment]
@sabine can I be assigned this issue?

**Comment by RWUBAKWANAYO** [comment]
@sabine,   I'd be happy to work on this. Please assign me the issue.

**Comment by IdaraNabuk** [comment]
@sabine I would love to work on this issue. Kindly assign it to me.

**Comment by Raven49** [comment]
> @Raven49 do you want to be assigned to this issue?

Yes please assign it to me

**Comment by Raven49** [comment]
Kindly assign this issue to me @sabine @SaySayo

**Comment by Raven49** [comment]
Thank you @sabine

**Comment by FatumaA** [comment]
Hi,
@Raven49 are you working on this? Do you need some help on it? 

And if not, can this be reassigned @sabine? If so, I'd like to pick it up

**Comment by FatumaA** [comment]
Working on this then @SaySayo
