### ISSUE TITLE
Documentation for alt-ergo packages missing

### ISSUE THREAD

**Issue by bclement-ocp** [ocaml/ocaml.org#1686]
The following URLs:

https://ocaml.org/p/alt-ergo/latest/doc/index.html
https://ocaml.org/p/alt-ergo-lib/latest/doc/index.html
https://ocaml.org/p/alt-ergo-parsers/latest/doc/index.html
https://ocaml.org/p/alt-ergo-plugin-ab-why3/latest/doc/index.html

(Note that the documentation for the alt-ergo packages points to the ancient 0.95.2 version that has an empty documentation, not to the recent 2.5.2 version that should have a documentation)

`dune build @doc` correctly builds the doc, and `@doc` is included as target with the `with-doc` marker on the published opam files. `odig doc` also works locally, so it looks like this is an issue with `ocaml.org`, but maybe something is wrong with our `opam` file on the repository?

**Comment by sabine** [comment]
@bclement-ocp Sorry about that, your packages seem fine and I promoted a new documentation epoch live where they built successfully.
