### ISSUE TITLE
Missing OCaml Workshop 2023

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#1688]
As reported in https://discuss.ocaml.org/t/ann-new-get-started-documentation-on-ocaml-org/13269/2.

cc @lukstafi

**Comment by RWUBAKWANAYO** [comment]
@tmattio, I'd be happy to work on this. Please assign me the issue and provide the necessary content to proceed.

**Comment by IdaraNabuk** [comment]
@tmattio Kindly assign this issue to me

**Comment by tmattio** [comment]
@SaySayo, we have Outreachy contributors interested in working on this issue it seems 🙂 Can I let you scope out the issue to give the right amount of instructions (it should maybe be an outreachy-medium issue?) and assign applicants to it?

**Comment by SaySayo** [comment]
Yes, absolutely. On it!

**Comment by SaySayo** [comment]
@tmattio, i'm scoping out the issue and I'm unsure where to get the data for the 2023 workshop. I’ve scanned through watch ocaml and also the icfp page, (https://icfp23.sigplan.org/home/ocaml-2023) and can’t find links to the recorded sessions.

**Comment by tmattio** [comment]
The recordings haven't been published I think, so we'd need to add them later. For now, we can start porting the information from the ICFP website.

**Comment by SaySayo** [comment]
### Task
Include the ICFP OCaml Workshop 2023 into the list of workshops displayed on this page https://ocaml.org/community#workshops.

Workshop has these fields:

-   title
-   slug 
-   location
-   date 
-   important_dates
-   presentations
-   program_committee
-   organising_committee
 and the rest of the body

How to solve this issue:

- In the data/workshops directory, create a `2023.md` file and copy out the information about the workshops and sessions from the [ICFP page](https://icfp23.sigplan.org/home/ocaml-2023) and fill them out in the same way they are filled out in the `2022.md` file

**Comment by Oluwabukolab** [comment]
Can I be assigned to this issue please? @SaySayo, all the other issues have been claimed.

**Comment by SaySayo** [comment]
@IdaraNabuk and @RWUBAKWANAYO, you have both been assigned to other issues

**Comment by SaySayo** [comment]
@sophiatunji, you will be assigned to this issue. cc @sabine
