### ISSUE TITLE
Package documentation generation should not introduce a H1 Title

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml.org#1690]
# Issue description

The new package website looks really great and I'm considering updating all our links to it. However, there's one issue that bothers me a bit. Currently, the package **Docs** section is adding the title **"package version"** to the index page (for example **irmin 3.9.0** in the screenshot), as shown below:

![image](https://github.com/ocaml/ocaml.org/assets/1471328/6a1b2210-b036-4eac-9c48-61a9b15be42e)

# Why I think the additional title is not great

I found this undesirable for three reasons:

1. A packages with custom `index.mld` will likely have its own name as the title, due to how `dune build @doc` currently generates pages. In this example, the irmin package already has **"Irmin"** as the title of its documentation. The same thing happens in many of our packages I maintain. There's no need to repeat the package name.
2. The version is arguably not very useful, and it's already available at the upper left corner (highlighted).
3. One may argue that the information can still be useful, and it might look okay-ish when there's no custom `index.mld` page. But, even if that's all true, there's still an inconsistency between the **Docs** page and the **Overview** page. The **Overview** page does not repeat package name or version. The **DESCRIPTION** section is not prefixed with the package name or version:

   ![image](https://github.com/ocaml/ocaml.org/assets/1471328/2a970c6f-2f20-4b79-94b1-321b11238f21)

# Concrete suggestion

I prefer _not_ to have the additional title **"package version"**. I wonder if we could stop adding it to the **Docs** index page.

**Comment by sabine** [comment]
Thank you for bringing this to our attention @favonia. Absolutely, it should not look like this. I opened an issue in the place where this can and will be fixed.

**Comment by favonia** [comment]
@sabine Is it okay to change this issue's title as well, as you seem to agree that it always looks better without the extra H1 title, with or without `index.mld`?

**Comment by favonia** [comment]
@sabine The new documentation pages were fixed. :heart: Thank you!
