### ISSUE TITLE
Add Ability to Record Upcoming Events

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1697]
This is an Outreachy Medium difficulty issue. You must have completed a simple issue (marked with label "outreachy") first, to be eligible for being assigned to this one.

Please only request to be assigned to this issue if you are applying to the GUI project.

# Task

It would be nice to have a directory for upcoming OCaml-related events and list them on the Community page at https://ocaml.org/community.

Event in this case can mean:
1. OCaml presentations (e.g. meetup or conference) happening somewhere around the world or online at a given date / time.
2. OCaml retreats (e.g. MirageOS retreat or others)
4. OCaml workshops, i.e. hands-on coding experiences.

Event has these fields:
- title
- url (where more information about the event can be found, only events that have a website explaining more can be added)
- textual location
- (optional) location (lat lon)
- start date
- (optional) start time, end time
- (optional) end date

How to solve this issue:
1. In the `tool/ood-gen/lib` directory, add a new file `event.ml` that reads markdown files from `data/events`. Take inspiration from `meetup.ml` on how to read markdown data.
2. modify `tool/ood-gen/bin/gen.ml` to register the new template parser you just created in step (1).
3. add a new dune rule to `src/ocamlorg_data/dune` to use ood-gen to generate `event.ml`.
4. modify `src/ocamlorg_data/data.ml` and `src/ocamlorg_data/data.mli` to expose the new Event module to the rest of the codebase.
5. modify `community.eml` to take upcoming events as a parameter, and add a section that renders a list of upcoming events
6. modify the `community` function in `src/ocamlorg_web/lib/handler.ml` to filter for the next 6 upcoming events and pass these to the template.

**Comment by IdaraNabuk** [comment]
@sabine Kindly assign this issue to me.

**Comment by AndroGenius-codes** [comment]
@sabine I am done working on my previous issue. I'd like to help with this

**Comment by AndroGenius-codes** [comment]
> @sabine I am done working on my previous issue. I'd like to help with this

Oh I see another person has requested for it.  Please @sabine if you open another issue do let me know

**Comment by tmattio** [comment]
Shouldn't we re-use the meetups for this @sabine? Looks like meetup, conference and retreats should fall in the same category, and we already have a directory for the workshops.

**Comment by sabine** [comment]
@tmattio IMO this here should only be about actual upcoming event dates, whereas both workshop and meetups are about keeping info about things past or ongoing.

There is definitely potential for unifying when we do a community page redesign.

**Comment by IdaraNabuk** [comment]
> @sabine Kindly assign this issue to me.

@sabine Can I go ahead and work on this issue?

**Comment by tmattio** [comment]
> There is definitely potential for unifying when we do a community page redesign.

Sounds good, I don't want to block this then, would be good to make a pass at all the data we have at some point and see if there's opportunities for simplification.

**Comment by sabine** [comment]
@IdaraNabuk I'm assigning you to this issue because the issue you had turned out really quite simple. This one's harder.

**Comment by IdaraNabuk** [comment]
> @IdaraNabuk I'm assigning you to this issue because the issue you had turned out really quite simple. This one's harder.

Thank you @sabine. I'll give it my best.

**Comment by IdaraNabuk** [comment]
Hello @sabine, I am still expecting your review on my PR: https://github.com/ocaml/ocaml.org/pull/1717. 

If everything is okay, is there any other task you would like to assign to me?
