### ISSUE TITLE
Page header misalignment with content on 'https://ocaml.org/docs'

### ISSUE THREAD

**Issue by RWUBAKWANAYO** [ocaml/ocaml.org#1699]
### Description: 
The problem arises on the https://ocaml.org/docs page, where the 'Learn OCaml' header is positioned on the left side, while the content below is centered. 
This misalignment disrupts the visual presentation of the project. To better understand the issue, please refer to the attached screenshot."

<img width="1260" alt="Screen Shot 2023-10-18 at 01 39 40" src="https://github.com/ocaml/ocaml.org/assets/68381641/51cf7d5a-1e61-45d1-9932-606d694165be">

**Comment by sabine** [comment]
Redesign is in progress. Not an issue that should be solved at this time.
