### ISSUE TITLE
Collapse Table on Releases Page on Small and Medium Screens

### ISSUE THREAD

**Issue by RWUBAKWANAYO** [ocaml/ocaml.org#1700]
### Description:
On the 'https://ocaml.org/releases' page, the content is currently displayed in the same row-based style as it appears on larger screens. 
This layout causes content to become hidden, requiring users to scroll through each release to view the complete content. This results in an unfavorable user experience. 
For a more comprehensive understanding of the problem, please consult the attached video demonstration.

https://github.com/ocaml/ocaml.org/assets/68381641/65b8d745-a71c-4b7f-9ef3-c7b0673637b3

**Comment by AndroGenius-codes** [comment]
@sabine can I work on this if it's something you think should be worked on

**Comment by sabine** [comment]
Looks like a useful issue to work on. Collapsing the rows to stacked columns will make it easier to browse on smaller devices. Looks like a medium issue to me as you would also be figuring out a way to stack that makes sense.

Do you want to be assigned to this issue? @RWUBAKWANAYO

**Comment by RWUBAKWANAYO** [comment]
@sabine, I'd like to work on this, please assign it to me!
