### ISSUE TITLE
The Js_of_ocaml link on the home page leads to MirageOS

### ISSUE THREAD

**Issue by AshineFoster** [ocaml/ocaml.org#1704]
The Js_of_ocaml link shown below taken from the home page leads to [mirage](https://mirage.io/).
![Screenshot 2023-10-21 at 21-41-05 Welcome to a World of OCaml](https://github.com/ocaml/ocaml.org/assets/40001976/f5a19322-42bf-4c6b-a30d-b189cf33817d)

**Comment by Oluwabukolab** [comment]
Can I work on this issue @sabine @SaySayo ? Completed my other issues and waiting for review

**Comment by SaySayo** [comment]
You will be assigned this issue @sophiatunji. cc @gpetiot
