### ISSUE TITLE
Collapse Table on Papers Page on Small and Medium Screens

### ISSUE THREAD

**Issue by oyenuga17** [ocaml/ocaml.org#1715]
@sabine this issue is similar to #1700, same thing happens on the papers page

<img width="422" alt="Screenshot 2023-10-24 at 10 29 13" src="https://github.com/ocaml/ocaml.org/assets/64274826/438bb65b-e7cb-4003-af18-aa1c1e636f01">

<img width="454" alt="Screenshot 2023-10-24 at 10 29 34" src="https://github.com/ocaml/ocaml.org/assets/64274826/4bbf6b69-76c2-49c9-a1f3-19d932ab8a29">

**Comment by oyenuga17** [comment]
@sabine please can I work on this issue?

**Comment by sabine** [comment]
@oyenuga17 If you're still up for it, this is a good issue to work on and we'd be very happy to have your help.

**Comment by oyenuga17** [comment]
Thank you @sabine, happy to help 😍
