### ISSUE TITLE
Standard library UI issues

### ISSUE THREAD

**Issue by AndroGenius-codes** [ocaml/ocaml.org#1718]
On the standard library page the hamburger menu on mobile is fixed when scrolling this has distorted the general appearance of the page. I have attached a video to show what I mean. I would like to fix this 

@sabine  @SaySayo 

https://github.com/ocaml/ocaml.org/assets/70571088/3975774e-cd2c-49d6-85fb-d317d3134135

**Comment by AndroGenius-codes** [comment]
@sabine @SaySayo good afternoon, please I need help locating the this page on my local repo. Can you help me with it?

**Comment by AndroGenius-codes** [comment]
> This page is a static page redirected from the old `v2.ocaml.org` site (and is generated on the compiler side). Unfortunately, this means that it cannot be easily fixed.

No wonder. Thank you very much

**Comment by sabine** [comment]
Closing in favor of 
- https://github.com/ocaml/ocaml.org/issues/1403
