### ISSUE TITLE
Typo in "A Tour of OCaml" Pattern Matching Cont'd section

### ISSUE THREAD

**Issue by aloebs29** [ocaml/ocaml.org#1730]
At the very end of the "Pattern Matching, Cont'd" section:

> Note that OCaml throws a warning when pattern matching does not catch call cases:

I'm assuming the word "call" is intended to be "all".

**Comment by sabine** [comment]
correct, thanks @aloebs29 !

**Comment by FatumaA** [comment]
Hi,
 Added a quick fix PR
