### ISSUE TITLE
A redirect to the latest documentation of a package

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#174]
Currently we only have a redirect to the latest package's "home" page i.e. at the time of writing https://v3.ocaml.org/p/irmin goes to https://v3.ocaml.org/p/irmin/2.8.0. 

We might also want a redirect that takes people directly to the latest documentation of a package so perhaps https://v3.ocaml.org/p/irmin/docs goes to https://v3.ocaml.org/p/irmin/2.8.0/doc/index.html -- this would be useful for people to add to their READMEs/Websites pointing to the latest API of a package.

We should also perhaps advertise these redirects on the packages landing page for people to use (I already do that when looking up APIs for example)

cc: @craigfe (who was looking for something like this)

**Comment by olivcamj** [comment]
Hi @patricoferris,  I am an Outreachy applicant and I would like to work on this issue. Any pointers on getting started?

**Comment by tmattio** [comment]
Hi @olivcamj 🙂 Were you able to setup the project already? We're asking applicants to get up and running before we assign them to an issue.

**Comment by olivcamj** [comment]
Hi @tmattio, yes ✅  I was able to set up the project and I completely understand I know that errors during the initial project setup can be a major setback.

**Comment by NiraliJoshi17** [comment]
hello, @patricoferris @tmattio  , I am an Outreachy applicant and I would like to contribute to this issue.

**Comment by tmattio** [comment]
@olivcamj Perfect, in this case you can start on this issue, no problem 🙂 
@NiraliJoshi17, the issue was already asked to be assigned by another Outreachy applicant, so I'll let you choose another one. Also, can you confirm that your environment is setup and that you can run the server locally?

**Comment by NiraliJoshi17** [comment]
@tmattio yes, I am done with the environment setup and I can run the server locally.

**Comment by olivcamj** [comment]
@tmattio Ok thank you!

**Comment by cdaringe** [comment]
```
let documentation_url =
  Sys.getenv_opt "OCAMLORG_DOC_URL"
  |> Option.value ~default:"https://docs-data.ocaml.org/live/"
```

=> invalid cert, & 403s
