### ISSUE TITLE
Changelog, community page faulty responsiveness on mobile 

### ISSUE THREAD

**Issue by AndroGenius-codes** [ocaml/ocaml.org#1742]
https://github.com/ocaml/ocaml.org/assets/70571088/679dc300-7f2d-4e14-9191-369904ed7cc5

**Comment by AndroGenius-codes** [comment]
Currently working on this

**Comment by AndroGenius-codes** [comment]
> Screenrecorder-2023-11-02-17-29-36-985.mp4

@sabine this is something I'd love to work on

**Comment by sabine** [comment]
Sounds great to me! Happy to have your help on this @AndroGenius-codes!

**Comment by sabine** [comment]
Seems resolved, possibly by #1722
