### ISSUE TITLE
Unsemantic blockquote usage throughout the documentation

### ISSUE THREAD

**Issue by toastal** [ocaml/ocaml.org#1758]
If we visit an example page such as [<cite>Installing OCaml</cite>](https://ocaml.org/docs/installing-ocaml), and in the browser console run a line like

```
Array.from(document.getElementsByTagName("blockquote"), (el) => el.innerHTML).join("\n\n")
```

What will be returned is the body of 5 `<blockquote>` elements. According to the HTML specification:

> The blockquote element represents a section that is quoted from another source.
>
> — W3C HTML spec, https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element

However, none of the aforementioned body content are quoted from the document or another source—making the usage of the `<blockquote>` element inappropriate & unsemantic.

According to the example pages source 

https://github.com/ocaml/ocaml.org/blob/5b50fbfac6f6b99aaecb2195f9273d2cd116fd5a/data/tutorials/getting-started/1_00_install_OCaml.md?plain=1#L16
https://github.com/ocaml/ocaml.org/blob/5b50fbfac6f6b99aaecb2195f9273d2cd116fd5a/data/tutorials/getting-started/1_00_install_OCaml.md?plain=1#L42
https://github.com/ocaml/ocaml.org/blob/5b50fbfac6f6b99aaecb2195f9273d2cd116fd5a/data/tutorials/getting-started/1_00_install_OCaml.md?plain=1#L75
https://github.com/ocaml/ocaml.org/blob/5b50fbfac6f6b99aaecb2195f9273d2cd116fd5a/data/tutorials/getting-started/1_00_install_OCaml.md?plain=1#L84
https://github.com/ocaml/ocaml.org/blob/5b50fbfac6f6b99aaecb2195f9273d2cd116fd5a/data/tutorials/getting-started/1_00_install_OCaml.md?plain=1#L92

a `>` token is used for this. According to CommonMark:

> A block quote marker, optionally preceded by up to three spaces of indentation, consists of (a) the character `>` together with a following space of indentation, or (b) a single character `>` not followed by a space of indentation.
>
> — CommonMark Spec v0.30, https://spec.commonmark.org/0.30/#block-quotes

`>` denotes a `<blockquote>` in Markdown and is rendered as such which is the root of the problem.

I believe what is trying to be conveyed is a callout/admonition (name varies per project). While feature-complete lightweight markup options such as [reStructuredText](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions) & [AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/) have a callout/admonition concept built in as they were made with technical documentation in mind, Markdown, at least the base spec, does not have this concept. Some Markdown forks have their own mostly incompatible ways to attempt to get around the necessity of such a feature, the OCaml documentation is not supporting some workaround. 

If a more robust lightweight markup language is out the question, I would suggest using some form that doesn’t use the already-taken `>` usage for `<blockquote>` so as to lessen the chance of rendering incorrectly inside other systems that do follow the spartan CommonMark spec as a baseline …and at a bare minimum, at least the rendering pipeline to the documentation site, the `<blockquote>` element should be rewritten to an element more appropriate for what a callout is trying to convey rather than the incorrect element.

**Comment by cuihtlauac** [comment]
Thanks @toastal. You are correct; the way we use `>` in markdown (at the beginning of line position) is incorrect. These aren't quotes. We need to fix this.
