### ISSUE TITLE
Turn `let` with 0 or 2+ text into a dedicated section

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1760]
Following the feedback by @Release-Candidate in [discuss](https://discuss.ocaml.org/t/new-tutorials-on-basics-of-ocaml)

- [X] Create a dedicated section in “Values and Function” on `let` that creates no or more than one name. Just show `_`, `()` and pairs. Refer to the companion  section in “Basic Data Types and Pattern Matching”
- [x] Get rid of the single constructor tree example. Replace by something monomorphic and non recursive

**Comment by christinerose** [comment]
> * Get rid of the single constructor tree example. Replace by something monomorphic and non recursive

@sabine is addressing this one soon

**Comment by christinerose** [comment]
Done!
