### ISSUE TITLE
Improve wording on `type` 

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1761]
Following the feedback by @Release-Candidate in [discuss](https://discuss.ocaml.org/t/new-tutorials-on-basics-of-ocaml/13396/4)

Add text explaining with more detail how the type declaration syntax works.

Here are the issues pointed by @Release-Candiate:
> `type 'a tree = Node of 'a * 'a tree list;;`
> * type, which declares a type. So far, so normal and understandable
But now:
> * 'a for a type variable. The concept of a type variable already confuses people, having that strange ' makes it worse and the backward syntax doesn’t help either. And then there is Rust which uses that for lifetimes.
> * the of: is that a keyword, another strange type of metavariable, a special type?
> the second worst of all of ML syntax, using * in the type of a tuple (whoever came up with that: you don’t use + for sum types, do you?)
> * the worst of the syntax, the “backwardness” of type definitions 'a tree instead of tree 'a and tree list instead of list tree
>
> And last: this a a recursive data structure, a tree. Most programmers have never used a tree in their whole life, much less the concise, recursive form. They have more practical knowledge of monads than of trees or recursive data structures or recursion in general.

**Comment by christinerose** [comment]
Done!
