### ISSUE TITLE
Feed page style issues

### ISSUE THREAD

**Issue by AndroGenius-codes** [ocaml/ocaml.org#1763]
![Screenshot_2023-11-14-07-41-55-514_com android chrome](https://github.com/ocaml/ocaml.org/assets/70571088/37f396db-c9ab-463c-93e0-2a60d05165f1)
@sabine @SaySayo 
This is what I get when I click on the feed button on mobile. I used both chrome,Microsoft edge and Safari got the same thing so I don't think it's browser related

**Comment by henilGondalia** [comment]
Same problem occurred in laptop/desktop also. It is not browser issue.

**Comment by AndroGenius-codes** [comment]
> Same problem occurred in laptop/desktop also. It is not browser issue.

Oh really? 
@sabine could I take a stab at fixing this

**Comment by oyenuga17** [comment]
@AndroGenius-codes, @henilGondalia, I don't think this is a bug. This is how browsers render xml by default, except some additional tweaks is done to render it in a more human-readable form. 🤔

**Comment by AndroGenius-codes** [comment]
> @AndroGenius-codes, @henilGondalia, I don't think this is a bug. This is how browsers render xml by default, except some additional tweaks is done to render it in a more human-readable form. 🤔

There should be a way  for the browsers to convert to html

**Comment by sabine** [comment]
@oyenuga17 is correct, that is a normal way for an RSS feed to display. The link to an RSS feed is generally copied over to a feed reader. It is a common practice to have an RSS feed link just go to the XML page.

> There should be a way for the browsers to convert to html

That would be up to the browser to implement. :slightly_smiling_face:

Closing this as wontfix.

**Comment by AndroGenius-codes** [comment]
> @oyenuga17 is correct, that is a normal way for an RSS feed to display. The link to an RSS feed is generally copied over to a feed reader. It is a common practice to have an RSS feed link just go to the XML page.
> 
> > There should be a way for the browsers to convert to html
> 
> That would be up to the browser to implement. 🙂
> 
> Closing this as wontfix

Alright then, Thank you
