### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by shindere** [ocaml/ocaml.org#1767]
On `https://ocaml.org/docs`, the link entitled `Data Types and Matching`,
which points to the URL `https://ocaml.org/docs/data-types` is dead.

**Comment by cuihtlauac** [comment]
Thanks Sebastien, this is indeed a bug.

**Comment by shindere** [comment]
Thanks a lot for such a quick fix!

**Comment by shindere** [comment]
Cuihtlauac Alvarado (2023/11/15 04:28 -0800):
> Thanks Sebastien, this is indeed a bug.

Thanks a lot for having fixed it and done so so promptly!
