### ISSUE TITLE
Incorrect styling of title headers in the release list section.

### ISSUE THREAD

**Issue by RWUBAKWANAYO** [ocaml/ocaml.org#1769]
### Description:
Upon visiting the 'https://ocaml.org/releases' page and navigating to the release list section, it becomes apparent that the title headers are experiencing styling issues. The problem is primarily related to incorrect text color. 
For a clearer understanding of the issue, please refer to the attached video demonstration.

https://github.com/ocaml/ocaml.org/assets/68381641/7306109c-e8de-4154-9ebd-5b3a7bcd7cd5

**Comment by sabine** [comment]
Yes, that seems to be a long standing problem to the point that I don't even know if anyone has ever seen those titles. IMO we could remove these titles. Go ahead if you want to @RWUBAKWANAYO. :+1:

**Comment by RWUBAKWANAYO** [comment]
@sabine, can you please merge the changes from ["Improve responsive layout on releases page" pull request](https://github.com/ocaml/ocaml.org/pull/1716)? It will help me fix this issue with the updated main branch. Thanks!

**Comment by sabine** [comment]
Done!

**Comment by RWUBAKWANAYO** [comment]
> Yes, that seems to be a long standing problem to the point that I don't even know if anyone has ever seen those titles. IMO we could remove these titles. Go ahead if you want to @RWUBAKWANAYO. 👍

@sabine, Instead of completely removing the titles, I'm wondering if it might be a good idea to implement a solution similar to what we did on the paper page. 
We could display the title on larger screens and collapse it on medium and small screens. This way, we maintain the information while optimizing the user experience. 
Please take a look at the screenshot below for reference. What do you think?

| Large Screen | Medium Screen |
|--------|-------|
| ![Large Screen](https://github.com/ocaml/ocaml.org/assets/68381641/34514888-8bbb-4835-8499-8a08bff32296) | ![Medium Screen](https://github.com/ocaml/ocaml.org/assets/68381641/3d728c7c-e675-4346-94bd-416d3460e28f) |

**Comment by sabine** [comment]
It's possible, and I think the styling on the papers page is much better, the titles are significantly smaller. Though the last column on the releases page would likely need to be renamed to something like "Resources" or another term that makes more sense.
