### ISSUE TITLE
Select Up to Two Exercises for Tutorials

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1780]
In https://github.com/ocaml/ocaml.org/pull/1753, the ability to link exercises to tutorials was added.

Now, we need to go over all the tutorials and link up to two exercises to them.

For some tutorials, there'll probably be more relevant exercises, so it makes sense to try and select the most relevant / interesting ones.

For some tutorials, we won't have exercises, that's fine. We omit them.

**Comment by Solar-Rays** [comment]
@sabine I wanna try my hands on this one. Can I be assigned this, please?

**Comment by sabine** [comment]
Sure @Solar-Rays, thanks for your help with this!

**Comment by ghost** [comment]
@sabine 
I would love to work on this

**Comment by Aquilaafuadajo** [comment]
@amarachigoodness74 can I pick this up while you work on #2114 ?

**Comment by ghost** [comment]
You can go ahead @Aquilaafuadajo

**Comment by Aquilaafuadajo** [comment]
Thanks @amarachigoodness74 🙏🏽 
@sabine please I would love to give this a try, I have completed my local setup

**Comment by komutumu** [comment]
Can I also give this a try @sabine ?
Would that be okay @Aquilaafuadajo ?

**Comment by Aquilaafuadajo** [comment]
@jahielkomu sorry, I already started working on this. I think you should check the issue board, there are many other to work on there 😊

**Comment by komutumu** [comment]
it is well @Aquilaafuadajo
