### ISSUE TITLE
Bug in tutorial "your first ocaml program", cannot get show to work

### ISSUE THREAD

**Issue by Randle-Lanre** [ocaml/ocaml.org#1794]
## runing:  dune exec helloo
  `File "bin/hello.ml", line 1, characters 24-28:
  1 | let string_list_pp = [% show: string list]
                              ^^^^
  Error: Uninterpreted extension 'show'.`

`helloo/lib/dune`
```ocaml 

(library
 (name helloo)
 (preprocess (pps ppx_deriving.show))
 (libraries ppx_deriving.runtime))
```
`bin/dune`

```ocaml
(executable
 (public_name helloo)
 (name main)
 (libraries helloo ))
 ```
 
`hello.ml`

```ocaml

let string_list_pp = [% show: string list]

let string_of_string_list = Format.asprintf "@[%a@]" string_list_pp

let world = String.split_on_char ' ' "Hello using an opam library"

```

`hello.mli`

```ocaml
val string_of_string_list : string list -> string
val world : string list
```

`main.ml`

```ocaml
let () = print_endline Hello.(string_of_string_list world)
```

running on  WSL Windows 11 
`dune version: 3.11.1`

`ocaml version: 4.13.1`

`opam list` indicates ppx_show and ppx_deriving are installed 
![image](https://github.com/ocaml/ocaml.org/assets/19264390/71f08a9a-ef98-447a-a2af-68906b790a18)

**Comment by cuihtlauac** [comment]
Hi @Randle-Lanre;

In `lib/dune`, the tutorial contains this:
```
(preprocess (pps ppx_show))
(libraries ppx_show.runtime))
```

But you have that:
```
 (preprocess (pps ppx_deriving.show))
 (libraries ppx_deriving.runtime))
```

Using the stanzas described in the tutorial, I can't reproduce the errors you see. Using your setup, the build fails, but with a different error.

Can you provide more information?

**Comment by Randle-Lanre** [comment]
@cuihtlauac  

correcting the dune file still results in the same error.
vscode intellisense also underlines it.

could it be that something is cached somewhere?
 
```ocaml 
(preprocess (pps ppx_show))
(libraries ppx_show.runtime))
```

**Comment by cuihtlauac** [comment]
What instructions did you follow to install ocaml, opam and Dune? Something may be wrong with your set up.

**Comment by Randle-Lanre** [comment]
@cuihtlauac Solved the issue, [the docs](https://ocaml.org/docs/your-first-program#using-the-preprocessor-to-generate-code) need to include that the preprocessor needs to also be included in the `bin/dune`, not just the `lib/dune` . 
I only figured this out in the [`ppx_show` repository ](https://github.com/thierry-martinez/ppx_show)

**Comment by cuihtlauac** [comment]
Thanks for investigating @Randle-Lanre. This is intriguing. I don't have it in `bin/dune`.

**`bin/dune`**
```lisp
(executable
 (public_name hello)
 (name main)
 (libraries hello))
```

**`bin/main.ml`**
```
let () = print_endline Hello.(string_of_string_list world)
```

**`dune-project`**
```list
(lang dune 3.11)

(name hello)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name")

(maintainers "Maintainer Name")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name hello)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
```

**`lib/dune`**
```lisp 
(library
 (name hello)
 (preprocess (pps ppx_show))
 (libraries ppx_show.runtime))
```

**`cat lib/hello.ml`**
```
let string_list_pp = [%show: string list]

let string_of_string_list = Format.asprintf "@[%a@]" string_list_pp

let world = String.split_on_char ' ' "Hello using an opam library"
```

**`lib/hello.mli`**
```ocaml
val string_of_string_list : string list -> string
val world : string list
```

File **`hello.opam`** is present but empty

Here are the versions
```shell
$ opam list -i ppx_show dune ocaml
# Packages matching: (name-match(ppx_show) | name-match(dune) | name-match(ocaml)) & installed
# Name   # Installed # Synopsis
dune     3.11.1      Fast, portable, and opinionated build system
ocaml    5.1.0       The OCaml compiler (virtual package)
ppx_show 0.2.1       OCaml PPX deriver for deriving show based on ppxlib

$ opam --version
2.1.4
```

**Comment by Randle-Lanre** [comment]
the major difference is the ocaml version 

```
$ opam list -i ppx_show dune ocaml
# Packages matching: installed & (name-match(ppx_show) | name-match(dune) | name-match(ocaml))
# Name   # Installed # Synopsis
dune     3.11.1      Fast, portable, and opinionated build system
ocaml    4.13.1      The OCaml compiler (virtual package)
ppx_show 0.2.1       OCaml PPX deriver for deriving show based on ppxlib
```

```
$ opam --version
2.1.2
```

i will try and get that to 5.1.0

**Comment by sabine** [comment]
Since we don't have a reproduction and it's not clear how to proceed here, I'm closing this.

If the issue appears again and there's a reproduction, please free to open a new issue.
