### ISSUE TITLE
The "opam switch" link on the install page does not point to useful information

### ISSUE THREAD

**Issue by binwang-dev** [ocaml/ocaml.org#1795]
The [Install OCaml page](https://ocaml.org/install) mentions that

> Opam needs to be initialised, which will create a default [opam switch](https://ocaml.org/docs/tour-of-ocaml#3-create-an-opam-switch).

The "opam switch" part is linked to https://ocaml.org/docs/tour-of-ocaml#3-create-an-opam-switch. However, the "A Tour of OCaml" page doesn't have a "create an opam switch" section, nor does it contain any information about opam switches. I think it should be pointed https://ocaml.org/docs/opam-switch-introduction instead, as the info there are very relevant to newcomers.

**Comment by binwang-dev** [comment]
The source for this part is here: https://github.com/ocaml/ocaml.org/blob/54c9b9dbe194e834a7eb9a9b04932bc3b535af3e/src/ocamlorg_frontend/pages/install.eml#L65

**Comment by cuihtlauac** [comment]
Thanks @binwang-dev, you are correct. This is bug and your suggestion is correct.
