### ISSUE TITLE
Finish open PR 1799 (Add Package Versions Page)

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1801]
The only thing left to do on https://github.com/ocaml/ocaml.org/pull/1799 is to render the release date for every package on the new package versions page.

This requires changing `ocamlorg_package.ml` to provide a means to look up all the release dates and versions of a package.

To render the publication dates of the other versions, we need to look them up in `handler.ml` and pass them to the template as an argument.

This require some changes in `ocamlorg_package.ml` and `ocamlorg_package.mli`. For example, we could add a function `get_versions_with_publication_date : state -> string -> (Version.t, float) list`, which, given the package state and the name of a package returns a list of all the versions and respective publication dates of the package.

**Comment by florentdrousset** [comment]
I'm interested in doing ths one !

**Comment by sabine** [comment]
@florentdrousset assigning this issue to you!

**Comment by florentdrousset** [comment]
Sorry @sabine, actually I'm not sure what should be the workflow there : since this hasn't been merged yet, should I create a new fork from https://github.com/sabine/ocaml.org/tree/pr_1669 ? 🤔

**Comment by sabine** [comment]
Yes, pulling that branch into your repository is a great way to start here.
👍

**Comment by sabine** [comment]
A way to do so is to add the other repository as a remote, pull the branch,
then create a new branch from that one that you push to your fork of
ocaml.org. (I have to look up how to do that every time, but ChatGPT is
pretty good at giving exact commands here.)
