### ISSUE TITLE
`docs/lists` has a 404 link for "comparsion of standart containers"

### ISSUE THREAD

**Issue by Sc4ramouche** [ocaml/ocaml.org#1821]
Hi there, while reading the https://ocaml.org/docs/lists documentation, I found that the link for "[comparison of standard containers](https://ocaml.org/docs/data-structures-comparison)" leads to a 404. (Here's a [link to the source](https://github.com/ocaml/ocaml.org/blob/4f32d84229b080cb9fc3cd54e886beaa6c073f1f/data/tutorials/language/0it_04_lists.md?plain=1#L423) in question)

When using a search engine, I discovered that such a page exists in the V2 docs — https://v2.ocaml.org/learn/tutorials/comparison_of_standard_containers.html.

Thus a couple of questions: 

* Should the link be updated in the V1 docs?
* Should I as a newcomer focus on V2 docs website? TBH, I didn't even know it exists until I ran into this 404 issue.

Would appreciate some guidance here! Thanks.

**Comment by cuihtlauac** [comment]
Hi @Sc4ramouche. This is indeed a bug; thanks for reporting.

The complexity bounds in the V2 docs seem to be accurate. This document was probably accidentally forgot when migrating from V2 to V3 (the current ocaml.org).

**Comment by Sc4ramouche** [comment]
> Hi @Sc4ramouche. This is indeed a bug; thanks for reporting.
> 
> The complexity bounds in the V2 docs seem to be accurate. This document was probably accidentally forgot when migrating from V2 to V3 (the current ocaml.org).

Thanks a lot for the reply here, appreciate it. 

Understood. Do you think that "Comparison of standard containers" document can be migrated to the V3 docs with it's current contents? If there were no changes planned to introduce for this doc, I can try to submit a PR, moving this doc to V3 and updating the link in the Lists doc.

**Comment by cuihtlauac** [comment]
We'd love to receive a PR on this from you. The current content is good enough to create a PR. If needed, we'll update it during the review. I suggest to start by putting it in the "Guides / Ressources" section. Maybe we'll move it somewhere else during the review, but that's a starting place.
