### ISSUE TITLE
Trim whitespace on RSS feed URLs

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1830]
The Frama-C RSS feed always contains unnecessary whitespace in the URLs of the feed entries.

## Task

Make the scraper more robust by trimming whitespace from the URLs in `planet.ml`.

**Comment by The-Amoghavarsha** [comment]
This looks interesting. We need to modify `ocaml.org/tool/ood-gen/lib/planet.ml`.  My first glance tells me that we need to add a trim function which could modify a few things in `source` and `External.Post` module. In turn, it might be applicable for all other feeds (eliminating unnecessary spaces).

**Comment by sabine** [comment]
Yes, or check for this whitespace problem, reject the post and push people to fix their feeds.

But I suppose just trimming the whitespace needs less code.

**Comment by sabine** [comment]
Frama-C fixed their RSS feed, so we probably don't have to do this.
