### ISSUE TITLE
Add a tiny tutorial on how to use the OCaml Playground in the "Get Started" section

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1853]
Relating to https://github.com/ocaml/ocaml.org/issues/1845.

# Task

We don't have a tutorial that explains to people how to use the OCaml Playground. The Playground is a reasonable space to run the examples from the tutorials, but it is not a REPL, so we need to explain how to put the code samples into the Playground so that they work properly. I.e. need to explain that we need `;;` just like in the REPL.

The markdown document should be placed in `data/tutorials/getting-started`, in the "Resources" category.

We used to have a tiny bit of explanation at https://github.com/ocaml/ocaml.org/blob/1970765678d3273820de64eb9cd98bc12f7ae5cf/data/tutorials/getting-started/gs_01_a_first_hour_with_ocaml.md#using-the-ocaml-playground before the "First Day with OCaml" tutorial got replaced by the "Tour of OCaml". However, I think we need something that's self-contained and similar to the REPL tutorial.

**Comment by The-Amoghavarsha** [comment]
It's almost done and waiting for approval at #1880

**Comment by sabine** [comment]
Resolved by #1880
