### ISSUE TITLE
Dune behaviour confusing in “Your First OCaml Program”

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1856]
Tutorial does not explain how to create more than exactly one file named `hello.ml` in folder `lib`. This is confusing to some. See:

https://discuss.ocaml.org/t/using-modules-15-characters-long-now/

Add small text or link to other doc to avoid having learners stuck

**Comment by heathhenley** [comment]
I opened a draft PR to try help with this, would really appreciate any guidance

**Comment by cuihtlauac** [comment]
> I opened a draft PR to try help with this, would really appreciate any guidance

Make sure your PR is consistent with this one
