### ISSUE TITLE
Release date for OCaml 5.1.1 is listed as 2024-12-8

### ISSUE THREAD

**Issue by hetzenmat** [ocaml/ocaml.org#1857]
The release date for OCaml 5.1.1 is listed wrongly as 2024-12-8 at [https://ocaml.org/releases](https://ocaml.org/releases).

Moreover, a leading 0 before the 8 should be added for consistency with previous date.

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1858
