### ISSUE TITLE
Address `begin .. end` expressions

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1863]
- [ ] Values & functions, `begin end` is just `( ... )`. Add explanation of this around line 290 in https://github.com/ocaml/ocaml.org/blob/main/data/tutorials/language/0it_00_values_functions.md in the applying functions section. Make a reference to another explanation in Imperative & Mutability.
- [ ] Imperative & Mutability (https://github.com/ocaml/ocaml.org/blob/main/data/tutorials/language/0it_06_imperative.md), what's where it's meant to be used

**Comment by The-Amoghavarsha** [comment]
Hey, help me understand this issue. 

1. Are you asking to add the usage of `begin and end` in [`Values & functions`](https://ocaml.org/docs/values-and-functions) function section in the documentation? And I didn't get the `...` part.

2. So the documentation already has a section called [Mutability, Loops, and Imperative Programming](https://ocaml.org/docs/mutability-loops-and-imperative), and there's a brief intro there explaining [Immutable vs Mutable Data](https://ocaml.org/docs/mutability-loops-and-imperative#immutable-vs-mutable-data), are you expecting to extend that?

**Comment by sabine** [comment]
> 1. Are you asking to add the usage of begin and end in [Values & functions](https://ocaml.org/docs/values-and-functions) function section in the documentation

Yes. The `( ... )` just means to say that `begin ... end` is just like brackets and I read this issue as that this notation should be introduced in values & functions.

> 2.

I don't know what exactly @cuihtlauac meant here, but I can see that `begin` ... `end` is being used in that document. :thinking:

**Comment by F-Loyer** [comment]
My understanding is that `begin...end` can also be used in a multiline expression where the limit of the scope of a nested match can then be seen far more easily than with just a pair of parenthesis.

Sure, the `begin` word seems to introduce a sequence. (In Scheme, it actually does!), but I guess we can use it when it is adequate in a pragmatic way, even in a pure functional expression.

Then, we could ask where to place it ? Among Values & functions seems logic... However, it is interesting when we have a long expression. One can construct it with `print_newline`, nested `if`... but `match ... with` is only introduced in a later section. But I have no idea of an expression which doesn't sound too artificial.

@sabine : I haven't found any begin, nor any end in the Values & functions page.

**Comment by cuihtlauac** [comment]
With respect to values, `begin` `end` and `()` are almost equivalent and only serve to group subexpressions, one can always replace one by the other.

```ocaml
# begin end;;
- : unit = ()

# begin 1, 2 end;;
- : int * int = (1, 2)

# (::) begin 1, [] end;;
- : int list = [1]
```

This does not apply to the module system, where the syntax requires parenthesis (`begin + end` doesn't work either). 

I believe the equivalence between `begin` `end` and `()` should be introduced in the _Values and Functions_ tutorial. Maybe in "Applying Functions" section, although the examples above shows it goes beyond.

I agree with you @F-Loyer, the difference is pragmatics. `begin` `end` are “intended” to be used in an imperative context, that's why they must be discussed in the _Mutability and Imperative Control Flow_ However, as you pointed, `begin` `end` can be used where ever they help. It's a pitty ocamlformat aggressively replaces by parenthesis.

It's ok to have some redundancy. There are things that deserved begin presented from various perspectives, in various contexts.

**Comment by F-Loyer** [comment]
Finally, I have seen the `begin...end`, but in the Mutability/Control flow page. The advantage of the presentation in this page is that Mutability/Control flow generates easily multi-lines expressions where the `begin...end` is the most useful. I find it also useful with nested `match...with`..

In Values and functions, it would be a little artificial since we have not yet expressions that makes `begin...end` very useful. The expression `a_function begin 5+6 end` while correct seems weird. And I don't find the relationship with the "Applying functions" section. If really we would have to insert `begin...end`, a dedicated paragraph would be better.
