### ISSUE TITLE
Hide "OCaml Packages" Image on Homepage on Mobile View

### ISSUE THREAD

**Issue by maiste** [ocaml/ocaml.org#1890]
Dear maintainers,
First of all, thanks for your hard work on making the OCaml ecosystem available for everyone 
👐

This issue is just to point out that there is a display problem with the image bellow the OCaml Package Explore link. The image appears to be right shift.

Here is two screenshots to show the issue on both Chromium and Firefox mobile :
![Screenshot_20231230-180622.png](https://github.com/ocaml/ocaml.org/assets/22150236/e77edf18-2096-4c99-838b-a3684cddfacf)

![Screenshot_20231230-180549.png](https://github.com/ocaml/ocaml.org/assets/22150236/fdddecd3-89c2-452d-b37d-58f33e168c29)

Hope it helps 😇

**Comment by FatumaA** [comment]
Hi,
Thank you for pointing this out. I think it is meant to be that way but will have to wait for confirmation. The maintainers are on break. 😌

**Comment by The-Amoghavarsha** [comment]
> Dear maintainers, First of all, thanks for your hard work on making the OCaml ecosystem available for everyone 👐
> 
> This issue is just to point out that there is a display problem with the image bellow the OCaml Package Explore link. The image appears to be right shift.
> 
> Here is two screenshots to show the issue on both Chromium and Firefox mobile : ![Screenshot_20231230-180622.png](https://private-user-images.githubusercontent.com/22150236/293472183-e77edf18-2096-4c99-838b-a3684cddfacf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzA2MDYsIm5iZiI6MTcwNDUzMDMwNiwicGF0aCI6Ii8yMjE1MDIzNi8yOTM0NzIxODMtZTc3ZWRmMTgtMjA5Ni00Yzk5LTgzOGItYTM2ODRjZGRmYWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA4MzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZDVmYjA4NTBlNDZkNjU2NTkxMTYxOTFjZDliY2EyMWRhMmI3ZGEzNDViZmJlNWU3ZmFjMDc1MTVkZmJlYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E0QdZY9ryHxeIT149ovNN5kt1NORLHBK_F4clVihJNQ)
> 
> ![Screenshot_20231230-180549.png](https://private-user-images.githubusercontent.com/22150236/293472185-fdddecd3-89c2-452d-b37d-58f33e168c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzA2MDYsIm5iZiI6MTcwNDUzMDMwNiwicGF0aCI6Ii8yMjE1MDIzNi8yOTM0NzIxODUtZmRkZGVjZDMtODljMi00NTJkLWIzN2QtNThmMzNlMTY4YzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA4MzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyY2RmZDUyYzAyMDY3ZTMxMWU3ZGQ2ZGQ1NjMwYjljZTcxOGY0MDNiNDI0ZDQ1MmE2NjdlZDVjYTM2YmZjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HiapxZZMSBSd2JNNmluW7gsWhVOXlPs1XMze9m724ns)
> 
> Hope it helps 😇

Hey, thanks for your interest. Are you sure that it's not slow internet related issues (improper loading)? Or did you accidentally click the web version on the mobile browser? Does the problem still persist?

**Comment by maiste** [comment]
It's not, just I retry and this time with mobile view in the browser and the problem persists!

**Comment by sabine** [comment]
As a maintainer, I think the right thing to do here is to hide the "OCaml Packages" image using the Tailwind `hidden` class on mobile screens, because the image just doesn't fit.

**Comment by The-Amoghavarsha** [comment]
> As a maintainer, I think the right thing to do here is to hide the "OCaml Packages" image using the Tailwind `hidden` class on mobile screens, because the image just doesn't fit.

It appears that removing a div class in `ocaml.org/src/ocamlorg_frontend/pages/home.eml` is going to solve the problem. The following is what we need to remove from lines 451 to 453.

``` html
    <div class="m-auto">
        <img src="<%s Ocamlorg_static.Asset.url "img/home/packages-home.png" %>" width="1047" class="max-w-none -mb-72 h-auto" alt="">
      </div>
```

AFAIK, it didn't break anything else. Also, I would suggest that we could also remove the source image as well, as it's not that relevant IMO. 

These are the screenshots after removing. 

![1](https://github.com/ocaml/ocaml.org/assets/35860305/00630bbe-e8e9-485e-a65c-1321394700ea)
![2](https://github.com/ocaml/ocaml.org/assets/35860305/61ac5d51-076f-4651-a7f8-6eee387e462f)

If you think I'm going in the right direction, let me know, I'll open a PR.

**Comment by sabine** [comment]
Fine with me. I think this image did not serve any actual purpose in the first place. Sorry, just seeing this. So much going on. :see_no_evil: :heart:
