### ISSUE TITLE
inconsistency in "Pattern Matching on User-Defined Types" example

### ISSUE THREAD

**Issue by SergeyRudyshin** [ocaml/ocaml.org#1891]
the example does not yield the [specified result](https://github.com/ocaml/ocaml.org/blob/806224240567caa94a3e2d9c9d36908a4702d7b1/data/tutorials/language/0it_00_values_functions.md?plain=1#L184) `val age : live_person -> int = <fun>`

instead the following is produced 
```
$ echo 'type name = { first : string; last: string };;
type live_person = int * name;;
let age (years, { first; last }) = years;;' | ocaml 
OCaml version 5.1.0
Enter #help;; for help.

# type name = { first : string; last : string; }
# type live_person = int * name
# val age : 'a * name -> 'a = <fun>
```

if changed to 
`let age (years, { first; last }) = years/2;;`
then it gives
`val age : int * name -> int = <fun>`

**Comment by cuihtlauac** [comment]
Thanks, @SergeyRudyshin you are correct.
