### ISSUE TITLE
Unclear paragraph in docs/functional-programming

### ISSUE THREAD

**Issue by Villetaneuse** [ocaml/ocaml.org#1899]
In [this part of the tutorial](https://ocaml.org/docs/functional-programming#pure-and-impure-functional-programming), I find the following paragraph unclear:
> Concentrating on writing small pure functions allows you to construct reusable code using a bottom-up approach, testing each small function as you go along. The current fashion is to carefully plan your programs using a top-down approach, but in this author's opinion, this often results in projects failing.

I don't really understand what this "top-down approach" is, and I don't know who "this author" is.

This is [there in the sources](https://github.com/ocaml/ocaml.org/blob/d6d26bd6071bc546aedda28a798b883cb164e79d/data/tutorials/language/0it_02_functional_programming.md?plain=1#L310).

**Comment by The-Amoghavarsha** [comment]
Hey, can you provide me with a link to the page to which you are referring to? Also, please do for #1900

**Comment by Villetaneuse** [comment]
> Hey, can you provide me with a link to the page to which you are referring to? Also, please do for #1900

Sorry, I edited the issue (on my way to do the same with #1900).

**Comment by The-Amoghavarsha** [comment]
Thanks :) I'll look into it.

**Comment by sabine** [comment]
Basically this entire document needs a rewrite and it is unclear how helpful it is with all the C references. It seems more of a distraction at this point. I'll retire it now.
