### ISSUE TITLE
docs/functional-programming: boxed... paragraph ends abruptly

### ISSUE THREAD

**Issue by Villetaneuse** [ocaml/ocaml.org#1900]
I think the paragraph about `Boxed vs. Unboxed types` [here](https://ocaml.org/docs/functional-programming#boxed-vs-unboxed-types) ends very abruptly.
The only sentence about OCaml is:
> In OCaml, the basic types are all unboxed.

What about the other types then?
Also, it would not harm to syntax colour C snippets.

See also [the sources](https://github.com/ocaml/ocaml.org/blob/d6d26bd6071bc546aedda28a798b883cb164e79d/data/tutorials/language/0it_02_functional_programming.md?plain=1#L420).

**Comment by The-Amoghavarsha** [comment]
@sabine I have an understanding of boxed and unboxed types, heaps, and garbage collection (from other languages). Do you want me to go ahead and write the content which has ended abruptly?

Or do you have plans to link it to books? AFAIK, there is not much content about the boxed and unboxed types in `OCaml Programming: Correct + Efficient + Beautiful (CS3110)`. In the case of `Real World OCaml`, there are mentions of boxed and unboxed, especially in chapters related to garbage collection, unboxed integers, unboxed runtime etc., but not explicit.

**Comment by sabine** [comment]
So, this document is in such a bad state that we want to retire and replace it entirely. We should probably hurry up with that.

**Comment by cuihtlauac** [comment]
Closing this because we removed that document
