### ISSUE TITLE
Clone of ocaml.org failing on windows due to `:` in filename

### ISSUE THREAD

**Issue by heathhenley** [ocaml/ocaml.org#1936]
Not sure it's meant to work, but it looks like the `:` in some of the `src/ocamlorg_frontend/pages/*:OECustomProperty` files cause clone to fail on Windows 11. I just switched to WSL and will use that, not sure if it's intended to work or not. Would be happy to help with fix if there's any suggestion (or add note to git section of `CONTRIBUTING.md` maybe?). 

Also cloned locally because I'm going to learn to O🐫 by going though the tutorial and docs, and I'm happy to keep an eye out for any of the issues that are related to doc updates and update along the way.

![windows_doesnt_like_colons](https://github.com/ocaml/ocaml.org/assets/5819478/a27a2156-ad64-468d-86b7-98ba57f226f8)

**Comment by sabine** [comment]
This has been mistakenly committed. I'm removing the offending file.

**Comment by sabine** [comment]
Thanks for reporting, sorry about that. I really need to watch more closely for random files that accidentally get included.

**Comment by heathhenley** [comment]
I'm not sure but I wonder if you might have to filter from the git history for the clone to work, I'll try again on windows today and see.

**Comment by heathhenley** [comment]
Nope that was wrong, all good now! 🎉
