### ISSUE TITLE
Add text and link to labelled args tutorial in relevant docs

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1944]
Documents with text on how to pass arguments to functions should mention labelled arguments. 

1. [X] [A Tour of Ocaml](../blob/main/data/tutorials/getting-started/1_01_a_tour_of_ocaml.md) section “Functions”
2. [X] [Values and Functions](../blob/main/data/tutorials/language/data/tutorials/language/0it_00_values_functions.md) section “Applying Functions”

Both should mention some functions have labelled parameters. When applying them, arguments must be labelled too. Add a sentence saying something about that.

Add link to [Labelled Arguments](https://ocaml.org/docs/labels) tutorial with relative url `[Labelled Arguments](/docs/labels)`

**Comment by PoorlyDefinedBehaviour** [comment]
Working on it

**Comment by PoorlyDefinedBehaviour** [comment]
I think this issue can be closed @cuihtlauac
