### ISSUE TITLE
Add Capability to List Tutorial Prerequisites as Meta Data

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1945]
Currently, some tutorials list prerequisites in their introduction section, and some don't, and listing (if present) varies. This is not optimal for user experience and maintenance.

1. Add a field `prerequisites_tutorials : string list` to both the `metadata` and `t` types in `tutorial.ml`. This holds the slugs of all the tutorials that are required reading _before_ this one.
1. Add some sensible references between tutorials in the `data/tutorials` folder for testing purposes (for instance, in “Values and Function” and “Basic Data Types and Pattern Matching”)
1. In `handler.ml`, in the function `tutorial`, you need to filter the tutorials for those that are prerequisites, i.e. (`slug` is an element of `tutorial.prerequisite_tutorials`).
1. In `tutorial.eml`, render the list of links to the prerequisite tutorials as a paragraph at the beginning.

Note: The fields `prerequisites_tutorials` cannot be computed from the `recommended_next_tutorials` defined in issue #1589 and implemented in PR #1928. Prerequisites are mandatory, but suggested next are optional.

**Comment by PoorlyDefinedBehaviour** [comment]
Working on it

**Comment by PoorlyDefinedBehaviour** [comment]
> Working on it

Was busy, will try to do it today
