### ISSUE TITLE
Tutorial titles only as metadata

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1971]
Currently, tutorial titles are duplicated in the sources. They appear both in the Yaml header (as field `title`) and at the first line of markdown content.

For instance, here is how it looks like in [`data/tutorials/language/0it_04_labels.md`](../blob/main/data/tutorials/language/0it_04_labels.md)
```markdown
---
id : labels
title: Labelled and Optional Arguments
description: >
  Provide labels to your functions arguments
category: "Introduction"
---

# Labelled and Optional Arguments

It is possible to give names and default values to function
parameters. This is broadly known as labels. In this tutorial,
we learn how to use labels.
```

We need to have the titles only in the metadata.

- [ ] Rename Yaml header field `title` into `short_title`
- [ ] Copy the markdown level 1 titles (`#`) into a Yaml header field `title`
- [ ] Change the [`src/ocamlorg_frontend/pages/tutorial.eml`](../blob/main/src/ocamlorg_frontend/pages/tutorial.eml) file to render the `title` of the tutorial at the head of each tutorial
- [ ] Remove the markdown level 1 (`#`) titles from the markdown files

It would be nice to have one commit per task in order.

**Comment by sabine** [comment]
The current `title` field in the metadata is the title as it should appear in the sidebar. This should first be renamed to `short_title`, and then the existing title from the Markdown document can be moved into a `title` field in the metadata.
