### ISSUE TITLE
 Typo in the documentation: which vs that in A Tour of OCaml

### ISSUE THREAD

**Issue by julbinb** [ocaml/ocaml.org#1972]
In [A Tour of Ocaml, Records section](https://ocaml.org/docs/tour-of-ocaml#records), 

https://github.com/ocaml/ocaml.org/blob/e810abd0d10a50e55fcb4e01fd90b6fa19f95fad/data/tutorials/getting-started/1_01_a_tour_of_ocaml.md?plain=1#L575

there is a sentence

> Here, the pattern `{ age = x; _ }` is typed with the most recently declared record type**, which** has an `age` field of type `int`.

The use of ", which" indicates that the type checker uses the most recently declared record type (period). Thus, if there is no "age" field in the most recent record, it would be an error.

Judging by the behavior of the OCaml compiler, the sentence should say "the most recently declared record type **that** has an `age` field" (no comma).

**Comment by cuihtlauac** [comment]
Thanks, @julbinb, you have an eagle eye! Do you want to write the PR yourself? We'd love a PR from you on this.

**Comment by julbinb** [comment]
Oops, you were faster!

**Comment by cuihtlauac** [comment]
> Oops, you were faster!

Sorry, I should have let you fix that one.

**Comment by julbinb** [comment]
No-no, you are absolutely good :)
