### ISSUE TITLE
Link on privacy policy page 404

### ISSUE THREAD

**Issue by AshineFoster** [ocaml/ocaml.org#1979]
The link on the privacy page to [Dashboard](https://ocaml.org/dashboard/analytics) give a 404 message.

**Comment by The-Amoghavarsha** [comment]
If I'm not wrong, should the broken link be replaced by https://plausible.ci.dev/ocaml.org?

**Comment by cuihtlauac** [comment]
Yes, you are correct @The-Amoghavarsha

**Comment by cuihtlauac** [comment]
See PR #1736 and #1855
