### ISSUE TITLE
Documenting the compiler release cycle?

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml.org#1985]
I am wondering if it would be a good idea to document the current release cycle of the compiler on ocaml.org?

I have the impression that it could be useful to at least write down that:

* the compiler follows a linux-like semantics for version numbers `major.minor.patch` where both minor and major version may contain breaking changes. 
* the compiler is released approximately every 6 months
* Three months before the release of a new version, the set of new features is frozen.
* Pre-release version(alpha, beta, rcs) of the compiler are published two to three months before the release in order to test this new version.

Such page could be also a good place to link to compiler repository and its `CONTRIBUTING.md` rather than having a small link in the footer.

Any opinion on this idea?

**Comment by cuihtlauac** [comment]
I think it would be a great addition. Do you already have such a document in the compiler's repo?

**Comment by Octachron** [comment]
Not really. As far as I can see, the knowledge about the release cycle is mostly diffuse and folkloric.
But you are right that it is probably a good idea to start to add the document on the compiler side first.

**Comment by Octachron** [comment]
The compiler version of the documentation is being reviewed at https://github.com/ocaml/ocaml/pull/12949 if you have any comments on the contents. 

My idea is to have a baseline description on the compiler side as a source, and let `ocaml.org` present it in potentially more appealing way. For instance, do we want graphics for representing the compiler cycles?.

**Comment by Octachron** [comment]
The above PR has been merged in the compiler.
Since the audience was mostly OCaml developers, the document in the compiler repository focus on explaining the release cycle for developer, so information about the periodicity of the release and the meaning of OCaml versions is mixed with information about the release process. It might make sense to split those two parts on ocaml.org.

**Comment by cuihtlauac** [comment]
I'd rather copy your doc in either Learn/Platform or Learn/Guides, mostly unchanged. Maybe with added cross-linking (to remember about the duplication). It would be less maintenance. 

Regarding images, we're not producing new illustrations at the moment, but this is something we're considering. Certainly, we can publish this doc without images and create an issue on that.
