### ISSUE TITLE
Misaligned select drop down on jobs page

### ISSUE THREAD

**Issue by psb** [ocaml/ocaml.org#1989]
The location select drop down is misaligned on the jobs page. It can be fixed by removing the tailwind class `lg:w-auto` in the browser dev console.

<img width="1392" alt="Screenshot 2024-01-23 at 14 43 56" src="https://github.com/ocaml/ocaml.org/assets/2823149/affbfea3-07e0-48fd-bfa6-2fee368cd4ad">

**Comment by cuihtlauac** [comment]
Thanks @psb, you are correct
