### ISSUE TITLE
Full data for "most used" packages

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml.org#2011]
At https://ocaml.org/packages there is a column marked "most used" which shows how many packages use each of the top 5 opam packages.

Is the full data available anywhere? Obviously I could derive it, but if someone happens to have it to hand it would save some time.

**Comment by kit-ty-kate** [comment]
We (the opam dev team) do not know how the ocaml.org website works. Could you reopen the ticket at https://github.com/ocaml/ocaml.org/issues instead? I would transfer it but i don't have the necessary rights on the ocaml.org repository for that.

In the future, if you have questions about opam.ocaml.org however, the issue tracker for that is at https://github.com/ocaml-opam/opam2web/issues

**Comment by avsm** [comment]
Transferred to ocaml.org. @johnwhitington you may want to look in https://github.com/ocaml/ocaml.org/tree/main/src/ocamlorg_package/lib /cc @sabine @cuihtlauac

**Comment by cuihtlauac** [comment]
Check `package_stats.ml` in that folder. That's where it's computed. There may be some data you need there.

BTW, some time ago, we refactored `ocamlorg_package` so it does not have any dependencies inside ocamlorg. You may be able to extract it and compile it alone. But I did not tried.

**Comment by sabine** [comment]
You could explore the GraphQL API at https://ocaml.org/graphiql to query the reverse dependencies of the packages:

```
{
  allPackages() {
    packages {
      name
      reverseDependencies
    }
  }
}
```

This would give you some JSON data on which you can compute the length of the reverseDependencies fields. If you just need the data, that is.

**Comment by johnwhitington** [comment]
Thanks everyone. I think I have what I need now.
