### ISSUE TITLE
Ready-to-paste install & dune dependency in package overview should not use version numbers

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2015]
In the general case, one wants to do:
```shell
$ opam install foo
```
Not 
```
$ opan install foo.0.9.9
```

The latter isn't _nominal_ it is exceptional. The same reasoning applies to Dune dependency. One lists a package name without a version. Specifying a version number is exceptional, specifying a fixed version number (with an equal sign) is even more.

Version numbers should be removed from both texts.

**Comment by sabine** [comment]
It makes sense to remove the version on the latest version URL.

I think if people are on a specific version we can assume they probably have a reason for why they aren't on the latest version URL. :thinking:

**Comment by The-Amoghavarsha** [comment]
So what's the middle ground here? Should we just remove the version number for the latest one and also let users use a specific version number (if they have a specific reason)?

**Comment by sabine** [comment]
Yeah, we should change it on the latest version URL only to have no version in the clipboard-copy boxes.

**Comment by The-Amoghavarsha** [comment]
Where to start from here? Need some ideas.

**Comment by sabine** [comment]
When on the latest version URL, have the copy to clipboard snippets without a version. On pages with a version URL, keep things as they are.

**Comment by shonfeder** [comment]
Fixing this for the `Dune Dependency` field will reduce friction to publishing packages, since the current behavior will lead newer contributors to put fixed bounds on deps that will then need correction before publishing to opam.

**Comment by sabine** [comment]
Resolved by #2668
