### ISSUE TITLE
Remove dune from explicitely installed packages in setup instructions

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2019]
In https://ocaml.org/install there is:
```shell
$ opam install dune merlin ocaml-lsp-server odoc ocamlformat utop dune-release
```

In https://ocaml.org/docs/installing-ocaml there is:
```shell
$ opam install dune ocaml-lsp-server odoc ocamlformat utop
```

@The-Amoghavarsha pointed this should be the same (issue #1995). 

Aside having the same, we can also remove `dune` in both. It is a dependency pulled by all the other packages but `utop`.

**Comment by The-Amoghavarsha** [comment]
Okay, I'm going to remove `dune` from both.
