### ISSUE TITLE
Some more documentation regression

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml.org#203]
Stand-alone documentation pages are back, it's great. Here's another batch of comment regarding regressions in the package documentations:
* Missing title and first paragraph ([old](https://guillaume.munch.name/software/ocaml/memprof-limits/Memprof_limits/index.html) vs. [new](https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/Memprof_limits/index.html); [old](https://guillaume.munch.name/software/ocaml/memprof-limits/recovering.html) vs. [new](https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/recovering.html))
* You cannot go back to the toplevel page using the table of contents from other pages (nor using the page hierarchy on the top right): the only way is to click on the "Documentation" tab. (See e.g. https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/Memprof_limits/index.html)
* Stand-alone page shows "Module" on the page hierarchy on the top right; it is not a module. (https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/recovering.html)
* Paragraph title lacks distinct styling: [old](https://guillaume.munch.name/software/ocaml/memprof-limits/index.html#discussion:-precise-vs.-statistical-limits) vs. [new](https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/index.html#discussion:-precise-vs.-statistical-limits). (Old one uses sans vs. serif; but just having it in bold is enough.)
* Missing syntax highlighting in the documentation

**Comment by gadmm** [comment]
I just tested the now live version of ocaml.org. The first issue is still present but it is pretty critical.

Some of the other issues are still present. I noticed that paragraph titles have been styled, thanks.

**Comment by jonludlam** [comment]
I belive I noticed this missing preamble in passing when upstreaming into odoc - so it should be fixed in part by https://github.com/ocaml/odoc/pull/842

**Comment by gadmm** [comment]
Do you mean with the title too? Please let me know when it is online so that I can have a look.

**Comment by gadmm** [comment]
Checking again, the critical issue of the title and the first paragraph missing is still there :) (compare [old](https://guillaume.munch.name/software/ocaml/memprof-limits/recovering.html) vs. [new](https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/recovering.html))

In addition the new title is odd ("module recovering.html").

**Comment by tmattio** [comment]
Quick update, and apologies for the lack of response on this issue @gadmm.

@sabine has been working upstream to implement JSON output to the HTML renderer in odoc that can be used in [voodoo](https://github.com/ocaml-doc/voodoo) to generate correct documentation that contains the preamble.

[The PR](https://github.com/ocaml/odoc/pull/908) has been merged a few days ago, so we'll work on voodoo and the ocaml-ci pipeline to fix the issue on the generated documentation. Expect to see the fix on the live documentation very soon!

**Comment by gadmm** [comment]
I did my routine check again and I was pleased to notice that the issue with missing title and first paragraph is gone. The last relevant issue is syntax highlighting, which is a duplicate of #99. So we can finally close this issue. Thanks!

**Comment by sabine** [comment]
Reminds me I need to go through all the issues and see if there's more that's accidentally still open! And indeed, the syntax highlighting is still open. 👍
