### ISSUE TITLE
Fix sentence on relationship between source files and modules 

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2034]
Tutorial: [Libraries with Dune](https://ocaml.org/docs/libraries-dune#minimum-project-setup)
File: [1ms_02_dune.md](../tree/main/blob/data/tutorials/language/1ms_02_dune.md), line 86

> In OCaml, each source file is compiled into a module.

* “Source file” is wrong, it should be ".ml file"
* “compiled into a module” is flummox. Let's reuse words from section [Modules and the file system](https://v2.ocaml.org/releases/5.1/htmlman/comp.html#s%3Amodules-file-system) of the manual

**Comment by The-Amoghavarsha** [comment]
> “compiled into a module” is flummox. Let's reuse words from section [Modules and the file system](https://v2.ocaml.org/releases/5.1/htmlman/comp.html#s%3Amodules-file-system) of the manual

What exactly should we use? Should we say, "In OCaml, each .ml file corresponds to a module."?
