### ISSUE TITLE
Add example on closure and references

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2035]
Page: [Mutability and Imperative Control Flow](https://ocaml.org/docs/mutability-imperative-control-flow)
Source: [0it_05_imperative.md](../blob/main/data/tutorials/language/0it_05_imperative.md)

Insert this example (or something similar) in the imperative tutorial.
```ocaml
let counter () =
  let n = ref 0 in
  fun () -> incr n; !n;;
```

This includes showing how it's used, and how it works.

Credit: https://youtu.be/T_w3OlZ5ASc?t=24m25s

**Comment by The-Amoghavarsha** [comment]
Thanks for the channel recommendation (indirectly). So I'm guessing it has to go under [side effects](https://ocaml.org/docs/mutability-imperative-control-flow#if--then--else--and-side-effects). Can we just call it, `Closures` after [while loop](https://ocaml.org/docs/mutability-imperative-control-flow#while-loop)?
