### ISSUE TITLE
Update Data Model to Allow Recording Resources from the Community

### ISSUE THREAD

**Issue by yurug** [ocaml/ocaml.org#2041]
Thank you for the glorious work on ocaml.org!

The learning resources are great already but may I suggest adding as extra material the online exercises available there:

https://ocaml-sf.org/learn-ocaml-public/#activity=exercises

? 

These exercises are probably interesting for beginners and intermediate OCaml developers.

**Comment by The-Amoghavarsha** [comment]
@cuihtlauac got any idea where we can add this? (If that's the case)

**Comment by yurug** [comment]
A simple solution would be to add the link cited above in a box similar to the "Recommended book" one,  advertising extra material for online practice.

Another - more ambitious - possibility would be to add exercise boxes pointing to appropriate exercises (all but "Advanced Functional Programming by François Pottier" can be considered beginner level I suppose and François' exercises can be very good for advanced learners). We can provide a list of URLs and short descriptions for each in the format of your choice.

**Comment by cuihtlauac** [comment]
> A simple solution would be to add the link cited above in a box similar to the "Recommended book" one, advertising extra material for online practice.

Yes, that's one option. However, book data is stored as Yaml+Markdown in the [`data/books`](../tree/main/data/books) folder and Learn OCaml probably doesn't fit in the template. Changing the syntax or filing with dummy values doesn't seem great.

It probably makes more sense to treat it as a one of kind thing, like the reference manual. 

> Another - more ambitious - possibility would be to add exercise boxes pointing to appropriate exercises (all but "Advanced Functional Programming by François Pottier" can be considered beginner level I suppose and François' exercises can be very good for advanced learners). We can provide a list of URLs and short descriptions for each in the format of your choice.

It would be great to be able to go both ways. Run the [nitety-nine lisp](https://www.ic.unicamp.br/~meidanis/courses/mc336/problemas-lisp/L-99_Ninety-Nine_Lisp_Problems.html) derived exercises in Learn OCaml and list the exercises from Learn OCaml in https://ocaml.org/exercises, as the others, possibly with labels like we do for RWO and CS3110 tutorials.

**Comment by yurug** [comment]
> It would be great to be able to go both ways. Run the [nitety-nine lisp](https://www.ic.unicamp.br/~meidanis/courses/mc336/problemas-lisp/L-99_Ninety-Nine_Lisp_Problems.html) derived exercises in Learn OCaml and list the exercises from Learn OCaml in https://ocaml.org/exercises, as the others, possibly with labels like we do for RWO and CS3110 tutorials.

That's even more ambitious than what I proposed :-)

**Comment by yurug** [comment]
>  Yes, that's one option. However, book data is stored as Yaml+Markdown in the [data/books](https://github.com/ocaml/ocaml.org/tree/main/data/books) folder and Learn OCaml probably doesn't fit in the template. Changing the syntax or filing with dummy values doesn't seem great.
> 
> It probably makes more sense to treat it as a one of kind thing, like the reference manual.

Should we start from here to get something simple working soon? Can you guide me in the process?

**Comment by cuihtlauac** [comment]
Sure! 

One possible way to go is to define another category of served data. This would allow defining a tile-base UI (like this one https://ocaml.org/jobs). We'd have one tile per learn resource. Learn-OCaml would be one. There's also this:

- https://github.com/gs0510/ofronds
- https://github.com/sudha247/learn-ocaml-workshop
- https://github.com/kayceesrk/cs3100_f19

I suspect there's even more.

This implies creating a new kind of served data. Folowing-up with the jobs example, this file: [`data/jobs`](../blob/main/data/jobs.yml) entails the jobs page.

- In [`tool/ood-gen/lib/job.ml`](../blob/main/tool/ood-gen/lib/job.ml) there's the Yaml parser. It translates into OCaml sources which are compiled and linked (ocaml.org runs from memory).
- In [`src/ocamlorg_frontend/pages/jobs.eml`](../blob/main/src/ocamlorg_frontend/pages/jobs.eml) there's the HTML template which is turned into the paged served with the Yaml data
- In [`src/ocamlorg_web/lib/handler.ml`](../blob/main/src/ocamlorg_web/lib/handler.ml) and [`src/ocamlorg_web/lib/router.ml`](../blob/main/src/ocamlorg_web/lib/router.ml) there's the bits that glues everything together. There's also some stuff in [`src/ocamlorg_data/lib/data.ml`](../blob/main/src/ocamlorg_data/data.ml)

That's the overall logic. @Clairevanden will think of the design.

Regarding the Yaml data we probably need fields for:
- Title
- Short description
- Long description
- Image
- Online Url
- Source Url
- License

This whole thing would allow displaying the tiles either in the exercises, in the community or anywhere else.

What do you think of this plan?

**Comment by ghost** [comment]
@sabine Can I try working on this?
@SaySayo @cuihtlauac @tmattio

**Comment by SaySayo** [comment]
@Dev-JoyA will you like to attempt this?

**Comment by SaySayo** [comment]
@amarachigoodness74 I have responded to your comment on another issue.

**Comment by 0xrotense** [comment]
Hello @SaySayo , Im an outreachy applicant.

Please, can I work on this?

**Comment by SaySayo** [comment]
@0xrotense you can go ahead

**Comment by 0xrotense** [comment]
Alright thanks

**Comment by sabine** [comment]
The original request, referencing to the Learn OCaml platform, has been resolved by https://github.com/ocaml/ocaml.org/pull/2140, however, the data hardcoded into the template could still be moved into a dedicated data model in ood-gen.
