### ISSUE TITLE
ocaml.org should link to the ocaml.org github repo

### ISSUE THREAD

**Issue by v-gb** [ocaml/ocaml.org#2043]
I've been meaning to report a few things about ocaml.org, but had no idea how to contact anyone responsible for the site : I looked at https://ocaml.org, https://ocaml.org/packages, https://v3.ocaml.org/packages, https://ocaml.org/community, I searched for "contact" or similar in the pages. I only found this repo by just guessing the url.

I think there should be a link to here in the footer, at a minimum. In the community page would be another option, but that's harder to find. What do you think?

**Comment by The-Amoghavarsha** [comment]
Hey @v-gb I think we have a direct GitHub link in the footer, as you can see in the following. (And also for the other links that you mentioned)

![image](https://github.com/ocaml/ocaml.org/assets/35860305/c1be994a-9586-4062-88c5-2085b6d3e92e)

If there are any other issues, you can open an issue anytime. There are many communication channels to discuss as you can see in the footer.

**Comment by v-gb** [comment]
That link points to ocaml/ocaml, not ocaml/ocaml.org.

**Comment by v-gb** [comment]
Another possibility would be to change that icon to point to [https:///www.github.com/ocaml](https:///www.github.com/ocaml). That contains ocaml.org as one the pinned repos.

**Comment by The-Amoghavarsha** [comment]
> Another possibility would be to change that icon to point to https:///www.github.com/ocaml. That contains ocaml.org as one the pinned repos.

This makes more sense as ocaml.org comes under the umbrella of OCaml's main repo.
