### ISSUE TITLE
Replace `bool option` by `bool` in data

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2051]
Data served by ocaml.org is static. Yaml files' headers from the [`/data`](../tree/main/data) folder are parsed and linked into the binary. The [`ood-gen`](../tree/main/tool/ood-gen) tool turns those files into caml sources compiled with the rest of the project.

The Yaml syntax is implicitly described by the `metadata` types in the files from the [`tool/ood-gen/lib`](../tree/main/tool/ood-gen/lib) folder. Parsing returns values of this type. However, at run time, another type is used. It is the type named `t` in the same file.

Some Yaml headers have optional fields containing optional toggles. Their parsers produce values of type `bool option`; this is not optimal. It adds unnecessary processing at runtime and code complexity.

This issue is about changing `bool option` typed fields in `t` types in the relevant files:

* [ ] [`planet.ml`](../blob/main/tool/ood-gen/lib/planet.ml)
* [x] [`release.ml`](../blob/main/tool/ood-gen/lib/release.ml)
* [X] [`workshop.ml`](../blob/main/tool/ood-gen/lib/workshop.ml)

The key idea is to replace `None` values by the default value (either `true` or `false`).

This is similar to PRs #1967, #2039 and #2042 (except they dealt about `list option`). Note that each type change affects other files and that the `metadata` types must not be changed.

**Comment by egmaleta** [comment]
Hi, I can handle this too.

Regarding changes in `workshop.ml`, they will be similar to the ones made in 31384d1 so I think is valuable to either wait for #2042 to merge or to make these particular changes in that pr's branch. The type adjustement for `Workshop.presentation.poster` can be trivially made inside the `transform_presentation` function I introduced at 31384d1. What should I do?

**Comment by sabine** [comment]
Thanks for you patience @egmaleta! We merged #2042 in the meantime. :+1:

Rebasing and resolving conflicts is usually not a big deal with PRs this small, so either of those ways of doing it would've been fine.

**Comment by egmaleta** [comment]
Good to know for future contributions, thanks :)

**Comment by egmaleta** [comment]
Hello, the 3rd task was completed in #2068.

In regards of the first one, what is the type to modify its `bool option` fields?
It seems to me that all types in task no.1 are metadata types and so they shouldn't be modified.

**Comment by cuihtlauac** [comment]
> In regards of the first one, what is the type to modify its bool option fields? It seems to me that all types in task no.1 are metadata types and so they shouldn't be modified.

You are right @egmaleta, first item was a false positive. It needs no change. 

Thanks you very much for your work on this!

Closing this as complete.
