### ISSUE TITLE
Use plural for tutorial titles on `Map` and `Set`

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2072]
Tutorials on modules `Map` and `Set` should have title “Maps” and “Sets”. Several reasons:
- Consistency with Lists, Options, Modules, Functors, Arrays, Sequences, etc.
- Diminish confusion between `X.map` and Maps

Tasks:
- [X] Sets
- [X] Maps

**Comment by 0xrotense** [comment]
Hello @cuihtlauac , I think the second task is fixed already, per my check.

**Comment by komutumu** [comment]
> Hello @cuihtlauac , I think the second task is fixed already, per my check.

I think so too as per my check.

**Comment by cuihtlauac** [comment]
Thanks @0xrotense and @jahielkomu, you two are right
