### ISSUE TITLE
Refer to both tutorials and API references as links

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2088]
1. Outside of code blocks, transform all references to standard manual modules, types and functions into links
2. Sentences referring to tutorials matching an standard library module should also contain a direct link to the API reference

Examples:

In [https://ocaml.org/docs/basic-data-types](../blob/main/data/tutorials/language/0it_01_basic_datatypes.md)

Good, links:

```md
Operations on `float` are provided by the [`Stdlib`](/api/Stdlib.html) and the [`Float`](/api/Float.html) modules.
```

Bad, no links:

```md
The predefined function `fst` returns the first element of a pair, while `snd` returns the second element of a pair.
```

**Comment by priyakumari02** [comment]
@cuihtlauac Can I work on this issue?

**Comment by sabine** [comment]
@priyakumari02 Totally, you can just go ahead and open a PR that mentions this issue. Then other people see someone is working on this. :+1: :sparkles:

**Comment by maha-sachin** [comment]
Hi @sabine, I am Maha from outreachy intern, May I know if this issue is assigned to anyone or is open?

**Comment by Dev-JoyA** [comment]
hi @sabine @SaySayo I am an outreachy intern, and i want to know if i can work on this issue, i am done with the ocaml set up.

**Comment by SaySayo** [comment]
Hi @maha-sachin, you can go ahead and open a pull request to this issue.

**Comment by MissJae** [comment]
Hi, @SaySayo @sabine  I'm Jennifer, an Outreachy applicant. So I was checking the links in the example given to better understand the task and realized that the links led to a 404 error. Is this supposed to happen? I'm very new to open-source contributions. 
<img width="656" alt="Ocaml Stdlib" src="https://github.com/ocaml/ocaml.org/assets/28650188/cf6924b4-e14a-4a40-86b2-e89a0aaecac5">

**Comment by MissJae** [comment]
Can I work on this? @SaySayo

**Comment by maha-sachin** [comment]
> https://ocaml.org/docs/basic-data-types

HI @SaySayo, Sure thing! I'll get right on it and open the pull request for this issue. Thanks for letting me know!
