### ISSUE TITLE
No language specification link in the language tab

### ISSUE THREAD

**Issue by F-Loyer** [ocaml/ocaml.org#2089]
Whatever the language site, we can guess that the langage specifications are under a language tab. Here, it is only in the Overview page quite near the bottom (between intermediate and expertise level).

I think a better exposition in the language tab could be needed.

**Comment by xavierleroy** [comment]
I was about to submit the exact same request as an issue.

It used to be the case that the reference manual was featured very prominently on the "learn" page.  Perhaps too prominently, I agree.  But right now it's damn hard to find!

I would suggest to add a direct link to the manual on the https://ocaml.org/docs page,
- either to the "Jump" bar
![image](https://github.com/ocaml/ocaml.org/assets/3845810/95ee93d0-b107-457f-a1c3-89cc49f39385)
- or to the side bar
![image](https://github.com/ocaml/ocaml.org/assets/3845810/a2df7263-cc72-4be4-b2bb-979b972b6acd)

**Comment by F-Loyer** [comment]
Near Standard Library API would be nice since both links have the same nature (reference materials).
