### ISSUE TITLE
Missing #require statement in cookbook, unbound "int8 ()"

### ISSUE THREAD

**Issue by F-Loyer** [ocaml/ocaml.org#2091]
In https://staging.ocaml.org/cookbook/generate-random-numbers/mirage-crypto-rng, and https://staging.ocaml.org/cookbook/generate-random-strings-and-arrays/mirage-crypto-rng, we should see the following statement.

```
#require "mirage-crypto-rng.unix";;
#require "randomconv";;
```

The spelling of the library is not always obvious for a given package (see the .unix suffix).

(I guess the presentation of the requirements: utop vs. dune syntax is a point to be decided... are we focused on things which can be compiled or things which can be tried in `utop`... the style - presence of `;;` or `let () =` typically should be harmonized between RNG and Today's Date)

I guess also that the required packages should also appear in the snippet page (even if they are displayed on the index page).

==

The https://staging.ocaml.org/cookbook/generate-random-strings-and-arrays/mirage-crypto-rng uses a `int8 ()` which is defined in the other page. I guess self-sufficient pages are what we try to achieve.

**Comment by sabine** [comment]
I would argue the cookbook should be files, and we could include a `dune` file.

ETA: also agree, we need to list the required packages, and probably even libs from the package that the recipe uses.

Also true, we got to either make pages self-contained, or group them into sets. I think for database recipes, grouping them into sets may be particularly important. On the random value gen, we can more easily make things self-contained.

**Comment by sabine** [comment]
The iteration of the cookbook I made yesterday now has one single file per recipe and now lists all the packages and libraries and ppxes used.

The aim for cookbook recipes is always to be short and self-contained.
