### ISSUE TITLE
Duplicate "Docs" link in Package Search Dropdown

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2110]
Earlier conflicting patches accidentally introduced a second "Docs" link on the package dropdown. This is a bug. Your help fixing this bug is appreciated. :)

![image](https://github.com/ocaml/ocaml.org/assets/6594573/5ff3d077-9715-431f-9348-6f0163fb57e6)

[Styles of Dropdown in Figma](https://www.figma.com/file/CyOe3rJmpX2z1Zr4EdNOfH/Design-System-(Do-not-delete)?type=design&node-id=180-291&mode=design&t=TQtXZ6oTXGgeCqLo-0)

**Comment by kiyov09** [comment]
I'm open to work on this one @sabine since I'm already kind of familiar with the search.

Btw, did my last contribution cause this?

**Comment by sabine** [comment]
This was a conflict with another change that I resolved wrong.

**Comment by kiyov09** [comment]
hey @sabine , I started looking into this one but I need access to the figma files to be sure how it should look.
I already requested access in the figma ui

**Comment by sabine** [comment]
@kiyov09 Doh, sorry about that. I changed the visibility of the file so that everyone with the link should have access now.
