### ISSUE TITLE
Implement "Resources" Card Components and Section for use on Learn Overview Page

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2114]
We have a design for a "Resources" section that has cards to external resources.

Your quest, if you choose to accept it is to implement this component so it can be used in one or more places on the pages.

![Screenshot from 2024-02-28 22-09-43](https://github.com/ocaml/ocaml.org/assets/6594573/eca2381f-dad8-4493-9557-26f1d4696557)

[Figma design](https://www.figma.com/file/eh8gAxaxrZT6RG3psHCm6M/Dark-%26-Light-mode-pages?type=design&node-id=1186%3A986&mode=dev)

Relevant external resources to link to:
* https://sherlocode.com/ (packages page)
* https://doc.sherlocode.com/ (packages page)
* https://github.com/ocaml-community/awesome-ocaml (learn overview)
* http://ocamlverse.net/ (learn overview)
* https://github.com/ocaml/ocaml.org/issues/2041 (learn overview)

A suitable image would need to be chosen/created based on the resource linked to.

**Comment by FatumaA** [comment]
Would love to pick this up but can only do so from next week

**Comment by ghost** [comment]
@FatumaA Please are still working on this?

**Comment by FatumaA** [comment]
> @FatumaA Please are still working on this?

Had not started on it. You can go ahead and take it 😊

**Comment by ghost** [comment]
Thank you @FatumaA

**Comment by Payne680** [comment]
@sabine can I also participate by working on this issues too ?

**Comment by ghost** [comment]
@Payne680 I already created a PR, just waiting for a review to confirm I am on the right path. So I can complete the task. 
You can pick another task

**Comment by Payne680** [comment]
Alright @amarachigoodness74 , I will look for another issue
