### ISSUE TITLE
Exercises are not listed in order

### ISSUE THREAD

**Issue by csaltachin** [ocaml/ocaml.org#2149]
Hey all, I recently noticed that the problems in the [Exercises](https://ocaml.org/exercises) page are not being displayed in "ascending" order, i.e. following the slug numbering [here](https://github.com/ocaml/ocaml.org/tree/main/data/exercises). Here's what the first few items currently look like for me;  I've tried both Chrome and Firefox in a couple devices just to be sure, but let me know if you can't reproduce it.

<details>
  <summary>~Large picture.</summary>
  <img src="https://github.com/ocaml/ocaml.org/assets/59682192/b4287e11-dce9-467d-bed7-b76c7ca8cfbc" width=80% height=80%>
  
</details>

I've also observed the same partial (unsorted) order when filtering exercises by difficulty.
I'm under the impression that they used to be in ascending order before. I'm not sure if that's the intended behavior, but I think the ascending order gives a nice progression to the problems, and it can be confusing for beginners to see some less trivial exercises right away within the first 4-5 in the list.

I'm pretty new to OCaml and not super familiar with Alpine or Dream+eml templating, but I tried to take a look anyways. Do feel free to ignore the following if it's too off-base.

As far as I can tell, [the Dream handler for the `exercises` route](https://github.com/ocaml/ocaml.org/blob/29b37c3e28ad1f09120a2b0de30916aa0f170f32/src/ocamlorg_web/lib/handler.ml#L458) gets the exercise list from the `Data.Exercise.all` value, which comes from calling [this `all` function](https://github.com/ocaml/ocaml.org/blob/29b37c3e28ad1f09120a2b0de30916aa0f170f32/tool/ood-gen/lib/exercise.ml#L76), which in turn uses some helpers from [this `Utils` module](https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/utils.ml) to read and decode the markdown files. In particular, I'd guess that [this](https://github.com/ocaml/ocaml.org/blob/29b37c3e28ad1f09120a2b0de30916aa0f170f32/tool/ood-gen/lib/utils.ml#L38) `Bos.OS.Path.matches` call is where the actual exercise order first materializes, since the rest looks like (presumably) order-preserving maps.

If that call cannot guarantee the order in which the markdown files/filepaths are enlisted (at least the [docs](https://erratique.ch/software/bos/doc/Bos/OS/Path/index.html#val-matches) don't seem to claim so), then would it be too unwieldy to sort the exercises explicitly inside the route handler? After all, the exercise list is filtered by difficulty [inside the handler](https://github.com/ocaml/ocaml.org/blob/29b37c3e28ad1f09120a2b0de30916aa0f170f32/src/ocamlorg_web/lib/handler.ml#L472) as well, right before passing the list to the template's main render function (`Ocamlorg_frontend.exercises`). Though, I imagine it would be ideal (if possible) for this sorting to happen at build time/statically instead of every time a request is handled. Not sure what the best way to do that would be. At least it should be a quite small sort.

**Comment by sabine** [comment]
> If that call cannot guarantee the order in which the markdown files/filepaths are enlisted (at least the [docs](https://erratique.ch/software/bos/doc/Bos/OS/Path/index.html#val-matches) don't seem to claim so)

If that call doesn't guarantee the order (which might really be the underlying cause), the resulting exercises should be sorted within `tool/ood-gen/lib/exercise.ml`, before they are emitted to an OCaml module. Sorting within the Dream handler will be unnecessary then.

**Comment by csaltachin** [comment]
I see now -- makes sense. I'll submit a PR shortly, if that sounds okay.
