### ISSUE TITLE
Unreadable documentation in dark-mode

### ISSUE THREAD

**Issue by nikolaushuber** [ocaml/ocaml.org#2155]
With the recent addition of a dark-mode for ocaml.org parts of the documentation for packages becomes basically unreadable (see attached screenshot). I have tried it on recent versions of Safari, Firefox, and Chrome, all give the same result. 

I didn't see an option on the webpage itself to toggle between light and dark mode (did I miss that somewhere?), so currently the only possibility is to change the preference settings of the operating system (I am working on a Mac, maybe this is different for other OSs?). 

<img width="1454" alt="Screenshot 2024-03-10 at 16 54 26" src="https://github.com/ocaml/ocaml.org/assets/14205282/64be78a4-6ed6-42bb-9fbc-0e4d1fff0816">

**Comment by sabine** [comment]
Doh, sorry about that, will revert until that is resolved.

**Comment by sabine** [comment]
Here's some preliminary adjustments to make this work:

https://github.com/sabine/ocaml.org/tree/dark_mode_package_docs

This is not done yet, but if I don't manage to do this by tomorrow, someone else could step in and finish this.

**Comment by sabine** [comment]
Addressed for now by https://github.com/ocaml/ocaml.org/pull/2159.
