### ISSUE TITLE
Update Outreachy information w/ previous round

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#2158]
The [OCaml Outreachy](https://ocaml.org/outreachy) page keeps track of all of the Outreachy internships that the community has taken part in. We should add the "December 2023" round to this list by updating: https://github.com/ocaml/ocaml.org/blob/main/data/outreachy.yml 

The presentation has already been uploaded to watch.ocaml.org and can be linked with timestamps for each of the projects: https://watch.ocaml.org/w/b7sv1LQSVZQH6trf4xpwFX

**Comment by maha-sachin** [comment]
@patricoferris, May I know this issue#2158, do you think this would be a suitable issue for an Outreachy intern to take on?

**Comment by cuihtlauac** [comment]
@maha-sachin: Sorry this is a data processing only issue, go for an issue labelled Outreachy
@patricoferris: Where is the data we need to translate into YAML?

**Comment by patricoferris** [comment]
Thanks for the response @cuihtlauac -- the data can either come from Outreachy.org itself or from interns/mentors from this round
