### ISSUE TITLE
The code in Modules chapter doesn't compile

### ISSUE THREAD

**Issue by mikhailazaryan** [ocaml/ocaml.org#2188]
The code provided [here](https://ocaml.org/docs/modules#module-signatures-are-types) doesn't compile with the following message:
Signature mismatch:
       Modules do not match:
         sig val message : string val print : unit -> unit end
       is not included in
         HelloType
       The value `hello' is required but not provided

**Comment by cuihtlauac** [comment]
Thanks @mikhailazaryan, this is indeed a bug.

**Comment by mikhailazaryan** [comment]
I guess it works with the code from the pull request linked here, doesn't it? I mean, if the "print" function would just be renamed to "hello"

**Comment by mikhailazaryan** [comment]
Alright, seen your answer
