### ISSUE TITLE
Dark mode unreadable in some pages

### ISSUE THREAD

**Issue by Sudha247** [ocaml/ocaml.org#2201]
Concretely, I see dark text over dark mode on the page https://ocaml.org/docs/is-ocaml-web-yet.

![Screenshot from 2024-03-14 11-18-03](https://github.com/ocaml/ocaml.org/assets/13328130/11bc0eb2-cb69-4315-bd5e-106e26694f63)

Relatedly, it will be useful to have some sort of toggle button to enable and disable dark mode. If I understood correctly, right now the mode is being pulled from the system defaults.

**Comment by cuihtlauac** [comment]
Isn't this addressed by PR #2191 ?
