### ISSUE TITLE
Migrate practice into a standalone repository

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2211]
1. [X] Create GitHub a project https://github.com/divyankachaudhari/ocaml-practice-exercises
2. [ ] Copy the data from the `practice` folder
3. [ ] Setup the exercises from unresolved issues 
5. [ ] Tweak Dune configuration to allow checking all the answers at once 
6. [ ] Setup codespace support
7. [ ] Setup replit support
8. [ ] Deduplicate copycat files, as much as possible

**Comment by divyankachaudhari** [comment]
@cuihtlauac could you please clarify this issue more? I don't understand what's to be done. I want to try to take on this issue. Do we need to create a local project on our end?

**Comment by maha-sachin** [comment]
Hi @cuihtlauac @SaySayo , Can I work on this?

**Comment by divyankachaudhari** [comment]
Is this https://github.com/divyankachaudhari/ocaml-practice-exercises a good first step?

**Comment by cuihtlauac** [comment]
> Is this https://github.com/divyankachaudhari/ocaml-practice-exercises a good first step?

Yes it is, that's the idea. Take a look at project https://github.com/cuihtlauac/camellito 

This works both in codespace and replit, that's what we are look for

**Comment by cuihtlauac** [comment]
@maha-sachin:
> Hi @cuihtlauac @SaySayo , Can I work on this?

Go for #2224 first

**Comment by Ozyugoo** [comment]
Hi @cuihtlauac, has anyone started on this? If not, I would like to try my hands on it.

**Comment by 0xrotense** [comment]
Hi @cuihtlauac, is this task for a single person?

Thanks

**Comment by MissJae** [comment]
Hi, @cuihtlauac can multiple people work on this task?

**Comment by Kxrishx03** [comment]
Hii! @cuihtlauac  @divyankachaudhari  I would like to help with this task if you need.

**Comment by maha-sachin** [comment]
@cuihtlauac ,I'm keen to work on this issue as it's currently unassigned. I believe I can contribute effectively to its resolution and would like to take on the task.

**Comment by Appleeyes** [comment]
@cuihtlauac so I was trying to work on this issue 2 weeks ago but stopped because i thought someone was working on it, I have this setup: https://github.com/Appleeyes/ocaml-practice already
can you help me check and let me know if i should continue

**Comment by Blessing-Mba** [comment]
hi @cuihtlauac, I will like to work on this issue

**Comment by cuihtlauac** [comment]
Sorry @Blessing-Mba, this issue should have been closed.
