### ISSUE TITLE
Turn exercices 046, 048-050, 055-060 into practice

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2224]
This task consists of doing 10 exercises instead of one, as described in issues #2167, #2168, #2170, #2172, #2173, #2176, #2177, #2178, #2179 and #2180. Create 10 folders (numbers in 046, 048-050 and 055-060), and populate them as the others. Makes sure `dune build --root .` and `dune test --root . answer` work.

- [X] 046 #2250
- [X] 048 #2269
- [X] 049 #2270
- [X] 050 #2271
- [X] 055 #2272
- [X] 056 #2273
- [X] 057 #2274
- [X] 058 #2275
- [X] 059 #2276
- [x] 060 #2277

**Comment by maha-sachin** [comment]
@cuihtlauac, I'll start working on it right away! Thanks for assigning the task to me.

**Comment by maha-sachin** [comment]
@cuihtlauac , I was able to find the below exercises, but was unable to find `043,044,045,047,051,052` in the main branch. Can you help me with that? I will work on the existing ones in the meantime.
```
046_truth_table.md
048_truth_table_2.md
049_gray_code.md
050_huffman_code.md
```

**Comment by cuihtlauac** [comment]
Thanks @maha-sachin, I've updated the numbers

**Comment by maha-sachin** [comment]
> Thanks @maha-sachin, I've updated the numbers

@cuihtlauac, Okay Thanks and I noted.

**Comment by Appleeyes** [comment]
can i still work on this since no PR yet @cuihtlauac ?

**Comment by maha-sachin** [comment]
> can i still work on this since no PR yet @cuihtlauac ?

@Appleeyes, Hi I am currently working on this.

**Comment by cuihtlauac** [comment]
> can i still work on this since no PR yet @cuihtlauac ?

@Appleeyes: There is also #2246

**Comment by Appleeyes** [comment]
> > can i still work on this since no PR yet @cuihtlauac ?
> 
> @Appleeyes: There is also #2246

I have made prs for this issue.. Thank you

**Comment by maha-sachin** [comment]
Hi @saysayo.  @cuihtlauac , I am currently writing my application for this project via the Outreachy portal, and one of the prompts asks us to work with you to provide a timeline of the work we plan to accomplish on the project and what tasks we will finish at each step. May I inquire how to answer best this question and which projects you feel are great to include for this?

Thank you very much.

Best regards,
Maha
