### ISSUE TITLE
Add a badge from the green web foundation to the carbon footprint page

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2238]
At https://www.thegreenwebfoundation.org/green-web-check/?url=OCaml.org, there's a badge image that can be downloaded.

The image should be displayed on https://ocaml.org/policies/carbon-footprint (see https://github.com/ocaml/ocaml.org/blob/main/data/pages/carbon_footprint.md) in a suitable position to let people know that OCaml.org runs on green energy.

The image should be put in https://github.com/ocaml/ocaml.org/tree/main/data/media in a new folder `pages`.

**Comment by 0xrotense** [comment]
can I work on this?

**Comment by 0xrotense** [comment]
I just created a new PR #2241 to fix this, Please help me review it.
