### ISSUE TITLE
Exercise 005 and 008 don't compile

### ISSUE THREAD

**Issue by divyankachaudhari** [ocaml/ocaml.org#2287]
* [x] 005 [Fix error in practice 005 ex.ml file #2285](https://github.com/ocaml/ocaml.org/pull/2285)
* [x] 008 [Fixed issue in ex.ml of practice/008 #2289](https://github.com/ocaml/ocaml.org/pull/2289)

**Comment by divyankachaudhari** [comment]
With respect to PR #2242, @jahielkomu you can create a new PR.

**Comment by jahielkomu** [comment]
> With respect to PR #2242, @jahielkomu you can create a new PR
Hello @divyankachaudhari please review changes in the new PR
Thanks

**Comment by komutumu** [comment]
> With respect to PR #2242, @jahielkomu you can create a new PR.

Hello @divyankachaudhari please review changes in the new PR
Thanks
