### ISSUE TITLE
for opam releases, expose changelog and release date

### ISSUE THREAD

**Issue by avsm** [ocaml/ocaml.org#229]
This makes it convenient to browse details of a given release.

Via @hannesm in https://twitter.com/h4nnes/status/1482019842030981121

**Comment by hannesm** [comment]
what I meant is -- apart from OCaml releases -- this information would be nice to have for individual opam packages :)

**Comment by cuihtlauac** [comment]
I believe these PRs:
* https://github.com/ocaml/ocaml.org/pull/530
* https://github.com/ocaml/ocaml.org/pull/564

have fixed this. Let's close it.
