### ISSUE TITLE
(UI) Render DateTime of Event on the Client Side in the User's Timezone

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2327]
In the events directory, we record the date/times of events in UTC. However, in the templates, we would like to display these in the viewer's timezone.

A straightforward way to do this is to use the JavaScript `Date` object to parse and render the time like this:

https://stackoverflow.com/questions/1837183/displaying-date-time-in-users-timezone-on-client-side

Modify the template [`community.eml`](https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_frontend/pages/community.eml) such that, when JavaScript is available, the date/time is rendered in the user's timezone.

**Comment by maha-sachin** [comment]
Hi @sabine,  I am Maha can you help me to assign this issue?

**Comment by sabine** [comment]
Hey @maha-sachin, happy to have you!

Outside the Outreachy application period, we tend to not assign issues to individuals (due to the effort of unassigning, in case the task is later abandoned). Best is to just comment here, as you did, and make an attempt. If you get stuck, you can open a draft PR and ask for help. :heart:

**Comment by maha-sachin** [comment]
> Hey @maha-sachin, happy to have you!
> 
> Outside the Outreachy application period, we tend to not assign issues to individuals (due to the effort of unassigning, in case the task is later abandoned). Best is to just comment here, as you did, and make an attempt. If you get stuck, you can open a draft PR and ask for help. ❤️

@sabine, Thank you for the warm welcome! I'm excited to be part of Outreachy and eager to contribute. I'll follow your suggestion and attempt the task.If I encounter any difficulties, I'll be sure to reach out for assistance. Thanks again! 😊🌟
