### ISSUE TITLE
(Data) Extend the Data Model of Academic Institution to Record Information about Course Materials

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2328]
In the [Wireframes for the improved "Teaching and Research" page](https://www.figma.com/file/eLNSdvayxqvvfBsRsdbJXN/OCaml-Home-Page?type=design&node-id=5%3A2500&mode=design&t=I6cJuQypSS6xjBag-1) (formerly "Academic Users"), we list course materials from lectures.

To make this truly useful, we need to improve the data model in [`academic_institution.ml`](https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/academic_institution.ml):
1. Add a field `year : int option` to `course`, so that we can sort the courses by most recent.
2. Add a field `lecture_notes_available: bool option` to represent whether lecture notes can be found at the URL pointed to by the field `online_resource`
3. Similarly, add a field `exercises_available: exercise_availability option` where `type exercise_availability = Yes | Interactive` (where `Yes` maps to the string `"yes"`, and `Interactive` maps to the string `"interactive"`) to represent whether there are exercises provided at the URL pointed to by the field `online_resource`.

To make this data available in the templates, you need to change [`data.mli`](https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_data/data.mli) and render the new fields to the generated module in `academic_institution.ml`.

The task here is only to change the data model and maybe update one data entry (as to keep the PR small).

**Comment by 0xSaksham** [comment]
Hi Sabine, I'd like to take up this issue. What are the language requirements for this?

**Comment by sabine** [comment]
Hey @0xSaksham, would be happy to have you! This issue is all about making changes to OCaml code.

To confirm that the data is available to the templates, you might want to try and render the data to the the EML template `academic_users.eml` (this file format is a mix of OCaml and HTML). Implementing the UI will be a separate issue later, when the design is finalized.

**Comment by maha-sachin** [comment]
hi @sabine, I'd like to work on this issue.

**Comment by csaltachin** [comment]
Hi, I can pick this up if it's still open. Looks like there's no extra decoding logic here for now.

Is there currently a Dream route serving the `academic_users.eml` template? Just so I can check that the template hydrates correctly with the new course fields.

**Comment by sabine** [comment]
Hey @csaltachin! Yes, there's a route at https://ocaml.org/academic-users.

**Comment by vr-varad** [comment]
@sabine I would like to work on this issue if it is not worked upon.
