### ISSUE TITLE
Good code example for the playground

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#233]
Need to find a balance between simplicity, readability and engagement. Perhaps introducing some pattern-matching might achieve this better than the current `fac` function. See the discussion on twitter: https://twitter.com/wicko3/status/1482042995138600960

**Comment by lindig** [comment]
Ideas:
* Quicksort over a list, using `List.filter`, `List.concat`
* Binary tree as a container, function to compute set membership and size 
* Functional FIFO using two lists
* Operations on 2D or 3D vectors

**Comment by tmattio** [comment]
The code example was updated to demonstrate a parallel (to be on theme with OCaml 5 release) version of the Fibonacci sequence. I'll close this for now, but feel free to continue the discussion and suggest other examples.
