### ISSUE TITLE
Logo missing in manual pages

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2340]
![image](https://github.com/ocaml/ocaml.org/assets/1917592/b7356856-a9b7-46ee-89df-bc90cd91469d)

**Comment by shakthimaan** [comment]
The `colour-logo.svg` files have been committed to the repo.
Commit: https://github.com/ocaml-web/html-compiler-manuals/commit/52292ac6aadfef307711b2283b9eafdbc62a0d00

**Comment by sabine** [comment]
@shakthimaan This is still not resolved.

The search icon is missing on all Standard Library API pages.

On https://ocaml.org/manual/4.13/index.html, the logo is missing as well.

**Comment by shakthimaan** [comment]
The `colour-logo.svg` was showing as a folder for 4.13, and the same has been replaced with the actual file.

Commit: https://github.com/ocaml-web/html-compiler-manuals/commit/9cb91b6dda45f023c077358f9c43b3cbccf9e61a
