### ISSUE TITLE
OCaml.org Set Documentation Missing

### ISSUE THREAD

**Issue by miavuc** [ocaml/ocaml.org#2344]
https://ocaml.org/api/Set.S.html The set documentation on this page is down.

**Comment by LaifsV1** [comment]
I saw the same thing, but then noticed you can still access the v2.ocaml.org documentation.

https://v2.ocaml.org/api/Set.S.html

**Comment by sabine** [comment]
Thanks @miavuc and @LaifsV1, I fixed the links from the documentation to the Language Manual and to the Standard Library API.
