### ISSUE TITLE
(Data model) Add "event_type" Field to Events

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2361]
An event can either be
* a meetup
* a conference
* a seminar
* a hackathon
* a retreat

For this, extend the data model in [`event.ml`](https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/event.ml) to have a new field `event_type` that records what type the event is. For inspiration on how to do this, look at the "difficulty" field in [`book.ml`](https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/book.ml).

Both the recurring and upcoming events need to be extended. For an upcoming event that has a linked recurring event, this field will be populated from the linked recurring event.

Events in `data/event` will need to be updated.

Also, we need to render the new information as part of the Event card (as a tag below the event title).

**Comment by csaltachin** [comment]
Hi! I'd like to take a shot at this. A few questions:

- Do we want to require that the event type is always specified both in `data/event/*.md` files _and_ in `data/event/recurring.yml` entries? Or do we want to allow e.g. an upcoming event `2024-foo.md` to omit its event type if it has a linked recurring event that does specify an event type?
- Looking at the [`decode`](https://github.com/ocaml/ocaml.org/blob/1cb5e57c81f9311930de53f92cdb7f41e72ef056/tool/ood-gen/lib/event.ml#L64) function in `event.ml`, should it be an error (and should we throw) if an upcoming event and its linked recurring event have different event types? Or should we always use the type from the recurring event if any?
- I'm not super familiar with the site's design system, but as for rendering, it looks like we just need to add a couple divs in the `events.eml` template, with a similar Tailwind class as [the other Event card tags](https://github.com/ocaml/ocaml.org/blob/1cb5e57c81f9311930de53f92cdb7f41e72ef056/src/ocamlorg_frontend/pages/events.eml#L23), and hydrated via `event.event_type` and `recurring_event.event_type`. Does this sound roughly correct? Do we want to render a different icon (if any) for each event type?

**Comment by sabine** [comment]
> Do we want to require that the event type is always specified both in data/event/*.md files and in data/event/recurring.yml entries? Or do we want to allow e.g. an upcoming event 2024-foo.md to omit its event type if it has a linked recurring event that does specify an event type?

Yes, `event_type` can be `None` for events that have a recurring event linked.

> Looking at the [decode](https://github.com/ocaml/ocaml.org/blob/1cb5e57c81f9311930de53f92cdb7f41e72ef056/tool/ood-gen/lib/event.ml#L64) function in event.ml, should it be an error (and should we throw) if an upcoming event and its linked recurring event have different event types? Or should we always use the type from the recurring event if any?

I would error because it forces data hygiene.

> I'm not super familiar with the site's design system, but as for rendering, it looks like we just need to add a couple divs in the events.eml template

This is correct. We have a design draft here: https://www.figma.com/file/7hmoWkQP9PgLTfZCqiZMWa/OCaml-Community-Pages?type=design&node-id=673%3A5401&mode=design&t=WY9kKqHieq0dfYnO-1

**Comment by csaltachin** [comment]
Got it. I think I can have an initial PR soon. Just to double check, it sounds like `data/event/recurring.yml` entries should _always_ specify an event type, while `data/event/2024-foo.md` files can omit it, but _only_ if they have a linked recurring event.

Do we want to add a "workshop" variant for events like [`2024-09-07-ocaml-workshop.md`](https://github.com/ocaml/ocaml.org/blob/main/data/events/2024-09-07-ocaml-workshop.md)? Otherwise we could lump these in as seminars or conferences.

**Comment by sabine** [comment]
Yes, that's correct.

I would sort OCaml Workshop as a conference, simply by its primary nature being a sequence of talks and being less interactive than a seminar.

If we had workshop as an event_type, it would be something hands-on where people write code on their laptop to while using some instructions / exercises. However, I think such a kind of workshop often happens as part of a conference or of a meetup or during a retreat or seminar, so it should not be an entire event_type by its own.

**Comment by sabine** [comment]
Resolved by #2366
