### ISSUE TITLE
docs: "Error: Uninterpreted extension 'show'." in "Your First OCaml Program"

### ISSUE THREAD

**Issue by tamagosante** [ocaml/ocaml.org#2364]
1. https://ocaml.org/docs/your-first-program#using-the-preprocessor-to-generate-code
2. scroll to 
The files lib/en.ml and lib/en.mli need to be edited, too:
4. scroll to
lib/en.ml
4. code example
```ocaml
let string_list_pp = [%show: string list]

let string_of_string_list = Format.asprintf "@[%a@]" string_list_pp

let v = String.split_on_char ' ' "Hello using an opam library"
```

![image](https://github.com/ocaml/ocaml.org/assets/30693990/e5876c6e-7ac3-4335-96d8-6b5ab34989ea)

**Comment by sabine** [comment]
@hiaux0 The OCaml playground doesn't currently support any PPXes (preprocessor extensions), and it is unclear if it ever will.

It is necessary to try these examples with dune (specifically, using the dune stanza to run the ppx_show PPX).

**Comment by tamagosante** [comment]
@sabine gotcha.
I followed the tutorial with utop, that's where I got the error from (should have mentioned it)

Feel free to close this issue!
