### ISSUE TITLE
Packages in "Strong Community" section scroll off screen

### ISSUE THREAD

**Issue by leviroth** [ocaml/ocaml.org#237]
The packages in the "Strong Community" section scroll off the sides of the screen, depending on screen size.

It already looks weird on my laptop:

![ocaml-screenshot-2](https://user-images.githubusercontent.com/17488252/149633951-13ccab89-d90e-42b1-8092-f532fd4e99bb.png)

But the content is almost completely hidden on my phone:

![Welcome to a World of OCaml](https://user-images.githubusercontent.com/17488252/149633946-85aad24a-e952-4d2d-9335-22707a7a58a1.png)

**Comment by avsm** [comment]
Confirmed on mobile as well; needs some tailwind class magic for smaller screens.

**Comment by tmattio** [comment]
Fixed in #295
