### ISSUE TITLE
Publish an RSS feed for Events

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2392]
Similar to the OCaml Changelog, Events should be provided as a RSS feed (so that we can connect them with social media accounts on Twitter, LinkedIn, and Mastodon).

Hints:
- Look at the implementation of RSS feeds for the OCaml Changelog (https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/changelog.ml) as inspiration for how to do this for Events (https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/event.ml).
- The `create_feed` function for Events needs to be registered as a sub-command of `ood-gen` here: https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/bin/gen.ml
- You need to add a dune rule at https://github.com/ocaml/ocaml.org/blob/main/dune that runs the `ood-gen` tool to create the `.xml` file.
- Update the template at `events.eml` to add a link to the RSS feed.

**Comment by cuihtlauac** [comment]
As a reminder, ocaml.org currently publishes *two* feeds:
* https://ocaml.org/feed.xml
* https://ocaml.org/blog/opam/feed.xml

This is about publishing a third one.

**Comment by sabine** [comment]
There's also https://ocaml.org/changelog.xml
