### ISSUE TITLE
Implement a syndicated RSS feed for the OCaml Blog

### ISSUE THREAD

**Issue by hannesm** [ocaml/ocaml.org#242]
The https://v3.ocaml.org/blog seems to include some articles from some blogs, but the very nice to read planet (https://ocaml.org/community/planet/) seems to be not included in v3.

**Comment by tmattio** [comment]
Thanks for opening the issue @hannesm!

This change is intentional, and we've done that because by exposing every blog post of the different RSS feeds, we were serving some posts that had nothing to do with OCaml.

The current blog on v3 works by fetching the RSS feeds and manually listing the articles to link to from this feed. This way, we'll be sure to not have content that is not related to OCaml.

This is not an ideal situation, and we're open to ideas on how we can do better, but for now, we're encouraging people to send PRs to add new sources to https://github.com/ocaml/v3.ocaml.org-server/blob/main/data/rss-sources.yml.

Feel free to suggest additions to these RSS sources 🙂

**Comment by tmattio** [comment]
Closing this issue for now, but as I mentioned, feel free to add more sources to rss-sources.yml 🙂

**Comment by hannesm** [comment]
I don't quite understand, so instead of using syndication - as previously - RSS or atom feeds - you propose that "interesting blog articles" should be manually pushed to a yaml file in this repository? I doubt this will be done much.

The trouble "serving content unrelated to OCaml" - my perception is that the amount of non-OCaml articles is very minor, and various blogs have filters for `ocaml` tags.

So my reverse proposal is:
- re-enable syndicated blog entries, fetching automatically from the previous list
- once you encounter an article that is not on-topic, message the blog author whether they could provide a rss/atom feed for ocaml-only content
- document the process and invite others to contribute their feeds
- of course, the mechanism to include single articles is very nice and should be kept for blogs that only once in a while have an ocaml article

Thus, by default people don't have to change anything. I'd find it very sad to only have tarides, ahrefs, and jane street articles on the new OCaml website.

**Comment by tmattio** [comment]
> once you encounter an article that is not on-topic, message the blog author whether they could provide a rss/atom feed for ocaml-only content

That sounds reasonable 🙂 

> I'd find it very sad to only have tarides, ahrefs, and jane street articles on the new OCaml website.

Definitely! Our hope was that the community would add their RSS sources when they see that the new website doesn't contain their blog posts. This didn't happen, and I agree it's a heavy process for users.

Let's try to implement the workflow you laid down and see how it goes!

**Comment by hannesm** [comment]
> Definitely! Our hope was that the community would add their RSS sources when they see that the new website doesn't contain their blog posts. This didn't happen, and I agree it's a heavy process for users.

TBH, I still don't understand what is needed for achieving this. On the old website, there's https://ocaml.org/community/planet/syndication.html linked from https://ocaml.org/community/planet

Here, there's now a link in this issue to some yml file, but it is not very clear to me what needs to be done to have an atom/rss feed included - maybe I'm confused by both a link to some syndication resource, and a list of articles (unclear whether that is a list of articles to display or not to display -- unclear whether there is any automation that adds articles).

So I have an atom url https://hannes.robur.coop/atom -- but unclear how to proceed here. Maybe such a syndication guide would be worth to have on the new website?

**Comment by tmattio** [comment]
Closed in #279 
The contributing guide is tracked in #288
