### ISSUE TITLE
Reference Manual downloads for OCaml 5.2 give Error 404

### ISSUE THREAD

**Issue by frou** [ocaml/ocaml.org#2422]
Hi there. The four links to download the manual in the various formats are not working. Maybe I'm just impatient and they are being generated by some background job, but I thought I should report it anyway 😅 

Reached via:

* https://ocaml.org/releases
  * https://ocaml.org/manual/5.2/index.html
     * **"This manual is also available in [PDF](https://ocaml.org/releases/5.2/ocaml-5.2-refman.pdf), [plain text](https://ocaml.org/releases/5.2/ocaml-5.2-refman.txt), as a [bundle of HTML files](https://ocaml.org/releases/5.2/ocaml-5.2-refman-html.tar.gz), and as a [bundle of Emacs Info files](https://ocaml.org/releases/5.2/ocaml-5.2-refman.info.tar.gz)"**

**Comment by cuihtlauac** [comment]
Thanks @frou, this is in indeed a bug.

**Comment by sabine** [comment]
Context: currently these are manually generated and committed to https://github.com/ocaml-web/html-compiler-manuals. So the fix will be to check out the ocaml/ocaml 5.2 release branch, generate the manual there and open a PR with the files on the html-compiler-manuals repo.

**Comment by Octachron** [comment]
Note that those manual archives are still mirrored on https://caml.inria.fr/distrib/ocaml-5.2 .

**Comment by sabine** [comment]
The manuals will be available after the next deployment.

**Comment by sabine** [comment]
Sorry, I was wrong, there's some redirects missing.

**Comment by frou** [comment]
Thank you very much. I use the download to be able to generate [this Docset](https://github.com/frou/ocaml-docset) for the Dash application.
