### ISSUE TITLE
API docs not found

### ISSUE THREAD

**Issue by yawaramin** [ocaml/ocaml.org#2465]
OCaml module docs are gone: https://ocaml.org/api

Getting a 404 there. Can they be brought back?

**Comment by yawaramin** [comment]
Or did it officially move to https://ocaml.org/manual/5.2/api/ ?

**Comment by cuihtlauac** [comment]
Thanks, @yawaramin. That's a bug. The latter is the canonical URL, while the former should be a redirection. It was lost in refactoring, but it will be brought back.

**Comment by yawaramin** [comment]
Thanks!
