### ISSUE TITLE
compilerlibref api is 404

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#2469]
https://ocaml.org/manual/5.2/api/compilerlibref is 404

**Comment by sabine** [comment]
Where does this URL occur?



Here's another one that's coming from Google search results:

Bug:

https://ocaml.org/manual/attributes.html

redirects to

https://ocaml.org/manual/5.2/attributes.html/index.html

**Comment by sabine** [comment]
The open PR doesn't yet address the https://ocaml.org/manual/5.2/api/compilerlibref URL / redirect
