### ISSUE TITLE
(UI) Implement Event Card with Default Image for Recurring and Upcoming Events

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#2475]
In [Link to Figma page](https://www.figma.com/design/J0w4b9exaHhVpvabKoGqTn/Design-Github-Issues?node-id=616-2515&t=ABO0h6yDCxRnRSTz-1), we have a design for the new Event card:

![Screenshot](https://github.com/ocaml/ocaml.org/assets/312622/9f97454e-f070-4901-ad98-ffceaf0c2a68)

Your task here is to implement the new event card as a component:

* based on the location, choose one of the 6 images from [OCaml.org Design System / Default Images](https://www.figma.com/file/CyOe3rJmpX2z1Zr4EdNOfH/Design-System-(Do-not-delete)?type=design&node-id=1893%3A326&mode=design&t=UgyPyLwP0laKB5mv-1). (This can be done the same way as [background colors for package author default avatars in package_overview.eml](https://github.com/ocaml/ocaml.org/blob/1ac5dfdc5acfcdc95bab50af6904a140c1f6410b/src/ocamlorg_frontend/pages/package_overview.eml#L26).)
* Overlay the location as text on the image.

The component to be modified is in `ocamlorg_frontend/components/cards.eml`.

**Comment by maha-sachin** [comment]
Hi @sabine & @shakthimaan, can I have this issue?

**Comment by jatingodnani** [comment]
@sabine   should i do filtering or searching on client side or any server side api?
which techstack for frontend

**Comment by sabine** [comment]
@jatingodnani Check how filtering is done in other parts of the site, such as the jobs page.

**Comment by akankshat05** [comment]
Hello @sabine , Can i work on this issue?

**Comment by sabine** [comment]
@akankshat05 Hey, thanks so much for offering to help, we forgot to close this issue after it was completed. Sorry about that!

**Comment by akankshat05** [comment]
> @akankshat05 Hey, thanks so much for offering to help, we forgot to close this issue after it was completed. Sorry about that!

Okay, got it! I am a beginner in contributing to the repo. Could you please point me to some issues which can get me started? I have already set up my development environment.

**Comment by sabine** [comment]
@akankshat05 https://github.com/ocaml/ocaml.org/issues/2015 would be a great issue to start with, as it's quite simple but also useful :slightly_smiling_face:
