### ISSUE TITLE
docs broken link in library `code_kernel`

### ISSUE THREAD

**Issue by arbipher** [ocaml/ocaml.org#252]
https://v3.ocaml.org/p/core_kernel/v0.14.1/doc/Test_binary_searchable/index.html

The link is in the left column of the page https://v3.ocaml.org/p/core_kernel/v0.14.1/doc/index.html.

**Comment by arbipher** [comment]
Well, it's more subtle and complex than minutes ago when I created this issue.

The valid link for the module is https://v3.ocaml.org/p/core_kernel/v0.14.1/doc/Base_for_tests/Test_binary_searchable/index.html
I found the link in this [section](https://v3.ocaml.org/p/core_kernel/v0.14.2/doc/index.html#core_kernel.base_for_tests).

The module `Test_binary_searchable` is in package `core_kernel.base_for_tests` (not `core_kernel`).
The source for it is in [github/core](https://github.com/janestreet/core/blob/master/base_for_tests/src/dune).

I hope this info helps.

**Comment by gpetiot** [comment]
It looks like it's now fixed.
