### ISSUE TITLE
Installation documentation... .... confusing for noobs (and me noob to ocaml specifically)

### ISSUE THREAD

**Issue by christopherreay** [ocaml/ocaml.org#2556]
On this page:
https://ocaml.org/docs/installing-ocaml

the linux instructions require that installation is done as root / sudo (stating `apt install...`)
but it seems very likely to me that opam init -y should be run as the intended user.

there is a reasonable implication that `apt` should be run by root/sudo, however, there is no bounds placed on the implication, such that running opam init -y, should (likely I dont know) be run as user.

[issue transferred from ocaml repo)

**Comment by cuihtlauac** [comment]
Thanks, @christopherreay; you are right; this is not clear. In Linux, only distribution packages should be installed with super-user rights. All opam commands should be executed as a normal user.

**Comment by cuihtlauac** [comment]
I've filed PR #2558 on this. @christopherreay, let me now if it is clear enough now. 

I'm unsure about macOS. If I remember correctly, brew does not require sudo but port does. I haven't done that for a long time

**Comment by christopherreay** [comment]
> I've filed PR #2558 on this. @christopherreay, let me now if it is clear enough now. 
> 
> I'm unsure about macOS. If I remember correctly, brew does not require sudo but port does. I haven't done that for a long time

I'll give Steve a quick call and ask him

**Comment by christopherreay** [comment]
> I've filed PR #2558 on this. @christopherreay, let me now if it is clear enough now. 
> 
> I'm unsure about macOS. If I remember correctly, brew does not require sudo but port does. I haven't done that for a long time

yeah that looks great tyty
