### ISSUE TITLE
Vendor swiper js 

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#260]
We vendor most JS libraries directly in the site to avoid pulling in things from third-party sites, but looks like this one slipped in by accident. 

https://github.com/ocaml/v3.ocaml.org-server/blob/6bc9dce632bca5e210d941a742d72a25c52c2964/src/ocamlorg_frontend/layouts/layout.eml#L44

**Comment by tmattio** [comment]
Fixed in #268
