### ISSUE TITLE
Tezos documentation is not generated

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#262]

**Comment by tmattio** [comment]
@jonludlam the latest version of the tezos doc that was built was 11.0.
Do you have any pointer on how we could investigate why the documentation didn't build for `11.1` and `12.0`.
Same thing for `ocaml.4.14.1`, and probably other packages. It'd be useful to have an overview of the packages for which the documentation couldn't be generated. Do we have something like this at the moment?

**Comment by TheLortex** [comment]
There was an issue in the CI that prevented builds on 4.14 but it's now fixed and the tezos packages documentations are correctly generated.

**Comment by tmattio** [comment]
Thanks @TheLortex!
