### ISSUE TITLE
Website fails to build after PR#2746

### ISSUE THREAD

**Issue by mtelvers** [ocaml/ocaml.org#2747]
https://github.com/ocaml/ocaml.org/pull/2746 has broken the website build.  See https://deploy.ci.ocaml.org/job/2024-10-04/084900-ocluster-build-74a22a

**Comment by mtelvers** [comment]
@sabine Please can you take a look

**Comment by sabine** [comment]
Should be resolved by https://github.com/ocaml/ocaml.org/pull/2748
