### ISSUE TITLE
Blockquote misuse

### ISSUE THREAD

**Issue by toastal** [ocaml/ocaml.org#2752]
I was reading the page: https://ocaml.org/docs/installing-ocaml

Blockquotes are being used incorrectly.

![scrot-2024-10-07_1286x145](https://github.com/user-attachments/assets/65d78b0d-4764-450a-9458-b05a45c588b0)

![scrot-2024-10-07_1310x453](https://github.com/user-attachments/assets/1c0b3c95-7c3e-4953-8965-ac052f66b671)

> The blockquote element represents a section that is quoted from
> another source.
>
> — W3C HTML spec, https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element

There are more instances around these docs of blockquotes not referencing text from some other source. It appears these are being meant to be used a callout/admonition. Due to the choice of Markdown (not sure which fork) for lightweight markup over a different syntax that supports them, there is no support for these common elements for technical documentation. Regardless `<blockquote>` isn’t the semantic element for this & shouldn’t be used.

**Comment by cuihtlauac** [comment]
Thanks @toastal. You are right; quotations are for quotations. PR #2753 tentatively fixes this.

If you spot other such issues, we'd love to have a patch from you on this.
