### ISSUE TITLE
Add example to Exercise 3 (N'th Element of a List)

### ISSUE THREAD

**Issue by j-artur** [ocaml/ocaml.org#2858]
Exercise 3 currently shows no example of how to function should look like, it only shows how `List.nth` works.

Here's how it looks today:
![image](https://github.com/user-attachments/assets/e69de7ae-c3fc-4cc0-af6b-c94a789a0713)

Here's how exercise 3 used to look, with an example, according to [WebArchive](https://web.archive.org/web/20220404033804/https://ocaml.org/learn/tutorials/99problems.html):
![image](https://github.com/user-attachments/assets/5ff76065-870f-44b7-90d7-abc918fe9f9a)

**Comment by cuihtlauac** [comment]
Thanks @j-artur. You are correct, there was a regression
