### ISSUE TITLE
Process for deciding who's on the front page?

### ISSUE THREAD

**Issue by code-ghalib** [ocaml/ocaml.org#311]
I'm wondering whether there's a community process or guidelines for who gets included on the v3.ocaml.org front page.  

I think that part of the page serves as marketing mechanism for OCaml as a language/ecosystem - if you learn OCaml, you can land a job at X/Y/Z company.  

It works the other way too of course, if you want to work in OCaml, come work for X/Y/Z company. 

Is there already a process for how it is decided who appears on the front page, and who appears in the industrial users section?

We can as a community decide, that since this is high-visibility web-estate, it be auctioned, or be limited to OCaml Software Foundation members, or something else.  Or we can agree to enhance the front page to show random industrial users every time. 

I'm creating this issue for discussion purposes and seeking proposals and feedback from the community.

What I'd like to avoid is arbitrary inclusions/removals, for example, [like this](https://github.com/ocaml/v3.ocaml.org-server/commit/833127803144d7582d52d8010b73164f6b1d618d).

**Comment by tmattio** [comment]
Thanks @code-ghalib, that's a very important question 🙂 

We don't have a specific process to decide which logos are included on the homepage. The general governance of the website is described at https://v3.ocaml.org/governance though, and that should give some ideas on how decisions are taken.

Even though we're getting close to the launch date, the website is still in preview at the moment, so the decision process is a bit different now than it ought to be once it's officially launched. To have a reasonable momentum during development, we're "queuing" changes by pushing them to the preview site. The owners and delegates (as described in the governance document above) will be giving the green light for a proposed version, and we will launch this approved version of the site.

Now, once the website is launched, I expect that the decision process will be a bit different, and the owners and delegates should validate important changes such as the logos on the front page.

So to be a bit more specific, the owners and delegates will approve the currently proposed list of logos when giving the green light for launch and will be able to review PRs that propose changes to these once it's launched.

Now, this governance structure describes who's responsible for the final decision, but of course, OCaml.org remains a community website, so anyone can open PRs or suggest changes. If you think the logo cloud is not adequate or relevant, your suggestions are very much welcome!

I hope this answers the question and addresses the (rightful!) concerns you're expressing 🙂
