### ISSUE TITLE
picture on packages link in front page overflows

### ISSUE THREAD

**Issue by avsm** [ocaml/ocaml.org#314]
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/53164/153777052-d96447a8-e1f1-4568-a6ac-168b267442df.png">

The picture overflows on my laptop screen. However, we may want to consider having another picture there, as it's a little odd to have a screenshot of the website on the same website ;-)

**Comment by tmattio** [comment]
The overflow was intentional in the design.

> However, we may want to consider having another picture there, as it's a little odd to have a screenshot of the website on the same website ;-)

This isn't shocking to me, but I agree we can probably come up with something better 🙂 What do you think @asaadmahmood ?

**Comment by axrwl** [comment]
On mobile devices, it overflows too much see #338 

I suggest either vary the dimensions of the image based on screen size or just remove it altogether and display featured packages instead, or package statistics.

**Comment by sabine** [comment]
This issue looks like it has been completed. As I checked, no images on the home page overflow.

**Comment by axrwl** [comment]
It still overflows on certain screen resolutions (set dimension to responsive in chrome dev tools and vary the width) but in my opinion this is not a point of concern at all.

**Comment by sabine** [comment]
Closing this issue since further changes will happen when the home page redesign happens.
