### ISSUE TITLE
Render authors without email address in search result 

### ISSUE THREAD

**Issue by tmcgilchrist** [ocaml/ocaml.org#320]
The current search by author / maintainer doesn't seem to find all the packages for a person and / or doesn't provide paginated results. It looks like the author with and without email addresses returns different results.

eg https://v3.ocaml.org/packages/search?q=author%3A%22Tim%20McGilchrist%22 only shows aws packages but there are gitlab packages that should be there.
https://v3.ocaml.org/packages/search?q=author%3A%22Tim%20McGilchrist%22 shows everything.

Also I'd suggest that the author should be rendered as a real name without email address, and only as an email address if there is no real name.
eg Just `Tim McGilchrist` rather than `Tim McGilchrist <timmcgil@gmail.com>`

Mainly on the search results page, where packages with multiple authors look messy.  Perhaps also on individual package pages, though there is more screen area to use.

**Comment by axrwl** [comment]
Both of the links you have posted are same.

**Comment by art-w** [comment]
Another example: in the search results, clicking on the author link for [Daniel Bünzli](https://v3.ocaml.org/packages/search?q=author%3A%22Daniel%20B%C3%BCnzli%22) yields no results at all (because of the umlaut?)

**Comment by cuihtlauac** [comment]
This seems to be resolved. Should we close this issue?

**Comment by tmattio** [comment]
This seems to have been fixed, feel free to re-open if you still see this issue
