### ISSUE TITLE
Errors in ocaml.org/learn/tutorials/introduction_to_gtk.html

### ISSUE THREAD

**Issue by biloucat** [ocaml/ocaml.org#324]
In "Simple lablgtk program" there are missing "ignore" commands therefore some Warnings at compile time.
Same thing in "Graph widget" and more important:
  "window#add_accel_group accel_group;" is missing in test.ml file.

Sorry for my bad english, i'am french !

**Comment by tmattio** [comment]
Thanks for the report @biloucat. Would you be willing to send a PR with the fixes you're describing in the description?

**Comment by cuihtlauac** [comment]
Since https://ocaml-tutorial.org/introduction_to_gtk didn't make it into https://ocaml.org/docs it probably make sense to close this issue as "not planned"?
