### ISSUE TITLE
searching for "ocaml" in packages return 5.0.0+trunk

### ISSUE THREAD

**Issue by avsm** [ocaml/ocaml.org#329]
I was trying to find the docs for "Set.S", which is quite difficult from the v3.ocaml.org packages search.  Search should probably take you to the version of the package that has docs built, shouldnt it?

https://v3.ocaml.org/packages/search?q=ocaml

**Comment by tmattio** [comment]
The manual and stdlib documentation are not yet integrated into the doc site, so I wouldn't recommend using the opam packages to look for the standard library documentation. Both reading the documentation and accessing it is going to be more painful than it should be.

The documentation for `Set.S` can be found by going to: `Learn -> Standard Library API -> Set` (https://ocaml.org/api/Set.S.html).

Even when we integrate the manual and standard library, it's not clear whether the opam package documentation will be the best place to look for them, but for now, the standard library at https://v3.ocaml.org/p/ocaml-base-compiler/4.13.1/doc/Stdlib/index.html isn't really usable.

**Comment by tmattio** [comment]
@avsm not sure if there's any action to take here? Closing the issue, but feel free to re-open if the answer above isn't solving the issue.
