### ISSUE TITLE
Update books page to show that OCaml from the Very Beginning is now free

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml.org#331]
Per https://discuss.ocaml.org/t/ocaml-from-the-very-beginning-now-free-in-pdf-and-html-formats/

I'm happy to do the PR, but what do I do it against? V3 sources? Is there any procedure I need to know at this time of transition?

**Comment by tmattio** [comment]
Thanks @johnwhitington, a PR would be very appreciated! You can update the file at https://github.com/ocaml/ocaml.org/blob/main/data/books/en/ocaml-from-the-very-beginning.md?plain=1, which contains the metadata of the book. There's no specific procedure, you can land a PR with the update and it'll be deployed when merged.

**Comment by johnwhitington** [comment]
PR in #333
