### ISSUE TITLE
Read online link for OCaml from the very Beginning

### ISSUE THREAD

**Issue by axrwl** [ocaml/ocaml.org#336]
In the [books](https://v3.ocaml.org/books) page, a new button should be added under _OCaml from the very Beginning_ to point the reader to the free versions - [PDF](https://johnwhitington.net/ocamlfromtheverybeginning/mlbook.pdf) and [HTML](https://johnwhitington.net/ocamlfromtheverybeginning/index.html).

Currently the button points the readers to the amazon page for the same.

**Comment by tmattio** [comment]
This has been done in https://github.com/ocaml/ocaml.org/pull/333
