### ISSUE TITLE
Homepage's toplevel can be improved

### ISSUE THREAD

**Issue by axrwl** [ocaml/ocaml.org#337]
The toplevel on [homepage](https://v3.ocaml.org/) has an input area which is re-sizable by the user. But this results in visual bugs such as :

<p align="center">
<img width="470" alt="Screen Shot 2022-03-03 at 11 56 12 AM" src="https://user-images.githubusercontent.com/22836245/156508680-93e98eee-28e7-4647-9494-c8542e56a53c.png">
</p>
 
To fix this, the textarea shouldn't be re-sizable by the user and instead it should give a vertical scroll to the user. 

Moreover, it should be preferable to reduce the rounding of the borders and fill the colors in the three circles on top-left. Also, perhaps remove the horizontal line below the three circles.

Another visual improvement could be that the try button changes its color slightly upon hover.

**Comment by tmattio** [comment]
We removed the homepage toplevel in favor of the playground.
