### ISSUE TITLE
Image on home page gets cut on mobile devices

### ISSUE THREAD

**Issue by axrwl** [ocaml/ocaml.org#338]
An image on the [home page](https://v3.ocaml.org/) gets cut on mobile devices. 

<p align="center">
<img src="https://user-images.githubusercontent.com/22836245/156528026-441fb69b-d6d8-4225-82f0-4da6ef04fc8c.png" width="200"/>
</p>

Possible solutions are either hide the image on smaller screens or fix its dimensions along with alignment on smaller screens.

**Comment by tmattio** [comment]
Thanks @KingOfDireWolves! I'm closing this as a duplicate of #314. It looks like we should find a solution to improve both the desktop and mobile view at the same time.
