### ISSUE TITLE
tutorial is out of date with latest release.

### ISSUE THREAD

**Issue by birlorg** [ocaml/ocaml.org#341]
In data/tutorials/en/000_up_and_running.md

it says to install 4.11.1: `opam switch create 4.11.1` which is not the current release.  Having to manually update this every time a new release comes out seems annoying.

Looking through the documentation, it looks like to see the latest version one would run:

`opam switch list-available ocaml-base-compiler`

and then they can run `opam switch create 4.13.1` or whatever the latest version is at the time the user reads it.

Am I correct this is the right set of commands, and is this a good change?  If so, I can try my hand at submitting a PR.

**Comment by tmattio** [comment]
Hi @birlorg - thanks for the report!

It looks like the right set of commands, so feel free to submit a PR with this 🙂
