### ISSUE TITLE
Typos on About OCAML page

### ISSUE THREAD

**Issue by joanmh123** [ocaml/ocaml.org#343]
https://v3.ocaml.org/about
There are a few typos on the page in the Why OCAML section:
1. Missing period/full stop between the second and third sentences.
2. End of second paragraph- I would put a line break before" These Include".

**Comment by tmattio** [comment]
Looks like this has been fixed already. Closing now, but let me know if there's anything else.

**Comment by RaglandCodes** [comment]
In the [Up and Running page](https://ocaml.org/docs/up-and-running#installing-ocaml), I think the phrase "mentionned aboved" should by "mentioned above"

**Comment by cuihtlauac** [comment]
Thanks @RaglandCodes; this was misspelt. Now fixed

BTW: When you notice something like that in the docs, move to the bottom of the page; there's a link to the GH page corresponding. You should be able to post a fix in minutes. We all love  merging fixes ;-)
