### ISSUE TITLE
Typographic issues: orphaned line breaks on Dune page.

### ISSUE THREAD

**Issue by joanmh123** [ocaml/ocaml.org#344]
https://v3.ocaml.org/p/dune/3.0.3
There are some inconsistencies of line breaks throughout the page. In several instances, the lines are breaking with widows of just one or two words on the next line, although there looks to be enough room on the previous line. 

It's better to follow typography standards and avoid "widows and orphans" where possible so that the text is easy to read and looks professional.
<img width="648" alt="ocamlbug2" src="https://user-images.githubusercontent.com/58739696/157233556-66228a5e-f1e5-4c3a-b635-0a124374580c.png">
<img width="904" alt="caml_bg1" src="https://user-images.githubusercontent.com/58739696/157233565-febbd569-a42e-4dd3-830d-a40967c2337d.png">

I have called out a few examples of the widows/weird line breaks in the screenshots attached.

**Comment by joanmh123** [comment]
Looking closer, this issue also appears on 
https://v3.ocaml.org/p/dream/1.0.0~alpha3
https://v3.ocaml.org/p/js_of_ocaml/4.0.0 (just one problematic break on this page)

**Comment by tmattio** [comment]
The cause for this is that there are line breaks in the README of Dream, and Omd is inserting line breaks for these when transforming the markdown to HTML. IIUC, single line breaks in markdown shouldn't cause a line break in HTML, this is consistent with how GitHub renders the Markdown files.

This should be addressed upstream in [omd](https://github.com/ocaml/omd)
