### ISSUE TITLE
Python garbage collection misleadingly described

### ISSUE THREAD

**Issue by jeanas** [ocaml/ocaml.org#345]
From https://ocaml.org/learn/tutorials/garbage_collection.html:

> Python has a form of garbage collection, but it uses a simple scheme called reference counting. Simply put, each Python object keeps a count of the number of other objects pointing (referencing) itself. When the count falls to zero, nothing is pointing at this object, and so the object can be freed.
>
> Reference counting is not considered as serious garbage collection by computer scientists, yet it has one big practical advantage over full garbage collectors. [...]

Later, the page mentions the inability to collect cyclic data structures as a disadvantage of refcounting. That's true for refcounting as-is, but the reference to Python is misleading, since Python *does* collect cyclic data: it has *both* a refcounting scheme that reclaims most objects immediately after they get unused, *and* a mark-and-sweep collector that runs from time to time to collect cyclic structures.

It might work to simply replace the reference to Python with Swift, which only has reference counting as far as I can read (but I'm not expert in Swift).

**Comment by axrwl** [comment]
You are right about Swift only using reference counting.
