### ISSUE TITLE
Inconsistent use of sentence/title case in Case Studies 

### ISSUE THREAD

**Issue by joanmh123** [ocaml/ocaml.org#347]
https://v3.ocaml.org/success-stories
Scroll down to the case study showcase areas. Three are using sentence case and one is using title case. We need to choose one style and use it everywhere on the site where-ever we use a header.

**Comment by axrwl** [comment]
Whichever case gets chosen, don't forget to change the title on the respective success stories pages too.

**Comment by joanmh123** [comment]
Here's the list of inconsistencies and the suggested changes. It's a bit long. Thanks in advance for your patience.

~~In nav/header (top right all pages)~~
~~Search field:
Search OCaml packages
Change to:
Search OCaml Packages~~

~~Button:
Get started
Change to 
Get Started~~

~~Footer(all pages)
About us: Change to:
About Us~~

~~Learn Page:
https://v3.ocaml.org/learn
A memory model for multicore OCaml
Change to:
A Memory Model for Multicore OCaml~~

~~Packages Page:
https://v3.ocaml.org/packages
 Most used packages
Change to:
Most Used Packages 
Change to: 
Start contributing 
Change to: 
Start Contributing~~

~~Focus on your code, and opam takes care of distributing it
Change to:
Focus on Your Code, and Opam Takes Care of Distributing it~~

~~Button:
Learn how to contribute
Change to:
Learn More~~

~~The OCaml Community Page~~
~~https://v3.ocaml.org/community~~
~~Join our communities!
 Change to:
 Join our Communities!~~

~~Up and Running Page
https://v3.ocaml.org/learn/up-and-running-with-ocaml~~

~~Up and Running with OCaml
Change to:
Up and Running With OCaml~~

~~The OCaml top level (REPL)
Change to:
The OCaml Top Level (REPL)~~

~~Using the Dune build system
Change to:
Using the Dune Build System~~

~~A first project
Change to:
A First Project~~
**--CR: Some on this page were already changed, perhaps from my previous PR. (??)--**

~~Editor support for OCaml
Change to:
Editor Support for OCaml~~

~~Help us make these docs great!
Change to:
 Help Improve Our Documentation~~

~~Button:
Make a contribution
Change to:
Contribute~~

We will revisit the Learn sub pages later, so don’t worry about them too much for now.

~~The OCaml Community Page:
https://v3.ocaml.org/community 
Join our communities!
Change to:
Join Our Communities~~

~~Silicon Valley OCaml meetups
Change to:
Silicon Valley OCaml Meetups~~

~~Button
View opportunities
Change to:
View Opportunities~~

Industrial Users Page
https://v3.ocaml.org/industrial-users
Interested in learning more?
Change to:  Interested in Learning More?
**--CR: Not found on industrial_users.eml--**
**Also did search throughout repo, and I didn't find it anywhere but on the academic page**

~~Academic Users Page
https://v3.ocaml.org/academic-users 
Our influence
Change to: Our Influence 
Interested in learning more? 
Change to:  Interested in Learning More?~~


Success Stories page

~~Buttons:
Academic Users
Change to: In Academia~~
~~Industrial Users: 
Change to
In Industry~~


~~https://v3.ocaml.org/success-stories
What some of our users say about OCaml
Change to:
What Our Users Say About OCaml~~

~~Peta-byte scale web crawler
Change to:
Peta-byte Scale Web Crawler~~

~~Peta-byte scale web crawler
Change to:
Peta-byte Scale Web Crawler~~

~~Sensor analytics and automation platform for sustainable architecture
Change to:
Sensor Analytics & Automation Platform for Sustainable Architecture~~

~~Large scale trading system
Change to:
Large Scale Trading System~~

~~Books Page
https://v3.ocaml.org/books
OCaml from the very Beginning
Change to:
OCaml From the Very Beginning~~

~~Think OCaml: How to think like a Functional Programmer
Change to:
Think OCaml: How to Think Like a Functional Programmer~~

~~Governance Page
https://v3.ocaml.org/governance~~

~~Purpose - a document that represents reality
Change to:
Purpose - a Document That Represents Reality~~

~~Disambiguation - the meaning of [OCaml.org](http://ocaml.org/)
Change to:
Disambiguation - the Meaning of [OCaml.org](http://ocaml.org/)~~

~~Guiding principles of OCaml.org
Change to:
Guiding Principles of OCaml.org~~

~~Dispute resolution
Change to:
Dispute Resolution~~

~~Adoption of this document
Change to:
Adoption of This Document~~

~~Privacy Policy Page
https://v3.ocaml.org/privacy-policy~~

~~What we collect?
Change to:
Data collection~~

~~Changes and questions
Change to:
Changes & Questions~~

**Comment by christinerose** [comment]
Fixed title case in layout.eml. PR: https://github.com/ocaml/ocaml.org/pull/367
Changed "99 Problems" to "Exercises" in learn_layout.eml. PR: https://github.com/ocaml/ocaml.org/pull/368
Fixed title case in academic_users.eml. PR: https://github.com/ocaml/ocaml.org/pull/369
Fixed title case in community.eml. PR: https://github.com/ocaml/ocaml.org/pull/370
(Crossing them out in @joanmh123's original comment as I complete them)
(Also left notes of things I couldn't find: **--CR: note here--**)

**Comment by christinerose** [comment]
Fixed title case and some other line editing in industrial.eml. PR: https://github.com/ocaml/ocaml.org/pull/372
Line edits in learn.eml. PR: https://github.com/ocaml/ocaml.org/pull/373
Added serial comma to news.eml for consistency. PR: https://github.com/ocaml/ocaml.org/pull/374
Title case in not_found.eml. PR: https://github.com/ocaml/ocaml.org/pull/375

**Comment by christinerose** [comment]
Title case in package_overview.eml. PR: https://github.com/ocaml/ocaml.org/pull/376
Title case in package_toplevel.eml. PR: https://github.com/ocaml/ocaml.org/pull/377
Title case, grammar, and syntax in packages.eml. PR: https://github.com/ocaml/ocaml.org/pull/378
Capiltalise Opam in packages_search.eml. PR: https://github.com/ocaml/ocaml.org/pull/379

**Comment by christinerose** [comment]
Line edits for platform.eml. PR: https://github.com/ocaml/ocaml.org/pull/380
Changed "99 Problems" to "Exercises." PR: https://github.com/ocaml/ocaml.org/pull/381
Title case in tutorial.eml. PR: https://github.com/ocaml/ocaml.org/pull/382
Title case in up & running. PR: https://github.com/ocaml/ocaml.org/pull/383

**Comment by christinerose** [comment]
Line editing for governance.eml. PR: https://github.com/ocaml/ocaml.org/pull/384
Line editing for privacy_policy.eml. PR: https://github.com/ocaml/ocaml.org/pull/385
Title case in meetups.yml. PR: https://github.com/ocaml/ocaml.org/pull/386
Line editing (some) and title case for papers.yml. PR: https://github.com/ocaml/ocaml.org/pull/387

**Comment by christinerose** [comment]
Capitalised proper nouns in package names. PR: https://github.com/ocaml/ocaml.org/pull/388


I made a good dent in this today, but I can't find the following:
```
**Below not found on industrial_users.eml or success_story.eml**
Industrial Users Page
https://v3.ocaml.org/industrial-users
Interested in learning more?
Change to:  Interested in Learning More?

Peta-byte scale web crawler
Change to:
Peta-byte Scale Web Crawler

Peta-byte scale web crawler
Change to:
Peta-byte Scale Web Crawler

Sensor analytics and automation platform for sustainable architecture
Change to:
Sensor Analytics & Automation Platform for Sustainable Architecture

Large scale trading system
Change to:
Large Scale Trading System

**Following not on books.eml**
Books Page
https://v3.ocaml.org/books
OCaml from the very Beginning
Change to:
OCaml From the Very Beginning

Think OCaml: How to think like a Functional Programmer
Change to:
Think OCaml: How to Think Like a Functional Programmer
```

I'll look for more tomorrow

**Comment by christinerose** [comment]
Title case & monospace in videos.yml. PR: https://github.com/ocaml/ocaml.org/pull/393
Title case in tools.yml. PR: https://github.com/ocaml/ocaml.org/pull/395
Title case in jobs.yml. PR: https://github.com/ocaml/ocaml.org/pull/396

**Comment by christinerose** [comment]
I think I found where they were hidden! Those squares might be pulling from the separate documents. See if this fixes it. 
PR: https://github.com/ocaml/ocaml.org/pull/397

**Comment by christinerose** [comment]
Title case in the two mentioned book pages. PR: https://github.com/ocaml/ocaml.org/pull/398

```
Industrial Users Page
https://v3.ocaml.org/industrial-users
Interested in learning more?
Change to:  Interested in Learning More?
```
**Not found on industrial_users.eml**
**Also did search throughout repo, and I didn't find it anywhere but on the academic page**

I think I got the rest of them. Please let me know if you see more!

**Comment by tmattio** [comment]
Seems like all the inconsistencies have been addressed, so closing this for now. Thanks a ton, @joanmh123 @christinerose!
