### ISSUE TITLE
Create three columns on landing page

### ISSUE THREAD

**Issue by christinerose** [ocaml/ocaml.org#389]
Change the three (safe, build faster, work joyfully) sections to three columns near the top.

**Comment by joanmh123** [comment]
Here's the UX design and updated copy for section two of the home page, replacing the area "Be Safe, Build Faster, Work Joyfully" https://www.figma.com/file/eDDhmcsKsoe70zWRDLpXlX/Home-page-suggestions?node-id=81%3A881

**Comment by joanmh123** [comment]
Link to Figma file above

**Comment by joanmh123** [comment]
assigning to Thibaut to get it into production

**Comment by tmattio** [comment]
We're working on re-thinking the overall design and sections of the homepage, so closing this for now
