### ISSUE TITLE
Add tags to overview

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#39]
The current opam package registry displays the tags of the packages in the overview: https://opam.ocaml.org/packages/dream/

The V3 package registry should list them on the package overview package, between Install and Authors: https://v3.ocaml.org/p/dream/1.0.0~alpha2

They could be displayed with a badge, e.g.:

```html
<span class="inline-flex items-center px-2.5 py-0.5 rounded-md text-sm font-medium bg-gray-100 text-gray-800">
  Tag
</span>
```

**Comment by khansaUmatullah** [comment]
@tmattio can you please elaborate it for the sake of simplicity?

**Comment by tmattio** [comment]
@khansaUmatullah Just updated the description, thanks!

**Comment by JiaeK** [comment]
Hi, my development environment is all set. I would like to work on this issue.

**Comment by tmattio** [comment]
Hi @JiaeK, sure, it seems like a good issue to get started. I'll assign you.

**Comment by JiaeK** [comment]
Thanks, @tmattio. Just wanna confirm - so I need to fork [https://github.com/aantron/dream](url) in this case? And modify this [https://github.com/aantron/dream/blob/5f6b7f508193a1423acd91ee2c699857ca45fa29/docs/web/templates/index.html](url)?

**Comment by patricoferris** [comment]
Hi @JiaeK, thanks for helping out (another maintainer of v3 here) :))

You should only need to fork this repository to fix this issue. I believe we want to show the `tags` of the opam package metadata on the individual packages (*all of them,* not just dream, that was an example). I.e. these tags:

https://github.com/ocaml/v3.ocaml.org-server/blob/f9da1e68f6d57bc62eef3837f8f1d30ff6b89753/src/ocamlorg/lib/package.mli#L47 

Which the server pulls in for all packages from the opam-repository for example: https://github.com/ocaml/opam-repository/blob/a8e6a61ca4b6c45e8812cd438ac3faf4d0f5650b/packages/dream/dream.1.0.0~alpha2/opam#L4

And they should be rendered on the package overview page of the v3 site (attached is roughly where @tmattio was suggesting I think 😁 )

![tags](https://user-images.githubusercontent.com/20166594/137606291-587342a1-ad41-4551-9b15-3927b143b982.png)

I would suggest trying to find the HTML for this page, see how it is generated, where the `Ocamlorg.Package` module might be used which should start leading you in the direction to fixing this :))

**Comment by JiaeK** [comment]
Hi, @patricoferris ! Thanks for such a detailed direction. This happens to be my first contribution and I'm sitting here for the whole day trying to understand what you beautifully explained while shaking nervously, but can I check if I'm following the right way 🥲 ?   
I understand that where the tags should be rendered among the HTML, e.g. the HTML of [https://v3.ocaml.org/p/dream/1.0.0~alpha2](url), but I don't know how to link `; tags : string list ` to the HTML of it. Do I need to learn more about OCaml language or opam package metadata to understand `; tags : string list `?

**Comment by patricoferris** [comment]
Firstly, please don't feel any pressure whilst working on this issue. Asking questions when you are stuck is perfectly reasonable. We have no expectations, we just want you to learn some OCaml and start contributing to open-source code. We'll tend to answer in such a way that guides you to learning more rather than giving you a concrete set of instructions.

> but I don't know how to link ; tags : string list to the HTML of it

My suggestion to work this out is the following:
 - Other parts of the package metadata are being used for example the authors list or the license string.
 - This metadata is a record in OCaml and we use and access the fields as described [here](https://dev.realworldocaml.org/records.html).
 - Pairing these two bits of information you could search the files of this repository for code that accesses say the license field which is more than likely close to where you will need to add some more code to render the tags.

**Comment by JiaeK** [comment]
Thank you for your suggestion. I'll work on it right away :)

**Comment by JiaeK** [comment]
So I figured that some code for `let render ~readme ~license:_ package =` and some of HTML codes are needed from [src/ocamlorg_web/lib/templates/pages/package_template.eml](url). Do I need to put the additional codes for the special order inside of `let render ~readme ~license:_ package =` ? I guess it's object-oriented so this doesn't need a specific order.. 🤔 Correct me if I'm wrong, I'm really curious!
