### ISSUE TITLE
DOC: dune build not working

### ISSUE THREAD

**Issue by madhhuurrii** [ocaml/ocaml.org#392]
Hi there!
I have started learning Ocaml recently, was going through the official documentation for a headstart.
I noticed a problem while following this [tutorial](https://ocaml.org/learn/tutorials/up_and_running.html) i.e dune build throws an error when running. After a [quick check](https://stackoverflow.com/questions/71202746/ocaml-dune-build-error-after-running-dune-init-exec) I was able to figure out that the dune 3.0 doesn't include dune-project file which has to be manually done by the user while setting up.
It will be better if these steps can be included in the official docs as well.

**Comment by mooreryan** [comment]
For reference, there is a (merged) pull request https://github.com/ocaml/ocaml.org/pull/325 about this.

**Comment by madhhuurrii** [comment]
> For reference, there is a (merged) pull request #325 about this.

Hey, Thanks for the reference. yet the updated docs throws the error. Certainly after addling a `dune-project` file I was able to solve the error.

**Comment by cuihtlauac** [comment]
This issue seems to be resolved, I suggest we close it.
