### ISSUE TITLE
Add package publication date to overview, search results and package statistics

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#40]

**Comment by mndrix** [comment]
This may not be what @tmattio had in mind, but this is what I'd like to see:

* On the right hand side of each package overview page (like this one [for utop](https://v3.ocaml.org/p/utop/2.9.0)), between Tags and Authors, show "Published Dec 29, 2021"
* In the Version drop-down, show the date of each release (like "2.9.0 - Dec 29, 2021", "2.8.0 - Jun 18, 2021")

When I'm considering adding a dependency to my project, I find it helpful to know how regularly the package is being maintained.

**Comment by hannesm** [comment]
#229 is partially a duplicate of this issue.
