### ISSUE TITLE
Package search: explaining the results

### ISSUE THREAD

**Issue by art-w** [ocaml/ocaml.org#405]
My my this is so beautiful!.. I tried a few package searches but I didn't immediately understand all the results:

- Searching for [vg](https://v3.ocaml.org/packages/search?q=vg) yields a lot of results where it's not clear why they are related (it turns out that their author has an email `ivg@`). Perhaps the matches could be highlighted with `<mark>` for clarity?

- Searching for [json](https://v3.ocaml.org/packages/search?q=json), it's not clear why [plato](https://v3.ocaml.org/p/plato/1.1.2) is a match as "json" can't be found anywhere (but it is in the opam package long description)

**Comment by sabine** [comment]
I think this has been resolved.
