### ISSUE TITLE
Missing details on governance / about page.

### ISSUE THREAD

**Issue by tmcgilchrist** [ocaml/ocaml.org#416]
The old version of the website had a section about the `Governance of this website` and a list of maintainers. See https://ocaml.org/about.html#Governance-of-this-website 
Should there be an equivalent list of people on the new site?

The new website has `infrastructure@lists.ocaml.org` as a point of contact for ocaml.org infrastructure but there is no way to signup to the list (it seems to be in read-only mode) and the link is not prominent enough (should be highlighted or bold). 

The How to Contribute section on the old website is much clearer, the new website should link directly to https://github.com/ocaml/ocaml.org/blob/main/CONTRIBUTING.md

**Comment by samoht** [comment]
Yes we definitely need this on the new website.

**Comment by tmattio** [comment]
We have a governance page here: https://v3.ocaml.org/governance which details the governance of the site.

While I agree it's important to have a governance page on the site, I think the list of contributors and maintainers can remain on the repository?

**Comment by tmattio** [comment]
Closing for now, but feel free to re-open if you see anything missing from the link above.

**Comment by samoht** [comment]
Would be nice to at least link to the list of maintainers on the repository then. The goal is to make it easy for anyone to know who is maintaining the website or not but looking at that page.
