### ISSUE TITLE
Docs page of 'humor proof' is missing

### ISSUE THREAD

**Issue by JiaeK** [ocaml/ocaml.org#419]
As it has mentioned in #418, [humor proof](https://v3.ocaml.org/docs/humor_proof) docs page is missing. 

For instance, inside of https://v3.ocaml.org/docs/functional-programming, 
<br>

![humor_proof error](https://user-images.githubusercontent.com/78751231/162943089-76d5596e-eedf-4c43-b385-6a1f001b1411.png)

<br>

when you click the link, it should lead to something relevant to the [former version](https://ocaml.org/learn/tutorials/humor_proof.html) of its docs.

**Comment by tmattio** [comment]
Thanks for the report @JiaeK. This is fixed in #418
