### ISSUE TITLE
button to navigate to "standard library" takes me to a page that seems broken 

### ISSUE THREAD

**Issue by eriklovlie** [ocaml/ocaml.org#437]
I went to https://ocaml.org/ and scrolled almost to the bottom. There are two rows of large buttons, six in total. The one to the bottom left is called "Standard Library". Clicking that takes me here:

https://ocaml.org/p/ocaml-base-compiler/4.14.0/doc/index.html

That page only shows an "error log" so I suspect there is a problem somewhere. See attached screenshot
![Screenshot from 2022-04-29 14-33-59](https://user-images.githubusercontent.com/152405/165945198-19ae8154-b3e9-4c1d-bda1-2aadfc384799.png)
.

**Comment by tmattio** [comment]
Thanks for the report @eriklovlie!

**Comment by eriklovlie** [comment]
No worries. Site looks great :)
