### ISSUE TITLE
documentation of compiler+options

### ISSUE THREAD

**Issue by mobileink** [ocaml/ocaml.org#444]
I don't know if this is an OPAM issue or something for ocaml.org, but in any case it's hard to find info explaining what things like "4.14.0+options" means.  In fact I couldn't find anything here or on the opam website. All I could find was stuff like https://stackoverflow.com/questions/70665781/how-to-use-flambda-with-dune-in-ocaml

**Comment by tmattio** [comment]
This is now documented in https://ocaml.org/tools/compiler-release-cycle#what-does-an-ocaml-version-mean
