### ISSUE TITLE
`www` still serving v2 site

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/ocaml.org#450]
As mentioned by [Haudegen](https://discuss.ocaml.org/t/v3-ocaml-org-we-are-live/9747/13) on the OCaml Discuss the `www` subdomain still shows the old v2 site. I am not sure whether it should display the v3 site here or redirect to it but that doesn't seem quite right.

**Comment by tmattio** [comment]
Thanks for the report @Leonidas-from-XIV, this is fixed now!
