### ISSUE TITLE
RSS feed for OCaml Blog

### ISSUE THREAD

**Issue by mndrix** [ocaml/ocaml.org#453]
The [OCaml Blog](https://ocaml.org/blog) has some excellent content, however it appears not to publish an RSS feed of its own articles.  I searched the page for "rss" and "atom". I also examined the HTML looking for `<link rel="alternate" ...>`. If the blog has its own RSS feed, I couldn't find it.

Having an RSS or Atom feed that lists recent OCaml Blog articles, would make it easier for those using feed readers to follow the OCaml Blog.

**Comment by tmattio** [comment]
There's no RSS feed for the blog at the moment, but it could be implemented relatively easily I think. We could take example from Mirage's website which has a similar tech stack and provides an RSS feed: https://github.com/mirage/mirage-www/blob/master/lib/mirageio.ml#L73

**Comment by koonwen** [comment]
Hi! I'd like to work on this if nobody has started on it!

**Comment by tmattio** [comment]
Thanks @koonwen! I think @MirzaBabarBaig started working on it?

**Comment by tmattio** [comment]
@koonwen you can take over the issue if you want 🙂

**Comment by koonwen** [comment]
Okay thanks! I'll start working on it.

**Comment by tmattio** [comment]
Done in #524 and live at https://ocaml.org/feed.xml 🎉

**Comment by brabalan** [comment]
Thank you! I confirm it works with my tiny tool to populate the OCaml Weekly News.
