### ISSUE TITLE
Repeated code in the documentation

### ISSUE THREAD

**Issue by tianqizhao-louis** [ocaml/ocaml.org#457]
In the documentation of [language/If statements, loops, and recursions/mutually recursive functions](https://ocaml.org/docs/if-statements-and-loops#mutually-recursive-functions), it says "but there is a special syntax for defining a set of two or more mutually recursive functions", but the code block written below is the same as the code block above. It doesn't introduce any new special syntax. I assume it's a typo?

Code block of mutually recursive functions:

```ocaml
# let rec even n =
  match n with
  | 0 -> true
  | x -> odd (x - 1);;
Line 4, characters 10-13:
Error: Unbound value odd
```

Code block above:

```ocaml
# let rec even n =
  match n with
  | 0 -> true
  | x -> odd (x - 1);;
Line 4, characters 10-13:
Error: Unbound value odd
# let rec odd n =
  match n with
  | 0 -> false
  | x -> even (x - 1);;
Line 4, characters 10-14:
Error: Unbound value even
```

**Comment by tmattio** [comment]
I believe this has been fixed in #472.
