### ISSUE TITLE
A lot of pages redirect to v2.ocaml.org

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml.org#465]
I suspect this is not a name that is going to be stable in the future. Especially: 

https://ocaml.org/manual/

Yet people will gleefuly share and embed the redirected address in the www which will yield 404 in the long term. Not a very good idea.

**Comment by tmattio** [comment]
Thanks for the issue @dbuenzli!

> I suspect this is not a name that is going to be stable in the future.

I think it should, it's not much maintenance to keep it alive. In the long term, when we don't have any redirections to it, I think it'll still be a nice feature that people can explore the different versions of the website. (we should have `v1.ocaml.org`!)

> Yet people will gleefuly share and embed the redirected address in the www which will yield 404 in the long term.

To be safe, perhaps a better behavior would be to serve the manual directly from https://ocaml.org/manual/.

**Comment by dbuenzli** [comment]
> I think it'll still be a nice feature that people can explore the different versions of the website.

Certainly a good idea to confuse people and make them browse outdated information without noticing. Historians will be perfectly happy with a well indexed https://archive.org dataset. 

> To be safe, perhaps a better behavior would be to serve the manual directly from https://ocaml.org/manual/.

For sure. For now this looks one of these corporate websites which are unable to serve clean url and redirect you ten times before getting to the actual page (you don't) want.

URLs are a user interfaces, and the one that is provided now is a confusing one.

**Comment by cuihtlauac** [comment]
Related: https://github.com/ocaml/ocaml.org/issues/664

**Comment by shonfeder** [comment]
A newer user has been bitten my stale docs served on v2.ocaml.org: https://github.com/ocaml/ocaml.org/pull/325#issuecomment-1809403112

Anyone know what would be required to do one of the following:

1. Clearly mark these pages as deprecated
2. Update them so they do not have bad information
3. Redirect them to the equivalent current page, and remove the old content

**Comment by shonfeder** [comment]
Hi again. I ended up on another v2 page looking for information on the ocaml logo:

https://v2.ocaml.org/docs/logos.html

It was the second search result that came up for me for `ocaml logo`, and it is full of broken links.

I think it would really help with maintaining our information ecology if we could find a way to take these pages down and/or redirect them to current and functioning pages.

**Comment by sabine** [comment]
@shonfeder we're currently moving the manual to ocaml.org. The logo page has been moved to https://ocaml.org/logo already.

After the OCaml compiler manual is moved to ocaml.org, we will prevent indexing of v2.ocaml.org, so that people will no longer arrive on it coming from search engines.

**Comment by cuihtlauac** [comment]
Fixed by #2150
