### ISSUE TITLE
Playground should provide a feedback when it runs

### ISSUE THREAD

**Issue by Khady** [ocaml/ocaml.org#474]
I was giving a try to https://ocaml.org/play today. And ended up hitting the `run` button many times with the hope of something happening. My code didn't have side effect, so I couldn't see if anything was really happening. I later realized that even on bad code there's no feedback. For example if I change the example to add a typo and press the `run` button, nothing happens

```ocaml
type ('a, 'b) res = Ok of 'a | Err of 'b

let pp_res = function
  | Ok _ -> print_endlin "OK!" (* should yell a me for bad print_endlin *)
  | Err _ -> print_endline "Error!!"

let () = pp_res (Ok 10)
```

**Comment by patricoferris** [comment]
With the integration of Merlin and the changes in #670 I think this should be much better now.

![Image](https://user-images.githubusercontent.com/20166594/205490317-d3c89391-c366-4b25-a0a3-99ec8c7eee40.png)

**Comment by cuihtlauac** [comment]
Fixed by https://github.com/ocaml/ocaml.org/pull/670
