### ISSUE TITLE
Expired certificate on https://inbox.ocaml.org/

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml.org#484]
Everything is in the title.

**Comment by tmattio** [comment]
Thanks @dbuenzli, the maintainers of the infrastructure are aware of the issue and trying to get access to the server to address it. cc @mtelvers

**Comment by dbuenzli** [comment]
I'm not sure why this was closed. I can't access `inbox.ocaml.org`. This basically means we no longer have any reliable place to access the `caml-list` archives (e.g. gmane died a long time ago) which is a bit of ocaml history that is worth preserving in my opinion.

**Comment by sabine** [comment]
@dbuenzli there is a corresponding issue at https://github.com/ocaml/infrastructure/issues/15 that I should have mentioned.

**Comment by dbuenzli** [comment]
Ah thanks !
