### ISSUE TITLE
Add a tooltip for package documentation status

### ISSUE THREAD

**Issue by reynir** [ocaml/ocaml.org#494]
I think it could help with a tooltip or some text to explain what the coloured dots mean.

https://github.com/ocaml/ocaml.org/blob/2f673ed2183c9f948b331f126dcf39bf52d2fa55/src/ocamlorg_frontend/layouts/package_layout.eml#L60-L70

**Comment by sabine** [comment]
@reynir thank you for reporting, it helps us see what the most irritating issues are.

In the situation where we can't provide docs for some reason, I made the "Documentation" tab inactive and added a tooltip to explain the problem (#580).
