### ISSUE TITLE
HTML in Preformatted code is rendered in docs page

### ISSUE THREAD

**Issue by avestura** [ocaml/ocaml.org#496]
Even though `<!-- $MDX skip -->` exists on top of the pre-formatted text in documentation, the HTML is being rendered in the output.

For example: 

https://github.com/ocaml/ocaml.org/blob/main/data/tutorials/lg_01_functional_programming.md?plain=1#L440-L453

## This is how the markdown should look like (Github's readme screenshot):

![image](https://user-images.githubusercontent.com/9091958/174071572-4ea1676e-f167-4457-a42c-0dee7fd4020c.png)

## This is what it looks like now (ocaml.org/docs screenshot):

![image](https://user-images.githubusercontent.com/9091958/174071532-875b7455-c8ff-42a9-9ebd-aa1f0b69e025.png)

**Comment by tmattio** [comment]
Omd should probably escape the special characters when transforming the document to HTML. cc @tatchi

**Comment by cuihtlauac** [comment]
Direct link to faulty rendering: https://ocaml.org/docs/functional-programming#aliases-for-function-names-and-arguments

**Comment by cuihtlauac** [comment]
[Hilite](https://github.com/patricoferris/hilite) is the faulty component.

Removing highlighting removes colors and faulty behaviour 

```diff
diff --git a/tool/ood-gen/lib/tutorial.ml b/tool/ood-gen/lib/tutorial.ml
index a1a4a77..fe43a66 100644
--- a/tool/ood-gen/lib/tutorial.ml
+++ b/tool/ood-gen/lib/tutorial.ml
@@ -81,7 +81,7 @@ let all () =
         category = metadata.category;
         toc_html = Omd.to_html (Omd.toc ~depth:4 toc_doc);
         body_md = body;
-        body_html = Omd.to_html (Hilite.Md.transform omd);
+        body_html = Omd.to_html omd;
       })
     "tutorials/*.md"
```
w/ hilite:
![Screenshot_2022-11-24_11-20-31](https://user-images.githubusercontent.com/1917592/203759787-30a3f446-ed63-429a-95dd-8e809c2c3b90.png)
w/o hilite:
![Screenshot_2022-11-24_11-21-01](https://user-images.githubusercontent.com/1917592/203759772-ef0ef921-191d-4693-9cbc-8f1428a1d15b.png)

**Comment by cuihtlauac** [comment]
PR in Hilite: https://github.com/patricoferris/hilite/pull/5
