### ISSUE TITLE
\\n should be \n

### ISSUE THREAD

**Issue by Gu-Hongyan** [ocaml/ocaml.org#497]
Webpage: [https://ocaml.org/docs/cli-arguments](url)

Within this sentence: 

`Printf.printf "[%i] %s\\n" i Sys.argv.(i)`

stdout:

`[0] argv.ml\n[1] arg1\n[2] arg2\n[3] arg3\n%`

Maybe `\\n` should be `\n`.

Mac 12.4    opam 2.1.2

**Comment by tmattio** [comment]
Thanks for the report @youngerswift. Feel free to open a PR with the fix 🙂

**Comment by youngerswift** [comment]
@tmattio  Thanks a lot.  ^_^ However, the md source code is right. [https://github.com/caml/ocaml.org/blob/main/data/tutorials/tt_01_command_line_arguments.md](url)


<img width="763" alt="截屏2022-06-17 17 10 46" src="https://user-images.githubusercontent.com/17177219/174267595-5d010d16-57da-4e73-829f-07b22226f868.png">

**Comment by tmattio** [comment]
Indeed! So I'm guessing there's a bug somewhere when we transform the markdown to HTML: https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/tutorial.ml#L84

Either in omd or hilite. cc @tatchi

**Comment by youngerswift** [comment]
I think you are right ! 👍👍

**Comment by tatchi** [comment]
Hey,

I dig into it, and the issue is not coming from `omd` nor from `hilite`. That's due to the `Pp.string` function that does some `\` replacements:

```ocaml
let string ppf v =
  Fmt.pf ppf "{js|%s|js}" (Str.global_replace (Str.regexp "\\\\") "\\\\\\\\" v)
```

I'm not sure how we should best handle that? cc @tmattio

**Comment by tmattio** [comment]
Ah ok! I'll have a look at it again, thanks for checking @tatchi! 🙂
