### ISSUE TITLE
Document update using dune as primary build system?

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml.org#506]
https://ocaml.org/docs/modules
The document is still base on ocamlopt , I guess it a bit out of sync modern OCaml world.
Now we using dune for every single , small or large project of OCaml.
So the question is , why not just teach user using dune as primary build system for learning OCaml.

I tried to learn OCaml to build with ocamlopt, but it hard to manage a real size OCaml project.
Dune looks a real good tools , just like maven to java, cmake to cpp/c, cargo to rust.
So please rewrite document, base on dune build tools.

**Comment by ghost** [comment]
Ref: https://github.com/ocaml/ocaml/issues/11363

**Comment by ghost** [comment]
For a better document explain OCaml coding right and correct, i suggest CS3110 book.
https://cs3110.github.io/textbook/cover.html

It show write OCaml with Dune build system as well. 
How smart they are.

**Comment by tmattio** [comment]
Thanks for the report @cnmade, that sounds sensible, you're welcome to send a PR to improve the documentation with your suggestions 🙂
