### ISSUE TITLE
'comment-delim' items are intended to be hidden

### ISSUE THREAD

**Issue by jonludlam** [ocaml/ocaml.org#53]
see e.g. https://ocamlorg.herokuapp.com/p/tezos-base/8.0/doc/Tezos_base/Block_header/index.html#type-shell_header - specifically the `(*` and `*)` around the documentation of the record fields.

The idea is that you can cut-n-paste the record definitions and get valid code, but that they don't actually appear on-screen.

**Comment by tmattio** [comment]
Fixed in #130

**Comment by tmattio** [comment]
Reopening as the problem is fixed, but this introduces some regressions for long record fields / types. A proposed solution is to set a min-width and still wrap the record fields. cc @panglesd

**Comment by tmattio** [comment]
Closing again as the regression has been fixed in #142
