### ISSUE TITLE
Include blocks are not visibly demarcated.

### ISSUE THREAD

**Issue by jonludlam** [ocaml/ocaml.org#54]
Odoc usually shows a border on the right to show which sections come from included signatures. See the right-hand side of the include here:

<img width="789" alt="Screenshot 2021-07-29 at 11 28 34" src="https://user-images.githubusercontent.com/210963/127476615-43dbbdf9-22e5-4893-8893-46ffb7809a33.png">

and the bottom of the included section here:
<img width="782" alt="Screenshot 2021-07-29 at 11 29 29" src="https://user-images.githubusercontent.com/210963/127476770-32572c15-b77c-43ff-a021-451bb550f7fd.png">

**Comment by JiaeK** [comment]
Hi, can I work on this issue? And can I get some details?

**Comment by jonludlam** [comment]
Sure. The issue is that the CSS used for v3.ocaml.org comes partly from tailwind's `typography` plugin with some [extra rules](https://github.com/ocaml/v3.ocaml.org-server/blob/main/asset/doc.css) - and so is missing some of the rules declared in [odoc's css](https://github.com/ocaml/odoc/blob/master/src/odoc/etc/odoc.css). We need to port the rules relating to `include` blocks into v3's CSS file.
