### ISSUE TITLE
inbox.ocaml.org down?

### ISSUE THREAD

**Issue by leahneukirchen** [ocaml/ocaml.org#550]
Hi,

I'm unable to connect to https://inbox.ocaml.org/ since August 1st, is the service still up?

**Comment by tmattio** [comment]
@tmcgilchrist is this intentional?

**Comment by avsm** [comment]
@leahneukirchen sorry about this -- we're working on bringing it back up asap. If you need the archives in the meanwhile, there's a snapshot up to 2018 in https://github.com/nojb/caml-list.

**Comment by leahneukirchen** [comment]
I run a mirror at https://inbox.vuxu.org/caml-list/ anyway. I hope the missing mails are backfilled. :)

**Comment by sabine** [comment]
Closing this because this issue is old and does not relate to the website ocaml.org.

If necessary, this can be reopened at https://github.com/ocaml/infrastructure/
