### ISSUE TITLE
Missing documentation 

### ISSUE THREAD

**Issue by jfeser** [ocaml/ocaml.org#558]
Documentation on package pages seems to be missing. For example, https://ocaml.org/p/core_kernel/v0.14.0/doc/index.html.

**Comment by tlh24** [comment]
In the meantime, you can look at the older documentation here, e.g. https://ocaml.janestreet.com/ocaml-core/v0.14/doc/core/index.html

**Comment by tmattio** [comment]
The issue has been resolved, sorry for the inconvenience!
