### ISSUE TITLE
Documentation for (most/lots of) packages are 404

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocaml.org#560]
https://ocaml.org/p/base/v0.15.1~5.0preview/doc/index.html shows a 404 page with a link to open an issue.
https://ocaml.org/p/cmdliner/1.1.1/doc/index.html
https://ocaml.org/p/odoc/2.1.1/doc/index.html
https://ocaml.org/p/re/1.10.4/doc/index.html
...

Not sure what happened, there used to be some documentation there for at least some of these packages, but I struggle to find a single package that is not a 404 at the moment, which seems to indicate something going wrong with all packages' docs?

**Comment by voodoos** [comment]
Duplicate of https://github.com/ocaml/ocaml.org/issues/558

There is definitely an issue, not sure who we could ping, maybe @tmattio, @TheLortex ?

**Comment by jonludlam** [comment]
We're having a look - thanks!

**Comment by dangdennis** [comment]
It's back now! Thanks. What was the issue?

**Comment by tmattio** [comment]
The issue seems to be resolved, thanks!
I'll close the issue, but feel free to give some details on what went wrong @jonludlam
