### ISSUE TITLE
docs generation: error with mld files in title

### ISSUE THREAD

**Issue by avsm** [ocaml/ocaml.org#583]
See the monorepo docs: https://ocaml.org/p/opam-monorepo/0.3.2/doc/lock.html

The "module lock.html" is an incorrect title for the page.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/53164/192140659-349b14bd-1f8a-42db-91f2-564e89981091.png">

**Comment by sabine** [comment]
Thanks for reporting, that's indeed a confusing sight.

**Comment by sabine** [comment]
Interestingly, for this particular package, the docs also seem to be missing the first section:
https://github.com/tarides/opam-monorepo/blob/feeb325c9c8d560c6b92cbde62b6a9c5f20ed032/doc/lock.mld

And it's hard to find the other files in the docs folder as they are only linked inside the content of the index page. :thinking: But this is a topic for the sidebar rework.
