### ISSUE TITLE
Documentation generation failed for temporary reasons

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/ocaml.org#588]
I was looking to check out the [documentation of sexplib](https://v3.ocaml.org/p/sexplib/v0.15.1/doc/index.html) but the build failed because of issues resolving the packages needed to build the documentation:

```
...
E: Failed to fetch http://deb.debian.org/debian/pool/main/r/rustc/rust-gdb_1.48.0%2bdfsg1-2_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/shared-mime-info/shared-mime-info_2.0-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/x/xdg-user-dirs/xdg-user-dirs_0.17-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
OS package installation failed
```

It seems like a temporary issue with the Debian mirror system, so it would be good to have a way to detect this and attempt to re-run it at a later point in time.

cc @TheLortex

**Comment by sabine** [comment]
Closing in favor of upstream https://github.com/ocurrent/ocaml-docs-ci/issues/119.
