### ISSUE TITLE
Github flavored markdown is not supported

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#59]
This breaks the tables, checklist, etc.

E.g. https://ocamlorg.herokuapp.com/p/ppx_deriving_yaml/0.1.0

![image](https://user-images.githubusercontent.com/6162008/127536086-d3699a50-72d9-429b-9f82-d4190107f775.png)

Related to #35

**Comment by gadmm** [comment]
Also, some links are not converted to links, while other links have a weird line break: compare https://v3.ocaml.org/p/memprof-limits/0.2.0 with https://gitlab.com/gadmm/memprof-limits/ (technically gitlab markdown, but I guess those features are somehow standard).

Another issue with sharing the package description with the one made for the repository / source package is that relative links are broken (see for instance the "statistical analysis" link). (Well this page deserves to be in the documentation, but odoc does not handle images well.)

(The previous website used the opam file description which worked better in my case, but anyway I will adapt once things work well-enough and get settled.)

**Comment by cuihtlauac** [comment]
Stalled: waiting an release of OMD including PR#292

**Comment by shonfeder** [comment]
See https://github.com/ocaml/opam-repository/pull/22654

Thanks for the heads up on your need there.

**Comment by tmattio** [comment]
This was fixed by the latest release of omd, thanks a ton @shonfeder and @bobatkey!

See https://ocaml.org/p/ppx_deriving_yaml/0.1.0/README.md.html
