### ISSUE TITLE
Information about OCaml 5

### ISSUE THREAD

**Issue by kayceesrk** [ocaml/ocaml.org#590]
Currently ocaml.org does not talk about the next major release of the OCaml programming language, OCaml 5. Given that alpha releases are out, it may be useful to have it featured prominently so as to encourage early adopters to try it out. 

We may consider including a "Try OCaml 5.0" banner that links to the current, up to date installation instructions. 

This was brought up originally in https://discuss.ocaml.org/t/multicore-with-opam-instructions/10548/7

**Comment by avsm** [comment]
The 5.0 beta is the best time to put this on ocaml.org; the alpha contains a number of breaking changes.

@kayceesrk would it be possible to correct the existing materials to point to the right instructions; e.g.
- https://github.com/ocaml-multicore/parallel-programming-in-multicore-ocaml (refers to 5.0.0+trunk)
- ttps://github.com/ocaml-multicore/multicore-opam is now deprecated so should push a README note to not use it (and perhaps add the latest instructions)

I think some of the confusion is that older information on those places as well.

**Comment by Octachron** [comment]
Like I said in the discuss thread, I have a slight preference for waiting for the beta releases before encouraging more widely people to try OCaml 5. However, the first beta releases are quite close and it definitively make sense to start working now on the ocaml.org announce for the beta.
