### ISSUE TITLE
[Design Feedback] Changes on font weight and spacing for flyout menus

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#61]
v3:

![image](https://user-images.githubusercontent.com/6162008/127654148-55c4cdb0-aad9-4a71-8427-66762c7aea10.png)

v3-server:

![image](https://user-images.githubusercontent.com/6162008/127654117-eebf04b4-b081-4e00-96b8-a7c385162ee9.png)

**Comment by dangdennis** [comment]
What’s the desired approach here? Is it a choice between the two weights and spacing? 

1. It’s easier on the eyes with the lighter weight (server)
2. Menu spacing feels better because the wider width makes my eyes scan a little less.
3. The principles button of the above looks more correct.
