### ISSUE TITLE
Docs: Headings should be formatted as links (so they can be referenced easily)

### ISSUE THREAD

**Issue by d4h0** [ocaml/ocaml.org#618]
Hi,

On https://ocaml.org/docs/up-and-running (and I assume similar pages) the headings are not HTML links – although they seem to have all `id` attributes assigned (which make them linkable).

For example, currently there is the `Installing OCaml` heading, which has an `id` attribute with the value `installing-ocaml`, which can be linked via `https://ocaml.org/docs/up-and-running#installing-ocaml`.

If someone wants to send someone a link to that heading, they have to look at the HTML code to get the ID, and then create the link manually, which is not user-friendly.

Personally, I often bookmark links to specific sections to find them faster.

**Comment by cuihtlauac** [comment]
Hi, thanks for reporting this.

You write:
> If [one needs a] link to that heading, they have to look at the HTML code to get the ID, and then create the link manually, which is not user-friendly.

However, the "ON THIS PAGE" section has URI fragments links pointing to the headers such as:
```
https://ocaml.org/docs/up-and-running#installing-ocaml
```
Isn't it what you are looking for?

Am I correct to assume you would also like to have those links available in the main text too? In the Android API reference, there is a button at the side of the heading text allowing to copy the URI fragment link, see for instance:
```
https://developer.android.com/reference/android/app/Activity#configuration-changes
```
Is this the kind of user experience you have in mind?

**Comment by d4h0** [comment]
> However, the "ON THIS PAGE" section has URI fragments links pointing to the headers such as:
> Isn't it what you are looking for?

Yes, that would work, too... :)

However, on my 14-inch display at a zoom level of 100%, this section is not visible... ;)

Even after you mentioned the "ON THIS PAGE" section, I had to look at the source code to find it.

The lack of a TOC was actually another issue I had with the documentation :)

One potential solution would be to move the TOC to the left side menu, similar to what ReScript does:

https://rescript-lang.org/docs/manual/latest/introduction

Or there could be some kind of expandable section that is indicated via a button (which then would also work on mobile).

I think, linking the headings would still be valuable, and shouldn't be too difficult to implement. On smartphones, for example, it would be easier to get a URL to a section this way, I believe.

> Am I correct to assume you would also like to have those links available in the main text too?

Yes, I'd prefer if the whole heading is a link, not just a tiny button at the side that is visible on hover. I think, this is more obvious, is less like to lead to problems on mobile, and even should be a bit better for SEO (search engine optimization = getting more visitors).

**Comment by cuihtlauac** [comment]
Now I understand your point w.r.t. heading links, "ON THIS PAGE" and ToC. It's all related. I believe you have a valid point; thanks again.

> > Am I correct to assume you would also like to have those links available in the main text too?

> Yes, I'd prefer if the whole heading is a link, not just a tiny button at the side that is visible on hover. I think, this is more obvious, is less like to lead to problems on mobile, and even should be a bit better for SEO (search engine optimization = getting more visitors).

In rescript and in Android, I see the heading link as a button at the side. I must admit I haven't ever seen the design you would like to experience. Can you share an example of it?

I'm considering splitting the matter into two parts.

1. Merging "ON THIS PAGE" inside the navmap toc to better support the rendering experience on small screens. This is a bug.
1. Have links to heading available inside the text, either next to the heading or inside itself). This is a feature request

**Comment by d4h0** [comment]
> In rescript and in Android, I see the heading link as a button at the side. I must admit I haven't ever seen the design you would like to experience. Can you share an example of it?

The Rust docs would be such an example:

https://doc.rust-lang.org/std/

Rust has a strong focus on user experience, so getting inspiration from there is probably not the worst thing someone could do... ;)

> I'm considering splitting the matter into two parts.

Yes, that would make sense.

**Comment by cuihtlauac** [comment]
Replaced by the following issues:
1. https://github.com/ocaml/ocaml.org/issues/619
2. https://github.com/ocaml/ocaml.org/issues/620
