### ISSUE TITLE
Migrate "ON THIS PAGE" inside the ToC navmap

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#619]
It makes more sense to have all the navigation information in one single place.

Additionally, on small screens, the "IN THIS PAGE" section is not visible.

> > However, the "ON THIS PAGE" section has URI fragments links pointing to the headers such as:
Isn't it what you are looking for?
>
> Yes, that would work, too... :)
>
> However, on my 14-inch display at a zoom level of 100%, this section is not visible... ;)
>
>Even after you mentioned the "ON THIS PAGE" section, I had to look at the source code to find it.
>
>The lack of a TOC was actually another issue I had with the documentation :)
>
>One potential solution would be to move the TOC to the left side menu, similar to what ReScript does:
>
>https://rescript-lang.org/docs/manual/latest/introduction
>
>Or there could be some kind of expandable section that is indicated via a button (which then would also work on mobile).

Thanks to @d4h0 for initially reporting this on https://github.com/ocaml/ocaml.org/issues/618. This issue deals with the first half of it.

**Comment by tmattio** [comment]
I think this is done, right? cc @sabine
