### ISSUE TITLE
Usability problem in documentation: Side menu position is reset when selecting a module.

### ISSUE THREAD

**Issue by MdeLv** [ocaml/ocaml.org#623]
For example, when using [documentation for ocaml-compiler 4.07.1](https://ocaml.org/p/ocaml-base-compiler/4.07.1/) :
You select Library ocamlcommon, then module Env (on left side/"Module" to develop not on right sode/"Env" that would jump to module Env's signature), then you select its module PathMap.

Module Env.PathMap signature is displayed as expected, but the vertical position of the side menu is immediately reset (IN THIS PACKAGE ... library bigarray ...). This behaviour is really not usable and that makes navigation exhausting.

This is a pure GUI issue. The selected position of the side menu MUST be managed/stored.
New comers will be sensitive to this boring usability problem...

I'm not aware about how to fix that for the moment because I didn't develop this website and didn't look at its code.
So let's discuss and see if you can fix that simply or if I can help fixing that.

**Comment by cuihtlauac** [comment]
Hi @MdeLv, thanks for reporting this. You're right, this is painful. We need to sort this out.

**Comment by sabine** [comment]
@MdeLv we currently have a patch on https://staging.ocaml.org which slightly reduces the problem (by hiding the other libraries and rendering a more compact view of the tree). This is work in progress that can change any time.

The ocaml compiler has a lot of modules in some of its libraries and I agree, it's quite painful to see so many items in a tree view. Definitely open to ideas how to better display the module view. Feel free to link example sites that solves this nicely or add ideas/sketches. Improving the package docs browser is a priority.

**Comment by cuihtlauac** [comment]
Tutorials are also affected by this problem.
