### ISSUE TITLE
Broken internal #initialising-opam anchor

### ISSUE THREAD

**Issue by jmid** [ocaml/ocaml.org#635]
I was just visiting https://ocaml.org/docs/up-and-running

When I was here https://ocaml.org/docs/up-and-running#installation-for-unix
I read `After having installed opam, you will need to initialise it, see below.` and clicked [see below].
It points to `#initialising-opam` (dead) and should instead point to `#initialising-opam-on-unix` I think.

**Comment by cuihtlauac** [comment]
Thanks @jmid. You're right. Fix: https://github.com/ocaml/ocaml.org/pull/636
