### ISSUE TITLE
[Design Feedback] Package search page

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#64]
Page: https://v3.ocaml.org/packages/search?q=dream

![image](https://user-images.githubusercontent.com/6162008/127654882-78baf50c-3ac1-4d3d-917c-40bf8d3c1086.png)

**Comment by dangdennis** [comment]
the icon is slightly misaligned in mobile view, iPhone 12 Pro Max.

![E44B89EC-48A4-4DAA-87FC-B8212B5DF00E](https://user-images.githubusercontent.com/22418429/131292923-dd118517-6f62-490f-8df3-c51e53521984.png)

Can I make a PR fix for this?

**Comment by tmattio** [comment]
@dangdennis Thanks for the report, sure, a PR for this would be more than welcome 🙂

**Comment by dangdennis** [comment]
> @dangdennis Thanks for the report, sure, a PR for this would be more than welcome 🙂

Hi @tmattio I've become too busy to help in the meantime. Please excuse me this time 😞 

I'm still interested in helping as soon as I can.
