### ISSUE TITLE
[Design Feedback] Package overview page

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#65]
Page: https://v3.ocaml.org/p/dream/1.0.0~alpha2

![image](https://user-images.githubusercontent.com/6162008/127654974-2a476bb8-41d3-4884-9aec-90353ddf8a7a.png)

**Comment by gadmm** [comment]
I find the green dot over Documentation weird: it makes me think of a notification "there's something new under this tab" but it does not disappear when you click it. This is very distracting.

**Comment by tmattio** [comment]
Thanks @gadmm! As you may know, the dot indicates that the documentation is available for this package. It is not always the case, as some packages documentation fail to generate (e.g. https://v3.ocaml.org/p/dream/1.0.0~alpha1/doc/index.html)

Do you have a suggestion on a better way to indicate to the user whether the doc is available, not available, or failed to generate?

**Comment by gadmm** [comment]
I am not an UX designer; when such questions arose on an open-source program I was contributing to, we would take inspiration from the the various platform HIGs, or copy what already existed, no need to reinvent the wheel. You have examples on this very website, see e.g. the iconography for the build status of PRs in the PR page, or that of the success status of tests at the bottom of PRs.

**Comment by ulugbekna** [comment]
1. I agree about confusing green dot, I almost filed a question to ask about it.
2. It would be nice to show when the version of the package was published (I use it for example to see whether the package is maintained, but I guess that's a generally useful thing to show)
