### ISSUE TITLE
[Design Feedback] Package documentation page

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#66]
Page: https://v3.ocaml.org/p/dream/1.0.0~alpha2/doc/Dream/index.html

![image](https://user-images.githubusercontent.com/6162008/127655048-9f18e888-e963-488d-bf81-794089686b58.png)

**Comment by ulugbekna** [comment]
Cool work!

A couple of nits: 

- 1) the scroll seems unnecessary here; 2) "Module" being capitalized "conflicts" with the module name IMHO -- it could be slightly easier on eyes if it weren't capitalized or had less opacity or were gray-ish.
![image](https://user-images.githubusercontent.com/16353531/127680195-78675847-7dee-4c1e-9b56-f59de77d1b93.png)

- I think it would be more readable if the main text's "box" was in the center and the "contents" took less space (cf rescript's manual)
![image](https://user-images.githubusercontent.com/16353531/127680462-a935271b-0e5b-43a3-80ff-2882e8423bc6.png)

![image](https://user-images.githubusercontent.com/16353531/127680416-82c5f74e-c130-4376-b93b-95150b4059cc.png)

- Version of the package could be right next to the name of the package? It seems like an important thing that one almost always needs to check before proceeding with reading, but the version currently is across the whole page. 

![image](https://user-images.githubusercontent.com/16353531/127680610-ea29f190-8c49-4833-91e9-e43dd462bda0.png)
![image](https://user-images.githubusercontent.com/16353531/127680632-c5e2cb4b-5ae3-49e6-ad12-27206edf09af.png)

**Comment by gadmm** [comment]
I miss the code highlighting.

**Comment by gadmm** [comment]
Comparison of https://guillaume.munch.name/software/ocaml/memprof-limits/ and https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/index.html:
- Some documentation pages are missing; to me this is a critical issue. (See for instance "A guide to recover from interrupts" which should be a link; it does not even show any error visually although the css class is `xref-unresolved`.)
- Inter-page links give weird English; compare for instance "_Global memory limits_ let you bound..." with "_Memprof_limits:global_memory_limits_ let you bound...". I understand the need to disambiguate which page is being pointed to, but this could be done while remaining in English, for instance "_Global memory limits (`Memprof_limits`)_ let you bound...".

**Comment by gadmm** [comment]
Is there any issue tracking the lack of code colouring?

**Comment by tmattio** [comment]
There is now: https://github.com/ocaml/v3.ocaml.org-server/issues/99 🙂
