### ISSUE TITLE
Pull-in voodoo and the ocaml.org pipeline in the repository

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#669]

**Comment by cuihtlauac** [comment]
Do mean making:

* https://github.com/ocaml-doc/voodoo
* https://github.com/ocurrent/ocaml-docs-ci

Part of https://github.com/ocaml/ocaml.org? and then archive them? Like it was once done for ocaml/ood? Couldn't another option be to have them owned by the ocaml/ocaml.org **team** (in the governance sense)?

**Comment by tmattio** [comment]
Not entirely sure about the ocaml-docs-ci pipeline, but I think at least voodoo should live in the ocaml.org repository.
