### ISSUE TITLE
Remove opam pins

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#678]
We use opam pins for some dependencies:

- esbuild
- tailwindcss
- code-mirror
- merlin-js
- js_top_worker-rpc
- js_top_worker
- js_top_worker-client

cc @jonludlam @patricoferris @voodoos do you think we could cut releases of these on the opam repository?

**Comment by voodoos** [comment]
`merlin-js` needs some cleanup and documentation before the first release, I will try to do it but that's not a priority at the moment :-)

**Comment by sabine** [comment]
Issue doesn't seem to be progressing and also not important nor urgent, so closing.
