### ISSUE TITLE
Ocamlformat version discrepancy

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#689]
PR https://github.com/ocaml/ocaml.org/pull/660 has allowed upgrading many opam packages of the ocaml.org switch. However, this has upgraded ocamlformat (to 0.24.1 at the time of writing) while `.ocamlformat` requires 0.21.0. The discrepancy has to be resolved, either my stalling ocamlformat in the dependencies or updating `.ocamlformat`. Maybe we should do both.

**Comment by tmattio** [comment]
It's a nice opportunity to advertise https://github.com/tarides/ocaml-platform-installer :grin:
If you install the Platform tools with it, their dependencies won't conflict with your project's dependencies. It will also read the version in `.ocamlformat` to install the correct version of the tool.

But regardless, it's a good idea to upgrade to the latest version!
