### ISSUE TITLE
Import Platform announcements from Discuss

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#691]
Including previous compiler release announcements, and announcements for the Platform tools (Dune, Merlin, odoc, etc.).

Related to this, we should probably archive https://github.com/ocaml/platform-blog since we've imported it here and the blog has a section for the announcement.

cc @dra27

**Comment by cuihtlauac** [comment]
Isn't https://opam.ocaml.org/blog already down?

**Comment by tmattio** [comment]
Not from what I can see: https://opam.ocaml.org/blog/opam-2-1-3/

**Comment by cuihtlauac** [comment]
Ok, that's creepy. Let's assume it was a temporary network failure.

**Comment by tmattio** [comment]
I mean, the redirection doesn't work, the URL you had redirects to https://opam.ocaml.org/blog/blog/opam-2-1-3/, but navigating to the blog from the opam website's navbar still works

**Comment by sabine** [comment]
Resolved by https://github.com/ocaml/ocaml.org/pull/1109
