### ISSUE TITLE
Rendering discrepancies and CSS caching

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#704]
Here are two screenshots of the community page, one from a localhost run, one from the online run.

![Screenshot_2022-12-13_15-59-02](https://user-images.githubusercontent.com/1917592/207367946-210b8b4e-0390-4600-9593-49abee9d1587.png)
![Screenshot_2022-12-13_15-58-30](https://user-images.githubusercontent.com/1917592/207367951-72b7d817-8791-490e-becc-6039f71f4306.png)

Discussions and tests with @tmattio showed that forcefully invalidating the cache for `main.css` resolved the issue. This should be automatic.

**Comment by sabine** [comment]
Probably the simplest efficient way to ensure that CSS updates always reach the user is to add a hash of the content to the filename (of the css file).

`<link rel="stylesheet" href="/css/main.[hash_of_the_file_content].css">`

This bypasses the issue of dealing with cache invalidation (which is not always possible) entirely and ensures that the browser only loads new css when the content has actually changed.

An alternative to hashing the file content is to look at the last commit that modified the file and use that.

**Comment by sabine** [comment]
I think the ideal solution here would be a PPX that, at compile time hashes the file content and copies the file accordingly, then returns the path of the hash-named file.

**Comment by sabine** [comment]
Close in favor of #839
