### ISSUE TITLE
Items disappearing in the navbar 

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#708]
Here is what I do:

1. Pick a package with several libraries. For instance, Yaml: https://ocaml.org/p/yaml/3.1.0/doc/index.html
1. Click a module in one of the libraries, here Yaml_unix: https://ocaml.org/p/yaml/3.1.0/doc/Yaml_unix/index.html
1. Once there, the navbar only lists the yaml_unix library

Shouldn't it continue to display the whole list?

![Screenshot_2022-12-15_17-16-51](https://user-images.githubusercontent.com/1917592/207912847-3f4fe907-68db-4b99-90a2-f778ff044c56.png)

![Screenshot_2022-12-15_17-17-41](https://user-images.githubusercontent.com/1917592/207912844-ce0479cf-3840-421e-8880-ecb9eb43bf0c.png)

**Comment by sabine** [comment]
The problem with displaying the whole list is that some libraries are super spammy with a lot of top-level modules. With the AJAX-fetch navigation, I think we no longer need to hide those. Without the AJAX navigation, hiding the other libraries after "entering" a library is one way to keep the currently selected module as close to the viewport as possible. Ideally we can find a better solution that works for all packages - those with a lot of top-level modules and libraries and those with very few.
