### ISSUE TITLE
OCaml playground broken

### ISSUE THREAD

**Issue by bloa** [ocaml/ocaml.org#717]
I saw the recent announcement for OCaml 5 and ended up on the online playground.
The default example does not run, instead leads to the following error:

    Line 7, characters 0-0:
    Error: Syntax error

As seen on this screenshot:
![chromium](https://i.imgur.com/ex33Mbu.png)

Steps to replicate:
1. go to https://ocaml.org/play
2. click on "Run"

The error seems to appear as soon as the program includes a newline.  
Single-line programs don't trigger a syntax error but seem to silently fail instead.

Happy holidays :)

**Comment by cuihtlauac** [comment]
Thanks for this detailed report. Happy holidays too

**Comment by tmattio** [comment]
@cuihtlauac and I can't reproduce anymore, so closing for now, but feel free to re-open if you see the bug happen again
