### ISSUE TITLE
Link to RSS feed

### ISSUE THREAD

**Issue by kuchta** [ocaml/ocaml.org#718]
It would be great, if RSS feed is linked in the blog page (and maybe even main page) so that RSS readers can find it.

**Comment by cuihtlauac** [comment]
Thanks for the suggestion, that would indeed be usefull

**Comment by cuihtlauac** [comment]
Fix PR: https://github.com/ocaml/ocaml.org/pull/719

This adds a small RSS link at the bottom of each page.

**Comment by kuchta** [comment]
Hi @cuihtlauac. Thank you for quick reply. Showing the link on the page is indeed usefull, but I meant linking the RSS feed to page for RSS Autodiscovery. See https://www.petefreitag.com/item/384.cfm

**Comment by cuihtlauac** [comment]
Thanks, @kuchta; I've updated as indicated.
