### ISSUE TITLE
Mutability of records not clear enough

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#724]
@kumar-ish wrote (in https://github.com/ocaml/ocaml.org/issues/720):

> Also just a minor issue: in the same page it says "One feature which I didn't cover: OCaml records can have mutable fields" -- but in the previous section that covered records, it did mention records having mutable fields: "Records may be mutable: ..."

Actually, https://ocaml.org/docs/if-statements-and-loops states:

> One feature which I didn't cover: OCaml records can have mutable fields.

And, https://ocaml.org/docs/data-types states:

> Records may be mutable:

All this is correct. But it needs to be said somewhere that writing “record x is mutable” means the same as “record x has mutable fields”

**Comment by kumar-ish** [comment]
Just to be a bit clearer, I meant to say that the ordering of it was off -- so a later section (if-statements-and-loops) was saying that the tutorials hadn't covered OCaml records having mutable fields even though an earlier section had covered it (data-types)

**Comment by sabine** [comment]
Resolved with the publication of the "Mutability and Imperative Control Flow" tutorial.
