### ISSUE TITLE
Several recent package docs broken?

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#728]
![Screenshot_2022-12-22_10-41-01](https://user-images.githubusercontent.com/1917592/209105404-8d5ce5a9-cff2-47c1-a31d-bbabcd45a283.png)
![Screenshot_2022-12-22_10-40-00](https://user-images.githubusercontent.com/1917592/209105408-a6520235-2977-483f-95c8-df6556a5d62f.png)
![Screenshot_2022-12-22_10-38-41](https://user-images.githubusercontent.com/1917592/209105410-445d8bf7-3b6b-4d9a-8ca8-794fb63a0017.png)
![Screenshot_2022-12-22_10-38-17](https://user-images.githubusercontent.com/1917592/209105414-1a6e94b8-7d0d-4d5e-b060-1b878556e444.png)

**Comment by tmattio** [comment]
Looks like these have been generated now, thanks @TheLortex!

**Comment by TheLortex** [comment]
There was a bit of downtime for new packages due to voodoo and omd updates, sorry about that!
