### ISSUE TITLE
Feature request: support `latest` in the url that links to the latest version of package documentation

### ISSUE THREAD

**Issue by arbipher** [ocaml/ocaml.org#730]
I searched the issues, and it's similar to #726 but this is for package documentation.

It would be useful when the documentation is bookmarked with the `latest` in the URL, then we don't need to update the links periodically.

e.g.
Current: `https://v3.ocaml.org/p/base/v0.15.1/doc/Base/index.html`
Expected: `https://v3.ocaml.org/p/base/latest/doc/Base/index.html`

This link `https://v3.ocaml.org/p/base/` can redirect to the latest version `https://v3.ocaml.org/p/base/v0.15.1/`. However, the entry page is not convenient to use.

**Comment by cuihtlauac** [comment]
Thanks, @arbipher; you are right; the `latest` thing should also apply to the package documentation and is badly needed. Here is another issue which is relevant to this discussion:

https://github.com/ocaml/ocaml.org/issues/534

**Comment by arbipher** [comment]
Thanks for pointing out an existing issue.

I think we are concerning the same problem. If the fixed URL for the search engine is solved, so does the bookmark.
