### ISSUE TITLE
Replace TryOCaml in “A First Hour with OCaml” document ?

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#738]
Does it make sense to replace the reference to TryOCaml in the [A First Hour with OCaml](https://ocaml.org/docs/first-hour) document?

CONS:

* Up and running
* Solid, MTBF not known but looks excellent

https://try.ocamlpro.com/

PROS:

* OCaml 4.13
* French
* Not a terminal-like REPL experience

**Comment by tmattio** [comment]
Yes, we should recommend the official playground now that we have one, the doc was written when the playground didn't exist

**Comment by tmattio** [comment]
Closed in #817
