### ISSUE TITLE
Playground unit tests

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#742]
Using the playground RPC mechanisms, it should be possible to have units tests run in build CI. Tests should cover:

* Default playground code
* Basics such as Fibonacci and factorial
* Raising exception
* Standard output

This would allow detecting regression or breakage of the playground as fast as possible.

**Comment by sabine** [comment]
We never had issues with the playground code breaking a lot, so maybe we just close this for now as this will come up naturally later when packages can be loaded into the playground and a way to check for breakage may be coming from upstream odoc even.
