### ISSUE TITLE
Ood: Remove code copied from Omd

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#744]
File [tools/omd/lib/tutorial.ml](https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/tutorial.ml#L28) contains a copy of function `to_plain_text` from Omd (see: https://github.com/ocaml/omd/blob/master/src/html.ml#L160).

If Omd is updated to expose this function, such as proposed in PR https://github.com/ocaml/omd/pull/300, it should be used.

**Comment by sabine** [comment]
Closing this because a migration from omd to cmarkit seems likely.
