### ISSUE TITLE
Improve GraphQL Tests

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#76]
As discussed in #73 there are a few missing tests such as: 

- [ ] What if the limit is `None`?
- [ ] What if the offset is not `0`?
- [ ] Are the correct 3 packages returned when you ask for and offset `0` and limit `3`?
- [ ] A test to check for correct functionality for edge cases in `limit` and `offset` (negative, out of bounds etc.)
- [ ] Correctly returning `None` if a package is not found
- [ ] Should the length of packages be something the function calculates rather than something the user passes in ?

(just for clarification, the current tests are great and are the only "real" ones -- this is just in response to some outstanding tasks in the original PR)

cc @dinakajoy

**Comment by tmattio** [comment]
I think this has been fixed, feel free to reopen if that's not the case
