### ISSUE TITLE
Add Matrix/Mastodon to the "join our communities" section

### ISSUE THREAD

**Issue by avsm** [ocaml/ocaml.org#767]
For https://ocaml.org/community:

- Matrix is suggested in: https://discuss.ocaml.org/t/ocaml-org-recapping-2022-and-queries-on-the-fediverse/11099/26 for a general channel.  We do have an OCaml "space" that includes all the known rooms (including the general one) over at `#ocaml:roscidus.com` or `#ocaml:recoil.org`. We could republish this on the main Matrix as well, @talex5?
 
- A link to Mastodon and the `#ocaml` hashtag is probably appropriate alongside Twitter. Not sure which homeserver to link to though: perhaps https://types.pl

**Comment by swrup** [comment]
[#ocaml-language:matrix.org](https://matrix.to/#/#ocaml-language:matrix.org)
