### ISSUE TITLE
Red bar for OCaml 5 at top of page clashes with OCaml orange

### ISSUE THREAD

**Issue by lindig** [ocaml/ocaml.org#769]
A red  bar at the top of https://ocaml.org was recently added:

```
OCaml 5.0 is available! This release of OCaml comes with support for shared-memory parallelism
through domains and direct-style concurrency through algebraic effects! [Try it now →]
(https://ocaml.org/news/ocaml-5.0)
```

The red colour rgb(153, 27, 27) is not in a good relation to the otherwise dominant colour orange used for OCaml. It is neither a contrast, nor an obvious variation of the colour. I would argue it adds to the already inconsistent use of colours on the page. I would suggest to use logos from other projects and companies only in black/white or grey as a first step to calm this down and think about a colour scheme.

**Comment by cuihtlauac** [comment]
Hi @lindig, you are correct, we don't have a colour scheme. As a consequence, too many or inconsistent colours are used. I picked that red in the hope it would be impactful, but I agree it may create an unpleasant shock. That bar was an interim thing; it will go away. We are beginning to work on some redesign. Hopefully, the colour situation will be improved.

Regarding corporate logos, those assets are often provided under licensing terms which require using the coloured versions in a web context. Graphical charters tend to restrict the use of monochrome logos to colour-constrained print media.

Many thanks for your feedback.

Update: Actually, we have a colour scheme! Setting the color of the banner to red was a mistake. Sorry about that.

**Comment by meghaaa30** [comment]
hey, I am an outreachy applicant. I would like to work on this issue. Can you elaborate more on the issue?

**Comment by lindig** [comment]
I think the issue is well articulated. What is not clear?

**Comment by meghaaa30** [comment]
What color would you prefer the red bar to be changed into? Where can i find the related files?

**Comment by tmattio** [comment]
It's been 3 months since OCaml 5 was released. One alternative to updating the colour of the banner would be to remove it and move the link to somewhere less intrusive.

**Comment by meghaaa30** [comment]
Okay, can you provide me the link to the related files?

**Comment by cuihtlauac** [comment]
The latest update of the landing page adds a link to the newest version. The banner can go away. @meghaaa30 would you like to do that?

**Comment by meghaaa30** [comment]
> The latest update of the landing page adds a link to the newest version. The banner can go away. @meghaaa30 would you like to do that?

Yes! And
 please provide me with the link to the file too.

**Comment by cuihtlauac** [comment]
@meghaaa30 can you DM me on Google Chat? Use my email from the git logs.
