### ISSUE TITLE
Hosting a sourcehut instance

### ISSUE THREAD

**Issue by redianthus** [ocaml/ocaml.org#770]
[Sourcehut](https://sourcehut.org) was requested by [some users](https://discuss.ocaml.org/t/ocaml-org-recapping-2022-and-queries-on-the-fediverse).

I don't know the process to get an instance running on `ocaml.org` so maybe someone who knows about it could explain what should be done first ?

**Comment by cuihtlauac** [comment]
Thanks for the suggestion @zapashcanon. For the record, let me add some context in order for this item to be understandable on its own. 

In his post [OCaml.org: recapping 2022 and queries on the Fediverse](https://discuss.ocaml.org/t/ocaml-org-recapping-2022-and-queries-on-the-fediverse/11099), @avsm wrote (bold emphasis mine): 

> [git.ocaml.org 4](http://git.ocaml.org/) (not launched): a service that we have considered since 2019 and did not launch is a git mirror, or an alternative way of procuring OCaml ecosystem source code than from GitHub. There have been a small but steady [stream of requests](https://discuss.ocaml.org/t/publishing-without-github/3232) for this, with several motivations: availability (GitHub is a central point of failure), security (replicating ecosystem git branches is sound and secure practise), and privacy. The core OCaml team is firmly committed to GitHub at present, but launching a read-only mirror is in scope for 2023 **if a maintainer is willing to step forward and survey available solutions (ideally not as heavy-weight as GitLab) for mirroring scripts. Once we have a robust read-only git mirror, we can begin to consider how to accept patch contributions (particularly to the opam repository) via email or other mechanisms, but no promises until we reach the first read-only milestone.**

[hyphenrf](https://discuss.ocaml.org/u/hyphenrf) replied: 

> I know I’m no maintainer and this is no survey but please consider sourcehut 5! It’s lean, easy to maintain, and very email-friendly! It could even double as the new home for ocaml-list.

Up to my understanding, this item may be more relevant to https://github.com/ocaml/infrastructure. @tmattio shall we transfer it there?

**Comment by tmattio** [comment]
I think it's ok to keep the issue here, it'll probably be more visible than on infrastructure. When we decide on which service to use, we can open an issue upstream.

**Comment by avsm** [comment]
I explained what we need pretty clearly in the quoted portion above:
> The core OCaml team is firmly committed to GitHub at present, but launching a read-only mirror is in scope for 2023 if a maintainer is willing to step forward and survey available solutions (ideally not as heavy-weight as GitLab) for mirroring scripts. Once we have a robust read-only git mirror, we can begin to consider how to accept patch contributions (particularly to the opam repository) via email or other mechanisms, but no promises until we reach the first read-only milestone.

Noone's stepped up yet to do the survey and the read-only mirror portion first, and this has to happen as a minimum for us to understand what's involved, before moving onto the advanced stuff.  I'll close this issue until someone does step up, as it won't make progress till then.

**Comment by avsm** [comment]
Why the thumbs down @zapashcanon? Are you volunteering to help?  I can reopen if you're interested.
