### ISSUE TITLE
What is a “symbolic relay debugger”?

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#774]
The term is used in https://v3.ocaml.org/about (src/ocamlorg_frontend/pages/about.eml).

* Is it a typo for “symbolic replay debugger” (suggested by @dra27)
* Is it something real?

The term is also present in a Tarides Blog Post: https://tarides.com/blog/2022-11-22-six-surprising-reasons-the-ocaml-programming-language-is-good-for-business

Reported by @pitag-ha

**Comment by dra27** [comment]
It really is a typo! cf. the first sentence of the manual “This chapter describes the OCaml source-level replay debugger ocamldebug.”. Source-level/symbolic are largely interchangeable terms.

It refers to the ability of the debugger to “time travel” (at least on Unix)

**Comment by cuihtlauac** [comment]
Fix PR: https://github.com/ocaml/ocaml.org/pull/776
