### ISSUE TITLE
Write a success story on the Coq Proof assistant

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#779]
Coq and OCaml share the same origin. Coq won the ACM System Award.

**Comment by sabine** [comment]
Do we know a company that uses Coq with great success? They could write a success story.

The academic users page doesn't really have a space for this kind of content right now. Maybe it does in the future.

**Comment by tmattio** [comment]
We've done a pass at the success stories and will update them soon.
