### ISSUE TITLE
Top padding is overly large

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml.org#798]
Hi,

Would it make sense to remove large whitespace (top padding) between the header and main text body? It seems a bit screen-space-wasteful to me

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16353531/212173747-350deb7d-82ab-4114-b7d2-f4478e74e33c.png">

**Comment by cuihtlauac** [comment]
Thanks for your report @ulugbekna. We have started working on a redesign of the pages. Whitespace is a concern, some is needed to avoid feeling overwhelmed by too much content, but not too much as screen space is precious. We'll try to take your input into account. Don't hesitate to send us feedback, we like it, we need it.

**Comment by sabine** [comment]
Changed in https://github.com/ocaml/ocaml.org/pull/792.
