### ISSUE TITLE
Space on the left side

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#799]
Shouldn't we have the same amount of space between the content at the left limit of the area where it sits (highlighted in red)?

* In the central content and in the left navigation area? 
* In all pages?

![Screenshot_2023-01-13_08-19-16](https://user-images.githubusercontent.com/1917592/212262581-ef6e1e1e-0165-4128-b74e-2ed3d5d35a17.png)
![Screenshot_2023-01-13_08-06-38](https://user-images.githubusercontent.com/1917592/212262587-8a9421ef-56af-44ee-bafe-cc187c232eed.png)

**Comment by sabine** [comment]
Good question for Claire.

**Comment by cuihtlauac** [comment]
Not observable any longer
