### ISSUE TITLE
Display of featured packages could look better on smaller screens

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#819]
![8c5e30cbab0a22a433805be61d7624d0f94e579c_2_276x375](https://user-images.githubusercontent.com/6594573/212686711-17cd7295-7e7a-41af-9845-184c2d0f60b6.png)

Horizontal scroll may be a common pattern on phones and tablets, but doesn't currently look appealing on medium-sized screens.

**Comment by FatumaA** [comment]
@SaySayo

**Comment by SaySayo** [comment]
You can go ahead with a fix for this issue. Let me know if you need any assistance. @FatumaA

**Comment by FatumaA** [comment]
Thanks, and will do

**Comment by sabine** [comment]
@FatumaA You are now assigned this issue. :+1:

**Comment by FatumaA** [comment]
@SaySayo this issue no longer seems to be the case assuming that the highlighted section is under featured packages. I've added a screen recording.

https://github.com/ocaml/ocaml.org/assets/67555014/74897d5c-8d31-4ce7-b9af-803367278699

**Comment by SaySayo** [comment]
Your screen recording is on a large screen, try shrinking the window to get a smaller screen width and test it out. @FatumaA

**Comment by FatumaA** [comment]
Here is one focussing on smaller screens


https://github.com/ocaml/ocaml.org/assets/67555014/92176b78-e17a-4928-a2c2-fd97eb23fb96

**Comment by FatumaA** [comment]
I've noticed the blog page needs extra padding around it. it quite close to the edge. and there is misalignment on the learn page. I don't think i've seen issues for that. 
@SaySayo

**Comment by SaySayo** [comment]
You can create those issues with screenshots of the misalignments you noticed

**Comment by SaySayo** [comment]
Also @sabine, I'm unsure what the issue here is as on the screen recording it looks good to me. If it's already been fixed, the issue may be closed perhaps.

**Comment by FatumaA** [comment]
Oh wait, I found the issue here. On it.


https://github.com/ocaml/ocaml.org/assets/67555014/7bee63c8-80cb-426b-9f67-ee9ab5b69633
