### ISSUE TITLE
Some documentation pages are missing

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#82]
Reported by @gadmm in #66

> Comparison of https://guillaume.munch.name/software/ocaml/memprof-limits/ and https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/index.html:
> 
> - Some documentation pages are missing; to me this is a critical issue. (See for instance "A guide to recover from interrupts" which should be a link; it does not even show any error visually although the css class is xref-unresolved.)

**Comment by gadmm** [comment]
I still see the bug, and it critically affects the display of my package's documentation. Isn't this an odoc regression?

**Comment by jonludlam** [comment]
The missing link to `recovering.mld`? Yes: https://github.com/ocaml/odoc/issues/752 - we'll be releasing 2.0.1 shortly with the fix.

**Comment by gadmm** [comment]
Thanks! Let me know when I should test again, or I'll try again in some time.

**Comment by tmattio** [comment]
This seems to be fixed: https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/recovering.html
Feel free to re-open if this is still a problem
