### ISSUE TITLE
Bad redirections in URLs with trailing slashes

### ISSUE THREAD

**Issue by TheLortex** [ocaml/ocaml.org#820]
The trailing slash middleware https://github.com/ocaml/ocaml.org/pull/170 introduced problems in some situations:
- https://ocaml.org//github.com/ocaml/ocaml.org/pull/170/ redirects to an arbitrary URL
- https://ocaml.org/packages/////////////////////////////////////////////////////////////// leads to too many redirections

Thanks to @reynir who identified the issue in mirage.io

**Comment by cuihtlauac** [comment]
A bit of context:

1. Initial issue: https://github.com/ocaml/ocaml.org/issues/166
2. Faulty PR: https://github.com/ocaml/ocaml.org/pull/170
3. Issue in mirage-www: https://github.com/mirage/mirage-www/issues/772
4. PR in mirage-www: https://github.com/mirage/mirage-www/pull/788
5. New (this) issue: https://github.com/mirage/mirage-www/pull/788#issuecomment-1373455519

Summary: the code introduced in https://github.com/ocaml/ocaml.org/pull/170 is faulty. It went unnoticed until it was copied into mirage-www. Thanks to @TheLortex and @reynir for reporting this.

Questions:

1. @TheLortex are you working on fixing this, or do you want to fix it first on our side?
2. Isn't the _copying_ suggesting this should go into dream?

**Comment by TheLortex** [comment]
@cuihtlauac I'm not actively working on it, so I would be happy if you can fix it on you side. 

> Isn't the copying suggesting this should go into dream?

That's a complex matter because we don't know if the canonical path for given route should end by a slash or not. _not ending by a slash_ every path is an opinionated decision so it might have difficulties going in dream. But I agree that would be useful.

**Comment by reynir** [comment]
I think it could make sense to upstream functions to Dream that help deal with the somewhat complex semantics of the `Location` header, at least. I agree about getting it into dream could be difficult - I personally don't like it much as it can break semantics of relative links in the html and I made a library with a different approach (though still suffering from the same bug) https://github.com/reynir/dream-normalize-route. Another point against upstreaming is that dream hasn't seen seen any activity in a while.

**Comment by cuihtlauac** [comment]
Fixed by https://github.com/ocaml/ocaml.org/pull/866
