### ISSUE TITLE
Inter-page links give weird English

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#83]
Reported by @gadmm in #66

> Comparison of https://guillaume.munch.name/software/ocaml/memprof-limits/ and https://v3.ocaml.org/p/memprof-limits/0.2.0/doc/index.html:
> 
> - Inter-page links give weird English; compare for instance "Global memory limits let you bound..." with "Memprof_limits:global_memory_limits let you bound...". I understand the need to disambiguate which page is being pointed to, but this could be done while remaining in English, for instance "Global memory limits (Memprof_limits) let you bound...". (edit: an alternative might be to be able to define the text of the link separately from what is pointed to, which I did not manage to do otherwise with odoc.)

**Comment by jonludlam** [comment]
This is a bug in odoc.
