### ISSUE TITLE
Playground doesn't Run

### ISSUE THREAD

**Issue by mtelvers** [ocaml/ocaml.org#834]
Trying https://ocaml.org/play from macOS using either Safari or Chrome (109.0.5414.87) doesn't give any output in the right hand panel.  The example Fibonacci code appears but nothing else.  Below is the output from DevTools

![image](https://user-images.githubusercontent.com/10965410/213165950-e9847180-a0eb-4e6f-b5d5-4b3adc64c837.png)

**Comment by sabine** [comment]
I see the same error in the console.

Clicking the "Run" button seems to produce the correct output in the right hand panel, but this error should not happen in the first place.

I suspect the playground does not run the code example immediately after the page loads (which would be expected UX), so changing it to run immediately would make sense. ETA: The playground actually does run after loading, however, loading took very long because the files were sent uncompressed (which is now fixed).

**Comment by sabine** [comment]
I looked into this again, and while I do see the "`g.caml_unix_times` is not a function" error, I don't see the timeout. :thinking:

I also get Error-colored Content-Security-Policy Warnings on `playground-v1.js`, but that is unrelated.

**Comment by mtelvers** [comment]
I do not see the timeout error today either, and it is working as expected.  I no longer have error lines 2 - 5, only the first and the last.  Nothing changed on my side (I haven't even closed my browser window!) I note that on the network trace, `playground-v1.js` is only 1.1MB today, where it was 3.5MB before.  Thanks for looking into it.

**Comment by peter-jerry-ye** [comment]
Hi,

May I ask how the issue was solved? I experienced the same issue today.

![image](https://user-images.githubusercontent.com/16731997/225530992-8ac6697b-8737-4e71-96f2-01cedace98bd.png)

**Comment by sabine** [comment]
@peter-jerry-ye Thanks for reporting.

What you got here looks different because there is an additional error "Maximum call stack size exceeded". Can we get more context to reproduce?

**Comment by peter-jerry-ye** [comment]
@sabine I'm using Microsoft Edge 111.0.1661.41 on Windows 11
Other than that, I have no information. I just opened the https://ocaml.org/play and it reported error. 
I can not run anything. If I press run, it will wait some time and give more errors like this (the first few lines are the same as above)
![image](https://user-images.githubusercontent.com/16731997/225534641-59ba4be7-4108-4f28-a84b-cb6e96bdfb9b.png)

**Comment by peter-jerry-ye** [comment]
@sabine Hi, for your information, the playground now works fine. Not sure what changed.
The new version I'm using is Microsoft Edge 111.0.1661.44 on Windows 11.
The playground shows "OCaml version 5.0.0 Compiled with Js_of_ocaml version 5.1.1+2f5be3f0-dirty"
![image](https://user-images.githubusercontent.com/16731997/227085308-0d7b371e-93ad-4f36-b308-ac46542fe139.png)

**Comment by sabine** [comment]
@peter-jerry-ye thanks for letting us know! I suspect that https://github.com/ocaml/ocaml.org/pull/996 which fixed Merlin in the playground did it! So I'll be closing the issue. 👍
