### ISSUE TITLE
Markdown table are broken on package overview

### ISSUE THREAD

**Issue by xvw** [ocaml/ocaml.org#85]
Hi. The package application is very cool, thanks a lot, but even table works pretty well from Odoc, on Markdown, it seems broken: https://v3.ocaml.org/p/preface/0.1.0

(the extremely large table (`----|----`) is due to markdown linter).

ps: I don't know if I have to submit the report here or on the front-end part.

**Comment by ifazk** [comment]
Posting this here to save anyone else the trouble of trying to figure out what's going on. Feel free to correct me if I got something wrong here.

This is a an upstream issue and duplicate #59. The most relevant upstream issue is https://github.com/ocaml/omd/issues/205

**Comment by cuihtlauac** [comment]
Duplicate of: https://github.com/ocaml/ocaml.org/issues/59
