### ISSUE TITLE
Expose List of Outreachy Interns

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#855]
Follow-up work on PR: https://github.com/ocaml/ocaml.org/pull/854

@patricoferris wrote:
> This PR only adds information and all of the Ood code for the data, I'm hoping someone with more design skills can take this and actually show it on the frontend :)) I've done my best to add project descriptions but you can't actually see them on the Outreachy site unless you mentored the project.

This is about creating the suggested page

**Comment by theVJagrawal** [comment]
hey @cuihtlauac I'm interested in this can you please elaborate it more

**Comment by cuihtlauac** [comment]
Hi @theVJagrawal, thank you very much; we appreciate very much your intention to contribute; this would be great.

You are right; my description of the work to be done is lame.

The https://github.com/ocaml/ocaml.org/pull/854 PR mostly contains two kinds of things:
* Data, in Yaml format, describing contributions made by outreachy interns in OCaml (file `data/outreachy.yml`)
* OCaml code allowing ocaml.org to process that data (file: `tool/ood-gen/lib/outreachy.ml`)

The rest of the code acts as requirements or “glue”. However, the https://github.com/ocaml/ocaml.org/pull/854 PR, does not contain the code exposing the outreachy internship data as a web page in ocaml.org.

We would like to have such a web page; displaying the contents of `outreachy.yml` in a pleasant and friendly manner. That mostly boils down into having a file `outreachy.eml` which processes the outreachy data and turns it into HTML. Some changes are also needed in a couple of files to bind a URL to its contents.

Hope it helps, don't hesitate to ask for more information.

**Comment by theVJagrawal** [comment]
hey @cuihtlauac thanks for your comment, i would like to work on this issue so could you please assign it to me

**Comment by cuihtlauac** [comment]
Thanks, @theVJagrawal this is great. Don't worry about the issue assignment, we mostly don't.

**Comment by theVJagrawal** [comment]
hey @cuihtlauac thanks for the reply, I'm going to take this issue as a part of my academic course work so could you please assign it to me

**Comment by cuihtlauac** [comment]
@theVJagrawal - I'm delighted to hear your contribution could be helpful in a course. We will happily assign this issue to you as soon as you make a PR.

**Comment by sabine** [comment]
One of our interns will be working on this issue as well. This does not prevent @theVJagrawal from working on it, as the two of you would be able to review each other's respective PR as you will likely come up with different designs.

@theVJagrawal If you are still interested in working on this issue, please confirm and give a timeline for your course work.

**Comment by patricoferris** [comment]
It might be quite nice to link to / embed videos from the channel: https://watch.ocaml.org/c/outreachy_ocaml/videos

**Comment by cuihtlauac** [comment]
Is there a way to point at some time in a watch.ocaml.org video? I see three videos there but it seems several interns are speaking during each of them.

**Comment by patricoferris** [comment]
Yep, great idea! There's a `start` queryParam e.g. https://watch.ocaml.org/w/vXJtTj3cULRa1bZB5HrecX?start=5m24s

**Comment by cuihtlauac** [comment]
Here is a PR: https://github.com/ocaml/ocaml.org/pull/970

**Comment by cuihtlauac** [comment]
Implemented in https://github.com/ocaml/ocaml.org/pull/854
