### ISSUE TITLE
HTMX doesn't like single quote characters in HTML attributes

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#877]
HTMX errors when a single quote character is present in an attribute.

Example page: https://ocaml.org/p/ocaml-base-compiler/4.14.1/doc/Genprintval/Make/index.html. Navigating from any other documentation page to this one fails due to the single quote in `install_generic_printer'`.

In order to make navigation happen anyway, when HTMX errors, I opened https://github.com/ocaml/ocaml.org/pull/876.

One way to avoid this issue is to encode `'` as `&#39;` in odoc. Realistically, that would be the safest thing to do, since `'` is a valid string delimiter in HTML.

**Comment by cuihtlauac** [comment]
> One way to avoid this issue is to encode ' as &#39; in odoc.
> Realistically, that would be the safest thing to do,
> since ' is a valid string delimiter in HTML.

Shouldn't an issue be filed in odoc?

**Comment by sabine** [comment]
I opened https://github.com/ocaml/odoc/issues/924 upstream.

**Comment by sabine** [comment]
The better approach is to fix htmx, since what odoc is emitting is valid HTML. I opened https://github.com/bigskysoftware/htmx/issues/1236.

**Comment by sabine** [comment]
Status: Upstream issue has been fixed, waiting on new release of `htmx`.
