### ISSUE TITLE
Packages 2nd Version

### ISSUE THREAD

**Issue by ILeandersson** [ocaml/ocaml.org#89]
This is an updated version of the package site 
<img width="625" alt="Screenshot 2021-09-03 at 15 35 56" src="https://user-images.githubusercontent.com/73180976/132025295-68feee76-2753-46c2-a105-62442b247dde.png">
<img width="624" alt="Screenshot 2021-09-03 at 15 36 08" src="https://user-images.githubusercontent.com/73180976/132025300-e0d32c7d-90c8-40eb-8c0e-fa55b169b416.png">

**Comment by tmattio** [comment]
Thanks a lot @ILeandersson 🎉  

> We may want to track this in https://github.com/ocaml-doc/voodoo?

@kanishka-work This issue is about the design of the landing page for the package site I think, so this is the right place for it (it won't impact the doc generation or the doc pipeline) 🙂

**Comment by jonludlam** [comment]
I'd like to amend my previous position and suggest that we could even track this particular issue on v3.ocaml.org to keep all the designs in once place? One of the goals of the integration was to ensure consistency between all parts of the website, and while having @ILeandersson coordinating the design work mostly achieves this, it's _slightly_ odd that the design feedback issues are in two different repos. Obviously I understand that the _implementation_ work for the packages page is here, but that's a distinction that I feel is not important for the design.

Having said that I still think that all other issues -- bugs -- relating to paths `/package`, `/p` or `/u` should be on this repository though.

**Comment by tmattio** [comment]
> we could even track this particular issue on v3.ocaml.org

Agreed 🙂

**Comment by patricoferris** [comment]
Hmm ok, feel free to transfer it back, sorry for the noise! Personally, I find it odd that PRs here would fix issues over there and anybody wanting to fix the issue on v3.ocaml.org needs to be redirected over to here. I suppose we can just add a comment to any issue that requires implementation in v3.ocaml.org-server.
