### ISSUE TITLE
Add Opam publish documentation

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#9]
The landing page has a call to action to the opam publish documentation, which does not exist yet.

**Comment by mimi-tech** [comment]
@tmattio I am interested in solving this bug.  Please I need your help and guideline. I have forked the repo and cloned it as well. But I can't find the landing page. Please can you direct me on this? Thank you.

**Comment by tmattio** [comment]
Hi @mimi-tech!

Did you build the project and try to start it with `make start`? If it builds and starts correctly, you should be able to access the site at http://localhost:8080/

**Comment by mimi-tech** [comment]
Hi @tmattio ! Hope you are fine. 
Thanks for your reply. I am getting all these errors when building the project with "make start". Please what do I do. Thank you.

Error: Program js_of_ocaml not found in the tree or in PATH
 (context: default)
Hint: opam install js_of_ocaml-compiler
File "dune", line 16, characters 5-9:
16 |      node
          ^^^^
Error: Program node not found in the tree or in PATH
 (context: default)
File "src/gettext/test/dune", line 4, characters 12-20:
4 |  (libraries alcotest gettext gettext_po))
                ^^^^^^^^
Error: Library "alcotest" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "src/ocamlorg/lib/dune", line 13, characters 2-17:
13 |   cohttp-lwt-unix
       ^^^^^^^^^^^^^^^
Error: Library "cohttp-lwt-unix" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "src/ocamlorg/test/dune", line 3, characters 12-20:
3 |  (libraries alcotest ocamlorg))
                ^^^^^^^^
Error: Library "alcotest" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "src/ocamlorg_toplevel/bin/dune", line 8, characters 7-22:
8 |   (pps js_of_ocaml-ppx)))
           ^^^^^^^^^^^^^^^
Error: Library "js_of_ocaml-ppx" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "src/ocamlorg_toplevel/bin/dune", line 22, characters 7-21:
22 |   (run jsoo_listunits -o %{targets} stdlib base)))
            ^^^^^^^^^^^^^^
Error: Program jsoo_listunits not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_toplevel/bin/dune", line 36, characters 5-21:
36 |    %{bin:js_of_ocaml}
          ^^^^^^^^^^^^^^^^
Error: Program js_of_ocaml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_toplevel/bin/dune", line 62, characters 7-21:
62 |   (run jsoo_listunits -o %{targets} stdlib)))
            ^^^^^^^^^^^^^^
Error: Program jsoo_listunits not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_toplevel/bin/dune", line 71, characters 7-22:
71 |   (pps js_of_ocaml-ppx))
            ^^^^^^^^^^^^^^^
Error: Library "js_of_ocaml-ppx" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "src/ocamlorg_toplevel/bin/dune", line 78, characters 5-21:
78 |    %{bin:js_of_ocaml}
          ^^^^^^^^^^^^^^^^
Error: Program js_of_ocaml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_toplevel/bin/dune", line 101, characters 9-20:
101 |     (run jsoo_minify ../toplevel_stdlib.bc.js -o stdlib-4.13.0.js)
               ^^^^^^^^^^^
Error: Program jsoo_minify not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_toplevel/lib/dune", line 6, characters 7-22:
6 |   (pps js_of_ocaml-ppx)))
           ^^^^^^^^^^^^^^^
Error: Library "js_of_ocaml-ppx" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "src/ocamlorg_web/lib/dune", line 12, characters 2-10:
12 |   timedesc))
       ^^^^^^^^
Error: Library "timedesc" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "src/ocamlorg_web/lib/templates/components/dune", line 5, characters 9-23:
5 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
             ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 11, characters 9-23:
11 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 17, characters 9-23:
17 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 23, characters 9-23:
23 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 29, characters 9-23:
29 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 35, characters 9-23:
35 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 41, characters 9-23:
41 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 47, characters 9-23:
47 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 53, characters 9-23:
53 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 59, characters 9-23:
59 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/components/dune", line 65, characters 9-23:
65 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/layouts/dune", line 5, characters 9-23:
5 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
             ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/layouts/dune", line 11, characters 9-23:
11 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 5, characters 9-23:
5 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
             ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 11, characters 9-23:
11 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 17, characters 9-23:
17 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 23, characters 9-23:
23 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 29, characters 9-23:
29 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 35, characters 9-23:
35 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 41, characters 9-23:
41 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 47, characters 9-23:
47 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 53, characters 9-23:
53 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 59, characters 9-23:
59 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 65, characters 9-23:
65 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 71, characters 9-23:
71 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 77, characters 9-23:
77 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 83, characters 9-23:
83 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 89, characters 9-23:
89 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 95, characters 9-23:
95 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
              ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 101, characters 9-23:
101 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 107, characters 9-23:
107 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 113, characters 9-23:
113 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 119, characters 9-23:
119 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 125, characters 9-23:
125 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 131, characters 9-23:
131 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 137, characters 9-23:
137 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 143, characters 9-23:
143 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 149, characters 9-23:
149 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 155, characters 9-23:
155 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 161, characters 9-23:
161 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 167, characters 9-23:
167 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 173, characters 9-23:
173 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 179, characters 9-23:
179 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 185, characters 9-23:
185 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 191, characters 9-23:
191 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 197, characters 9-23:
197 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 203, characters 9-23:
203 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 209, characters 9-23:
209 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/lib/templates/pages/dune", line 215, characters 9-23:
215 |   (run %{bin:dream_eml} %{deps} --workspace %{workspace_root})))
               ^^^^^^^^^^^^^^
Error: Program dream_eml not found in the tree or in PATH
 (context: default)
File "src/ocamlorg_web/test/dune", line 4, characters 12-20:
4 |  (libraries alcotest ocamlorg_web))
                ^^^^^^^^
Error: Library "alcotest" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
File "tool/ood-gen/bin/dune", line 19, characters 25-33:
19 |  (libraries cmdliner bos alcotest ood_gen))
                              ^^^^^^^^
Error: Library "alcotest" not found.
Hint: try:
  dune external-lib-deps --missing --root . @@default
make: *** [all] Error 1

**Comment by pitag-ha** [comment]
hi @mimi-tech, nice that you're interested in OCaml!

I'm not a mentor for this project, but I've just come across this question and might be able to help.

>Please what do I do.

I was thinking that instead of giving you the instructions on what to do, it might be even more helpful to guide you on how to approach these kind of problems. What do you think?

So as a general piece of advice: when you see that an error message contains a hint, as here for example `Hint: opam install js_of_ocaml-compiler` and `Hint: try: dune external-lib-deps --missing --root . @@default`, it is usually very helpful to try those hints. Of course, it is likely that it will not directly solve your problem, but it can already lead you in the right direction. And it can also help you understand what is going wrong. Furthermore, in general, when you get an error it is very helpful to try to find out what the error is about.

So concretely, here you could do three things:
- you could try the two hints the compiler is giving you. If you've already tried, it would be very helpful if you could point out what happened when trying them in your questions here, since that helps us guide you further.
- you could try to understand the hints: Do you know / can you guess what the command `opam install ...`, that's suggested in one of the hints, would do? And have you looked into what the command in the other hint `dune external-lib-deps --missing --root . @@default` would do?
- and of course, in general it is very helptul to try to understand the error messages. In this case there is a repeating pattern in the different messages. Can you see which pattern I'm talking about?

**Comment by pitag-ha** [comment]
By the way, I'm not 100% sure, but I think the idea for the contribution period also on this project is that folks first set up the project and, once that's done, start working on an issue (let me know @tmattio if that's wrong). So maybe you could first finish setting up the project and then come back to some issue? By the way, we also know that setting up OCaml projects isn't always that easy, so we're trying to come up with a good way to give general help on that.

**Comment by Lontchi12** [comment]
Hello Mentors, please i'm interested in working on this issue, i have my environment up and running already, would be glad if i'm given the go ahead Thank you

**Comment by farwa-batool** [comment]
I would like to work on, and fix this issue. Should I go ahead? @tmattio

**Comment by tmattio** [comment]
@farwa-batool I think @Lontchi12 wanted to work on this. Is it still the case @Lontchi12?

**Comment by Lontchi12** [comment]
Yes Sir @tmattio  its still the case, i've been waiting for your reply

**Comment by tmattio** [comment]
Oops, sorry about that @Lontchi12 🙂 I'm assigning the issue to you, feel free to ask if you have any questions

**Comment by Lontchi12** [comment]
Okay thank you Sir @tmattio will start right away

**Comment by Lontchi12** [comment]
Hello Sir @tmattio , i'm finding it difficult to access the file with which i'm to work on, and also i don't know if i'm to create a new file for the opam documentation or the file is already existing and i just have to add the documentation data inside

**Comment by gs0510** [comment]
@Lontchi12 If you look at https://v3.ocaml.org/packages, and click on the button at the end (`Learn how to contribute`) you will see that it doesn't do anything, it just takes you back to the same page. The documentation for publishing opam packages exists here: https://v3.ocaml.org/p/opam-publish/2.1.0, so you should add a redirect to take the user to this page instead.

**Comment by Lontchi12** [comment]
Okay thank you Sir i just opened a PR already on this issue please review
