### ISSUE TITLE
Broken links in documentation: missing `index.html`

### ISSUE THREAD

**Issue by panglesd** [ocaml/ocaml.org#926]
Many API links (apart from the one in the sidebar) recently lead to 404.

It seems the reason is that the `index.html` part is missing from many links. 

For instance, clicking on the `Ppxlib` module will lead to https://ocaml.org/p/ppxlib/0.29.0/doc/Ppxlib/ instead of https://ocaml.org/p/ppxlib/0.29.0/doc/Ppxlib/index.html.

Many packages and package version suffer from the bug (from my test, I think that the number of affected ppxlib version has grown since I started writing the issue!). For instance, [merlin-lib](https://ocaml.org/p/merlin-lib/4.7.1-500/doc/index.html) is also affected.
However, some packages are not affected: [yojson](https://ocaml.org/p/yojson/2.0.2/doc/Yojson/index.html)'s doc currently works well.

**Comment by sabine** [comment]
Something really odd happened just then, we have to look into it. For a short moment, package search was down as well.

It should be working again, for now, as we've reverted the upgrade to odoc 2.2.0.

**Comment by sabine** [comment]
Root cause has been identified and fixed.
