### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by maiste** [ocaml/ocaml.org#94]
This issue aims to centralize the discussions about the French translation of the website.

Work to do:
- [X] Industrial users (#86)
- [X] Academic institutions (#150)
- [ ] Books
- [ ] Tutorials 
- [ ] Workflows
- [ ] Releases

**Comment by tmattio** [comment]
We've temporarily removed the french translations of the content.
We probably want to come back to it at some point, but I'll close this until then.
