### ISSUE TITLE
Keeping in-sync with ocaml.org

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#95]
This issue is a place to keep track of changes upstream in ocaml.org whilst ood is not the main, promoted placed to be storing this information. This issue can just be extended as new content is potentially merged in ocaml.org and closed later whenever we can do that. 

### To Do

- [x] Import r2c into industrial users https://github.com/ocaml/ocaml.org/pull/1573
- [x] Add the macOS/iOS app to "A First Hour with OCaml" https://github.com/ocaml/ocaml.org/pull/1582
- [x] Incorporate changes to "Data types" tutorial https://github.com/ocaml/ocaml.org/pull/1576 
- [x] Add better currying description https://github.com/ocaml/ocaml.org/pull/1595
- [x] Add list tutorial https://github.com/ocaml/ocaml.org/pull/1565
- [ ] initial ocaml on windows explanation ocaml/ocaml.org#1600

### To Monitor

- Adds ‘Building and publishing’ tutorial (replacement PR) ocaml/ocaml.org#1606
- Add a solution for “94. An arithmetic puzzle.” in 99 Problems ocaml/ocaml.org#1597
- Rewrote set tutorial from scratch. ocaml/ocaml.org#1596
- Add an example of an adjacency list ocaml/ocaml.org#1594
- Update solution for 12 to be more succinct ocaml/ocaml.org#1593
- 99problems.md add solution for 22 ocaml/ocaml.org#1592
- update 99problems.md (number 13) ocaml/ocaml.org#1591
- 99problems update (number 12) ocaml/ocaml.org#1590

**Comment by fangyi-zhou** [comment]
https://github.com/ocaml/ocaml.org/pull/1614

**Comment by vphantom** [comment]
https://github.com/ocaml/ocaml.org/pull/1615

**Comment by teodorlu** [comment]
https://github.com/ocaml/ocaml.org/pull/1621

**Comment by tmattio** [comment]
Closing as OCaml.org's PR should be frozen now and we're getting close to launching V3.

**Comment by christinerose** [comment]
I was asked to open this PR today. https://github.com/ocaml/v2.ocaml.org/pull/1625
