### ISSUE TITLE
Change all instances of images to include alt text

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#96]
We use images in lots of different places (logos for companies, university emblems, background images for conferences etc.) -- since ood is the source of truth for which images we use, it is also probably the correct place to add `alt` text describing the images. 

It would be good to change all instances of a path pointing to an image in `media` to something like:

```ocaml
module Image = struct
  type t = {
    path : string;
    alt : string;
  }
end
```

**Comment by chepyego** [comment]
can i work on this issue?

**Comment by tmattio** [comment]
Hi @chepyego, sure that seems like a good issue to get started 🙂

**Comment by chepyego** [comment]
okay let me work on it @tmattio

**Comment by chepyego** [comment]
can someone brief me about this ticket @tmattio  i have the application installed but i don't know how to find this files

**Comment by patricoferris** [comment]
Hi @chepyego for sure :)) 

The data in the website is stored [in markdown and yaml files](https://github.com/ocaml/v3.ocaml.org-server/tree/main/data). This is then [read by other OCaml files](https://github.com/ocaml/v3.ocaml.org-server/tree/main/tool/ood-gen/lib) to ensure they are correctly formatted and then we "print" OCaml code for the data. So for example the following markdown and yaml:

```
---
title: Hello
---

## World
```

Would eventually end up as the OCaml:
```
type t = { title : string; body_md : string; body_html : string }

let all = [
  { title = "Hello"; body_md = "##World"; body_html = "<h2>World</h2>" }
]
```

Most of this is now automatic but sometimes we have images e.g. 

https://github.com/ocaml/v3.ocaml.org-server/blob/21a140f9f7133ab9878a48add71276a7cc6ecebd/tool/ood-gen/lib/success_story.ml#L3

And then see the generated success stories as OCaml in:

https://github.com/ocaml/v3.ocaml.org-server/blob/21a140f9f7133ab9878a48add71276a7cc6ecebd/src/ocamlorg_data/success_story.ml#L15

What this issue proposed is to replace anywhere we have `image : string option` where we record just the path to an image with a more useful type, namely:

```ocaml
module Image = struct
  type t = { path : string; alt : string }
end

(* Success story *)
type t = {... 
  image : Image.t option;
}
```

And we would have to update the markdown and yaml to be 

```
---
image:
  path: "some/path/to/file.jpg"
  alt: "Textual description of the image"
 ...
---
```

Hopefully that's enough to get you started :))

**Comment by oabdulhamid1** [comment]
Hi @tmattio can I work on project #96

**Comment by chepyego** [comment]
hey @oabdulhamid1 am working on this issue

**Comment by oabdulhamid1** [comment]
Alright, thanks @chepyego

**Comment by patricoferris** [comment]
How's it going @chepyego, anything we can help with (no rush/pressure just checking in) :)) ?

**Comment by chepyego** [comment]
hey @patricoferris  thanks for checking out, am not making any good progress, there are these folders ,under "ocamlorg_data " there some couple of folder i,e book.ml,  ood.ml, ood.mli they kind of confuse both seems to have similar data

**Comment by patricoferris** [comment]
What in particular are you confused with?

 - The difference between `ml` and `mli`? (see: https://dev.realworldocaml.org/files-modules-and-programs.html#scrollNav-2)
 - All other files in `ocamlorg_data` apart from `ood.ml` and `ood.mli` are autogenerated by the tools in `tool/ood-gen`. The mapping there is as you might expect i.e. `tool/ood-gen/lib/book.ml` generates `ocamlorg_data/book.ml`
 - Something else?

**Comment by tmattio** [comment]
@chepyego are you still working on this? @Lontchi12 would like to work on something and we're running out of good first issues. If you jumped on something else, they could take over 🙂

**Comment by Lontchi12** [comment]
I would really really love to help out here @chepyego, please @tmattio i just pulled from the remote main branch i have some conflicts, how do i resolve that? should i just accept all incoming changes or do you suggest i stash them for the moment?

**Comment by Lontchi12** [comment]
I would really really love to help out here @chepyego, please @tmattio i just pulled from the remote main branch i have some conflicts, how do i resolve that? should i just accept all incoming changes or do you suggest i stash them for the moment?

**Comment by tmattio** [comment]
> please @tmattio i just pulled from the remote main branch i have some conflicts, how do i resolve that?

You should branch out of `main` if you work on this issue, so if you have conflicts, you can move your changes to a new branch (if you want to keep your changes), and reset your main branch to `ocaml/v3.ocaml.org-server`. You can do the last step with `git reset --hard <remote>/main` where `<remote>` is the name of the remote you created for the upstream repository.

**Comment by Lontchi12** [comment]
Okay thank You

**Comment by Lontchi12** [comment]
I don't know if i should go ahead with this issue or wait for @chepyego's response @tmattio

**Comment by tmattio** [comment]
@Lontchi12 I think you can go ahead, @chepyego's last message was two weeks ago. If they are still working on this, we'll find a way for you to collaborate on this issue.

**Comment by Lontchi12** [comment]
Hello @tmattio  Please can you elaborate more on this issue with an example and the files to be changed too so i can hurrily finish with this task and submit my final Application Please?

**Comment by tmattio** [comment]
@Lontchi12 - @patricoferris's description of the issue here should go a long way to help you get started: https://github.com/ocaml/v3.ocaml.org-server/issues/96#issuecomment-941114748

But I'll note that you shouldn't feel that you need to do as much work as possible during the application period. For what it's worth, we're much more interested in the quality of the PRs than the quantity when reviewing the applicants' work.

**Comment by Lontchi12** [comment]
`type t =
  { title : string
  ; slug : string
  ; image : string option
  ; alt : string
  ; url : string option
  ; body_md : string
  ; body_html : string
  }`


Hope i'm on the right path @tmattio  and also when i run make test my changes dissappear am i supposed not to run that command?

**Comment by SwizzCoder** [comment]
Hello @gpetiot @punchagan @SaySayo @tmattio 
I am outreachy applicant. I wish to ask if I can be assigned to this issue as part of my contribution for this contribution phase.

**Comment by sabine** [comment]
@SwizzCoder sorry, this is not a reasonable issue to work on, we're closing this one.
