### ISSUE TITLE
Mobile breakpoints happens in two steps in the problems page

### ISSUE THREAD

**Issue by YassineHaouzane** [ocaml/ocaml.org#960]
While working on #890 i noticed the following bug the breakpoints from `lg` to `md` in the problems page happens in 2 steps :

1. We remove the sidebar when the screen's width is equal to 1024px
2. Then when the screen's width is under 1024px the tailwind `md` breakpoint gets applied.

Here is a gif of the issue happening (you can see at the top right the width of the window) : 
![breakpoints](https://user-images.githubusercontent.com/81616372/222517783-a2ae62ec-9e88-4a66-8629-4f27af1044ce.gif)

I was able to reproduce it on production with the following browser: 
* Google Chrome: Version 110.0.5481.178 (Official Build) (64-bit)

**Comment by cuihtlauac** [comment]
Thanks, @YassineHaouzane, you have an eagle eye!
