### ISSUE TITLE
Dream errors poping-up in logs

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#995]
Noticed this in my local build:

```
dream.router ERROR REQ 5 Dream.param: missing path parameter "page"
```

@mtelvers confirms there're also in the live build.

**Comment by sabine** [comment]
Sorry about those. I need to figure out a better way to have an optional path parameter for serving the README/CHANGELOG/LICENSE files. Maybe it should be a different route in `router.ml`? :thinking: 

ETA: This will resolve as soon as I rearrange the package handlers and routes. And that is up next.
